### ISSUE TITLE
EdmError/EdmLocation does not provide file name

### ISSUE THREAD

**Issue by fpintos** [OData/odata.net#1]
When parsing an EDMX file using EdmxReader we can get a list of EdmError.
The CsdlLocation in these error objects do not have the name of the file where the error originated, although they contain line/column information.

This is not a problem for standalone files, but if the model references other models, it is hard to pinpoint which file contains the error.

Expected: for CsdlLocation to contain file name, in addition to line/column numbers.

**Comment by LewisCheng-MSFT** [comment]
We have added a public string property called Source to CsdlLocation to indicate the source Uri of the Xml. For each referenced model, we populate this property with the Uri of it extracted from the top-level Edmx. Users DON'T need to pass any 'name' through XmlReader or directly to EdmxReader. This could help in your scenario and you can expect to see it in v6.10.

**Comment by fpintos** [comment]
Awesome, thanks!






Sent from Windows Mail





From: Lewis Cheng
Sent: ‎Monday‎, ‎January‎ ‎19‎, ‎2015 ‎10‎:‎47‎ ‎AM
To: OData/odata.net
Cc: Fabio Pintos





We have added a public string property called Source to CsdlLocation to indicate the source Uri of the Xml. For each referenced model, we populate this property with the Uri of it extracted from the top-level Edmx. Users DON'T need to pass any 'name' through XmlReader or directly to EdmxReader. This could help in your scenario and you can expect to see it in v6.10.
