### ISSUE TITLE
It doesn't work if "null" value in the payload of collection of entity 

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#100]
For example, I have an action with a collection of entity parameter in which the element type is nullable.

Now, I invoke this action with payload as:

``` json
{
  "Customers": [
     { "@odata.type":"#NS.Customer",  "Id":109,"Name":"Avatar" },
     null,
     {"@odata.type":"#NS.Customer", "Id":901,"Name":"Robot" } 
    ]
}
```

The ODataRead will fail to read this payload. Please investigate it and fix it. Thanks.

**Comment by mikepizzo** [comment]
I believe this should work now.  Please re-activate if this is still an issue.
