### ISSUE TITLE
AutoExpand in sub child

### ISSUE THREAD

**Issue by agminformatique** [OData/odata.net#1001]
I have a problem with AutoExpand attribute when it's used in a sub child.
I need to expand a child in an AutoExpand entity.

### Assemblies affected

Microsoft.AspNet.OData v6.1.0

### Reproduce steps

I use 4 entites
class Entity1
{
   int identite;
   string libelle;
   EntityType entityType;
}
class EntityType
{
   int idEntityType;
   string libelle;
   EntityAutoExpand entityAutoExpand;
}
[AutoExpand]
class EntityAutoExpand
{
   int idEntityAutoExpand;
   string libelle;
   List<EntityAutoExpandSubItems> listSubItems;
}
class EntityAutoExpandSubItems
{
   int idEntityAutoExpandSubItems;
   string libelle;
}

When I call my WebService on EntityType with 
https://localhost:9443/odata/EntityType?$expand=entityAutoExpand($expand=listSubItems)
that's work would expected.

But if I call on Entity1
https://localhost:9443/odata/Entity1?&$expand=EntityType($expand=EntityAutoExpand($expand=EntityAutoExpandSubItems))
I have an error 500 with message "An element with the same key have already be added"

### Additional detail

When I remove AutoExpand attribute, that's work.

Thanks in advance

**Comment by mikepizzo** [comment]
This appears to be an issue with WebAPI OData, not OData Library.

Unfortunately, we don't have an easy way to move bugs between repos. For proper tracking, please re-open this issue in [WebAPI OData](https://github.com/OData/WebApi/issues).

Also, please let us know what happens with the following two queries:
https://localhost:9443/odata/EntityType?$expand=entityAutoExpand
https://localhost:9443/odata/Entity1?&$expand=EntityType($expand=EntityAutoExpand)

Thanks!

**Comment by agminformatique** [comment]
Ok, sorry for my mistake.
I have created an new issue in WebApi OData repository and completed with your queries
Thanks
