### ISSUE TITLE
Can't override Content-Type to be just application/json

### ISSUE THREAD

**Issue by wizofaus** [OData/odata.net#1002]
Some older odata (pre v4) services won't accept Accept: application/json;odata-metadata=minimal

E.G:

var context = new DataServiceContext(new Uri("http://services.odata.org/V3/OData/OData.svc"));
var product = context.CreateQuery<Product>("Products").FirstOrDefault();

### Expected result

Should return the first product

### Actual result

Error from server - unsupported MIME type
### Additional detail

There appears to be no easy way in the design of the odata library to override the Accept to be just application/json, as DataServiceClientFormat is sealed.  It defines "MimeApplicationJson" but there is no way of telling it to use this.

Workaround:

                BuildingRequest += (object sender, BuildingRequestEventArgs args) =>
                {
                    args.Headers["Accept"] = "application/json";
                };

**Comment by wizofaus** [comment]
(BTW I also noticed that while processing the result, a lot of NotImplementedException's are thrown by ClientEdmModel - again, the class is sealed and the only implementation of the EntityContainer getter always throws this exception so it appears to be unavoidable. Is this a known issue?)

**Comment by mikepizzo** [comment]
We have different versions of ODataClient for consuming OData V1-V3 versus consuming an OData V4 service.  For consuming OData V1-V3, please see https://www.nuget.org/packages/Microsoft.Data.OData/
