### ISSUE TITLE
Model.Validate() returns exception about lack of assertion for proper model

### ISSUE THREAD

**Issue by lukred** [OData/odata.net#1006]
### Assemblies affected

OData .Net lib 7.3.1

### Reproduce steps

I have a simple annotation term of type enum:

` <Term Name="EntitySetCategory" Type="DataPlatform.Category" AppliesTo="EntitySet"/>
`
```
<EnumType Name="Category">
        <Member Name="Data" />
        <Member Name="Dictionary" />
      </EnumType>

```

I use this annotation in my enitysets:

`<Annotation Term="Self.EntitySetCategory" EnumMember="DataPlatform.Category/Dictionary" />
`
### Expected result

My model should be successfully parsed via CsdlReader.TryParse() and calling Validate() should not return any error.

### Actual result

Model is successfully parsed, but there is one error from Validate(..):

{ExpressionNotValidForTheAssertedType : The type of the expression is incompatible with the asserted type. : (433, 12)}

### Additional detail

It looks like my model is fine and the error is caused by lack of internal assertion in the library.

ExpressionTypeChecker.cs
Line 127:
 default:

                    discoveredErrors = new EdmError[] { new EdmError(expression.Location(), EdmErrorCode.ExpressionNotValidForTheAssertedType, Edm.Strings.EdmModel_Validator_Semantic_ExpressionNotValidForTheAssertedType) };
                    return false;

I do need to call Validate() in my code because the model is huge and this required. Is there some workaround ?

**Comment by xuzhg** [comment]
@lukred 

You can use the overload function to validate the model by your own validation rule. 

See public API at: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Validation/EdmValidator.cs#L49

Thanks!
