### ISSUE TITLE
Validations.None still validates property names in ODL V7

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1008]
*In ODL V6, setting ODataMessageWriterSettings.EnableFullValidation = false enables writing special characters (@, .) in property names.  Setting Validations.None in ODL V7 does not support writing these special characters.*

### Assemblies affected

*OData .Net V7.x*

### Reproduce steps

Set WriterSettings.Validations to none and attempt to write a property whose name contains "@" or ".".

### Expected result

The property should be written.

### Actual result

Error Message=The property name 'dynamicExpandedNavigation@odata.nextLink' is invalid; property names must not contain any of the reserved characters ':', '.', '@'.

### Additional Information

This is blocking customers attempting to move from ODL V6 to ODL V7.

**Comment by mikepizzo** [comment]
Fixed by change #1010.

**Comment by srinivasupadhya** [comment]
@mikepizzo can you please repose to this [post](https://stackoverflow.com/questions/55085301/odata-disable-property-name-validation) if you know the answer?
