### ISSUE TITLE
Unable to register regular MVC routes when Odata route registered in a aspnet core app

### ISSUE THREAD

**Issue by shibut12** [OData/odata.net#1026]
*Short summary (3-5 sentences) describing the issue.*
I'm getting following error when I registered a regular MVC route in my aspnet core web app that already has a Odata route defined.
ArgumentNullException: Value cannot be null.
Parameter name: routeName
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestScope(HttpRequest request, string routeName)

The error started appearing after I registered a regular MVC route in startup.cs.

My app source code is maintained in https://github.com/shibut12/netcore-odata-v4.git

### Assemblies affected
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions

### Reproduce steps

1. git clone https://github.com/shibut12/netcore-odata-v4.git
2. cd netcore-odata-v4
3. Open ODataNetCore in visual studio
4. Build and run .net core web app and error will appear in web browser

### Expected result
The application is supposed to allow OData routes and regular ASPNET MVC routes work side by side.

### Actual result
Error is thrown while application is loading.
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
Parameter name: routeName
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestScope(HttpRequest request, string routeName)
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestScope(HttpRequest request, string routeName)
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestContainer(HttpRequest request, string routeName)
Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetRoutingConventions(HttpRequest request)
Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates(RouteContext context)
Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Routing.Route.OnRouteMatched(RouteContext context)
Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Routing.RouteCollection+<RouteAsync>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by xuzhg** [comment]
@shibut12 It looks you are meaning the Asp.Net Core using Web API OData. I move your issue to:  https://github.com/OData/WebApi/issues/1197 and close this one.
