### ISSUE TITLE
EnumMember not supported in the Annotation

### ISSUE THREAD

**Issue by zmyvszk** [OData/odata.net#1028]
When I ran the validation library to validate my csdl. I got the following errors:
**ExpressionNotValidForTheAssertedType:The type of the expression is incompatible with the asserted type.**

When I looked into the code, I found that the code doesn't support the EmumMember in the Annotation.

Just want to verify this situation and hope it helps!

Thanks!

### Assemblies affected

6.x

**Comment by xuzhg** [comment]
Merged at #1031. Thanks!

**Comment by xuzhg** [comment]
Keep it open whether we should make sure to port it to maintenance-6.x branch.

**Comment by AlanWong-MS** [comment]
Nope
