### ISSUE TITLE
PR #951 (maintenance-6.x) needs to be ported to master for Microsoft.OData.Client 7.x JSON Batch support

### ISSUE THREAD

**Issue by biaol-odata** [OData/odata.net#1034]
*Microsoft.OData.Client 7.x support for JSON Batch: It needs to be ported from work done on approved PR for maintenance-6.x branch: https://github.com/OData/odata.net/pull/951.*
*Note that the ODL-Core part of PR #951 has been ported to 7.x (master) via PR #992, what is remaining is the ODL-Client part that needs to be ported to 7.x(master).*

### Assemblies affected

*Microsoft.OData.Client 7.x.*

### Reproduce steps

*N/A.*

### Expected result

*N/A.*

### Actual result

*N/A.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by robward-ms** [comment]
Fixed in 7.4.0.
