### ISSUE TITLE
Support reading/writing OData 4.01 compatible JSON payloads

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1037]
OASIS has defined a [4.01 version](http://docs.oasis-open.org/odata/odata-json-format/v4.01/csprd04/odata-json-format-v4.01-csprd04.html) of the OData JSON format with a number of simplifications. ODL should support reading/writing JSON format according to OData 4.01.

### Assemblies affected

ODL 7.4.

### Additional detail

In PR #989 we added support for writing the new 4.01 delta format by specifying ODataVersion.401 in WriterSettings.  In addition to supporting the new Delta format, we need to make sure that the generated JSON complies with additional 4.01 requirements.  Specifically, when 4.01 is specified, the writer should:
1) Omit the odata. prefix from control information in the JSON payload
2) Omit the # prefix from @type primitive values
3) Recognize metadata and streaming type parameters with and without the "odata" prefix

In Addition, the ODataReader should support reading valid 4.01 payloads, including:
1) Interpret control information with or without the odata. supports control information without the odata. prefix
2) Consume primitive value type annotations with or without the # prefix
3) Recognize metadata and streaming type parameters with and without the "odata" prefix

**Comment by robward-ms** [comment]
Fixed in 7.4.0.
