### ISSUE TITLE
ODataUriExtensions.BuildUri ignores $apply

### ISSUE THREAD

**Issue by voronov-maxim** [OData/odata.net#1045]
ODataUriExtensions.BuildUri does not add $apply to the uri.

### Assemblies affected
Microsoft.OData.Core, Version=7.4.0.20119

### Reproduce steps
```c#
[Fact]
public void BuildUrlWithApplyGroupBy()
{
    var query = new Uri("http://gobbledygook/People?$apply=groupby((FirstName))");
    var parser = new ODataUriParser(HardCodedTestModel.TestModel, ServiceRoot, query);
    ODataUri uri = parser.ParseUri();

    Uri res = uri.BuildUri(ODataUrlKeyDelimiter.Parentheses);
    Assert.Equal(query, res);
}
```
### Expected result
uri should be ?$apply=groupby((FirstName))

### Actual result
uri is empty

**Comment by AlanWong-MS** [comment]
Thanks for filing this issue! I stepped into the code and yep, looks like we're missing the parsing logic for $apply in the [BuildUri implementation](https://github.com/OData/odata.net/blob/3d9811a453fe2d2aad3fa84e499a8c30e2c34c48/src/Microsoft.OData.Core/Uri/ODataUriExtensions.cs#L23).
