### ISSUE TITLE
Odata Edm lib issue with vocabulary

### ISSUE THREAD

**Issue by zmyvszk** [OData/odata.net#1046]
DuplicateAnnotation:The annotated element 'microsoft.graph.managedAppProtection' has multiple annotations with the term 'Org.OData.Core.V1.Description' and the qualifier ''. 

Plan: Might be an issue in Edm lib, same term both defined in type and sub type. Need to investigate on this. This would be a fix on Odata side.

**Comment by mikepizzo** [comment]
This requires investigation; if we are throwing validation exceptions because the same term is defined on a type and a subtype then it's something we need to fix.

**Comment by AlanWong-MS** [comment]
Addressed with #1067
