### ISSUE TITLE
Fix on Odata Edm lib

### ISSUE THREAD

**Issue by zmyvszk** [OData/odata.net#1047]
I saw “SelectRestrictions” used in Graph beta version as below, but I can’t find it in our capabilities definition. Does it include in v4.0.1 version? 

Plan: remove the annotation from ags or make Edm lib not through exception if a property is not defined as type as will. This will be a fix on Odata side.

**Comment by xuzhg** [comment]
It's not OData problem.

`SelectRetrictions` is not defined in OData Capabilities annotation.
The developer should use "NavigationRestrictions" for $select.

Please contact with Graph team to verify.
