### ISSUE TITLE
default stream setup

### ISSUE THREAD

**Issue by kevinciq** [OData/odata.net#1053]
I was after some guidance on porting the old v6 / net45 code setup for attaching a default stream in Microsoft.AspNetCore.OData 7.0.0-beta1 / asp.net core 2.0.

e.g. ODataUtils.SetHasDefaultStream.

### Reproduce steps

In v6, I would setup the following:

            config.Routes.MapHttpRoute("myobjdownload",
                    "data/MyObj/{id}/content",
                    new { controller = "MyObj", action = "DownloadMyObj},
                    null);

Followed by:

            var entityType = model.FindDeclaredType(typeof(MyObj).FullName);
            ODataUtils.SetHasDefaultStream(model, entityType as IEdmEntityType, hasStream: true);
            model.SetHasDefaultStream(entityType as IEdmEntityType, hasStream: true);

I'd also have to specify a serializer:

            config.Formatters.InsertRange(
                                        0, 
                                        ODataMediaTypeFormatters.Create(
                                                                        new MySerializerProvider(),
                                                                        new DefaultODataDeserializerProvider()
                                                                        )
                                        );

And in `MySerializerProvider` override `GetEdmTypeSerializer` to find my implementation of `ODataEntityTypeSerializer` for my domain object:

        public override ODataEntry CreateEntry(SelectExpandNode selectExpandNode, EntityInstanceContext entityInstanceContext)
        {
            var entry = base.CreateEntry(selectExpandNode, entityInstanceContext);

            var instance = entityInstanceContext.EntityInstance as T;

            if (instance != null)
            {
                entry.MediaResource = new ODataStreamReferenceValue
                {
                    ContentType = "application/pdf",
                    ReadLink = MyUrlBuilder(instance, entityInstanceContext)
                };
            }
            return entry;
        }

Doing an OData pull on my service would then embed the following in my objects:

            odata.mediaContentType=application/pdf
            odata.mediaReadLink=https://myurl/data/myobj/%3fid%3dmyid/content

I would then declare the controller method like so:

        [HttpGet, HttpHead]
        public HttpResponseMessage DownloadMyObj(string id)
        {

And I could request it via:

                using (HttpClient client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/pdf"));
                    using (HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, "https://myurl/data/myobj/?id=myid/content"))
                    using (HttpResponseMessage response = client.SendAsync(request).Result)

### Expected result

In v7, I have the following code in the controller:

        [HttpGet, HttpHead]
        public FileStreamResult DownloadMyObj(string id)

And this in my Startup:

            var builder = new ODataConventionModelBuilder(app.ApplicationServices);
            var myObj= builder.EntitySet<MyObj>(nameof(MyObj).ToLower()).EntityType.HasKey(s => s.Id);
            var model = builder.GetEdmModel();
            app.UseMvc(routeBuilder =>
            {
                routeBuilder.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
                routeBuilder.MapODataServiceRoute("ODataRoute", "data", model);
                routeBuilder.EnableDependencyInjection();
            });

### Actual result

Apologies, but after going through all the docs and tests I haven't been able to figure out a way to do what I did in v6 in v7. So, I thought I'd ask if there was any guidance on this that I'm missing.

In v6 I was able to have my domain objects output with a default stream linked for a PDF attachment relevant to the domain object.

**Comment by kevinciq** [comment]
Apologies, wrong repo I think. I got this working via https://github.com/OData/WebApi/issues/772#issuecomment-348670747 and implementing my own `ODataResourceSerializer`

**Comment by biaol-odata** [comment]
Resolved.

**Comment by norcino** [comment]
@kevin-osborne I am trying without success to do what I was use to do using SetHasDefaultStream in OData for .net framework.
I need to add the odata media link read link and content type, can you point me to some resource or example?

**Comment by kevin-osborne** [comment]
> @kevin-osborne I am trying without success to do what I was use to do using SetHasDefaultStream in OData for .net framework.
> I need to add the odata media link read link and content type, can you point me to some resource or example?

@norcino see https://github.com/kevin-osborne/ODataSample
