### ISSUE TITLE
.NET Core support for Microsoft.Spatial

### ISSUE THREAD

**Issue by roji** [OData/odata.net#1060]
Microsoft.Spatial doesn't support .NET Core, which limits its usefulness if it's intended to be a general spatial type library.

/cc @divega @ajcvickers

**Comment by xuzhg** [comment]
@roji 

What do you mean "Microsoft.Spatial doesn't support .NET Core?".

Since v7.1.1,  Microsoft.Spatial includes the .Net Standard version. See Release note at: http://odata.github.io/odata.net/v7/#ODL-7.1.1

If you create .NET project and refer to the Microsoft.Spatial nuget package, it should work as below:

![image](https://user-images.githubusercontent.com/9426627/35706856-406e8b3c-075c-11e8-8fd3-d30c1a8b777a.png)

Thanks your reporting and Please let us know any further questions.

Regards,
-OData Team

**Comment by roji** [comment]
Apologies, I missed that while looking at your build system - I can indeed see the latest nuget including .NET Standard 1.1.

Are you intending this to be a general purpose spatial type library, to be used by database providers to represent spatial data?

**Comment by xuzhg** [comment]
From OData .NET implementation, I think that's right.
However, I saw your other issue to support WKB, That's not in our plan currently to extend Microsoft.Spatial to support general spatial database.  So, you can transfer your Data to WKT and use the library as well.

**Comment by roji** [comment]
@xuzhg thanks for your responses. An approach that would pass through WKT would be problematic from a performance standpoint - but a database provider could implementing the binary reading/writing itself, using only the types from Microsoft.Spatial.

/cc @divega

**Comment by divega** [comment]
> but a database provider could implementing the binary reading/writing itself

@roji do you think this logic change from provider to provider? If the answer is now, we may want to try the path of asking OData to consider a PR that adds WKB support.

Anyway, it seems with .NET Standard support we probably have enough to prototype something.

**Comment by roji** [comment]
@divega I'm not sure how critical WKB support actually is, or to what extend it's a standard wire format across databases. I know PostgreSQL uses an extension of WKB that they call EWKB, and I'm not sure it's 100% compatible. SQL Server has its own thing, although as you guys said maybe database-side conversion could yield a WKB stream instead.

Long story short, I already have code reading PostgreSQL's EWKB binary representation into types, it should be fairly easy to at least prototype reading into Microsoft.Spatial. I'll try to do this in the coming days if I can squeeze it in.
