### ISSUE TITLE
OData self-referencing hierarchy support.

### ISSUE THREAD

**Issue by ag-petrov** [OData/odata.net#1064]
I have a few questions that I can't answer myself after reading the [docs](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html). For example if you have the following model which represents the basics of a self-referencing hierarchy(**ReportsTo** points to **EmployeeID** of its parent).

```
public class Employee
    {
        // Primary key
        public int EmployeeID
        {
            get;
            set;
        }

        public string FirstName
        {
            get;
            set;
        }

        // Foreign key
        public int ReportsTo
        {
            get;
            set;
        }
    }
```

1. How can one get the entire tree structure? I suppose that here **$levels=max** shoud be used?
2. If we can get the entire structure, can we get it, filter it and sort it in a single request?
3. How can we get the direct children(subordinates) of a single employee?
4. Can we get the N - levels of subordinates for a given employee?
5. Is there any specific query for getting the top level employees?

**Comment by hadjieva** [comment]
@AlanWong-MS We would appreciate if you can answer the questions above, because they are related to our next release and the possibility to provide support for Hierarchy with OData v4.

**Comment by KenitoInc** [comment]
Closing this.
Feel free to create a new issue if there are any more questions to be answered.
