### ISSUE TITLE
Case Insensitive is broken for concurrent parsers

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1065]
Creating an ODataUriParser resets all other ODataUriParsers in the app domain using the default ODataUriResolver to case insensitive.

### Assemblies affected

OData .Net lib 7.x

### Reproduce steps

~~~csharp
var parser1 = new ODataUriParser(model, url);
parser1.Resolver.EnableCaseInsensitive = true;
var parser2 = new ODataUriParser(model, url);
Console.WriteLine("Parser1 is {0}", parser1.Resolver.EnableCaseInsensitive ? "CaseInsensitive" : "CaseSensitive");
~~~

### Expected result

Parser1 is CaseInsensitive

### Actual result

Parser1 is CaseSensitive

### Additional detail

Each time a new instance of an ODataUriParser is created, it creates a new instance of ODataUriParserConfiguration.  The constructor of ODataUriParserConfiguration sets it's Resolver to the ODataUriResolver default instance, then sets EnableCaseInsensitiveUriFunctionIdentifier to false.  Setting EnableCaseInsensitiveUriFunctionIdentifier to false sets the EnableCaseInsensitive property on the Resolver to false.  The end result is that, if an application creates an ODataUriParser, sets EnableCaseSensitive to true, and then somewhere else in the app domain another ODataUriParser is created, EnableCaseSensitive is reset to false.  The work-around is to always create a new instance of an ODataUriResolver for the ODataUriParser before setting case insensitive.

**Comment by biaol-odata** [comment]
I think it might be due to the fact that the ODataUriResolver is a singleton: http://odata.github.io/odata.net/v7/#01-05-di-support

**Comment by mikepizzo** [comment]
Fixed, along with several other case insensitivity issues, as part of PR #1063.
