### ISSUE TITLE
Odata Query on primary key of not existentelement  key delivers exception instead of empty result

### ISSUE THREAD

**Issue by slnetgit** [OData/odata.net#1072]
*Querying on primary keys generates an exception when the key does not exist. 
The workaround is to add a dummy true expression in the condition (eg : 1==1 && item.Id == XXX).
This Forces a filer Expression to be generated instead of a Primary key request
*

### Assemblies affected
wcf odata 5.8.3 and older

### Reproduce steps

Without the dummy expression the ADO.NET request results in querying :
http: //localhost//test.svc/Role(XXX)
With the dummy condition, the request is:
http: //localhost//test.svc/Role()?$filter=true and (Id eq 1)
The expected behaviour (null returned) is correct in the second case.

My case Looks like 
string maskeNr = currentLs.abrech_maske;
DataServiceQuery<abrmaske> abrmaskeq =    ent.abrmaske.Where(p => p.ab_nr == maskeNr&&1==1) as DataServiceQuery<abrmaske>;
               abrmaske abrmaske = abrmaskeq.SingleOrDefault();
If I do´nt use the 1==1 I run into a problem when the query does not deliver a row.

### Expected result
Querying by an Expression like 

abrmaske  result =    ent.abrmaske.Where(p => p.ab_nr == maskeNr) .SingleOrDefault();
should deliver either a result of the oelement or null, bnut never an exception. 

( as implied by the Notation of the Expression,)

*What would happen if there wasn't a bug.*

### Actual result

Querying for an entity which does not exist delivers a resorce not found exception from the server

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by AlanWong-MS** [comment]
@slnetgit, thank you for opening this issue. At this time, our OData 5.x branches are under maintenance and will receive security fixes, if any. The ongoing recommendation is to move to newer versions; if the issue still exists in our master branch, we'll be happy to accept it. Thanks for your understanding.
