### ISSUE TITLE
Better story for creating complex spatial types

### ISSUE THREAD

**Issue by roji** [OData/odata.net#1073]
According to [your documentation](http://odata.github.io/odata.net/v7/#03-01-define-spatial-property), it would seem that creating spatial types beyond GeometryPoint pretty much requires one to download a separate [SpatialFactory.cs](https://github.com/OData/odata.net/blob/ODataV4-7.x/test/FunctionalTests/Microsoft.OData.TestCommon/SpatialFactory.cs) file from your test suite. It's not an amazing user story for a library to not come with decent means to create its own types - does it make sense to simply include SpatialFactory.cs inside the library?

**Comment by AlanWong-MS** [comment]
@roji, thanks for bringing this up. The SpatialFactory.cs file that you linked does seem to have valuable code that could belong in the library itself. A good point from here is to open a PR with the proposed change, and then we can take a formal look at it.

**Comment by roji** [comment]
Hi Alan, thanks for the quick answer.

I've looked inside, and SpatialFactory seems to cover a lot of internal complexity. The API it exposes seems to be pretty good, so it could be a matter of just including it into your package - unless you want to review the API and see if it could be improved. I'm not sure exactly what value I can bring to this, though...

/cc @divega @ajcvickers

**Comment by xuzhg** [comment]
Closed as duplicated to #509.
