### ISSUE TITLE
No way to override Primitive Serialization and deserialization of Payload.

### ISSUE THREAD

**Issue by shahzorkhan123** [OData/odata.net#108]
We are looking to expose few properties that are string types as Edm.Binary.
We want to avoid extra effort of deserialization from payload (in ODL), then serialization to string for our data layer,

The point of extensibility we want is at 
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightReaderUtils.cs#L99 
ConvertValue()

The expectation is something like

```
IODataPrimitiveConverter
{
 public object ConvertToPayloadValue( 
      object value, 
      IEdmPrimitiveTypeReference primitiveTypeReference, 
      ODataMessageReaderSettings messageWriterSettings);

public object ConvertFromPayloadValue( 
      object value, 
      IEdmPrimitiveTypeReference primitiveTypeReference, 
      ODataMessageReaderSettings messageReaderSettings);
}
```

**Comment by congysu** [comment]
Thanks @shahzorkhan123 for reporting the issue.  Please feel free to send a pull request on it.

**Comment by congysu** [comment]
Follow-up check-in: Add PayloadValueConverter API 2912b73d92d16c85d57e7577fe370a814d2cb203
