### ISSUE TITLE
ODL 7.x no longer writes type annotations for resource collections in full metadata

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1086]
ODL 6.x wrote type annotations for resource collections in full metadata. ODL 7.x no longer does so.

### Assemblies affected

*OData .Net lib 7.x.*

### Reproduce steps

Write an expanded collection of resources in full metadata.

### Expected result

In ODL 6.x, these would be written with the type annotation.

### Actual result

In ODL 7.x., the type annotation is missing.

### Additional Info

By spec, the type annotation for nested collections and resources is not strictly required, even in full metadata.  But, since we wrote this information in ODL 6.x, we should continue to write in ODL 7.x.  We can omit this in 4.01.

**Comment by tloten** [comment]
I've run into this issue - my odata server is using ODL v7.2, and a number of it's clients are using ODL v6.13.
If I bump the server to v7.5, the v6.13 clients that are issuing requests in the form:
`client.Widgets.AddQueryOption("$expand", "Children($select=Id)").ToList();` 
will fail as the client isn't able to process the type annotation that is now present.

I notice the pull-request had a reverted commit that looked like the compatiblity mode would allow control over the annotation. Was there a reason that was reverted/omitted?
Happy to provide more details if required, or I can make a new issue if that's better. Thanks.
