### ISSUE TITLE
URI parsing without validating properties (question)

### ISSUE THREAD

**Issue by DFKA** [OData/odata.net#1095]
Hi,

I wanted to hear if it is possible to use ODataUriParser or similar, to parse a OData URI without validating the properties?

My current case is that I’m parsing URI’s saved in DB, and allowing the user to change the different clauses, like $filter.

Occasionally properties which are used in $filter are removed from the OData metadata, which results in; “Could not find a property named '<old property>' on type ‘<type>’ when using ODataUriParser. ParseFilter.

What I’m trying to archive is to display all the properties in $filter for the user, including the removed ones, so that the user can fix it themselves.

Thanks,
DFKA

**Comment by mikepizzo** [comment]
The easiest way to do this is to mark the type as "open"; then the ODataUriParser will return a DynamicPathSegment for unknown properties.

**Comment by DFKA** [comment]
Thanks for the responce.
When you mention type as “open”, is that what’s equal to OpenType="true" for EntityType and ComplexType?

What is the best way to set this? Do I need a custom type resolver, or can I update it directly using the EDM model?

**Comment by mikepizzo** [comment]
Yes; this is equivalent to OpenType="true".

In the EDM model, you can set this when creating the type:
~~~c#
     var entityType = model.AddEntityType("ns", "entityType", /*baseType*/null, /*isAbstract*/false, /*isOpen*/true);
~~~

**Comment by DFKA** [comment]
Ok, and it can’t be changed afterwards?
I’m currently reading the EDM model with ODataMessageReader.

**Comment by mikepizzo** [comment]
Unfortunately the IsOpen property on EdmEntityType and EdmComplexType is read-only.

**Comment by KenitoInc** [comment]
@DFKA 
Closing this issue. Feel free to create a new issue if you encounter any problems
