### ISSUE TITLE
Relative Metadata Paths in OData Client Generator T4

### ISSUE THREAD

**Issue by mprigge** [OData/odata.net#1103]
The OData Client generation code clearly requires an absolute path. For us, that's been kind of annoying as our APIs implement authentication which requires us to cache a copy of the API metadata in a file for the T4 to consume. Additionally, different developers have their code in different locations on their development systems, so requiring an absolute path can be troublesome.

I've hacked our ttinclude to detect whether a relative path was provided and then attempt to resolve it using Host.ResolvePath(). Is that something that others would find useful? If so, I can contribute it back with updates to the instructions, etc (or an existing contributor can just grab the snippet below).

This slides into the ttinclude at around line 119. It attempts to determine whether the supplied value is a relative path. If it is, it resolves the path and then lets the rest of the existing logic run its course.

```
if(Uri.TryCreate(value, UriKind.Relative, out uri)) {
	value = Path.GetFullPath(Host.ResolvePath(value));
}
```

@AlanWong-MS - Tagging you here as I know you were working on the code generator recently, but please disregard if that's no longer true.

**Comment by AlanWong-MS** [comment]
That sounds like a cool idea @mprigge! [Here's the location](https://github.com/OData/odata.net/blob/master/src/CodeGen/ODataT4CodeGenerator.ttinclude#L119) (~line 119) being referenced in the ttinclude file. If you decide to move forward with integrating that feature into Client Generator, you're more than welcome to open a PR for it and we can take a look into merging it.

**Comment by noakesey** [comment]
Hi @mprigge - did you ever raise a PR for this?  I think it will help the D365FO community.  Want me to raise it?

**Comment by KenitoInc** [comment]
Currently we only support code generation using the [OData connected service](https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService). If this issue still persists, kindly create a new issue at https://github.com/OData/ODataConnectedService/issues
