### ISSUE TITLE
ContextUrl should include explictly selected nav props

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1104]
*According to OData 4.01, An explicitly selected nav prop should appear in the contextUrl without a () suffix even if it is also $expanded. $select means "include nav link". $expand means "include inline data".*

### Assemblies affected

*ODL 6.x, 7.x*

### Reproduce steps

$select=navProp,$expand=navProp($select=prop1)

### Expected result

Contexturl should be: navProp,navProp(prop1)

### Actual result

Contexturl is: navProp(prop1)

### Additional detail

In OData 3.0, the user was required to explicitly $select things that were $expanded.
In OData 4.0, we said that $expand implicitly meant you wanted to select, and that $select of a nav prop meant you wanted the navLink.
To address this, in ODL for OData 4.0, we automatically add an $expand nodes to the $select.
This means that we can't tell whether a nav prop has been explicitly selected or implicitly added because it was $expanded.
Later, when we generate a ContextUrl, we remove any $select items that are also $expand items.

**Comment by biaol-odata** [comment]
PR #1286 has been merged. Issue can be closed as fixed.
