### ISSUE TITLE
Where is the documentation on how to use the OData.Client

### ISSUE THREAD

**Issue by AmitBhatnagar24** [OData/odata.net#1117]
http://odata.github.io/ has a [tutorial ](http://odata.github.io/odata.net/)on how to use the OData Client  this points to a [page ](http://odata.github.io/odata.net/#04-01-basic-crud-operations)where the client section examples do not work.

So then I goto the [library version 7 document](http://odata.github.io/odata.net/v7/) page and there is no client related documentation.

Any suggestions on how I can use the latest version and see working examples? The unit tests do not provide any clarity at all.

**Comment by gathogojr** [comment]
[Getting Started with OData Client](https://docs.microsoft.com/en-us/odata/client/getting-started)
