### ISSUE TITLE
OData Client & T4 documentations

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#112]
Including, e.g.:
Get started tutorials
Guides:
  CRUD, query, batch, etc.
Corresponding samples.

**Comment by LaylaLiu** [comment]
Committed in following two commits:
https://github.com/OData/odata.net/commit/3520efa62733a281b71df4803d28c262b8f45c5c
https://github.com/OData/odata.net/commit/d23697c8e4c71e95924339355763866073d36964
