### ISSUE TITLE
Do we still need config.EnableEnumPrefixFree(true)?

### ISSUE THREAD

**Issue by dgq111** [OData/odata.net#1125]
*We are biting the bullet and upgrading to 7.x from 6.x - Do we still need config.EnableEnumPrefixFree(true)?*

### Assemblies affected

*This function is not provided in class HttpConfiguration after update, this is because updating the package Microsoft.AspNet.WebApi.Core package to v5.2.4 introduced a new Microsoft.Web.Http.dll.
In the documentation of OData v4.01, the new OData spec allows to query without namespace and enum type, but not sure why this method is removed in Microsoft.AspNet.WebApi.Core package.*

**If we still need that, what is the replacement?**

**Comment by biaol-odata** [comment]
@dgq111 looks like that the question is for WebAPI instead of ODL? And you can find an related discussion: https://github.com/OData/WebApi/issues/904.
