### ISSUE TITLE
OData 7.4; url convention: http://domain.com/xxx/xxx/EntitySet?$filter=NavigationPropertyToCollection/any() fails

### ISSUE THREAD

**Issue by dgq111** [OData/odata.net#1127]
This url convention fails in 7.4 for some reason: 
*http://domain.com/xxx/xxx/EntitySet?$filter=NavigationPropertyToCollection/any()*

Using the previous version of 6.14, this query worked well.

**Error message:** The property 'NavigationPropertyToCollection' cannot be used in the $filter query option.
**Exception type:** Microsoft.OData.ODataException
**Source:** System.Web.OData

**Comment by mikepizzo** [comment]
Can you provide a repo?  Something like:

~~~c#
            EdmModel model = new EdmModel();

            var entityType = model.AddEntityType("ns", "entityType");
            entityType.AddKeys(entityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            var childEntityType = model.AddEntityType("ns", "childEntityType");
            childEntityType.AddKeys(childEntityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));

            entityType.AddUnidirectionalNavigation(new EdmNavigationPropertyInfo()
            {
                Name = "NavigationPropertyToCollection",
                Target = childEntityType,
                TargetMultiplicity = EdmMultiplicity.Many
            });
            
            var container = model.AddEntityContainer("ns", "container");
            container.AddEntitySet("EntitySet", entityType);

            string relativeUri = @"EntitySet?$filter=NavigationPropertyToCollection/any()";
            ODataUriParser parser = new ODataUriParser(model, new Uri(relativeUri, UriKind.Relative));

            var filter = parser.ParseFilter();
            Debug.Assert(filter != null && filter.Expression.Kind == QueryNodeKind.Any);
~~~

**Comment by dgq111** [comment]
Mike,
Thanks again for responding! 
We specifically upgraded the following packages:

Microsoft.AspNet.OData 5.9.1
Microsoft.OData.Core 6.16
Microsoft.OData.Edm 6.16
Microsoft.Spatial 6.16

TO

Microsoft.AspNet.OData 6.0.0
Microsoft.OData.Core 7.4.1
Microsoft.OData.Edm 7.4.1
Microsoft.Spatial 7.4.1

I was able to reproduce in the above unit test by adding this snippet before the assert:
```
filterQueryValidator.Validate(filter,new ODataValidationSettings()
            {
                AllowedArithmeticOperators = AllowedArithmeticOperators.All,
                AllowedFunctions = AllowedFunctions.AllFunctions,
                AllowedLogicalOperators = AllowedLogicalOperators.All,
                AllowedQueryOptions = AllowedQueryOptions.Filter
                                      | AllowedQueryOptions.Format
                                      | AllowedQueryOptions.Count
                                      | AllowedQueryOptions.OrderBy
                                      | AllowedQueryOptions.Select
                                      | AllowedQueryOptions.Skip
                                      | AllowedQueryOptions.Top,
                MaxTop = 50
            },model);
```
This is *FilterQueryValidator* coming from Microsoft.AspNet.OData 6.0.0 specifically in the System.Web.OData.dll.  It appears that the query is parsing fine, but not passing this validation.  

We are using the ODataConventionModelBuilder class to build our EdmModel

**Comment by mikepizzo** [comment]
Make sure that you are setting EnableFilter to true in the DefaultQuerySettings passed to your FilterQueryValidator:

~~~c#
 var filterQueryValidator = new FilterQueryValidator(
         new DefaultQuerySettings() { 
             EnableFilter = true
          } );
~~~

I believe that Microsoft.AspNet.OData 5.x defaulted to true for the various Enable flags, where-as in 6.x they need to be explicitly set to enable.

**Comment by dgq111** [comment]
@mikepizzo Thank you for your time
