### ISSUE TITLE
ODatalib 7.4; url convention $select is failing in particular case

### ISSUE THREAD

**Issue by dgq111** [OData/odata.net#1128]
Using the following URL convention:
http://domain.com/xxx/xxx/EntitySet(12345)/ChildEntity(123)?$select=ChildEntityProperty

Notice we are requesting the ChildEntity property in the $select clause.  It is failing validation using ODatalib 7.4.

The previous ODatalib 6.14 that we were using, it does not fail.

*Error Message:* The property 'ChildEntityProperty' cannot be used in the $select query option.
*Exception type:* Microsoft.OData.OdataException.
*Source:* System.Web.OData.

**Comment by mikepizzo** [comment]
Hi @dgq111;
Which specific version of ODataLib are you using? are you using the latest (7.4.3)?

Can you provide a snippet of your model, showing (at least):
1) Entity type for EntitySet
2) Entity type for ChildEntity nav prop on EntitySet

Even better would be a simple repo using ODataLib; something like the following:
~~~c#
            EdmModel model = new EdmModel();
            var entityType = model.AddEntityType("ns", "entityType");
            entityType.AddKeys(entityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            var childEntityType = model.AddEntityType("ns", "childEntityType");
            childEntityType.AddKeys(childEntityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            childEntityType.AddStructuralProperty("ChildEntityProperty", EdmPrimitiveTypeKind.String);
            entityType.AddUnidirectionalNavigation(new EdmNavigationPropertyInfo()
            {
                Name = "ChildEntity",
                Target = childEntityType,
                TargetMultiplicity = EdmMultiplicity.Many
            });
            var container = model.AddEntityContainer("ns", "container");
            container.AddEntitySet("EntitySet", entityType);

            string relativeUri = @"EntitySet(12345)/ChildEntity(123)?$select=ChildEntityProperty";
            ODataUriParser parser = new ODataUriParser(model, new Uri(relativeUri, UriKind.Relative));
            var select = parser.ParseSelectAndExpand();
            var selected = select.SelectedItems.First() as PathSelectItem;

            Debug.Assert(selected != null && selected.SelectedPath.FirstSegment.Identifier == "ChildEntityProperty");
~~~

**Comment by mikepizzo** [comment]
Make sure that you are setting EnableSelect to true in the DefaultQuerySettings passed to your FilterQueryValidator:

~~~c#
 var filterQueryValidator = new FilterQueryValidator(
         new DefaultQuerySettings() { 
             EnableSelect = true
          } );
~~~

I believe that Microsoft.AspNet.OData 5.x defaulted to true for the various Enable flags, where-as in 6.x they need to be explicitly set to enable.

**Comment by dgq111** [comment]
@mikepizzo  Thank you for your time
