### ISSUE TITLE
Edm Lib documentation

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#114]
Get started tutorials, guides, samples, e.g.:
  Create an Edm model
  Search Edm model schema elements
  Add metadata annotations
  ...

**Comment by MrTomWhite** [comment]
Do you think you could attach a link to the issue when these tasks are closed?

If the docs are plaintext you could make a pr for proofing and testing the docs

**Comment by congysu** [comment]
Thanks @MrTomWhite. @lewischeng-ms, see if could add the commit hashs or the gh-pages http://odata.github.io/odata.net/

**Comment by lewischeng-ms** [comment]
@MrTomWhite @congysu , please refer to https://github.com/OData/odata.net/commits/gh-pages. There is one commit for each post. Thanks.

**Comment by congysu** [comment]
* 2. [EDMLIB](http://odata.github.io/odata.net/#02-01-build-basic-model)
  * 2.1 Build a basic model
  * 2.2 Read and write models
  * 2.3 Define entity relations
  * 2.4 Define singleton
  * 2.5 Define type inheritance
  * 2.6 Define operations
  * 2.7 Define annotations
  * 2.8 Using model utilities
  * 2.9 Other topics
