### ISSUE TITLE
Port client-side DateTime support fix to 7.x

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#1151]
DateTime Support on the client side is missing. See #715 for PR details.

### Assemblies affected
OData Client/Core 7.4.4

### Reproduce steps
See #473. 

### Expected result
DateTime should be supported in the client library.

### Actual result
DateTime is not supported in the client library.

**Comment by wmalgadey** [comment]
Is there a release plan, when this could be pushed to nuget? after all tests are green of course.

**Comment by wmalgadey** [comment]
So! Will you merge it? Could it happen in the next release of odata client 7.x?

**Comment by AlanWong-MS** [comment]
Pending CR on the PR, I've pinged some members to help with that. :) We should be able to fit it into the next release of 7.x.

**Comment by AlanWong-MS** [comment]
Merged, it'll be in next release of 7.x.
