### ISSUE TITLE
Perf: OData Property Cache Handler can avoid allocating more strings

### ISSUE THREAD

**Issue by ysanghi** [OData/odata.net#1172]
Odata.PropertyCacheHandler.GetProperty can be optimized to avoid string allocations.

### Assemblies affected

OData .NET v7.x 

### Reproduce steps
Perf optimization.

### Expected result

Less or not string allocations.

### Actual result

String allocations happening.

**Comment by xuzhg** [comment]
I merged your PR. Thanks your contribution.

**Comment by biaol-odata** [comment]
From PropertyCacheHandlerTests::PropertyHandlerGetProperty(), there is an assert failure at this line:
            Debug.Assert(depth >= 1, $"{nameof(depth)} should always be greater than 1");
where value of depth is 0.

Should we change L 41-42 in PropertyCacheHandler.cs with the following:
            Debug.Assert(depth >= 0, $"'depth' should always be greater than or equal to 0");
            string depthStr = depth == 0 ? string.Empty : depth.ToString(CultureInfo.InvariantCulture);

**Comment by biaol-odata** [comment]
Close as merged.
