### ISSUE TITLE
JSON query support

### ISSUE THREAD

**Issue by xiaotupansy** [OData/odata.net#1178]
Can you consider to support json query in odata?

Here is a typical odata query uri :
http://localhost:54179/api/User?$filter=Nickname eq 'eeeeee'

what I want is like grahpql :
http://localhost:54179/api/User?{human(id: "5") {Nickname}}

I think it's more convenient to use json query other than odata query syntax for frontend developers.
If this can't be done directly, a js library to convert json query to odata query syntax would be helpful.

**Comment by KenitoInc** [comment]
Closing this.
Feel free to create a new issue if there are any more questions to be answered.
