### ISSUE TITLE
Should JSON Batch convert header names to lower case?

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1179]
*ODataJsonLightBatchWriter, when it writes out headers, converts the header name to lower case, which should be fine (since HTTP specifies that header fields are case-insensitive), but clients may be doing case-sensitive comparisons.  We could consider not forcing to lower case, and letting the writer choose what case to write the headers.*

### Assemblies affected

*OData .Net lib 7.4.x*

### Reproduce steps

*Write out a JSON Batch request/response containing a mixed case header*

### Expected result

*Client may expect the header field name to be written in the same case it is specified in the headers collection.*

### Actual result

*The header field is written in all lower case*

### Additional detail

ODataJsonLightBatchWriter.cs, L603 and L643 call 
~~~c#
                    this.jsonWriter.WriteName(headerPair.Key.ToLowerInvariant());
~~~
we could remove the "ToLowerInvariant()" in order to write in the specified case.

Note that the OData JSON Format currently specifies that header fields are written out in lower case, but we could push that responsibility to the caller by removing the ToLowerInvariant() above.

Note that HTTP supports case-insensitive header comparisons: https://tools.ietf.org/html/rfc7540#section-8.1.2.

**Comment by biaol-odata** [comment]
We should be able to make a quick code update if that is what is needed. However, to help make a through decision, couple points I would like to bring up:

- As mentioned previously in related discussions, both [section for request](http://docs.oasis-open.org/odata/odata-json-format/v4.01/csprd03/odata-json-format-v4.01-csprd03.html#sec_BatchRequest) and [section for response](http://docs.oasis-open.org/odata/odata-json-format/v4.01/csprd03/odata-json-format-v4.01-csprd03.html#sec_BatchResponse) in OData v4.01 protocol, specifies the following: “The name of each pair **MUST be the lower-case header name**”. If ODataJsonLightBatchWriter didn't write the header in lower case, it were not following the spec.
- OData protocol [references HTTP/1.1](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_NormativeReferences), which is case-insensitive; HTTP 2 is not specified by OData protocol yet; Implementation side (Microsoft.OData.Core) has similar reference to HTTP/1.1 as well.

**Comment by biaol-odata** [comment]
@mikepizzo thoughts?

**Comment by mikepizzo** [comment]
We will keep the current behavior, at least for now. We may have to add a switch in the future, but I'd rather not...
