### ISSUE TITLE
Add flag to include "odata." prefix in 4.01 JSON responses

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1180]
*OData 4.01 supports writing JSON responses with or without the "odata." prefix for control information. In ODL, setting the response version to 4.01 always omits the "odata." prefix.  While that should be the default, we should also support a flag for writing the "odata." prefix in a 4.01 response.*

### Assemblies affected

*OData .Net lib 7.4.x*

**Comment by mikepizzo** [comment]
This can be done using dependency injection:

            container.AddService<ODataSimplifiedOptions>(
                Microsoft.OData.ServiceLifetime.Singleton,
                (IServiceProvider provider) => new ODataSimplifiedOptions(ODataVersion.V401)
                {
                    EnableWritingODataAnnotationWithoutPrefix = false
                });

**Comment by madansr7** [comment]
@mikepizzo , this solution does not work in scenarios where DI cannot be applied. What is the suggested pattern in that case?

**Comment by mikepizzo** [comment]
Provided simple sample showing how to support this through a simple custom containerbuilder.
