### ISSUE TITLE
Remove unneeded json string escaping in JsonValueUtils

### ISSUE THREAD

**Issue by maximpashuk** [OData/odata.net#1181]
I am using Microsoft.AspNetCore.OData beta4, but my issue related to Microsoft.OData.Core.

I see differences in json response containing russian language symbols in normal odata query and batched odata query.
Batched odata response always escaping russian symbols while normal response has no escaping.
```
"country": "Россия" <-- no escaping in GET request

"country":"\u0420\u043e\u0441\u0441\u0438\u044f" <-- escaping in $batch request
```

I realize from the docs ([OData JSON Format Version 4.0](http://docs.oasis-open.org/odata/odata-json-format/v4.0/cs01/odata-json-format-v4.0-cs01.html#_Toc365464699) and [RFC4627](https://www.ietf.org/rfc/rfc4627.txt)) that escaping of non-ASCII symbols is not required.
Docs says just that "Any character MAY be escaped"

From source code i realized that $batch endpoint uses [JsonValueUtils](https://github.com/OData/odata.net/blob/fb4630ec1cf49bb10ef41a33bd81863f8b765220/src/Microsoft.OData.Core/Json/JsonValueUtils.cs#L476) there ALL characters with code > 127 ALWAYS escaped.

I think forcing escaping is not optimal - 6 bytes (\uXXXX) on each character is growing json size, also deserializing logic is more complicated.
Also ODataOutputFormatter from ODATA WebApi has to forced escaping.

So please refactor JsonValueUtils to escape symbols only required to be escaped (", \, etc.)

**Comment by mikepizzo** [comment]
Can you clarify where the escaping is occurring? Is it just escaping the URL, or is it escaping properties within a (request? response?) payload?

I was able to write a simple test that produced the following output:

~~~json
{
  "responses": [
    {
      "id": "1",
      "status": 200,
      "headers": {
        "odata-version": "4.0",
        "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"
      },
      "body": {
        "@odata.context": "http://testservice/$metadata#customers",
        "value": [
          {
            "@odata.id": "customers/1",
            "id": "Россия"
          }
        ]
      }
    }
  ]
}
~~~

**Comment by maximpashuk** [comment]
Hi.
Escaping is occurred in properties in response payload when using **/$batch** odata endpoint.
Escaping not occurred when using simple GET/POST requests.

Batched responses has special format, different from format you just posted.

**Comment by mikepizzo** [comment]
I see.
From your example I thought that you were using the new JSON batch format.  Let me try a test with the multipart/mixed format.

**Comment by igor-moskvitin** [comment]
@mikepizzo can you provide some exaple of working json batch, please? (related with https://github.com/OData/WebApi/issues/1532)

**Comment by xuzhg** [comment]
It can repro:

1. Create a model like:
```c#
public class Customer
    {
        public int Id { get; set; }

        public string Country { get; set; }
    }
```

2. Create a controller

```C#
public class CustomersController : ODataController
    {
        [EnableQuery]
        public IActionResult Get()
        {
            Customer c = new Customer
            {
                Id = 1,
                Country = "Россия"
            };
            return Ok(new[] { c });
        }
    }

```

3. Add services:
```C#
services.AddOData();

…

app.UseODataBatching();
app.UseMvc(b =>
   {
         b.MapODataServiceRoute("odata", "odata", GetEdmModel(), new DefaultODataPathHandler(),
                ODataRoutingConventions.CreateDefault(),
                new DefaultODataBatchHandler()
    );
  });
```

4. Send a post request to `http://.../odata/$batch`

```json
{
    "requests": [
       {
         "id": "0d24a607-3fb0-4a83-a8fb-ef33f8c7e4ba",
         "method": "GET",
         "url": "http://localhost:5000/odata/Customers",
         "headers": {
             "accept": "application/json;odata.metadata=full"
          }
        }
    ]
}
```

**Comment by maximpashuk** [comment]
Just few words more about string escaping.

Well-known Newtonsoft.Json serializer has a special enum [StringEscapeHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_StringEscapeHandling.htm) to control escaping behavior during json serialization.

JsonLight serializer in OData has only 'EscapeNonAscii' behavior implemented in terms of newtonsoft.json (see [JsonValueUtils](https://github.com/OData/odata.net/blob/fb4630ec1cf49bb10ef41a33bd81863f8b765220/src/Microsoft.OData.Core/Json/JsonValueUtils.cs#L481))

Probably, compromise solution is to change behavior of JsonValueUtils to escape only control characters ('Default' behavior in terms of newtonsoft.json)

I think this will satisfy most of people.

**Comment by xuzhg** [comment]
Update:

if you set `Accept=application/json`, you will get the correct result: 

```json
{
    "responses": [
        {
            "id": "0d24a607-3fb0-4a83-a8fb-ef33f8c7e4ba",
            "status": 200,
            "headers": {
                "content-type": "application/json; odata.metadata=full; odata.streaming=true; charset=utf-8",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5000/odata/$metadata#Customers",
                "value": [
                    {
                        "@odata.type": "#BatchTest.Models.Customer",
                        "@odata.id": "http://localhost:5000/odata/Customers(1)",
                        "@odata.editLink": "http://localhost:5000/odata/Customers(1)",
                        "Id": 1,
                        "Country": "Россия"
                    }
                ]
            }
        }
    ]
}
```

**Comment by xuzhg** [comment]
@maximpashuk @igor-moskvitin Do you have any chance to take a look about my Pull request about this escape string?  #1242. Please let me know any problem.

**Comment by xuzhg** [comment]
Merged. Thanks.
