### ISSUE TITLE
ODataUriParser: Numbers in resource path cause exception

### ISSUE THREAD

**Issue by antonGritsenko** [OData/odata.net#1184]
I have very strange behavior. I'm using ODataUriParser to parse URLs. Regards http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#_Toc505773200, numbers are allowed in OData resource path:

> 4.3.6 Key-as-Segment Convention
> Services MAY support an alternate convention for addressing entities by appending a segment containing the unquoted key value to the URL of the collection containing the entity. Forward-slashes in key value segments MUST be percent-encoded; single quotes within key value segments are treated as part of the key value and do not need to be doubled or percent encoded.
> Example 25: valid OData URLs:
> http://host/service/Employees/A1245
> http://host/service/People/O'Neil
> http://host/service/People/O%27Neil 
> http://host/service/Categories/Smartphone%2FTablet

But then I try to use something like "http://host/api/v1/Entities/Key2WithNumber" I got 

> Microsoft.OData.UriParser.ODataUnrecognizedPathException : Resource not found for the segment 'Key2WithNumber'.

### Assemblies affected

I'm using Microsoft.OData.Core.7.4.4

### Reproduce steps
Code:
```
parser = new ODataUriParser(this.edmModel, serviceRoot, uri);
parser.ParsePath();

```
uri = "http://host/api/v1/Entity/Key2WithNumber"
serviceRoot = "http://host/api/v1/Entity"
### Expected result

If no number in path then everything works as excepted (so EdmModel is correct).

### Actual result

Exception: Microsoft.OData.UriParser.ODataUnrecognizedPathException : Resource not found for the segment 'Key2WithNumber'.

**Comment by mikepizzo** [comment]
The key as segment convention assumes that the path before the key is an entity collection.  In your example, since the serviceRoot contains "Entity" the "Key2WithNumber" segment is the first segment, which cannot be a key and (in my test) failed whether it contained a number or not.

Also, make sure the segment "Entity" is an entity set, not a single entity, and that you set the slash as the key delimiter.

In the following test, where "EntitySet" is an entity set defined in the model, I was able to successfully parse the query:

            Uri uri = new Uri("http://host/api/v1/EntitySet/Key2WithNumber");
            Uri serviceRoot = new Uri("http://host/api/v1");
            var parser = new ODataUriParser(model, serviceRoot, uri)
            {
                UrlKeyDelimiter = ODataUrlKeyDelimiter.Slash
            };
            parser.ParsePath();

**Comment by mikepizzo** [comment]
Great; thanks for the follow-up @antonGritsenko!
