### ISSUE TITLE
Batch is broken by load balancer (proxy).

### ISSUE THREAD

**Issue by VirusQuartirus** [OData/odata.net#1187]
*When batch request comes through load balancer or proxy ODL fails to read batch request because service base uri differs from batch part uri.*

### Assemblies affected

*OData .Net lib 7.4.*

### Reproduce steps

*Use Fiddler and locally hosted service. Use http://localhost.fiddler as service host name.*

### Expected result

*Batch should work as expected.*

### Actual result

*Service crashes at ODataBatchUtils.ValidateReferenceUri() with following message:
Microsoft.OData.ODataException: 'Absolute URI http://localhost.fiddler/XXX/ is not start with the base URI [http://localhost/XXX/] specified by the operation message.'*

### Additional detail

*Typically proxies and load balancers are adding X-Forwarded-XXX headers to request. So the ODatalib should care of them. Alternatively Client should provide possibility to use BatchPayloadUriOption.RelativeUri in order to avoid such an issue*

**Comment by biaol-odata** [comment]
Closed as merged.
