### ISSUE TITLE
Avoid String allocations when writing strings that require special character handling

### ISSUE THREAD

**Issue by ysanghi** [OData/odata.net#1191]
JsonValueUtils.WriteEscapedJsonString allocates additional strings when dealing with special characters.  

### Assemblies affected

OData .NET LIB

### Additional detail

JsonValueUtils WriteEscapedJsonString uses Substrings to write strings to underlying textwriter but because of the immutable nature of .NET strings it allocates new strings. To further this, strings are objects in .NET and this makes objects visible to GC. This lead high allocations and excessive work needed by GC to clean this objects up. This can be avoided by using a buffer.

**Comment by AlanWong-MS** [comment]
Thanks for filing the issue and opening a PR! The fix has now been merged and should be included in our upcoming ODL release. ETA for the release is slated for end of the month.
