### ISSUE TITLE
Translate a QueryToken to string after creating it via UriQueryExpressionParser.ParseFilter

### ISSUE THREAD

**Issue by mariangemarcano** [OData/odata.net#1193]
I'm evaluating to use OData parser (without the model):

the following works fine:

`var queryToken = new UriQueryExpressionParser(50).ParseFilter("id eq 2")`

I'm looking for a built-in support to translate a QueryToken that contains a filter to string. 

How can this be done?

Or what are the available options to create the filter text after having a QueryToken (the reverse operation)?

**Comment by AlanWong-MS** [comment]
Unfortunately, there isn't native support to translate a QueryToken to a string, only when they're converted to nodes. You could draw ideas from reviewing the "Translate" methods in [NodeToStringBuilder](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Uri/NodeToStringBuilder.cs).

**Comment by mariangemarcano** [comment]
@AlanWong-MS  thanks for the answer, is it possible to create a node from a QueryToken, or do we need a model to accomplish this?

**Comment by AlanWong-MS** [comment]
From taking a look at the [tests for BinaryOperatorToken](https://github.com/OData/odata.net/blob/539543076e7e0328120644934bddcd60c9fea484/test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/Binders/BinaryOperatorBinderTests.cs#L180) (the type of token created from your example "id eq 2"), it seems to be possible but [those methods](https://github.com/OData/odata.net/blob/539543076e7e0328120644934bddcd60c9fea484/src/Microsoft.OData.Core/UriParser/Binders/BinaryOperatorBinder.cs#L44) are not part of the public API. I referenced the links in case sampling the code could work for you. Another option, though not entirely recommended, is to fork your own branch of the code base, convert those methods to public, and then use your local copy of OData.

**Comment by AlanWong-MS** [comment]
Closing for now. Please feel free to comment further if you have more questions and I can re-open. Thanks for the interest!
