### ISSUE TITLE
Expected behaviour for 7.0.0-beta4 on ASP.Net Core

### ISSUE THREAD

**Issue by leadfollowmove** [OData/odata.net#1194]
I have a simple Web API that has a class (customer) with two related entities (people and addresses). I can run in debug and interact with the API through Postman fine. However, if I try and post or put and any of the fields are empty or null the API returns error 400. If I fill in every field, or remove empty fields from my JSON payload the actions work fine. Is this expected or have I missed a setting to ignore empty fields?

When I test this with an Angular 5 client application it doesn't drop empty fields from the JSON payload so my assumption is that OData should just ignore these rather than me needing to somehow remove them from the payload prior to sending?

### Assemblies affected

7.0.0-beta4 

### Reproduce steps

JSON payload:
{
	"Standing":"RED",
	"Addresses": [{"StreetAddress":"95 Bevis road","Suburb":"Applecross","Locale":"","PostCode":"","Active":""}],
	"People":[{"FirstName":"Sally","LastName":"Fields","Mobile":"+61 222 988 199","Email":"sally@gmail.com", "Notify": ""}]
}

### Expected result

Put or Post action would add or update the object.

### Actual result

Status: 400 Bad Request. The input was not valid.

### Additional detail

I'm assuming this is coder-error and that as someone new to this I've made a rookie mistake?

**Comment by xuzhg** [comment]
@leadfollowmove 


What did you mean the empty is the values like `"Locale":"","PostCode":"","Active":""`? 

If the types of `Locale, PostCode, Active` are `string`, the values are accepted. So, Would you please share me your metadata document or point me to your sample repro for me to dig more? Thanks

**Comment by leadfollowmove** [comment]
@xuzhg thanks for responding. I've uploading a repo to help: https://github.com/leadfollowmove/Odata-test

The JSON payload pasted in my OP triggers the 400 error when pushed through Postman.

Payload from my Angular client that also triggers error 400:
{"Standing":"VIP","Addresses":[{"UnitOrBuilding":"","StreetAddress":"88 Smythe Street","Suburb":"Downtown","Locale":"","PostCode":"","HomePhone":"","Notes":"","Active":""}],"People":[{"FirstName":"Pam","LastName":"Greer","Mobile":"44 222 333 444","Email":"","Notes":"","Notify":true}]}

Hope this helps.

**Comment by xuzhg** [comment]
@leadfollowmove 

The problem looks "Active" property 's value can't be "", because it's a `Boolean` type.

When i change your payload and issue a request:

![image](https://user-images.githubusercontent.com/9426627/41801066-3684ed7e-762d-11e8-91f7-8fe100a7c160.png)

I can get the following debug information: 

![image](https://user-images.githubusercontent.com/9426627/41801035-15c1ceb8-762d-11e8-95de-5e99e91361a5.png)

**Comment by leadfollowmove** [comment]
Thanks @xuzhg I hadn't noticed that. Is there a design pattern recommendation for handling this?

Otherwise, I'll look at writing something on the controller for Post and Put actions to check the related entities for empty boolean parameters and set them to false before saving the model to the DB.

**Comment by xuzhg** [comment]
@leadfollowmove you can find the definition about `Boolean` at http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt

```C#
booleanValue = "true" / "false"
```
