### ISSUE TITLE
ODataLib Client fails to deserialize payload with @odata.context relative URL.

### ISSUE THREAD

**Issue by VirusQuartirus** [OData/odata.net#1208]
*When JSON Lite payload contains @odata.context annotation with relative URL instead of absolute URL OData .NET client fails to deserialize response.*

### Assemblies affected

*OData .Net lib 7.5.0.*

### Reproduce steps

*Read response with relative URL in @odata.context annotation. (Use Fiddler Autoresponder?).*

### Expected result

*Client should deserialize response as usual.*

### Actual result

*Client fails with following error:
Microsoft.OData.ODataException: 'The top level context URL '$metadata#FooBar' should be an absolute Uri.'.*

### Additional detail

*According to [OData V4 spec](http://docs.oasis-open.org/odata/odata-json-format/v4.01/cs01/odata-json-format-v4.01-cs01.html#_Toc499720585):
The context annotation returns the context URL (see [OData-Protocol]) for the payload. This URL can be absolute or **relative**.
This output comes from Java Olingo implementation and we are blocked by this issue right now.*

**Comment by Tiberriver256** [comment]
SAP Netweaver Gateway OData v4 APIs also use relative Uri in their responses
