### ISSUE TITLE
OData query is very slow

### ISSUE THREAD

**Issue by patnolan** [OData/odata.net#1209]
Odata queries seem to be extremely slow.

When I run SQL Profiler, a query I execute via OData (which selects the top 20 records) takes less than a second to execute. However, it can take up to 45sec for the data to be returned to the browser.

Is there anyway to speed this up or pinpoint where the performance hit is?

I'm using Microsoft.AspNetCore.OData Version 7.0.0

**Comment by AlanWong-MS** [comment]
@patnolan, thanks for filing this issue! The library is part of our [WebAPI library](https://github.com/OData/WebApi); could you please file your issue there? Could you also please provide the sample query and model that you used (to understand if size of entities could be an issue)?

Closing this so we can take the discussion to the WebAPI side. Thanks!
