### ISSUE TITLE
Reference issue for System.Runtime and Microsoft.Odata.Edm

### ISSUE THREAD

**Issue by QiyuanHU** [OData/odata.net#1213]
I am using vs 2015 update 3, after update to Odata V4 client code generator v7.5, we can no longer generate code.....got reference issue for System.Runtime and Microsoft.Odata.Edm

### Reproduce steps

Install Odata V4 client code generator V7.5
Config my metadata endpoint
Run custom tool

### Expected result
Generate the client code

### Actual result

Compiling Transformation:
Complaining Some dependency not found like System.runtime
Also saying the type or namespace name 'IEdmIntegerValue' could not be found and other namespace not found

### Additional detail

![capture](https://user-images.githubusercontent.com/8180000/42777770-dcc7eea0-88ef-11e8-9159-0c64eeea70a2.PNG)

**Comment by QiyuanHU** [comment]
My endpoint: https://api.aadr.mspim.azure.com/api/v2/$metadata

**Comment by AlanWong-MS** [comment]
Can you try to add the following dependencies to your project?
- System
- System.Data
- System.Data.DataSetExtensions
- System.Net.Http
- System.XML
- System.Xml.Linq

In the past, the extension was compiled with VS2015 and automatically helped add the needed dependencies to the project. We now compile the extension with VS2017 (to enable support for VS2017) and there seems to be an issue with it adding those dependencies for you. The workaround at the moment is to add them manually.

I was able to generate the proxy code with https://api.aadr.mspim.azure.com/api/v2/$metadata and no errors. See screenshots below.

![image](https://user-images.githubusercontent.com/22382722/42845648-7c807954-89cb-11e8-9508-5036986bd836.png)

![image](https://user-images.githubusercontent.com/22382722/42845632-6d593844-89cb-11e8-8df6-55c6cbfd431e.png)

**Comment by AlanWong-MS** [comment]
Another issue could possibly be that you already have Microsoft.OData.Edm installed on your project. The new Client Code Gen has a dependency on Microsoft.OData.Edm 7.5.0 and if you would like to use Client Code Gen, you will have to use [an older version](https://github.com/OData/lab/tree/Tools/Tools) of it.

**Comment by paulodero** [comment]
@QiyuanHU It is recommended to use [OData Connected Service](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) for code generation. Connected service supports VS 2017 and 2019 and uses the latest OData libraries v7.6.3. In case of any issue with code generation please report on [Connected service repo](https://github.com/OData/ODataConnectedService/issues).
