### ISSUE TITLE
Reference issues for CSdlREaderSettings, IEdmVocabularyAnnotations and others.

### ISSUE THREAD

**Issue by StarNamer** [OData/odata.net#1215]
I am trying to generate the OData objects for our MS Dynamics 365 for Finance and Operations system, Following the tutorial at https://blogs.msdn.microsoft.com/odatateam/2014/03/11/tutorial-sample-how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class/, I get multiple errors referenced in the 'tt' files, although the line numbers are way off, so I assume this is actually a problem with the'ttinclude' file.

First few:
The type or namepace name 'CsdlReaderSettings' could not be found...
The type or namespace name 'IEdmVocabularyAnnotation; could not be found....
Cannot implicitly convert type...
etc....

### Assemblies affected

 Trying to use latest OData client code generator (7.5.0) with VS2017. There seem to be several missing references.

### Reproduce steps

Create a new console app (.Nert framework)
Add XML file containing D365fFO metadata download from url https://usnconeboxax1aos.cloud.onebox.dynamics.com/data/$metadata in a OneBox developmnent Hyper-V virtual machine downloaded from LCS.dynamics.com - version is 7.2 Pplatform Update 12.
Add item ODataClient.tt
Edit to include XML file as source.
Save

### Expected result

Generate to 1.2 million line OData file which describes our Dynamics 365 for Finance and Operations set up.

### Actual result

Many errors and output is simply "ErrorGeneratingOutput"

### Additional detail

Since the XML is from a Microsoft product (Dyanmics 365 fFO) and I am only using Microsoft tools, it should be fairly easy to reproduce the bug.

**Comment by StarNamer** [comment]
![image](https://user-images.githubusercontent.com/1997874/43137718-75cc3142-8f44-11e8-9001-0306d2b41956.png)

**Comment by StarNamer** [comment]
I have successfully run this using VS2015 update 3 inside the D365 Onebox. Obviously, the problem is with the VS2017 version.

**Comment by KDGundermann** [comment]
Same Problem here with 
- VS 2017 v15.8.9 
- OData v4 Client Code Generator v7.5.1

using an EDMX generated from Microsoft Dynamics Nav 2018 WebService

**Comment by paulodero** [comment]
@StarNamer We recommend you use [OData Connected Service](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) for client code generation since it is up to date and uses latest OData Libraries v7.6.3. Please register an issue in [OData Connected Service Repo](https://github.com/OData/ODataConnectedService) incase you get challenges.
