### ISSUE TITLE
Is it possible to declare multiple routes for ASPNET.Core OData

### ISSUE THREAD

**Issue by patnolan** [OData/odata.net#1219]
I'm using the Microsoft.AspNetCore.OData 7.0.0 nuget package.

I've registered my OData route prefix like the following.

```
app.UseMvc(routeBuilder =>
{
    var builder = new ModelODataBuilder();
    routeBuilder.EnableDependencyInjection();
    routeBuilder.MapODataServiceRoute("ODataRoutes", "odata/Route1", builder.GetEdmModel(app.ApplicationServices));
});
```

Each OData Controller has a ODataRoutePrefix where the prefix corresponds to an EntitySet declared and configured in the GetEdmModel. For example

`[ODataRoutePrefix("Service1")]
`
However, I need some services to have a route prefix of "odata/Route1" while others have "odata/Route2". For example

http://odata/Route1/Service1 http://odata/Route2/Service2

I can't work out how to configure this. The following code does not work

```
app.UseMvc(routeBuilder =>
{
    var builder = new ModelODataBuilder();
    routeBuilder.EnableDependencyInjection();
    routeBuilder.MapODataServiceRoute("ODataRoute1", "odata/Route1", 
    builder.GetEdmModelForRoute1(app.ApplicationServices));

    routeBuilder.MapODataServiceRoute("ODataRoute2", "odata/Route1", 
   builder.GetEdmModelForRoute2(app.ApplicationServices));
});
```

Could you please advise how this can be done?

I have asked question on StackOverflow but no one seems to know
https://stackoverflow.com/questions/51490177/is-it-possible-to-declare-multiple-routes-for-aspnet-core-odata

**Comment by biaol-odata** [comment]
@patnolan This is an WebApi issue, can you please create it [over there](https://github.com/OData/WebApi/issues)

**Comment by biaol-odata** [comment]
@patnolan hmm, from code snippet, you are trying to associate same route prefix ("odata/Route1") with multiple route names/multiple Edm models; but in the urls, you have different route prefixes (odata/Route1 and odata/Route2) --- is that a typo?

Anyway, we have added a new parameter new parameter 'RouteName' to the ODataRouteAttribute to support multiple route names in [WebApi](https://github.com/OData/WebApi/pull/1390). But it might not support multiple Edm models. Can you see whether it can be of any help for you case?

**Comment by brijeshb** [comment]
Is it possible to have odata rely purely on the ODataRoute attribute routing and not require the base route?

**Comment by padhumailin** [comment]
Multiple EDM would be helpful, when need to expose only related metadata information for each routes.
for example
http://******.com/file/Accounts/$metadata#Accounts -> will expose only Accounts related metadata info

http://******.com/file/Sales/$metadata#Sales-> will expose only Sales related metadata info

**Comment by gathogojr** [comment]
Multiple routes and Edm models are supported in Microsoft.AspNetCore.OData 8.x. You refer to the sample [here](https://github.com/OData/AspNetCoreOData/blob/e03e5e76e89e114280929bef303b794b86b4f291/sample/ODataRoutingSample/Startup.cs#L77)
