### ISSUE TITLE
add .NET Standard 2.0 build

### ISSUE THREAD

**Issue by ctaggart** [OData/odata.net#1224]
Please add a .NET Standard 2.0 build. I understand that you ship a .NET Standard 1.1 build. It is good practice now to include the .NET Standard 2.0 build too.

![image](https://user-images.githubusercontent.com/80104/43754417-a0d82e42-99bf-11e8-8ee3-cd3ed448c062.png)

**Comment by biaol-odata** [comment]
@ctaggart  .NET standard 2.0 is compatible with .Net Standard 1.1. I have created a .netcore 2.0 app and can successfully exercise the latest ODL v7.5.

**Comment by ctaggart** [comment]
https://twitter.com/davidfowl/status/1008453902058917888
![image](https://user-images.githubusercontent.com/80104/44158667-1e4adb80-a06a-11e8-91c0-ce4e66ae3fc2.png)

**Comment by ctaggart** [comment]
Nevermind. There are no additional dependencies:

![image](https://user-images.githubusercontent.com/80104/44304750-b8847b00-a319-11e8-922e-26eb60859894.png)
