### ISSUE TITLE
Compiler Error "The type or namespace name 'EdmxReader' does not exist in the namespace 'Microsoft.OData.Edm.Csdl' (are you missing an assembly reference?)"

### ISSUE THREAD

**Issue by toryb** [OData/odata.net#1225]
When using the Connect Services functionality in VS 2017 and generating the .CS file, the code generated includes a line in the GeneratedEdmModel.LoadModelFromString() method that references global::Microsoft.OData.Edm.Csdl.EdmxReader which is a type that does not seem to exist.

### Assemblies affected
Microsoft.Odata.Client 7.5.0

### Reproduce steps

1. Add Microsoft.Odata.Client 7.5.0 library from nuget
2. Create a Connect Service in VS2017. (I have attached a sample XML file that can be used.)
3. Build project.

### Expected result
Project successfully builds.

### Actual result
Compiler Error "The type or namespace name 'EdmxReader' does not exist in the namespace 'Microsoft.OData.Edm.Csdl' (are you missing an assembly reference?)"

### Additional detail
I have worked around this simply by changing the line of code from:
`return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);`
to:
`return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);`

Thanks

**Comment by biaol-odata** [comment]
@toryb That is the correct work around. I believe it is related to https://github.com/OData/odata.net/issues/632.

**Comment by toryb** [comment]
@biaol-odata Thanks for the reply. I saw #632 but it is closed and it is quite old so I wanted to make sure people knew it was still a problem. I also wanted to document the work around for others.

**Comment by AlanWong-MS** [comment]
Thanks for the opening this issue! For clarification, our Connected Services project resides [here](https://github.com/OData/lab/tree/master/ODataConnectedService), which is separate from our OData.net repo; in the future, please report issues pertaining to Connected Services [here](https://github.com/OData/lab/issues). We'll take a look.

**Comment by KanishManuja-MS** [comment]
You are running into this issue because you have a higher version of OData installed and the connected service package expects version 6.17.

**Comment by biaol-odata** [comment]
fixed by https://github.com/OData/lab/pull/90.
Closed.
