### ISSUE TITLE
[PERF] EDM is allocating string by recalculating the full type name every time it is being asked. 

### ISSUE THREAD

**Issue by ysanghi** [OData/odata.net#1226]
[PERF] EDM is allocating string by recalculating the full type name every time it is being asked. 
### Assemblies affected

OData .NET EDM Lib

### Reproduce steps

Run EDM and take allocation traces

### Expected result

Less string allocations

### Actual result

More string allocations

**Comment by biaol-odata** [comment]
@ysanghi looks like you have a PR. Assigned accordingly.

**Comment by xuzhg** [comment]
Merged and released in 7.5.1.
