### ISSUE TITLE
query with /$each path segment cannot be parsed

### ISSUE THREAD

**Issue by lukred** [OData/odata.net#1228]
I want to use /$each path segment for my queries. However, it cannot be parsed ODataUriParser.ParsePath() throws exception.
Query looks like this:
{{env}}/MyEntitySet/$each/MyFunction()

### Assemblies affected

Microsoft.OData.Core 7.4.4 
Microsoft.OData.Edm 7.4.4
Microsoft.AspNet.OData 6.1.0

### Expected result

Parse should return proper path segments knowing the "$each" segment

### Actual result

Throws exception

### Additional detail

Link to documentation details:

http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingEachMemberofaCollection

**Comment by biaol-odata** [comment]
I think $each is not implemented in ODL yet.

**Comment by AlanWong-MS** [comment]
$each is in PR #1110 at the moment and is pending merge.

**Comment by mikepizzo** [comment]
This should be implemented in OData Library as of October last year. Please let us know if you're still having issues with this in the latest release.
