### ISSUE TITLE
Why DefulatMaxOperationsPerChangeset in OdataConstant is set to  1000 ?

### ISSUE THREAD

**Issue by maharajan1986** [OData/odata.net#1231]
When I submit more than 1000 requests in a  batch it throws Internal Server Error.

### Assemblies affected

Microsoft.OData.Core, Version=7.0.0.0

### Reproduce steps

-- Add a 1001 item to a simple resource
-- call context.SaveChanges(SaveChangesOptions.BatchWithSingleChageSet)
-- It throws error

### Expected result

From our application we are submitting more than 1000 operations in a single batch set, and this will be more sometimes. So we need to customize this value according to our need.

### Actual result

It throws Internal Server Error in client when there is more than 1000 operations in a single batch.

**Comment by maharajan1986** [comment]
@AlanWong-MS  Thank you for getting back to me. I am referring server side.
Here is the file 
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/ODataConstants.cs
and the constant is set to 1000 
**internal const int DefulatMaxOperationsPerChangeset = 1000;**

**Comment by AlanWong-MS** [comment]
Yes, that's correct. The default number of operations per changeset is 1000. I believe this value is arbitrary. If you have access to the service, you may change the value via the [ODataMessageQuotas](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/ODataMessageQuotas.cs) setting.

Sample code:
```
using (var messageWriter = new ODataMessageWriter(requestMessage, new ODataMessageWriterSettings
{
    BaseUri = new Uri(serviceDocumentUri),
    MessageQuotas = new ODataMessageQuotas
    {
        MaxOperationsPerChangeset = maxOperationsPerChangeset
    }
}))
```

Please let me know if this helps answer your question. Thanks.

**Comment by maharajan1986** [comment]
@AlanWong-MS  I changed to 5000, still same issue, (or I may do it in wrong way)
Please see the place where I am changing in my application
https://github.com/maharajan1986/Aparte/blob/master/AparteApi/App_Start/WebApiConfig.cs

**Comment by AlanWong-MS** [comment]
Thanks for the sample application. From what I see in our test cases and your application, I don't think there is a bug with OData library. However, there may be an issue with our WebAPI OData integration and I've created a bug separately in that [repo](https://github.com/OData/WebApi/issues/1585) to track it. Please proceed with any further findings that you may have in that thread. Closing this one.
