### ISSUE TITLE
OData Client Generation, please give clear instructions on which extension to use - both don't work

### ISSUE THREAD

**Issue by RayKoopa** [OData/odata.net#1238]
*Short summary (3-5 sentences) describing the issue.*
You offer the following 2 extension on the VS marketplace:
- [OData v4 Client Code Generator](https://marketplace.visualstudio.com/items?itemName=bingl.ODatav4ClientCodeGenerator)
- [OData Connected Service](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService)

Which one should we use? Which one is still maintained? Why are there two available anyway?

### Background

I already know having installed both at the same time is a bad idea because it messes with the templates or whatever they do. However, even separately, I cannot get any of them to create an OData client for me.

**OData Connected Service**
1. Only shows an error message if you try to access a development server with a self-signed HTTPS certificate, but doesn't give clear details on why it couldn't find the metadata resource.
![image](https://user-images.githubusercontent.com/9631152/44661334-a5089c80-aa0a-11e8-8b6f-733c1aa708be.png)
Simple enough, switch dev server to HTTP and think you're done, but...
- [Throws possibly bogus error if it finds NavigationProperties](https://github.com/OData/lab/issues/76). 
![image](https://user-images.githubusercontent.com/9631152/44661425-ee58ec00-aa0a-11e8-9bc6-7952ef4075f8.png).
I now try narrowing down the navigation properties since it seems to work if I remove all dependencies and slowly add them back, one after another. _It's sad it doesn't show which property exactly caused the issue, this would really help me._ If I found the root cause, I'll post the relevant metadata here (I can't now because it shows too much of our company's database and I'm not allowed to post that).
- [Uses an outdated template not compiling because `EdmxReader` was renamed to `CsdlReader`.](https://github.com/OData/odata.net/issues/1049)

**OData v4 Client Code Generator**
1. Simply doesn't create a new item in the "Add New Item" dialog for me. Tried to add an item to a .NET Framework and .NET Core library project, wasn't in both lists. Renders it useless for me.

### Additional detail

I'm using VS2017 Professional with the latest updates.

**Comment by KanishManuja-MS** [comment]
@RayKoopa - The connected services offers you a UI to generate the client code whereas the client code generator needs parameters to be set explicitly. In the future, one of the tools will be deprecated.

You can refer to the workaround mentioned in #1225 . That issue has been fixed and should be available in the next release for that package but in the meanwhile feel free to use the workaround.

I believe that there is more investigation needed for https://github.com/OData/lab/issues/76. Although I suspect that client code generator would also see the same issue, but it may be worth trying.

**Comment by RayKoopa** [comment]
Thanks, I'll stick with the Connected Service one then, because the other one, for some reason, doesn't yield me a new template in the Add New Item dialog.
