### ISSUE TITLE
Expanding navigation property on OpenType entities throws NullReferenceException

### ISSUE THREAD

**Issue by yaibrahi** [OData/odata.net#1241]
Expanding a non dynamic navigation property on an entity that is marked as OpenType in EDM with no dynamic properties throws NullReferenceException. 

For example:
http://localhost:5000/TripPinService/People('scottketchum')?$expand=Friends

### Assemblies affected

Assembly: Microsoft.AspNetCore.OData, Version=7.0.1.20718, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### Expected result

No exception is thrown.

### Actual result

NullReferenceException is thrown and the following stack trace is produced:

NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.BuildPropertyContainer(IEdmEntityType elementType, Expression source, Dictionary<IEdmNavigationProperty, ExpandedNavigationSelectItem> propertiesToExpand, ISet<IEdmStructuralProperty> propertiesToInclude, ISet<IEdmStructuralProperty> autoSelectedProperties, bool isSelectingOpenTypeSegments)
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.ProjectElement(Expression source, SelectExpandClause selectExpandClause, IEdmEntityType entityType, IEdmNavigationSource navigationSource)
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.GetProjectionLambda()
Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder.Bind(object entity)
Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplySelectExpand<T>(T entity, ODataQuerySettings querySettings)
Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(object entity, ODataQuerySettings querySettings)
Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func<Type, IEdmModel> modelFunction, IWebApiRequestMessage request, Func<ODataQueryContext, ODataQueryOptions> createQueryOptionFunction)
Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func<Type, IEdmModel> modelFunction, Func<ODataQueryContext, ODataQueryOptions> createQueryOptionFunction, Action<HttpStatusCode> createResponseAction, Action<HttpStatusCode, string, Exception> createErrorAction)
Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
WebApiContrib.Core.ParallelApplicationPipelinesExtensions+<>c__DisplayClass0_0+<<UseBranchWithServices>b__1>d.MoveNext()
WebApiContrib.Core.ParallelApplicationPipelinesExtensions+<>c__DisplayClass0_0+<<UseBranchWithServices>b__3>d.MoveNext()
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Additional Details
It seems that 'EdmLibHelpers.GetDynamicPropertyDictionary((IEdmStructuredType) elementType, this._model)' returns null.

**Comment by xuzhg** [comment]
@yaibrahi Do you have a corresponding CLR type associated with the Edm model?

**Comment by xuzhg** [comment]
Move it to Web API Repo and close it.

**Comment by xuzhg** [comment]
https://github.com/OData/WebApi/issues/1614
