### ISSUE TITLE
Add Interfaces to to OData Client to support mocking in unit tests

### ISSUE THREAD

**Issue by rifuller** [OData/odata.net#1250]
I have a function that has a dependency on the OData client to perform its task. I inject the OData client (and other dependencies) into the function so that I can unit test the behaviour of the function.  Classes in Microsoft.OData.Client do not implemented an interface making it impossible to pass a fake into the function in the context of unit tests.

### Assemblies affected

Microsoft.OData.Client

### Reproduce steps

1. Generate an OData client using: https://outlook.office.com/api/v1.0/$metadata
1. View the generated client code

### Expected result

The generated class implements an interface that allows its methods/properties to be mocked.

### Actual result

The generated class

    public partial class EntityContainer : global::Microsoft.OData.Client.DataServiceContext

does not extend an interface that would allow its implemented to be mocked.

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by kornakar** [comment]
If you have access to the Visual Studio Enterprise, you could use MS Fakes for mocking the client code.
I had a question about it a while back so it may help you set up the fakes if you need to: [https://github.com/OData/odata.net/issues/1167](https://github.com/OData/odata.net/issues/1167)

**Comment by rifuller** [comment]
> If you have access to the Visual Studio Enterprise, you could use MS Fakes for mocking the client code.
> I had a question about it a while back so it may help you set up the fakes if you need to: #1167

Thanks for the suggestion.  I have a strong preference towards NSubstitute though as it works well with the dependency injection pattern.  MS Fakes, though my understanding is limited, takes a different approach than DI.

**Comment by rifuller** [comment]
> @rifuller This is a valuable suggestion but not in our radar. If you can contribute to it, we would love to take a look.

I can possibly take a look at this in October.  Do you accept pull requests on github for the project?  If not, please point me to the DevOps repo.

**Comment by chuanboz** [comment]
I created another proposal in #1271 , that instead of adding interface for OData Client, I'd propose to add IODataClientFactory similar to IHttpClientFactory, to provide extensibility and dependency injection support, and that will also support UT mocking by injecting a different implementation of IODataClientFactory.

See also a similar long discussion for IHttpClientFactory vs. IHttpClient https://github.com/dotnet/corefx/issues/1624

**Comment by madansr7** [comment]
@rifuller , we are identifying work for our next release of OData client, if you would like to make a contribution for this issue we would be happy to review.

**Comment by rschiefer** [comment]
@madansr7  Its ridiculous this code is not mockable.  It is 2019 and all code should be developed with unit testing in mind.  

-The generated client should have an interface that can be easily mocked.
-ODataQueryOptions should be mockable or faked.
-DataServiceQuery should be mockable or faked.

**Comment by chuanboz** [comment]
@rschiefer , Take a look of https://github.com/dotnet/corefx/issues/1624 for similar discussion on HttpClient, and reason why they decided not to introduce interface for HttpClient, but rather create a IHttpClientFactory interface.

**Comment by chuanboz** [comment]
And I do agree with you that "all code should be developed with unit testing in mind", but I have different opinion on how to achieve that.

If you give could details proposal on your solution, I think that would help driver deeper discussion.

**Comment by rschiefer** [comment]
I'm definitely open to using a factory pattern.  Anything is better than what we have today.

**Comment by chuanboz** [comment]
The support for factory pattern is already checked in here: https://github.com/OData/Extensions/blob/master/src/Microsoft.OData.Extensions.Client.Abstractions/IODataClientFactory.cs I'm still working on publish a usage document for this, and I will also try to include a sample usage for Unit Test with IODataClientFactory.

Take a look and give me feedback whether that could meet your scenario.

**Comment by chuanboz** [comment]
@rschiefer , I've added one examples to the docs PR pending review (https://github.com/MicrosoftDocs/OData-docs/pull/67)

And here is the example test method that used Moq to mock ODataClient usage.

using Moq;
using Moq.Protected;

[TestMethod]
public void TestGetHappyCase()
{
    var mockHttpMessageHandler = new Mock<HttpMessageHandler>();
       mockHttpMessageHandler.Protected()
      .Setup<Task<HttpResponseMessage>>("SendAsync", ItExpr.IsAny<HttpRequestMessage>(), ItExpr.IsAny<CancellationToken>())
      .Returns(new HttpResponseMessage()
       {
      StatusCode = HttpStatusCode.OK,
      Content = new StringContent(@"{
  ""@odata.context"": ""http://services.odata.org/V4/(S(uvf1y321yx031rnxmcbqmlxw))/TripPinServiceRW/$metadata#People"",
  ""@odata.nextLink"": ""https://services.odata.org/V4/(S(uvf1y321yx031rnxmcbqmlxw))/TripPinServiceRW/People?%24skiptoken=8"",
  ""value"": [
    {
 ""@odata.id"": ""http://services.odata.org/V4/(S(uvf1y321yx031rnxmcbqmlxw))/TripPinServiceRW/People('keithpinckney')"",
 ""@odata.etag"": ""W/\""08D751CC35005AA0\"""",
 ""@odata.editLink"": ""http://services.odata.org/V4/(S(uvf1y321yx031rnxmcbqmlxw))/TripPinServiceRW/People('keithpinckney')"",
 ""UserName"": ""keithpinckney"",
 ""FirstName"": ""Keith"",
 ""LastName"": ""Pinckney"",
 ""Emails"": [ ""Keith@example.com"", ""Keith@contoso.com"" ],
 ""AddressInfo"": [],
 ""Gender"": ""Male"",
 ""Concurrency"": 637067809800608416
    }
  ]
}")});

    var sc = new ServiceCollection();
    sc.
    .AddODataClient("TripPin")
    .AddHttpClient()
    .ConfigurePrimaryHttpHandler(() => mockHttpMessageHandler.Object);

    var sp = sc.Build();

    var controller = new PeopleController(sp.GetService<IODataClientFactory>());
    var people = controller.Get().ToList();
    people.Count.Should().Be(1);
    people[0].UserName.Should().Be("keithpinckney");
}

In the above example, it demonstrated a unit test that simulate a happy case scenario where the OData client call returned 1 item.

You could also use similar approach to test other unhappy cases, for example, use below code to test the behavior when the dependency OData service is unavailable.

    var mockHttpMessageHandler = new Mock<HttpMessageHandler>();
       mockHttpMessageHandler.Protected()
      .Setup<Task<HttpResponseMessage>>("SendAsync", ItExpr.IsAny<HttpRequestMessage>(), ItExpr.IsAny<CancellationToken>())
      .Returns(new HttpResponseMessage()
       {
      StatusCode = HttpStatusCode.ServiceUnavailable
       )});

Let me  know if that's what you want, or if you have additional scenario and we could discuss how to support it.

**Comment by rschiefer** [comment]
In most of my use cases it would be much easier to setup an DataServiceQuery object response in the mock instead of a string response. Then you would get compile time checking on the response properties and not have to worry with getting the string response perfect. This would require DataServiceQuery to have an interface so I could mock its underlying iqueryable data as well as any of the other methods like totalcount.

**Comment by chuanboz** [comment]
I understand this is not as easy as you would expect and interface on DataServiceQuery would be your preference, but from mocking perspective do you see this could cover the scenarios you want to mock?

**Comment by rschiefer** [comment]
I couldn't use that because the maintenance of string-based responses outweighs the value of the unit tests.

**Comment by chuanboz** [comment]
If that is only about the string serialization, it should be easily solvable by using the entity together with Json serialization.

``` csharp
var person = new Person {LastName = "Pinckney", FirstName = "Keith"};
var json = JsonConvert.SerializeObject(person), Encoding.UTF8, "application/json");
Content = new StringContent(@"\{
  ""value"": [
    \{
         {json}
    \}
  ]
\}")});
```

**Comment by chuanboz** [comment]
I do want to clarify that if there is specific proposal on how to introduce interface on DataServiceQuery, especially if someone has bandwidth to send a PR to show the proposal, I think that would be super helpful.

**Comment by rschiefer** [comment]
@chuanboz did you see my PR?

**Comment by weitzhandler** [comment]
👃🏻

**Comment by se-andbjo** [comment]
Any news on this? I would rather work with interfaces as most of the others in this discussion. But as of now it's not even possible to write Unit tests since the extension method `ConfigurePrimaryHttpHandler` doesn't event exist anymore.

Anyone know how to mock a OData set?
