### ISSUE TITLE
what about ODataComplexValue in 7.x branch?

### ISSUE THREAD

**Issue by XenoAmess** [OData/odata.net#1258]
Hi.
I'm changing some codes from using your 5.x codes to 7.x branch, to deal with OData V4.
I see some of my codes are using a class ODataComplexValue. 
But I cannot find ODataComplexValue in 7.x.
Or , I found it but it is removed from product codes.
So I want to ask about this.
Why is it deleted? Is it deleted in the protocol, thus I can delete my codes related to it, Or I have to implement it again?
And if I didn't use [public IEnumerable<ODataProperty> Properties] and [public string TypeName]
in my code, is it necessary to implement them?
Thanks.
related class : [ODataComplexValue](https://github.com/OData/odata.net/blob/ODataV4-7.x/test/FunctionalTests/Taupo/Source/Taupo.Astoria/Contracts/OData/ODataComplexValue.cs)

**Comment by xuzhg** [comment]
@XenoAmess We re-introduced a new class named "ODataResourceValue" to play like the "ODataComplexValue". Please try and let us know any questions.
