### ISSUE TITLE
Client side dependency injection support via IODataClientFactory, similar to IHttpClientFactory

### ISSUE THREAD

**Issue by chuanboz** [OData/odata.net#1271]
ASP.NET Core 2.1 includes a new IHttpClientFactory service that makes it easier to configure and consume instances of HttpClient in apps, see [Initiate HTTP Requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)

The request here is introduce something similar to ODataClient, with the IODataClientFactory and corresponding IODataClientHandler, and the builder pattern IODataClientBuilder to use asp.net core dependency injection to construct the factory independently.
### Assemblies affected
Microsoft.OData.Client

To avoid impact existing consumer of the client assembly, might consider introduce a new Microsoft.Extensions.OData package for this new functionality, this is similar to IHttpClientFactory which is in Microsoft.Extensions.Http package.

### Reproduce steps
1. Generate an OData client with visual studio.
2. View the generated client code.

### Expected result
The generated class support extensibility and plugin model similar to IHttpClientFactory. 

Something like this:
```C#
    /// <summary>
    /// Factory to create OData client containers to an ODATA service, similar to IHttpClientFactory.
    /// Type T will be the concreate class generated from visual studio in standard usage.
    /// </summary>
    /// <remarks>
    public interface IODataClientFactory<T> where T : DataServiceContext
    {
        /// <summary>
        /// create the client container to an OData service, specifying a logical named the client
        /// </summary>
        /// <param name="name">the logic name of the client to use, including both HttpClient and ODataClient.</param>
        /// <returns>the container client with the handling logic injected from dependency injection container.</returns>
        T CreateClient(string name);
    }
```
and also introduce the OData handler similar to HttpMessageHandler, that could hook into the DataServiceContext to hook up with built-in event to impact OData Client behavior. Some example of such handler, like retry, metric, exception handling, versioning, sending request via HttpClient, etc.
```C#
    /// <summary>
    /// A single handler that can alter the behavior of odataclient
    /// </summary>
    public interface IODataClientHandler
    {
        /// <summary>
        /// Called within IODataClientFactory{T}.CreateClient(string) after the DataServiceContext created.
        /// If multiple handlers are registered, then they are called in reverse order of registration.
        /// </summary>
        /// <param name="context">the default client container created, implementation could hook up with the event to change its behavior.</param>
        void OnClientCreated(DataServiceContext context);
    }
```

and the usage in Controller would be like this, similar to IHttpClientFactory.
```C#
public SampleController(IODataClientFactory<SampleDataServiceContext> clientFactory)
{
       var client = clientFactory.CreateClient("Github");
       // rest of usage will be similar to the existing public documentation.
}
```

### Actual result
No such interface exists yet to injection handler logic as well as leverage asp.net core 2.1 DI support.

### Additional detail
We're planning to use this in Microsoft Intune and we'd like to contribute the change to public and make it public pattern to leverage asp.net core DI support.

**Comment by chuanboz** [comment]
See also the uber long discussion for HttpClient on why they decided to not to introduce abstraction or interface on HttpClient, but rather decided to introduce IHttpClientFactory

https://github.com/dotnet/corefx/issues/1624

The same argument and reasoning could be applied to ODataClient, and that's why the propose is to introduce IODataClientFactory than to make existing DataServiceContext as interface.

This will also simplify the change a lot, as we only have 2 extra interface to add, with similar user experience as HttpClient.

**Comment by chuanboz** [comment]
I find below 2 public document about the ODataLib dependency injection support, they both just talked about the server side of hosting OData service and using dependency injection, but does not mention about the client side story.

http://odata.github.io/odata.net/v7/#01-05-di-support
https://odata.github.io/WebApi/13-04-DependencyInjection/

so the request here is to add the client side support of dependency injection via IODataClientFactory and related IODataClientHandler and IODataClientBuilder

**Comment by chuanboz** [comment]
Great to hear you're willing to look and merge. I will work on it this month to clean up our existing implementation and send the PR to review.

**Comment by chuanboz** [comment]
ODataLib support both v3 and v4, with v4 on master branch and using namespace Microsoft.OData.Client and v3 on maintenance-5.x branch using namespace Microsoft.Data.Services.Client.

I'm thinking to put this on master branch to support both v3 and v4 with conditional compilation to share the code, and use Microsoft.Extensions.ODataClient for v4 support and Microsoft.Extensions.DataServiceClient for v3 support.

I do not propose to put it on maintenance-5.x because then we could not be easily share the same code which I see would be almost identical for v3/v4 support.

@xuzhg , let me know if that work for you? Or if you'd like me to add that support for v4 first in master branch?

**Comment by xuzhg** [comment]
I don't think we want to introduce such conditional compilation owing that we have corresponding branches for different version. So, it will be helpful to implement first in master branch.

**Comment by chuanboz** [comment]
I have added above commit for basic support and still working on the testing before I could send Pull Request.

I'd want some feedback on making Microsoft.Extensions.ODataClient package to compile with .net standard 2.0 only and does not support .net standard 1.1 which rest of ODL support.

I introduce this restriction because the implementation of the default handler depends on IHttpClientFactory in https://www.nuget.org/packages/Microsoft.Extensions.Http/ which is only introduced in .net standard 2.0.

I do not see that as an issue because I assume for people that needs this ODataClientFactory DI support will have .net standard 2.0 anyway, but would like more feedback on that to validate it.

**Comment by chuanboz** [comment]
close this issues, the proposed changes are checked in to OData\Extensions repo, and support both OData v3 and v4 client.
