### ISSUE TITLE
Singleton instance not possible without Keys

### ISSUE THREAD

**Issue by henning-krause** [OData/odata.net#1274]
When I add a singleton to my OData-Context (https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/using-a-singleton-in-an-odata-endpoint-in-web-api-22) and don't define a key, the ODataConventionModelBuilder.GetEdmModel() method throws an exception stating that I need to define a key. 

But I don't really need a key property on a Singleton instance. This has also been reported on https://issues.oasis-open.org/browse/ODATA-895 and if I read the issue comments right, the standard has been updated to relax this requirement on Singleton instances.

### Assemblies affected

Microsoft.Odata.Edm 7.5.0
Microsoft.Odata.Core 7.5.0
Microsoft.AspNet.Odata 7.001

### Expected result

 ODataConventionModelBuilder.GetEdmModel() should build the model successfully even without a key.

### Actual result

An exception is thrown stating that the Singleton instance needs a key.

### Additional detail

My current workaround is to create a dummy property called Id and decorate it with a [Key] attribute.

**Comment by xuzhg** [comment]
@henning-krause Thanks. That's a new feature in our plate.

**Comment by xuzhg** [comment]
Thanks. Close it because ODL allows to create keyless singleton in the latest version. And the corresponding Web API OData issue is create at https://github.com/OData/WebApi/issues/1631

**Comment by Sayan751** [comment]
I am still having this issue in Microsoft.AspNetCore.OData 8.0.8, latest ATM.
