### ISSUE TITLE
Uri parser to support Swagger

### ISSUE THREAD

**Issue by bixu-ms** [OData/odata.net#129]

**Comment by MrTomWhite** [comment]
Do we have a general approach for this work? Is it basically just transpiling Metadata into swagger's format? 

Will this be general enough to support the creation of other types of service description languages in the future? 

This work may be interesting to some of the folks on the Microsoft/VIPR team, especially @tonycrider, .

**Comment by congysu** [comment]
The task is about: A flexible, and tolerable Uri parser in OData v4 Lib to support ~/$swagger, or ~/swagger.json in a request uri.
