### ISSUE TITLE
Reference segment in the context URL

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#1292]
Within `src/Microsoft.OData.Core/UriParser/Visitors/PathSegmentToContextUrlPathTranslator.cs`, how should the ReferenceSegment be addressed for the context URL?

**Comment by mikepizzo** [comment]
If the /$ref terminates the path segment (i.e., Orders/$ref) then the contextUrl should just be #ref (or Collection($ref).  see http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_EntityReference.

$expand=nav/$ref does not have a representation in the ContextUrl.

**Comment by gathogojr** [comment]
Issue superseded by https://github.com/OData/odata.net/issues/1434 that has a detailed description
