### ISSUE TITLE
Remove Contentions from Microsoft.OData.Edm

### ISSUE THREAD

**Issue by ysanghi** [OData/odata.net#1296]
There are locks being taken in hot paths in Microsoft.OData.Edm leading to tons of contentions leading to unnecessary scalability.

### Assemblies affected

Microsoft.OData.Edm.dll

### Reproduce steps
Concurrency of 1000's of threads trying to operate on the same EDM Model.

### Expected result

Less contentions, more scalability.

### Actual result

Less concurrency, more contentions

**Comment by KanishManuja-MS** [comment]
@ysanghi Thanks for your contribution. Will your PR completely fix this issue or do you think there would be more effort required to allow for concurrency?
