### ISSUE TITLE
System.NotSupportedException when calling OData service from NetCoreApp2.1

### ISSUE THREAD

**Issue by jblagorce** [OData/odata.net#1303]
I have set up a multi targetting (net4.5.2/netstandard2) class library allowing to consume one of our enterprise OData services.
To access this OData service we use a proxy class generated with the OData v4 Client Code Generator (v7.5.0)

Unfortunately, when trying to use this library in a Netcoreapp2.1 application I encounter the following issue as soon as I try to enumerate a collection.

`Container.MyDataSet.ToList();` produces the following exception :

"System.NotSupportedException : This target framework does not enable you to directly enumerate over a data service query. This is because enumeration automatically sends a synchronous request to the data service. Because this framework only supports asynchronous operations, you must instead call the BeginExecute and EndExecute methods to obtain a query result that supports enumeration."

Is this expected behaviour, or did I miss something ?

### Assemblies affected

Microsoft.OData.Client v7.5.0

**Comment by rahul7720** [comment]
Any updates on this?

**Comment by KanishManuja-MS** [comment]
@gathogojr @paulodero Any idea if any changes were made regarding this?

**Comment by jblagorce** [comment]
@KanishManuja-MS @rahul7720 
For my part, I solved the issue using a partial workaround :
https://stackoverflow.com/a/53339432/1236044

**Comment by gathogojr** [comment]
Question from 2018. Reporter of the issue reported that they found a workaround
