### ISSUE TITLE
Unable to call Action with Complex Type as parameter.

### ISSUE THREAD

**Issue by NetTecture** [OData/odata.net#1304]
Really not super. 7.5.1, CLIENT side. Server metadata first: I define the following action on the server:

```
<Action Name="BulkChange" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(PropertyCore.InspectionDuty)"/>
<Parameter Name="Comment" Type="Edm.String" Unicode="false"/>
<Parameter Name="Changes" Type="Collection(PropertyCore.InspectionDutyChange)"/>
</Action>
```
With the following complex type:

```
<ComplexType Name="InspectionDutyChange">
<Property Name="Operation" Type="Operations.Operations" Nullable="false"/>
<Property Name="Identity" Type="Edm.Guid" Nullable="false"/>
<Property Name="IsDisabled" Type="Edm.Boolean" Nullable="false"/>
<Property Name="SeriesStart" Type="Edm.DateTimeOffset"/>
<Property Name="Interval" Type="Common.Interval"/>
<NavigationProperty Name="Module" Type="PropertyCore.Module"/>
<NavigationProperty Name="Equipment" Type="PropertyCore.Equipment"/>
<NavigationProperty Name="OperatorTask" Type="PropertyCore.OperatorTask"/>
</ComplexType>
```

No problem on the server. On the client, I try to serialize a parameter object:

```
            new {
                    Comment = "comment try",

                    Changes = new[] {
                        new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                        new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                    },
```

and things go south. THe following is the exception, indicating a bad code path in serialization:

Microsoft.OData.ODataException: Unsupported primitive type. A primitive type could not be determined for an instance of type 'Api.Odata.InspectionDutyChange'.

Result StackTrace:	
at Microsoft.OData.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValue(Object value, IEdmTypeReference actualTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightCollectionWriter.WriteCollectionItem(Object item, IEdmTypeReference expectedItemType)
   at Microsoft.OData.ODataCollectionWriterCore.InterceptException(Action action)
   at Microsoft.OData.TaskUtils.GetTaskForSynchronousOperation(Action synchronousOperation)
--- End of stack trace from previous location where exception was thrown ---

I have cut all elements of the client library and down (the client library being SImple.OData.Client).

This also does not work if I rename the type with an anonymous rype, only the eerror message turns a LOT worse:

Microsoft.OData.ODataException: Unsupported primitive type. A primitive type could not be determined for an instance of type '<>f__AnonymousType11`2[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.

This points to a wrong code path using collections of complex types, which otoh is seen as valid by the server side odata library.

Any workaround?

**Comment by xuzhg** [comment]
That's related to : https://github.com/xuzhg/Docs/blob/master/Docs/OData/ODataComplexValue.md

**Comment by paulodero** [comment]
@NetTecture This issue is related to issue #1305 and what @xuzhg has mentioned above. [Simple.OData.Client is using wrong methods](https://github.com/simple-odata-client/Simple.OData.Client/blob/61dc9fd08e877a9e52812bce4c1d9b5e109f41ed/src/Simple.OData.Client.V4.Adapter/RequestWriter.cs#L259-L289) for a collection of complex type. Please refer to [Microsoft.OData.client and see how it implemented a writer for Collection of complex type](https://github.com/OData/odata.net/blob/209e434e567f67aa8220cc9682aaf2e0c2a98873/src/Microsoft.OData.Client/Serialization/Serializer.cs#L571-L612).
