### ISSUE TITLE
IN operator containing single quote (apostrophe) within a string literal throws an error

### ISSUE THREAD

**Issue by adzhiljano** [OData/odata.net#1313]
According to the [OData ABNF v4.0](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/abnf/odata-abnf-construction-rules.txt) (I don't think this will be changed in v4.01):

> string           = SQUOTE *( SQUOTE-in-string / pchar-no-SQUOTE ) SQUOTE
SQUOTE-in-string = SQUOTE SQUOTE ; two consecutive single quotes represent one within a string literal

**two consecutive single quotes represent one within a string literal**, but when trying to use a single quote in a string literal inside IN operator  like `$filter=StringProperty in ('i''m', 'test')` - a parsing error is produced

### Assemblies affected

Microsoft.OData.Core version=7.5.0
Microsoft.AspNet.OData version=7.0.1

### Reproduce steps

`$filter=StringProperty in ('i''m')`
`$filter=StringProperty in ('i''m', 'test')`

### Expected result

No error will occur

### Actual result

An error with the following message occurs:
`The query specified in the URI is not valid. Invalid JSON. A comma character ',' was expected in scope 'Array'. Every two elements in an array and properties of an object must be separated by commas.`

### Additional detail

The following work as expected (haven't checked all the functions and operators though, but I guess they are being parsed in a common manner):
`$filter=contains(StringProperty, 'i''m')`
`$filter=StringProperty eq 'i''m'`
`$filter=startswith(StringProperty ,'i''m')`
`$filter=concat(StringProperty,'i''m') eq 'sometexti''m'`

**Comment by adzhiljano** [comment]
Forgot to mention something else which is related:

`$filter=StringProperty eq "foo"`(**notice the double quotes**) results in :

`The query specified in the URI is not valid. Syntax error: character '"' is not valid at position 18 in 'StringProperty eq "foo"'.`

but the following is fine:

`$filter=StringProperty in ("foo", "bar")`(**notice the double quotes**)

Correct me if I'm wrong, but the string literals inside the IN operator are not parsed according to the ABNF.(may be this should be the title of this issue)

**Comment by biaol-odata** [comment]
looks like escape character issue related to single/double quotes.

**Comment by biaol-odata** [comment]
Potential related to issue on WebAPI: https://github.com/OData/WebApi/issues/1596
