### ISSUE TITLE
Client side Generator add Auth-Header to the request

### ISSUE THREAD

**Issue by paule96** [OData/odata.net#1315]
*If you have protected your metadata site of your odata api, you can't generate the Client Code without the Manipulation of the file `{funyfilename}.ttinclude`. It would be nice if a user of the Client Code Generator can set an Key-Value dictionary of headers.*

### Assemblies affected

*OData T4 client code Generator - 7.5.1*

### Reproduce steps

1. Protected your Metadata URL with an Header. (this is only an example. I don't compile this Code... )
```csharp
 app.Use(async (context, next) =>
   {
      var headerSet = context.Response.Headers..GetValues("Authorization").Any(d => d != null);
      if(headerSet){
          await next();
      }
      context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
      await context.Response.WriteAsync("No Header Auth please.");
   });
```
2. Create a new Console app in visual Studio
3. Add OData Model like [this tutorial](https://blogs.msdn.microsoft.com/odatateam/2014/03/11/tutorial-sample-how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class/) describes
4. Step 3 will fail!

### Expected result

I can configure my headers and then generated my Client Code.

### Actual result

I can't configure my headers.

### Additional detail

The current work around is to add the following lines under the line 875 in the file `{funyfilename}.ttinclude`

```csharp
webRequest.Headers.Add(HttpRequestHeader.Authorization, "Bearer JWT-Token");
```

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by raheph** [comment]
@mikepizzo Can you share your thoughts?

**Comment by mikepizzo** [comment]
So the proposal is to add a dictionary of headers to the Configuration class that get passed to the service when downloading metadata (essentially, adds Headers to the webRequest under 875 of the ttinclude, similar to what you are doing manually)?

Seems reasonable.

@paule96; would you want/be able to provide a pull request with this functionality?

**Comment by KenitoInc** [comment]
Hey @paule96 
Am closing this issue. This feature was added to OData Connected Service v0.6
