### ISSUE TITLE
Json batch throwing 'System.UriFormatException: Invalid URI: The Uri scheme is too long.'

### ISSUE THREAD

**Issue by vaibhavb007msft** [OData/odata.net#1318]
The below call fails with the exception System.UriFormatException: Invalid URI: The Uri scheme is too long.at System.Uri.CreateThis(String uri  Boolean dontEscape  UriKind uriKind)[Entire stack attached]. 

If the below highlighted filter clause 'FileModifiedTime gt 2018-08-24T22:06:36Z' is removed, the error goes away. Removing any other filter clause doesn't resolve the issue. Hence I am not sure if the issue is really about the length of the uri or not. Further, this query works perfectly well if run as a normal GET call.

Can you please help me understand in what scenarios this error would be thrown? Also, is this related to the complexity of the filter query? Can you provide some guidance about how such complex filter clauses should be written? The partner team wants to add this particular filter as well.

{
  "requests": [
    {
      "method": "GET",
      "url": "files?$filter=(((Document/Author eq 'Abhishek Arun' OR Document/Author eq 'Substrate Recommendations Core' OR Document/Author eq 'Gaurav Anand' OR Document/Author eq 'Dario Bigongiari' OR Document/Author eq 'Ioannis Gabrielides' OR Document/Author eq 'Weikun Wang' OR Document/Author eq 'Sarunas Marciuska' OR Document/Author eq 'Jagruti Pandya' OR Document/Author eq 'Kevin Moynihan' OR Document/Author eq 'Anton Dergunov' OR Document/Author eq 'Jason Liu') OR (SharePointItem/ModifiedByDisplayName eq 'Abhishek Arun' OR SharePointItem/ModifiedByDisplayName eq 'Substrate Recommendations Core' OR SharePointItem/ModifiedByDisplayName eq 'Gaurav Anand' OR SharePointItem/ModifiedByDisplayName eq 'Dario Bigongiari' OR SharePointItem/ModifiedByDisplayName eq 'Ioannis Gabrielides' OR SharePointItem/ModifiedByDisplayName eq 'Weikun Wang' OR SharePointItem/ModifiedByDisplayName eq 'Sarunas Marciuska' OR SharePointItem/ModifiedByDisplayName eq 'Jagruti Pandya' OR SharePointItem/ModifiedByDisplayName eq 'Kevin Moynihan' OR SharePointItem/ModifiedByDisplayName eq 'Anton Dergunov' OR SharePointItem/ModifiedByDisplayName eq 'Jason Liu')) AND **(FileModifiedTime gt 2018-08-24T22:06:36Z)**) AND (Visualization/Type eq 'Word' OR Visualization/Type eq 'PowerPoint' OR Visualization/Type eq 'Excel' OR Visualization/Type eq 'Visio' OR Visualization/Type eq 'OneNote' OR Visualization/Type eq 'Pdf') AND (SharePointItem/ContentClass eq 'STS_ListItem_DocumentLibrary' OR SharePointItem/ContentClass eq 'STS_ListItem_MySiteDocumentLibrary') AND Visualization/Hide eq 0&$top=50&$select=FileName,FileExtension,FileModifiedTime,FileSize,Document,SharePointItem,Visualization,UserRelationship,DocumentInfo,AllTimeAnalyticsStats,LastSevenDaysAnalyticsStats,FileCreatedTime&$orderby=UserRelationship/LastAccessDateTime desc,SharePointItem/ContentClass,Visualization/Type",
      "id": "1",
      "headers": {
        "Content-Type": "application/json; charset=utf-8"
      }
    }
  ]
}

[exception-stack.txt](https://github.com/OData/odata.net/files/2562437/exception-stack.txt)
### Assemblies affected

OData .Net lib 7.4.1 is the library being used.

### Reproduce steps

Running the above batch query leads to this failure.

### Expected result

The batch call should have succeeded; and if any issue were to be any issue with the url, the individual request should have failed.

### Actual result

The batch call fails with a 500.

**Comment by mikepizzo** [comment]
The issue is inline 170 of ODataJsonLightBatchReader, where we are calling new Uri with UriKind.AbsoluteOrRelative.

This causes System.Uri to try and figure out whether the uri is absolute or relative. As part of figuring this out, it apparently scans the string for colons (":").  If it finds one, it assumes it is an absolute URL, and that the text up to the colon is the schema.

This is why the request works without the time in the filter (no colon) and fails otherwise.

**Comment by mikepizzo** [comment]
Repo:
Pass the above payload to the following routine:

~~~c#
       static void ReadBatch(string payload)
       {
            // Set up the payload
            var memoryStream = new MemoryStream();
            var writer = new StreamWriter(memoryStream);
            writer.Write(payload);
            writer.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            // Read the batch payload
            var batchRequestMessage = new ODataRequestMessage(memoryStream);
            var settings = new ODataMessageReaderSettings
            {
                BaseUri = new Uri("http://test")
            };
            var messageReader = new ODataMessageReader(batchRequestMessage, settings, model);
            var batchReader = messageReader.CreateODataBatchReader();
            while (batchReader.Read())
            {
                switch (batchReader.State)
                {
                    case ODataBatchReaderState.Operation:
                        var requestMessage = batchReader.CreateOperationRequestMessage();
                        Console.WriteLine("Request URL is {0}", requestMessage.Url);
                        break;
                }
            }
        }
~~~

**Comment by biaol-odata** [comment]
@vaibhavb007msft Maybe you should perform an url encode for the query option, so that
```
FileModifiedTime gt 2018-08-24T22:06:36Z --> FileModifiedTime%20gt%202018-08-24T22%3A06%3A36Z. 
```
Reference: https://www.urlencoder.org/

**Comment by biaol-odata** [comment]
OData [Url component](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_URLComponents) should be url-encoded as specified by RFC 3986.
```
OData follows the URI syntax rules defined in [RFC3986] and in addition assigns special meaning to several of the sub-delimiters defined by [RFC3986]
```

**Comment by mikepizzo** [comment]
The reference to percent-encoding is specific to the ABNF, not to how URLs are represented in payloads.
I would not expect that a URL within a batch payload would need to be escaped, and opened an OASIS issue to confirm.
We should handle this in our library by percent-encoding colons within the querystring in order to safely handle unescaped relative URLs in the batch payload.
We should also think about how this relates to escaped segments within a URL path.

**Comment by biaol-odata** [comment]
OData [Url component](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_URLComponents) specifies and quotes RFC3986 for percent-decoding, it will be great to clarify if this is considered a gray area. I checked all ODL versions starting from 5.x, and the batch reader expects url-encoded form.

**Comment by b1ueRa1n** [comment]
> The issue is inline 170 of ODataJsonLightBatchReader, where we are calling new Uri with the string containing the colon.
> 
> The Uri constructor apparently scans the string for colons (":"). If it finds one, it assumes that the text up to that point is a scheme.
> 
> This is why the request works without the time in the filter (no colon) and fails otherwise.

Thanks,@mikepizzo. you are right! but I have a question: Why the request 'ModifiedByDisplayName eq 'Gaurav Anand' AND (FileModifiedTime gt 2018-08-24T22:06:36Z)) '' is work, too? Despite The request contains colons. But it is short.

**Comment by udaysaikumargarlapati** [comment]
Guys, I also faced this issue after spending too much time,I came up with one solution like I have encoded the url first and then I have done uri.escapeuristring(encodedurl)

This solved my problem.

**Comment by mikepizzo** [comment]
@udayasaikumargarlapati: What version of OData Library were you using? This is due to an issue in System.Uri, and we implemented a workaround in OData Library in May.

**Comment by mikepizzo** [comment]
@b1ueRa1n - the reason it isn't a problem for short Uris is that System.Uri parses everything up until the first colon as the scheme, and as long as that is less than 1000 characters it accepts it.

**Comment by udaysaikumargarlapati** [comment]
@mikepizzo i am hitting the encoded fetchxml url of CRM in webapi c# with contains multiple colons.so after encoding I have did escapeuristring,then it is working
