### ISSUE TITLE
OData Client fails to parse $batch response for Linux

### ISSUE THREAD

**Issue by VirusQuartirus** [OData/odata.net#1320]
*When $batch response created by ExecuteBatchAsync is returned from Linux machine (so it uses 0x0A as a new line instead of 0x0D0A) OData client fails to deserialize last batch item*

### Assemblies affected

*OData .Net Client 5.x-7x.*

### Reproduce steps

*Use a Linux as a service host machine or use Fiddler autoresponder with modified response (replace \r\n line breaks with \n).*

### Expected result

*All responses have to be parsed by client.*

### Actual result

*Exception occurs.
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Invalid JSON. More than one value was found at the root of the JSON content. JSON content can only have one value at the root level, which is an array, an object or a primitive value.
  Source=Microsoft.OData.Client
  StackTrace:
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()

Inner Exception 1:
ODataException: Invalid JSON. More than one value was found at the root of the JSON content. JSON content can only have one value at the root level, which is an array, an object or a primitive value.

Microsoft.OData.ODataException
  HResult=0x80131509
  Message=Invalid JSON. More than one value was found at the root of the JSON content. JSON content can only have one value at the root level, which is an array, an object or a primitive value.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.Json.JsonReader.Read()
   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.OData.Json.BufferingJsonReader.Read()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtResourceEndImplementationSynchronously()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtResourceEndImplementation()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.ReadSynchronously()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.OData.ODataReaderCore.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderWrapper.Read()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()*
```
### Additional detail

*It's highly desirable to have this fix both in 5.x and 7.x versions.*

**Comment by biaol-odata** [comment]
This might be a bug in 5.x - 7.x due to different newline char used on Windows vs. Linux.

**Comment by VirusQuartirus** [comment]
> This might be a bug in 5.x - 7.x due to different newline char used on Windows vs. Linux.

Generally library handles Linux-style newline in a good way. It crashes only on the very last batch part (except cases when service returns NoContent response, than it works fine as well).
This behavior doesn't depend on the platform client runs on. So it crashes both on Windows and Linux systems.

**Comment by biaol-odata** [comment]
@VirusQuartirus Are you saying that, **the client, on either Windows or Linux,** throws above exception when parsing the last batch part in the Multi-part response generated by **OData service running on Linux**?
I believe client on Windows + service on Windows doesn't have such issue. That is why I think it is platform dependent related to line-break char(s). Right?

**Comment by VirusQuartirus** [comment]
Right. It's absolutely depends on line break in payload, but it's not depend on OS client runs on.
What I saw in OData client source code it tries to handle both \r\n and \n linebreaks in batch. But it looks like it doesn't handle it in a proper way by the end of a payload stream.
So if we have 10 batch parts we can read 9 of them, but the last one will cause an exception. Unless it's an NoContent response.

**Comment by biaol-odata** [comment]
@VirusQuartirus Sounds like this only happens when the response is generated by **OData service is on Linux**? This will require a setup of using a Linux box, which we don't usually do... So it would be nice to get a confirmation from you.

**Comment by VirusQuartirus** [comment]
Yes, technically it happens when I run our integration tests on Linux machine.
However you can use Fiddler's autoresponder feature to emulate this behavior. Just replace \r\n linebreaks with \n and use this response instead of real service.

**Comment by robertmclaws** [comment]
@biaol-odata Been watching this thread... I know no one asked me, but if the team is shipping a .NET Core compatible version of OData, then you folks should be heavily considering spinning up a Linux container and running your tests there too. You're never going to catch cross-platform bugs on a cross-platform runtime unless you have cross-platform tests.

**Comment by raheph** [comment]
@VirusQuartirus We are going to work on it, meanwhile contribution is much appreciated.

**Comment by marabooyankee** [comment]
@VirusQuartirus The library should work well for any platform as only CRLF is a valid separator in both Multipart messages and in the HTTP protocol as per the multipart [RFC ](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html#z0) and the HTTP protocol [RFC](https://tools.ietf.org/html/rfc7230#section-3). Hence any platform should explicitly use CRLF when composing messages.

**Comment by xuzhg** [comment]
related issue: https://github.com/OData/odata.net/issues/1842
