### ISSUE TITLE
Inconsistent behavior on 'DataServiceQuery.AddQueryOption' related to '$' character

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1333]
The `AddQueryOption` method on `DataServiceQuery` appears to perform specific validation depending on the name supplied in the call by looking for the `$` character in the beginning of the option name. This check is done in an inconsistent manner, conditionally causing an exception for some entries, but not for others.

This is incredibly misleading and unnecessary as far as I can tell.

### Assemblies affected

Microsoft.OData.Client 7.5.2

### Reproduce steps

Create any query using `DataServiceContext`, and then call `AddQueryOptions` with different values:
1. `AddQueryOptions("$select", "field")`
2. `AddQueryOptions("$expand", "field")`
3. `AddQueryOptions("$orderby", "field")`
4. `AddQueryOptions("$skip", 10)`
5. `AddQueryOptions("$skiptoken", "something")`

Then inspect the `RequestUri` property on the `DataServiceContext`.

### Expected result

Either of:
1. All calls should work correctly and append the requested query option to the Expression Url.
2. An exception should be thrown with a specific message telling why a given option is not supported.

### Actual result

Call 5 above causes an exception to be thrown when inspecting the `RequestUri` property on the `DataServiceQuery` object with an overly broad message:
> System.NotSupportedException: Can't add query option '$skiptoken' **because it begins with reserved character '$'**.
at Microsoft.OData.Client.ResourceBinder.ValidationRules.RequireLegalCustomQueryOption(Expression e, ResourceExpression target)
   at Microsoft.OData.Client.ResourceBinder.AnalyzeAddCustomQueryOption(MethodCallExpression mce)
   at Microsoft.OData.Client.ResourceBinder.VisitMethodCall(MethodCallExpression mce)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ResourceBinder.Bind(Expression e, DataServiceContext context)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.get_RequestUri()

Error message itself is completely misleading since I just provided several samples of options beginning with the `$` character that worked fine, going against what is stated in the bolded section. If "anything that began with ´$` was illegal", then for sure I'd get the very same error on the other calls?

### Additional detail

I actually found this out when creating an integration test for one of my OData routes:
```csharp
[DataTestMethod]
[DataRow("$filter", "Id eq 123")]
[DataRow("$orderby", "Id")]
[DataRow("$expand", "Property")]
[DataRow("$skiptoken", "token")]
public async Task GettingProductDetailsWithUnsupportedQueryOptionsShouldReturnBadRequest(
    string queryOption,
    string value)
{
    ...
}
```

Since I've added a custom validator on the server to convert `ODataException`s fired from `ODataQueryOptions<T>` validation, all of these should not pass validation as we only have `Count`/`Format`/`Select`/`Skip`/`Top` enabled.

All tests pass with the exception of the `$skiptoken` one, which fails even before reaching the server.

EDIT:
Seeing the same error with `$apply` and `$deltatoken` options.

**Comment by KanishManuja-MS** [comment]
@julealgon $skiptoken and $delta are reserved for the server to generate, although we could probably use a better error message here.

**Comment by gideonmulder** [comment]
For those looking for a workaround, I use this.
Before you execute, modify the internal RequestUri (no guarantee):

`query.GetType().GetProperty("RequestUri").SetValue(query, new Uri(query.RequestUri.AbsoluteUri + "&$apply=groupby((LabApplicationId,ReferenceNo))"), null);`

**Comment by avruivo** [comment]
My workaround:

```
pageSize = 10;
pageNumber = 2;
query = query.AddQueryOption("$count", $"true&$skiptoken=<cookie pagenumber='{pageNumber}' />");
query.Context.BuildingRequest += (sender, e) => e.Headers.Add("Prefer", $"odata.maxpagesize={pageSize}");
```
