### ISSUE TITLE
Missing overload of 'IncludeTotalCount' that takes a 'bool'

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1334]
This is a feature request issue.

`DataServiceQuery<T>` includes a parameterless `IncludeTotalCount` method, which is responsible for adding `$count=true` to the underlying query.

Using this approach, it is impossible to create a `$count=false` query unless one uses the general purpose `AddQueryOption` method explicitly and hardcodes the values.

It is also clunky to conditionally set the count via an outside boolean parameter, as you have to break the query with an `if` check like:
```csharp
var query = new DataServiceContext(...)
    .CreateQuery<Type>("types");
    
if (includeTotalCount)
    query = query.IncludeTotalCount();

query = query
    .Skip(...)
    .Take(...)
    .Select(...);
```

Versus:
```csharp
var query = new DataServiceContext(...)
    .CreateQuery<Type>("types")
    .IncludeTotalCount(includeTotalCount)
    .Skip(...)
    .Take(...)
    .Select(...);
```

### Assemblies affected

Microsoft.OData.Client 7.5.2

### Expected result

New overload of `IncludeTotalCount` that takes a `bool` parameter.
- `IncludeTotalCount(true)` should be identical in behavior to `IncludeTotalCount()`
- `IncludeTotalCount(false)` should set `$count=false` on the underlying query

### Actual result

Impossible to generate `$count=false` unless using the generic and hardcoded `AddQueryOption`.

### Additional detail

Having a way to explicitly set `$count` to false mimics the possible values on the server, as the count property on `ODataQueryOptions` can be one of:
- `null` 
  Equivalent to not calling `IncludeTotalCount()`

- `true`
  Equivalent to `IncludeTotalCount()` or `IncludeTotalCount(true)`

- `false`
  Equivalent to `IncludeTotalCount(false)`

This can be relevant to people manually handling OData query options on the server, as they have full control of the behavior on all 3 branches.

I needed to create an extension myself to have this in place so that I could stress-test our implementation with all 3 possibilities. My version actually takes a `bool?` as that led to easier parameterized testing (but I think a `bool` version would be more fitting on this API):
```csharp
public static DataServiceQuery<T> IncludeTotalCount<T>(
    this DataServiceQuery<T> dataServiceQuery,
    bool? value)
{
    if (dataServiceQuery == null)
        throw new ArgumentNullException(nameof(dataServiceQuery));

    switch (value)
    {
        case true:
            return dataServiceQuery.IncludeTotalCount();

        case false:
            // HACK: OData parser does not respect casing on booleans, so 'False' breaks. 
            // We need to ensure this is 'false' instead.
            // https://github.com/OData/WebApi/issues/1690
            return dataServiceQuery.AddQueryOption("$count", bool.FalseString.ToLower());

        default:
            return dataServiceQuery;
    }
}
```

**Comment by madansr7** [comment]
@julealgon , thanks for the suggestion. Would you be able to submit a PR based on your change?

**Comment by KenitoInc** [comment]
@julealgon Issue has been fixed. Wait for the next version to be pushed to nuget
