### ISSUE TITLE
Support expand transformation in $apply

### ISSUE THREAD

**Issue by kosinsky** [OData/odata.net#1344]
Aggregation extension specification (http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs02/odata-data-aggregation-ext-v4.0-cs02.html#_Toc435016586) defines expand transformation

**3.12 Transformation expand **
The expand transformation takes a navigation property path that could also be passed as a $expand system query option as its first parameter. The optional second parameter can be either a filter transformation that will be applied to the related entities or an expand transformation. An arbitrary number of expand transformations can be passed as additional parameters to achieve multi-level expansion.
The result set is the input set with the specified navigation property expanded according to the specified expand options.

**Comment by xuzhg** [comment]
Close it as merged.
