### ISSUE TITLE
Consider adding .net3.5 bits to nuget package

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#135]
Now ODL contains .net4.0 portable packages.  Shall also consider adding .net3.5 bits to nuget package, which will make the servicing and customer debugging easier.

**Comment by congysu** [comment]
Could be myget.

**Comment by lewischeng-ms** [comment]
@congysu Had put in msnuge for internal access only:
https://ms-nuget.cloudapp.net/packages/Microsoft.OData.Core.Net35
https://ms-nuget.cloudapp.net/packages/Microsoft.OData.Edm.Net35
https://ms-nuget.cloudapp.net/packages/Microsoft.Spatial.Net35
