### ISSUE TITLE
OData v3 client: PATCH request URI has double slashes after host

### ISSUE THREAD

**Issue by groovyfeng** [OData/odata.net#1352]
The PATCH requests from the OData v3 client has double slashes after the host segment. For example: PATCH http://localhost//Hybrid/StatelessConnectorService/mock/AccountService/Accounts(guid'c2cf7c2d-dead-adad-feaa-2d90df624e62'). It causes failures on HTTP servers that do not know how to handle it. 

### Assemblies affected

OData .Net lib 5.8.4, Assembly Microsoft.Data.Services.Client

### Reproduce steps

Send a patch request from an OData v3 client. Use a HTTP sniffer to monitor the traffic and the double slashes can be seen after the host segment.

### Expected result

There should be only one slash after the host segment in the PATCH request URI.

### Actual result

There are double slashes after the host segment in the PATCH request URI.

**Comment by chuanboz** [comment]
Can you share a standardalone repro and also attach the repro code?

**Comment by groovyfeng** [comment]
Below is the client code:

            Guid accountId = new Guid("C2CF7C2D-DEAD-ADAD-FEAA-2D90DF624E62");

            AccountServiceClient client = new AccountServiceClient(new Uri("http://localhost/Hybrid/StatelessConnectorService/mock/AccountService")); // AccountServiceClient is generated from EDMX using Connected Services
            client.Format.UseJson();
            client.AddAndUpdateResponsePreference = DataServiceResponsePreference.NoContent;
            client.MergeOption = MergeOption.PreserveChanges;

            var accountsQuery = (DataServiceQuery<Account>)(from a in client.Accounts where a.Key == accountId select a);
            IEnumerable<Account> accounts = await Task.Factory.FromAsync(accountsQuery.BeginExecute, accountsQuery.EndExecute, null);
            var account = accounts.First();

            // code to change account entity

            client.UpdateObject(account);
            await Task.Factory.FromAsync<DataServiceResponse>(context.BeginSaveChanges(SaveChangesOptions.PatchOnUpdate, null, null),
                   (queryAsyncResult) =>
                   {
                       var results = context.EndSaveChanges(queryAsyncResult);
                       return results;
                   });

**Comment by groovyfeng** [comment]
The bug is actually in my OData3 compat middleware: it constructs the metadata uri for GET results with double slashes, which is then used by the client to build the URI for PATCH/DELETE.
