### ISSUE TITLE
2 errors when building starter project in visual studio 2017 (setting up spatial os for ue4)

### ISSUE THREAD

**Issue by enicay02** [OData/odata.net#1355]
hey im trying to set up spatialos for ue4 , im following the guide they provided in their site , im in step "Building" 3rd step which is building starter project , after i open the starter project in vs 2017 and click "Build" IT SHOWS TWO errors :
1-- MSB3075	The command "C:\Users\........\UnrealEngine\Engine\Build\BatchFiles\Build.bat StarterProjectEditor Win64 Development "C:\Users\...........\UnrealGDKStarterProject\Game\StarterProject.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.	StarterProject	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets	44	
.
.
2-- Could not find definition for module 'SpatialGDK' (referenced via Target -> StarterProject.Build.cs)	StarterProject	C:\Users\......\UnrealGDKStarterProject\Game\Intermediate\ProjectFiles\UnrealBuildTool	1	
...
what to do to get rid of those ? i'd apreciate any help , thank you

**Comment by KanishManuja-MS** [comment]
Can you please post the link that you are following? We can then try to reproduce the issue from our end.

**Comment by gathogojr** [comment]
Issue from 2018. Missing repro steps and no reaction to request for more info to help repro the issue
