### ISSUE TITLE
Clean up unused CONST definition and MACROS

### ISSUE THREAD

**Issue by karataliu** [OData/odata.net#136]
There're some legacy CONST definition and MACROS in the project. 

WINDOWS_PHONE
ODATALIB_ASYNC
ASTORIA_SERVER
SILVERLIGHT

**Comment by lewischeng-ms** [comment]
And also the macro `WINRT` is useful for next generation .NET platform but we should give it a more meaningful name.

**Comment by lewischeng-ms** [comment]
`ODATALIB_ASYNC` should not be removed due to net35 and netcore50.
`ASTORIA_SERVER` should not be removed because it is used in OData.Service.
Also clean up ASTORIA_LIGHT

**Comment by lewischeng-ms** [comment]
Renamed `WINRT` to `DNXCORE50` to be compatible with the convention of .NET Core 5.

**Comment by lewischeng-ms** [comment]
Checked in as https://github.com/OData/odata.net/commit/d296d5d1af8fc570d0c4bdf1c03d795cf9b64597, https://github.com/OData/odata.net/commit/6636bc2d6a36091a7ade6c3b612caf97ade2aed6 and https://github.com/OData/odata.net/commit/6c595575c922eefa6023c870d22e48f6cad906c7
