### ISSUE TITLE
Way of restricting generated code to only certain types and actions

### ISSUE THREAD

**Issue by TWolverson** [OData/odata.net#1370]
I've generated a client for an instance of Dynamics 365, and I'm finding that the generated code file comes out at around 800k LOC. This is so huge that it makes Visual Studio struggle performance-wise. Aside from the related issues about making the generated code use modern language features more effectively, it would also be really helpful to restrict code generation to only the types my solution is interested in. I usually won't want to access all the different types in a particular API.

### Assemblies affected

OData Client 7.5.3

### Reproduce steps

Run the template using a metadata file gathered from Dynamics 365

### Expected result

The template would obey an optional list of restrictions causing it to only take notice of certain types and actions

### Actual result

The template consumes everything in the metadata, generating a huge file

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by gathogojr** [comment]
The ability to restrict schema types and Edm operations to be emitted in the generated client proxy is currently available when using [OData Connected Service extension](https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService)
