### ISSUE TITLE
Support $expand=*($select=column)

### ISSUE THREAD

**Issue by RanielQuirante** [OData/odata.net#1374]
Currently this method isn't supported yet, but the expand=* is already supported, as a workaround I do everything like this.

$expand=NavProp1($select=colid1),NavProp2($select=colid1),NavProp3($select=colid1)

instead of having it like this

$expand=*($select=colid1)

Hopefully this can be supported

**Comment by madansr7** [comment]
In general, property names without the context of the type on which its defined is not supported.
if the type on which property (colid) is defined is the same across the navigation properties, you can insert a type cast segment before the property name.

**Comment by gathogojr** [comment]
This would only work in a very extreme edge case where `colid1` is present across all the navigation property.
