### ISSUE TITLE
DataServiceQuery<T>.GetKeyPath returns an invalid key path when the keyString contains query options

### ISSUE THREAD

**Issue by joseph-volker** [OData/odata.net#1379]
DataServiveQuery<T>.GetKeyPath generates an incorrect key path when the keyString passed to it contains query options. In the generated string, the resource path is placed after the query options. 

For example, I want to get a single entity from the Person controller. The key for the person I want is 'russellwhyte'. I want to use the GET /People('russellwhyte') method. I also want to include this persons friends, so I add the $expand(Friends) query option.

### Assemblies affected

Microsoft.OData.Client.dll from NuGet package Microsoft.OData.Client version 7.5.3

### Reproduce steps

Sample code below. The Container and People classes were generated using the OData Connected Service version 0.3.0 extension for Visual Studio 2017. The web service used in this example is [](https://www.odata.org/odata-services/)

`
var tripPinUri = new Uri("https://services.odata.org/TripPinRESTierService");
var tripPinContainer = new Container(tripPinUri);
var person = tripPinContainer.People
					.AddQueryOption("$expand", "Friends")
					.ByKey("russellwhyte")
					.GetValue();
`

### Expected result

The request URL for `person` to be "/People('russellwhyte')?$expand=Friends"

### Actual result

The request URL for `person` is "/People?$expand=Friends('russellwhyte')"

### Additional detail

I have a repo at [](https://github.com/joseph-volker/OData-Connected-Service-single-entity-with-query-option-bug) that can reproduce the issue.

**Comment by raheph** [comment]
@joseph-volker Can you set the key before the query option and see whether it can work or not?
