### ISSUE TITLE
Support square brackets with in operator

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#1385]
When we added the IN operator, we specified the use of parens to make it more similar, i.e., to the SQL in operator:

   name in ('a','b','c')

However, due to possible ambiguity, OASIS has changed the syntax to use square brackets:

   name in ['a','b','c']

We should accept square brackets with the in operator, and generate square brackets in building URLs. 

### Assemblies affected

ODL

**Comment by KanishManuja-MS** [comment]
@mikepizzo Wouldn't this be a breaking change if we replace the brackets for the generation as well?

**Comment by KanishManuja-MS** [comment]
@xuzhg @mikepizzo #1164 is one of the reasons why square brackets were not originally supported for IN operator. I would love to get your thoughts on how to proceed with this as the scope of breaking change is more than I had anticipated.

**Comment by xuzhg** [comment]
It was merged. close it.
