### ISSUE TITLE
OData Client Code EnableUnqualifiedNameCall namespace

### ISSUE THREAD

**Issue by 1Jesper1** [OData/odata.net#1396]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected
OData Client 7.4.4
OData v4 Client Code 7.5.0
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

Using UnqualifiedODataUriResolver, the Code Generator uses "Default" as namespace for an action. When setting the namespace to empty, the Code Generator adds a dot to the namespace.

### Expected result
Code Generator should add an empty namespace for the extensionmethods for the actions.
*What would happen if there wasn't a bug.*

### Actual result
Code Generator adds a "Default" or dot as namespace
*What is actually happening.*

### Additional detail
Using this code to use UnqualifiedNameCall: https://github.com/OData/WebApi/issues/1303#issuecomment-376839092
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KanishManuja-MS** [comment]
@1Jesper1 Thanks for identifying the issue. We will add this to the backlog and we are always open to contributions.

**Comment by 1Jesper1** [comment]
Nice @KanishManuja-MS Could you please report back here when there is progress?

**Comment by 1Jesper1** [comment]
Hello @madansr7 and @KanishManuja-MS Has this issue been fixed yet?

**Comment by KenitoInc** [comment]
Hey @1Jesper1 
I would like to understand what you want to achieve with this functionality.
1. Do you want the client to make unqualified calls (without the namespaces)? If yes, why?
2. Note that a server that accepts unqualified calls, can accept qualified calls.

Client unqualified calls are dependent on if the server can accept unqualified calls

**Comment by 1Jesper1** [comment]
@KenitoInc I would like the client to execute the Restore method: `Models.ExtensionMethods.ByKey(client.Employees, keys).Restore().Execute();`

This only works when I change the generated `API.cs` like '     `[global::Microsoft.OData.Client.OriginalNameAttribute("Restore")]`

The original generated code is '        [global::Microsoft.OData.Client.OriginalNameAttribute("Default.Restore")]'

**Comment by KenitoInc** [comment]
@1Jesper1 Did the code snippets resolve your issues?

**Comment by KenitoInc** [comment]
@1Jesper1 Closing this issue for now. Incase you have more problems, you can reopen the issue.
