### ISSUE TITLE
Failure at writing OData context. Error: "Bad Request - Error in query syntax." thrown.

### ISSUE THREAD

**Issue by ShreyasRaghunath2007** [OData/odata.net#1401]
We have an API to accept or decline group membership requests. The URL looks like this:
POST ~/Groups('{Id}')/MembershipRequests/Approve
POST ~/Groups('{Id}')/MembershipRequests/Decline

I found that when the name of the group contains *approve* or *decline*, same as the name of the action, it fails with the following error: "Bad Request - Error in query syntax."

Example:
POST /Groups('test**Approve**@xyz.com')/MembershipRequests/**Approve**
POST /Groups('**decline**@xyz.com')/MembershipRequests/**Decline**

### Assemblies affected

All versions of the OData.

### Reproduce steps

The $metadata for the actions is:
```xml
<EntityType Name="GroupMembershipRequest" BaseType="Microsoft.OutlookServices.Entity">
  <Property Name="Requestee" Type="Microsoft.OutlookServices.GroupMembershipRequestPersona" />
  <Property Name="Requestor" Type="Microsoft.OutlookServices.GroupMembershipRequestPersona" />
  <Property Name="Comment" Type="Edm.String" />
  <Property Name="RequestDateTime" Type="Edm.DateTimeOffset" />
</EntityType>

<ComplexType Name="GroupMembershipRequestPersona">
    <Property Name="Name" Type="Edm.String" />
    <Property Name="Address" Type="Edm.String" />
    <Property Name="MailboxType" Type="Edm.String" />
    <Property Name="ExternalId" Type="Edm.String" />
    <Property Name="Title" Type="Edm.String" />
    <Property Name="ImAddress" Type="Edm.String" />
</ComplexType>

<ComplexType Name="ProcessGroupMembershipRequestResult">
    <Property Name="FailedRequests" Type="Collection(Microsoft.OutlookServices.CustomProperty)" />
</ComplexType>

<Action Name="Approve" IsBound="true">
    <Parameter Name="bindingParameter" Type="Collection(Microsoft.OutlookServices.GroupMembershipRequest)" />
    <Parameter Name="Ids" Type="Collection(Edm.String)" Nullable="false" />
    <Parameter Name="Comment" Type="Edm.String" />
    <ReturnType Type="Microsoft.OutlookServices.ProcessGroupMembershipRequestResult" />
</Action>

<Action Name="Decline" IsBound="true">
    <Parameter Name="bindingParameter" Type="Collection(Microsoft.OutlookServices.GroupMembershipRequest)" />
    <Parameter Name="Ids" Type="Collection(Edm.String)" Nullable="false" />
    <Parameter Name="Comment" Type="Edm.String" />
    <ReturnType Type="Microsoft.OutlookServices.ProcessGroupMembershipRequestResult" />
</Action>

<ComplexType Name="CustomProperty">
    <Property Name="Name" Type="Edm.String" />
    <Property Name="Value" Type="Edm.String" />
</ComplexType>
```

### Expected result

The action to succeed without throwing any error.

### Actual result
"Bad Request - Error in query syntax." error is thrown.

### Additional detail

Stack trace:
`"   at Microsoft.OData.UriParser.ODataPathParser.ExtractSegmentIdentifierAndParenthesisExpression(String segmentText, String& identifier, String& parenthesisExpression)\r\n   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)\r\n   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)\r\n   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)\r\n   at Microsoft.OData.UriParser.ODataUriParser.Initialize()\r\n   at Microsoft.Exchange.Services.OData.Web.ResponseMessageWriter.SetODataContextUriPath(ODataMessageWriterSettings writerSettings, ServiceModel serviceModel, Uri serviceRoot, ODataUri oDataUri, Uri contextUri) in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Web\\ResponseMessageWriter.cs:line 462\r\n   at Microsoft.Exchange.Services.OData.Web.ResponseMessageWriter.CreateODataMessageWriterInternal(ODataMessageWriterSettings writerSettings, IODataResponseMessage responseMessage, IODataRequestMessage requestMessage, ServiceModel serviceModel, ODataUri oDataUri, Uri contextUri, NameValueCollection queryString) in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Web\\ResponseMessageWriter.cs:line 431\r\n   at Microsoft.Exchange.Services.OData.Web.ResponseMessageWriter.CreateODataMessageWriter(IODataResponseMessage responseMessage, IODataContext odataContext) in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Web\\ResponseMessageWriter.cs:line 58\r\n   at Microsoft.Exchange.Services.OData.ODataResponse``1.WriteHttpResponse(IODataResponseMessage responseMessage) in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Framework\\ODataResponse.cs:line 239\r\n   at Microsoft.Exchange.Services.OData.Web.ODataResult.WriteRestODataResponse(ODataResponse response, Boolean allowSmartBuffering) in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Web\\ODataResult.cs:line 203\r\n   at Microsoft.Exchange.Services.OData.Web.ODataResult.End() in d:\\dbs\\sh\\utff\\0203_022202_1\\cmd\\88\\sources\\Dev\\Services\\src\\OData\\Web\\ODataResult.cs:line 129"`

**Comment by xuzhg** [comment]
@ShreyasRaghunath2007 

I tested your scenarios as belows, all cases are passed.

```C#
        [Theory]
        [InlineData("Groups('abc')/MembershipRequests/NS.Approve()")]
        [InlineData("Groups('abc')/MembershipRequests/Approve()")]
        [InlineData("Groups('abc')/MembershipRequests/NS.Approve")]
        [InlineData("Groups('abc')/MembershipRequests/Approve")]

        [InlineData("Groups('testApprove@xyz.com')/MembershipRequests/NS.Approve")]
        [InlineData("Groups('testApprove@xyz.com')/MembershipRequests/Approve")]
        [InlineData("Groups('testApprove@xyz.com')/MembershipRequests/NS.Approve()")]
        [InlineData("Groups('testApprove@xyz.com')/MembershipRequests/Approve()")]

        [InlineData("Groups('decline@xyz.com')/MembershipRequests/NS.Approve")]
        [InlineData("Groups('decline@xyz.com')/MembershipRequests/Approve")]
        [InlineData("Groups('decline@xyz.com')/MembershipRequests/NS.Approve()")]
        [InlineData("Groups('decline@xyz.com')/MembershipRequests/Approve()")]
        public void ParsePathAction(string path)
        {
            // Arrange
            var model = new EdmModel();

            // group
            var group = new EdmEntityType("NS", "Group");
            group.AddKeys(group.AddStructuralProperty("Id", EdmPrimitiveTypeKind.String));
            model.AddElement(group);

            // GroupMembershipRequest
            var groupMembershipRequest = new EdmEntityType("NS", "GroupMembershipRequest");
            groupMembershipRequest.AddKeys(groupMembershipRequest.AddStructuralProperty("Id", EdmPrimitiveTypeKind.String));
            model.AddElement(groupMembershipRequest);

            var navigationProperty = group.AddUnidirectionalNavigation(new EdmNavigationPropertyInfo
            {
                Target = groupMembershipRequest,
                TargetMultiplicity = EdmMultiplicity.Many,
                Name = "MembershipRequests"
            });

            var action = new EdmAction("NS", "Approve", null, true /*isBound*/, null /*entitySetPath*/);
            IEdmTypeReference int32Type = EdmCoreModel.Instance.GetInt32(isNullable: true);
            IEdmTypeReference stringType = EdmCoreModel.Instance.GetString(isNullable: true);

            var collection = new EdmCollectionTypeReference(new EdmCollectionType(new EdmEntityTypeReference(groupMembershipRequest, false)));
            action.AddParameter("bindingParameter", collection);
            action.AddParameter("comments", stringType);
            model.AddElement(action);

            action = new EdmAction("NS", "Decline", null, true /*isBound*/, null /*entitySetPath*/);
            action.AddParameter("bindingParameter", collection);
            action.AddParameter("comments", stringType);
            model.AddElement(action);

            var container = new EdmEntityContainer("NS", "Container");
            var groups = container.AddEntitySet("Groups", group);
            var requests = container.AddEntitySet("Requests", groupMembershipRequest);
            groups.AddNavigationTarget(navigationProperty, requests);
            model.AddElement(container);

            // Act
            var parser = new ODataUriParser(model, new Uri("http://host"), new Uri("http://host/" + path))
            {
                Resolver = new UnqualifiedODataUriResolver()
            };
            var pathSegments = parser.ParsePath().ToList();

            // Assert
            Assert.Equal(4, pathSegments.Count());
            var operationSegment = Assert.IsType<OperationSegment>(pathSegments.Last());
        }
```

**Comment by xuzhg** [comment]
@ShreyasRaghunath2007 From your call stack, it fails in creating the first segment. So,that seems not related to the action. Would you please help check the non-ODL function at `SetODataContextUriPath`

**Comment by mikepizzo** [comment]
Issue was the result of a bad (truncated) Uri being passed in to CreateODataUriParser.
