### ISSUE TITLE
Error when using $count segment with $filter system query option

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#1406]
OData URI parser fails with ODataException when the $count segment is used in conjunction with the system query option $filter.

### Assemblies affected

Microsoft.OData.Core v 7.5.3

### Reproduce steps

1. Create ODataQueryOptions with $count segment and $filter query option, i.e. MyEntitySet/$count?$filter=MyProperty eq 1
2. Try accessing query's Filter.FilterClause property
 
### Expected result

The OData query options' filter is properly parsed into a lexical tree. 

### Actual result

The ODataException is thrown: Microsoft.OData.ODataException: 'Could not find a property named MyProperty' on type 'Edm.Int32'.'

**Comment by xuzhg** [comment]
@korygin 
I tested it and it looks fine at my side. Would you please share me your repo to dig more.

Below is my test:

![image](https://user-images.githubusercontent.com/9426627/53042205-94c1ff00-343a-11e9-9a05-f059a60c494d.png)

**Comment by korygin** [comment]
Hi, after further investigation it appears the error is on our end, we've been passing the wrong EDM type reference to the query context. Closing the issue.
