### ISSUE TITLE
Need help with simple groupby on master – detail

### ISSUE THREAD

**Issue by SoaringCalifornia** [OData/odata.net#1413]
I have very simple scenario with master - detail tables:
Master table 
`Orders (OrderID, OrderDate, OrderTotal)` 
Detail table 
`Items (ItemID, OrderID, ItemName, Price)`

Important note: single Order can have multiple Items with same ItemName 

Trying to create OData equivalent for this simple SQL statement:

```
SELECT Items.ItemName, count(*), SUM(distinct Orders.OrderTotal)
FROM Items
JOIN Orders on Orders.OrderID = Items.ItemID
group by Items.ItemName
```

The `SUM distinct` part is to take care of repeating Items.ItemName for singe order.

Below produces wrong results for OrdersTotal since it sums up all Orders:

`https://localhost:44352/Items?$apply=groupby((ItemName),aggregate(ItemID with countdistinct as ItemCount, Orders/OrderTotal with sum as OrdersTotal))`

This one oddly gives an error: “The query specified in the URI is not valid. The parent value for a property access of a property 'ItemName' is not a single value. Property access can only be applied to a single value.”

`https://localhost:44352/Orders?$apply=groupby((Items/ItemName)) `

Is this even possible to archive with OData V4?

I’m using most recent OData libraries in my project:
Microsoft.AspNet.OData 7.1.0
Microsoft.AspNet.WebApi 5.2.7
Microsoft.OData.Core 7.5.4
Microsoft.OData.Edm 7.5.4
Microsoft.Spatial 7.5.4

Many thanks in advance!

**Comment by xuzhg** [comment]
@SoaringCalifornia Bascially,the **groupby** specifies the grouping properties. the grouping properties are a comma-separated list of one or more **single-valued property paths** (paths ending in a single-valued primitive, complex, or navigation property) that is enclosed in parentheses.

in your `$apply=groupby((Items/ItemName))` , the grouping properties is not a valid property path, because the property access (ItemName) can't be appended after the collection (Items). 

I think you can use the aggregate or compute transformation. @kosinsky is more familiar with the implementation about the aggregate than me. Maybe @kosinsky can share us some thoughts.

**Comment by kosinsky** [comment]
That's correct, you couldn't use collections in the groupby. As a result `$apply=groupby((Items/ItemName))` will fail.

For original question, you could try to use few transformations:
`https://localhost:44352/Items?$apply=groupby((ItemName, Orders/OrderTotal),aggregate($count as ItemCount))/groupby((ItemName), aggregate(ItemCount with sum as TotalItemCount, Orders/OrderTotal with sum as OrdersTotal))`
It should something like:

```
SELECT ItemName,
sum(ItemCount) as TotalItemCount,
sum(OrderTotal) as OrdersTotal
FROM
(
    SELECT Items.ItemName, count(*) as ItemCount, Orders.OrderTotal
    FROM Items
    JOIN Orders on Orders.OrderID = Items.ItemID
    group by Items.ItemName, Orders.OrderTotal
) T
group by ItemName
```
that's semantically equal to original query

**Comment by SoaringCalifornia** [comment]
@kosinsky - thank you so much, you made my day :)
Your solution worked as expected and produced correct results.
I did not know that you can group like that with OData!

**Comment by SoaringCalifornia** [comment]
@kosinsky - I tried adding Orders/TotalWithTax to get summary for order with taxes like below:

`https://localhost:44352/Items?$apply=groupby((ItemName, Orders/OrderTotal, Orders/TotalWithTax),aggregate($count as ItemCount))/groupby((ItemName), aggregate(ItemCount with sum as TotalItemCount, Orders/OrderTotal with sum as OrdersTotal, Orders/TotalWithTax with sum as OrdersTotalWithTax))`

and results for OrdersTotal and OrdersTotalWithTax are off by quite a bit.

What I'm doing wrong here?

**Comment by kosinsky** [comment]
`groupby((ItemName, Orders/OrderTotal, Orders/TotalWithTax))` gives all unique combinations of Name,Total and Tax
If you have data that looks like:
Item1  Total1 TotalTax1
Item1  Total1 TotalTax2

`groupby((ItemName, Orders/OrderTotal))`  will return only:
Item1  Total1
but `groupby((ItemName, Orders/OrderTotal, Orders/TotalWithTax))` preserve both rows. As a result you will sum Total1 twice.

I have two suggestions:
1.  Send two separate query and than combine client side
2. You could try to use Custom Aggregations Method and add Custom.SumDistinct 
Check https://github.com/OData/WebApi/pull/909/files as a reference. Shows how to register custom methods: https://github.com/OData/WebApi/pull/909/files#diff-59133b2a8285d55b2339f12c145cd3c0 and https://github.com/OData/WebApi/pull/909/files#diff-8af2f1789e925dcb1aa8e21c67cc5776 how to use them. 

You still will need to handle how SQL is generated in than case. If your OData endpoint is backed by EF6, https://stackoverflow.com/questions/33437455/code-first-entity-framework-6-1-custom-aggregate-function could be helpful. Then you could use CLR custom aggregates or do a bit of SQL string replacement of Custom.DistinctSum(Column) by sum(distinct Column) before EF6 executes SQL query.

**Comment by SoaringCalifornia** [comment]
@kosinsky I used first suggested approach in the past with decent results.
Second one seems to be quite complex for what I'm trying to do.
Thank you for your help!
