### ISSUE TITLE
SetPayloadValueConverter method is missing in ODataObjectModelExtensions 

### ISSUE THREAD

**Issue by kbarkhausen** [OData/odata.net#1417]
In the static class ODataObjectModelExtensions, the methods named "SetPayloadValueConverter" and "GetPayloadValueConverter" are missing in 7.5.2 but were part of the OData libraries version 6.15

### Assemblies affected

This is missing in Microsoft.OData.Core.ODataObjectModelExtensions

### Reproduce steps

If you examine ODataObjectModelExtensions you will see that these methods are missing.

### Expected result

These methods were part of 6.15 but have been removed - or simply not ported over to 7.5.2

Is there a reason for their removal or absence?

**Comment by xuzhg** [comment]
@kbarkhausen These two methods are removed because OData team want customer to use "Dependent Injection" to inject the customized payload value converter. Can you verify at your side whether you can use DI or not?

**Comment by xuzhg** [comment]
@kbarkhausen I close this, if you have further questions/concerns, please reopen it or file new issues for us. Thanks.
