### ISSUE TITLE
disable property name validation in writer

### ISSUE THREAD

**Issue by srinivasupadhya** [OData/odata.net#1423]
Im trying to create OData API (using Entity Framework as ORM). Everything works end to end. Im trying to set property name for an attribute.

### Assemblies affected

Microsoft.AspNetCore.OData - `v7.1.0`

using:
Microsoft.AspNetCore.Mvc - `v2.2.0`
Microsoft.EntityFrameworkCore - `v2.2.2`

### Reproduce steps

Approach: `DB first` with Model format: `Code`

`Startup.Configure`

```
            var builder = new ODataConventionModelBuilder(serviceProvider);
            var entitySetConfiguration = builder.EntitySet<A>("A");
            entitySetConfiguration.EntityType.Property(a => a.b).Name = "a@b";
            entitySetConfiguration.EntityType.Select().Filter().OrderBy().Page().Count();
            return builder.GetEdmModel();
```

`Controller`

```
        [ODataRoute]
        [EnableQuery]
        public async Task<IActionResult> Get()
        {
            var dbContext = get context;
            return Ok(dbContext.A);
        }
```

### Expected result

The OData response should use `a@b` as property name.

### Actual result

I see the below exception message: `The property name 'a@b' is invalid; property names must not contain any of the reserved characters ':', '.', '@'.`

### Additional Information

[StackOverflow post](https://stackoverflow.com/questions/55085301/odata-disable-property-name-validation)

**Comment by xuzhg** [comment]
@srinivasupadhya '@' is reserved in OData spec for the instance annotation. It's not also valid for most popular languages. Would you please let us know your usage scenario?
We can consider to add quoted syntax for identifiers. But it would be a significant cost and a large change. We need to understand your usage scenarios.

**Comment by srinivasupadhya** [comment]
@xuzhg the column name contains `@` & `.` currently. The UI expects the OData response to have the field with name same as column name. Changing that would be difficult.
Note: This works when we do EDMX way of mapping model to table.

**Comment by srinivasupadhya** [comment]
is there anyway to disable property name validation currently?

**Comment by srinivasupadhya** [comment]
ok. I did the below in Controller:

```
ODataMessageWriterSettings writerSettings = Request.GetRequestContainer().GetRequiredService<ODataMessageWriterSettings>();
            writerSettings.Validations = ValidationKinds.None;
```

Seems to be working.

**Comment by KenitoInc** [comment]
Issue was resolved
