### ISSUE TITLE
Properties defined in $compute and $apply could be used in a following query options ($select, $compute, $filter or $orderby)

### ISSUE THREAD

**Issue by kosinsky** [OData/odata.net#1426]
OData specification [5.1.9 System Query Option $compute](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#_Toc505773305) says:
_The $compute system query option allows clients to define computed properties that can be used in a $select or within a $filter or $orderby expression._

and [3      System Query Option $apply](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs02/odata-data-aggregation-ext-v4.0-cs02.html#_Toc435016567) says
_So the actual (or relevant) structure of each intermediary result will resemble a projection of the original data model that could also have been formed using the standard system query options $expand and $select defined in [OData-Protocol], with dynamic properties representing the aggregate values. The parameters of set transformations allow specifying how the result instances are constructed from the input instances._

That means that all dynamic properties generated in $apply, $compute and $apply=compute() must be visible for query options evaluated after $apply and $compute. Currently it works only for $filter and $orderby. Need to support it for other query options

**Comment by raheph** [comment]
Merged. Close it.
