### ISSUE TITLE
IEdmStructredType.IsOpen is hardcoded to false when instantiating EdmEntityTypeWithDelayLoadedProperties in ClientEdmModel

### ISSUE THREAD

**Issue by AdamCaviness** [OData/odata.net#143]
### Description
We are trying to add OpenType support to one of our entities.  The .NET client is using OData Client with OData Client Code Generator proxies and we would like to send up ODataProperties for each of our dynamic properties that are modified on the client.  *Microsoft.OData.Core.WriterValidationUtils.ValidatePropertyDefined()* does not allow this **even though the code in that Core method looks to account for it and the type in question is an OpenType**.  Please open WriterValidationUtils and look at the code where IsOpen is being checked before throwing the ODataException.  I presume this is a bug because the logic looks correct but the exception is still thrown for Open Types.

### Minimal repro steps
Implement an Open Type entity on the server.  On the client materialization, store the incoming properties that have no target CLR property on the model in some kind of a transient Dictionary<string, object> (example in comments below).  When OnEntryStarting in the client, remove the transient Dictionary<string, object> from the list of ODataProperties and instantiate an ODataProperty for each item in that transient Dictionary<string, object> property to go back up to the server.

### Expected result
The ODataProperties we instanitated on the client in OnEntityStarting should be sent back to the server because the ValidatePropertyDefined method in Microsoft.OData.Core.WriterValidationUtils should not throw an exception when the type IsOpen.  Again, I'm only saying this exception should not be throw when the type is an Open Type. 

### Actual result
OData Core throws an exception 
> The property 'Description' does not exist on type 'WhateverNamespace.WhateverModel'. Make sure to only use property names that are defined by the type.
This appears to be thrown from this code in OData Core:

```CSharp
internal static IEdmProperty ValidatePropertyDefined(string propertyName, IEdmStructuredType owningStructuredType)
{
	Debug.Assert(!string.IsNullOrEmpty(propertyName), "!string.IsNullOrEmpty(propertyName)");

	if (owningStructuredType == null)
	{
		return null;
	}

	IEdmProperty property = owningStructuredType.FindProperty(propertyName);

	// verify that the property is declared if the type is not an open type.
	if (!owningStructuredType.IsOpen && property == null)
	{
		throw new ODataException(Strings.ValidationUtils_PropertyDoesNotExistOnType(propertyName, owningStructuredType.ODataFullName()));
	}

	return property;
}
```
Notice there is a comment that even states that the exception should not be thrown if it is an open type.

### Further technical details
Microsoft.OData.Edm.IEdmStructuredType defines the IsOpen property that has an XML comment of 
>Gets a value indicating whether this type is open

so I would presume the code in *Microsoft.OData.Core.WriterValidationUtils.ValidatePropertyDefined()* should have worked but doesn't.

  
There may be a [related issue](https://github.com/OData/odata.net/issues/134).

**Comment by LaylaLiu** [comment]
To use open property, actually you can add a CLR property into your entity class just as other properties in this CLR class.

**Comment by AdamCaviness** [comment]
@LaylaLiu Thanks for the response.  I had already did that as a workaround but it is very constricting because A) I have to know what all the dynamic properties might be.  B) I have to maintain those over time.  Open Types provide a way to use dynamic properties, I don't want to use static properties on the client.  

Here is what I'm doing.  For some time I've had the OData Client code ingested as a project in my solution so I can handle a few special cases.  Regarding having dynamic properties on the client, I've added the following code to EntryValueMaterializationPolicy.MaterializeResolvedEntry

```CSharp
foreach (var e in entry.Properties)
{
	if (e.Value is ODataStreamReferenceValue)
	{
		continue;
	}

	var prop = actualType.GetProperty(e.Name, this.MaterializerContext.IgnoreMissingProperties);
	if (prop == null)
	{
		// ***********************************************
		// Support OData Open Types.
		// If the property has no destination, stick it in the DynamicProperties dictionary.
		var openType = entry.ResolvedObject as IOpenType;
		if (openType != null)
		{
			if (!openType.DynamicProperties.ContainsKey(e.Name))
				openType.DynamicProperties.Add(e.Name, e.Value);
			else
				openType.DynamicProperties[e.Name] = e.Value;
		}
		// ***********************************************

		continue;
	}

	if (entry.ShouldUpdateFromPayload)
	{
		ValidatePropertyMatch(prop, e, this.MaterializerContext.Model, true /*performEntityCheck*/);

		this.ApplyDataValue(actualType, e, entry.ResolvedObject);
	}
}
```
The little IOpenType interface:
```CSharp
using System;
using System.Collections.Generic;

namespace Microsoft.OData.Client
{
	public interface IOpenType
	{
		/// <summary>
		/// Gets the dynamic properties using the same likeness of 
		/// dynamic properties on the OData server.  It is expected 
		/// that the DataServiceContext implementation not send this back to the server.
		/// </summary>
		/// <value>
		/// The dynamic properties.
		/// </value>
		Dictionary<string, object> DynamicProperties { get; }
	}
}
```

So this gives me a dictionary of the same likeness of the model on the server.  Then in my derived DataServiceContext I hook OnEntryStarting:
```CSharp
Configurations.RequestPipeline.OnEntryStarting(ea => EntryStarting(ea));
```
and then for every IOpenType entity, I create an ODataProperty and send that back up to the server.
```CSharp
	if (entityState == EntityStates.Modified || entityState == EntityStates.Added)
	{
		var odataProps = i.Entry.Properties as List<ODataProperty>;
		if (odataProps == null)
			odataProps = new List<ODataProperty>(i.Entry.Properties);

		// I have other code here to remove any transient properties that should
		// not go back up to the server by using a TransientPropertyAttribute.  The 
		// DynamicProperties property in the given partial model is marked as a 
		// TransientProperty and removed from odataProps.

		// Send up Open Type dynamic properties.
		if (entity is IOpenType)
		{
			foreach (var dynamicProperty in ((IOpenType)entity).DynamicProperties)
			{
				var odataProperty = new ODataProperty() { Name = dynamicProperty.Key, Value = dynamicProperty.Value };
				odataProps.Add(odataProperty);
			}
		}
	}
	
	i.Entry.Properties = odataProps;
```


This would all be a very satisfactory solution to dynamic properties on the client if it were not for the issue mentioned at the beginning.  Microsoft.OData.Core.WriterValidationUtils.ValidatePropertyDefined should allow for sending ODataProperties up that were never on the model.

**Comment by LaylaLiu** [comment]
@AdamCaviness， Thanks for your comments and investigation. We indeed need to handle open type on client side more flexibly. It will be great if you would like to make pull request to contribute code.

**Comment by AdamCaviness** [comment]
I believe I've tracked down the origin of this issue.  WriterValidationUtil.ValidatePropertyDefined() was throwing an ODataException for undeclared properties for Open Types because the owningStructuredType was instantiated in ClientEdmModel with isOpen set to false for all types, even Open Types.  This can be addressed by providing the serviceModel's IEdmEntitySets to the ClientEdmModel from the TypeResolver and when instantiating types in ClientEdmModel, consult the actual IsOpen property on the IEdmEntityType.

**Comment by MrTomWhite** [comment]
🎉that's a great find. Do you have a pr that fixes it?

**Comment by AdamCaviness** [comment]
@MrTomWhite Yes sir, pull request pending.
