### ISSUE TITLE
The type or namespace name 'Library' does not exist in the namespace 'Microsoft.OData.Edm'

### ISSUE THREAD

**Issue by XavierAnnabi** [OData/odata.net#1435]
when using the connect services functionality in VS 2017 to generate the proxy class.
 Odata source is dynamics NAV 2018 with V1 the generated class works well no errors 
but with Odata V4 the generated class has errors 

### Assemblies affected

Microsoft.OData.Client 7.5.4.30215

### Reproduce steps
get the metadata for Odata V4 from Dynamics NAV 2018
save the metadata in XML file
add connected service with VS 2017 
specify the XML file as metadata
![image](https://user-images.githubusercontent.com/36770013/55161844-d67e4d80-513c-11e9-85c0-3c6eaedc3873.png)

### Actual result

Compile errors
![image](https://user-images.githubusercontent.com/36770013/55161939-0c233680-513d-11e9-9857-89a5078c9ab6.png)

Thanks.

**Comment by xuzhg** [comment]
@XavierAnnabi OData V4 library v7.x changes the namespace. Can you double check whether the namespace is correctly referencing to.
