### ISSUE TITLE
suppress the error in reading open entity’s undeclared primitive, collection and complex property value.

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#144]
For both V3 & V4

**Comment by AdamCaviness** [comment]
May you add some context to what this actually means?  This issue is presently still open and not associated with a commit but is referenced as part of [ODataLib 6.11.0] (http://blogs.msdn.com/b/odatateam/archive/2015/04/02/odatalib-6-11-0-release.aspx).  Thanks.

**Comment by challenh** [comment]
this is a feature request rather than a bug. Some OData services don't want their existing clients to fail on unrecognized properties while they upgrade service side and add new property into entity defintion

**Comment by AdamCaviness** [comment]
@LaylaLiu  @challenh Thank you for explaining this some. I'm afraid I still cannot determine if this is related to https://github.com/OData/odata.net/issues/143 and https://github.com/OData/odata.net/issues/134.  They seem to be at least related if not the same thing, can you confirm?  Also, can this Issue be related to an existing commit (I genuinely do not know if GitHub allows that on a closed Issue)?

**Comment by LaylaLiu** [comment]
@AdamCaviness This is not related to #143 & #134, It is about OData core library. The related commit should be https://github.com/OData/odata.net/commit/f1f910e5df516b7b232a6e25465d0be58928722f.
