### ISSUE TITLE
Incompatible type kinds were found. Found type kind 'Primitive' instead of the expected kind 'None'. on Microsoft.OData.ODataReaderCore.Read() when EnumType and EntityType had the same name.

### ISSUE THREAD

**Issue by leokc-ng** [OData/odata.net#1445]
*Short summary (3-5 sentences) describing the issue.*

We are experiencing error of Microsoft.OData.ODataReaderCore.Read() throw incompatible type kinds were found. Found type kind 'Primitive' instead of the expected kind 'None'.  

The cause of the issue was the report  entity contain a Enum field of type ItemType, where there exist another entity named ItemType,

Snippet of Enum field of ItemType
![image](https://user-images.githubusercontent.com/17868236/56016715-c915b580-5d2f-11e9-909f-25f63ab1003d.png)

Enum Type  definition
![image](https://user-images.githubusercontent.com/17868236/56017762-dbddb980-5d32-11e9-85a0-a1a856c859c9.png)

Entity Definition
![image](https://user-images.githubusercontent.com/17868236/56016827-16922280-5d30-11e9-8f2d-4addde0a86dc.png)

### Assemblies affected

Microsoft.OData.Core 7.5.4

**Comment by KanishManuja-MS** [comment]
OData protocol does not allow duplicate names for top-level elements in the same namespace. If you call Validate on the model, it should fail.

**Comment by suwblk** [comment]
I also got the same error in MS Excel when I had same name for "EntityType" and "EnumType" elements. With this explanation I fixed the duplicates. Now the url populates data correctly when entered in the web browser, but the same url still gives the same issue in excel. Could you please help ?

However "_EntityType_" **CustomerInfo** has a sub element "_Property_" that has name 'CustomerCategory'   which referres to the "EnumType" **CustomerCategory**. But that is not a top level element. 

![No duplicates CDSL](https://user-images.githubusercontent.com/41049983/77527027-79cd8400-6eb1-11ea-8891-f6c73774bc86.png)
![OData Excel issue](https://user-images.githubusercontent.com/41049983/77527053-82be5580-6eb1-11ea-8686-23fa58262d21.png)

**Comment by suwblk** [comment]
You can close this.

**Comment by gathogojr** [comment]
Related issue https://github.com/OData/odata.net/issues/1721. Issue reporter identified the problem and advised that the issue may be closed
