### ISSUE TITLE
Error when I try to use "in" logical operator in an "any" lambda operator

### ISSUE THREAD

**Issue by HigorSilvaRosa** [OData/odata.net#1447]
Hi!

I'm using OData 4, and I'm trying do this filter:
**$filter=Itens/any(c: c/NotaFiscalID in (8962,8503))**
But it just not work.

When a change te filter to this work pretty good:
**$filter=Itens/any(c: c/NotaFiscalID eq 8962 or c/NotaFiscalID eq 8503)**

The problem is just when I try to use the "in" logical operator.

Thank you!

**Comment by KanishManuja-MS** [comment]
@HigorSilvaRosa Thanks for pointing out. We will investigate this.
