### ISSUE TITLE
ODataLib deserialize instance annotations in a request payload

### ISSUE THREAD

**Issue by dingeins** [OData/odata.net#146]
The requirement comes from CRM. They'd like to allow special control information to be passed together with the data to the service when doing posts/updates.

It's also useful from a general perspective, e.g. `@odata.type` annotation be passed together with the complex type in a entity post to indicate if a base type instance or a derived type instance is posted, if the base type is defined in the model.

The current behavior, as is confirmed by our engineer, is the core lib will ignore the instance annotations in request payloads. Reverting this behavior might be a breaking change.

**Comment by dingeins** [comment]
The related issue in Web API: https://github.com/OData/WebApi/issues/289

**Comment by mikepizzo** [comment]
I'm surprised this hasn't been more of an issue.  Perhaps, if someone is impacted, they can contribute a fix (or propose an increased priority)?
