### ISSUE TITLE
The closed type Aimm.Client.BusinessLayer.ODataSupport.Default.CustomerStatus does not have a corresponding 1 settable propertyThe closed type Default.CustomerStatus does not have a corresponding 1 settable property

### ISSUE THREAD

**Issue by hlymca84** [OData/odata.net#1460]
The closed type Default.CustomerStatus does not have a corresponding 1 settable property i have CustomerStatus and which is enum but now when i am calling from OData Client Generator and call the oData Action i am getting this error.

Don't have any idea what's wrong i am making, When i am looking to data all is fine

**Comment by madansr7** [comment]
@hlymca84 , can you please provide more information on the error. Maybe a sample solution or a snippet of code.

**Comment by xuzhg** [comment]
@hlymca84 besides, would you please share us your CSDL file and steps to reproduce it? Thanks.

**Comment by hlymca84** [comment]
This i have managed to solve it, The issue was in with data, I have used enum and return result don't have that enum value so that where the issue was coming.

**Comment by gathogojr** [comment]
Issue reporter confirmed to have resolved the issue on their own
