### ISSUE TITLE
Issue with In operator

### ISSUE THREAD

**Issue by eduardomgsilva** [OData/odata.net#1461]
I have updated both Microsft.Odata.Core and Microsft.Odata.Edm from version  7.4.1 to version 7.5.4, i could use the In operator but i am getting the fowling error;
{
  "error": {
    "code": "",
    "message": "The query specified in the URI is not valid. The method or operation is not implemented.",
    "innererror": {
      "message": "The method or operation is not implemented.",
      "type": "System.NotImplementedException",
      "stacktrace": "   at Microsoft.OData.UriParser.QueryNodeVisitor`1.Visit(InNode nodeIn)\r\n   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor, ODataQueryContext queryContext)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    }
  }
} 

Am i missing something?

### Assemblies affected

Microsft.Odata.Core 7.5.4
Microsft.Odata.Edm 7.5.4

**Comment by xuzhg** [comment]
@eduardomgsilva It seems you are using OLD version of Web API OData. it's `System.Web.OData`, the new Web API namespace is `Microsoft.AspNet.OData`. did you see the same error message to use new version?

**Comment by eduardomgsilva** [comment]
@xuzhg Yes you are right i am using the old version, i will have to updated it but it's not going to be an easy update.
Thank you.

**Comment by eduardomgsilva** [comment]
Upgraded from System.Web.OData to Microsoft.AspNet.OData and it solved the problem
