### ISSUE TITLE
Support enum parameters for Uri function

### ISSUE THREAD

**Issue by kosinsky** [OData/odata.net#1467]
We could add custom Uri (query) functions using static CustomUriFunctions.AddCustomUriFunction method. However, functions with enum as parameters aren't fully suppored when multiple copies of the same IEdmModel (with small changes) are generated.

Following expressions should be suppored:
* `$filter=enumFunc('Rectangle')`
* `$filter=enumFunc(Fully.Qualified.Namespace.EnumType'Rectangle')`

**Comment by xuzhg** [comment]
Merged. Thanks.
