### ISSUE TITLE
Generated OData client doesn't support nested pagination

### ISSUE THREAD

**Issue by cory-hrh** [OData/odata.net#1477]
We have a custom OData service with server-side paging.
We have used the OData Client Code Generator to create a client from our model.
When we use the generated client to query an entity set "A" expanding a navigation property "B" there appears to be no way of retrieving the `B@odata.nextLink` value (if present) from the expanded "B" collections - we only receive the nextLink for "A".

### Assemblies affected

OData v4 Client Code Generator 7.5.1

#### Model setup

```XML
<EntityType Name="Parent">
    <Property Name="Name" Type="Edm.String" />
    <NavigationProperty Name="Children" Type="Collection(Child)" ContainsTarget="true" />
</EntityType>
<EntityType Name="Child">
  <Property Name="ChildName" Type="Edm.String" />
</EntityType>
```

#### Server setup
If we make the following request to the server:
`GET http://service/v1/Parents?$expand=Children` (with a page size of 1)

We receive the first page's JSON response:
```JSON
{
    "@odata.context": "http://service/v1/$metadata#Parents",
    "@odata.count": 9,
    "@odata.nextLink": "http://service/v1/Parents?$expand=Children&$skiptoken=abc..",
    "value": [
        {
            "@odata.id": "http://service/v1/Parent('ABLE')",
            "Name": "ABLE",
            "Children@odata.count": 3,
            "Children@odata.nextLink": "http://service/v1/Parents('ABLE')/Children?$skiptoken=xyz..",
            "Children": [
                {
                    "@odata.id": "http://service/v1/Parents('ABLE')/Children('ZULU')",
                    "ChildName": "ZULU"
                }
            ]
        }
    ]
}
```

i.e. We receive the first Parent "ABLE" and its first Child "ZULU".
Following `Children@odata.nextLink`  would return ABLE's next Child "YANKEE".
Similarly the main `@odata.nextLink` would return the next Parent "BAKER".

#### Client setup

We query the server using the generated client
```C#
DataServiceQuery<Parent> query = container.Parents.Expand("Children");
QueryOperationResponse<Parent> firstPage = await query.ExecuteAsync();

// We can get the link to the page with the next parent
var nextPageLink = firstPage.GetContinuation(); // Will return BAKER

// Docs implies this is how to retrieve nextLink for nested collections..
var nextChildLink = firstPage.GetContinuation(Enumerable<Child> firstNestedPageResult); // Should return YANKEE but actually fails

// Alternatively, GetAllPagesAsync() gets all Parents but won't retrieve all Children
QueryOperationResponse<Parent> allParents = await query.GetAllPagesAsync(); // Returns ABLE, BAKER, .. but only first child of each (ZULU but no YANKEE)
```

### Expected result

We would expect `nextChildLink` to represent the URL `http://service/v1/Parents('ABLE')/Children?$skiptoken=xyz..`

### Actual result

The `GetContinuation(enumerable)` call always fails with "The collection is not part of the current entry".

### Additional detail

From a brief investigation it appears this is due to `GetContinuation(enumerable)` internally depending on `NextLinkTable` which is never populated.

We are basing this expected behaviour on section [8.2.8.5 of the OData v4.0 specification](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_The_odata.maxpagesize_Preference).
> Example 8: a request for customers and their orders would result in a response containing one collection with customer entities and for every customer a separate collection with order entities. The client could specify odata.maxpagesize=50 in order to request that each page of results contain a maximum of 50 customers, each with a maximum of 50 orders.

> **If a collection within the result contains more than the specified odata.maxpagesize, the collection SHOULD be a partial set of the results with a next link to the next page of results**. The client MAY specify a different value for this preference with every request following a next link.

**Comment by 8over8** [comment]
Hi,

Do we have a work around for this?
I have a similar issue. Using the analogy in the original post I have a single instance of Entity A with a child collection of Entity B. Setting the PageSize property for the EnableQuery attribute on an ODataController will affect the child collection. E.g. if set to 10 then the child collection will only return the first 10 records. However, I do not get a generated @odata.nextLink generated for the child collection. Additionally, applying $top and $skip to the expanded child collection has no affect whatsoever. Example:

URL: {server}/odata/As({id}?$expand=Bs($top=5;$skip=0)

The above URL outlines a call to get a single instance of the model A identified by the parameter "{id}". I expand the child collection of model B. I apply $top and $skip to the expanded collection. This does not throw any exception but also is not applied to the query. They are simply ignored. I also don't receive any @odata.nextLink properties on the returned Entity A or on the child collection of Entity B.

**Comment by KenitoInc** [comment]
> Hi,
> Do we have a work around for this?
> I have a similar issue. Using the analogy in the original post I have a single instance of Entity A with a child collection of Entity B. Setting the PageSize property for the EnableQuery attribute on an ODataController will affect the child collection. E.g. if set to 10 then the child collection will only return the first 10 records. However, I do not get a generated @odata.nextLink generated for the child collection. Additionally, applying $top and $skip to the expanded child collection has no affect whatsoever. Example:
> URL: {server}/odata/As({id}?$expand=Bs($top=5;$skip=0)
> The above URL outlines a call to get a single instance of the model A identified by the parameter "{id}". I expand the child collection of model B. I apply $top and $skip to the expanded collection. This does not throw any exception but also is not applied to the query. They are simply ignored. I also don't receive any @odata.nextLink properties on the returned Entity A or on the child collection of Entity B.

@8over8 
Let me clarify a few issues
1. `top` & `skip` are only used on client side pagination. Server side pagination is driven by PageSize property in the EnableQuery attribute e.g *[EnableQuery(PageSize =2)]*. When we do the server driven paging, server always returns next page link to the response body. In Client side paging, we do not have a next page link in the response.
2. If the total number of items is less than the PageSize, we will not have next page link.

**Comment by KenitoInc** [comment]
@cory-hrh 
I have created a service similar to what you have. I wrote the client code below and I managed to get the nested pagination links. Kindly try it and confirm if it works for you.

Below is the code I have used to recreate the issue

            Container dsc = new Container(new Uri("https://localhost:44334/"));
            DataServiceQueryContinuation<Parent> nextLink = null;​
            int pageCount = 0;​
            int innerPageCount = 0;​
​
            try​
            {​
                // Execute the query for all parents and related children,​
                // and get the response object.​
                var response =​
                    dsc.Parent.AddQueryOption("$expand", "Children")​
                    .Execute() as QueryOperationResponse<Parent>;​
​
                // With a paged response from the service, use a do...while loop ​
                // to enumerate the results before getting the next link.​
                do​
                {​
                    // Write the page number.​
                    Console.WriteLine("Parents Page {0}:", ++pageCount);​
​
                    // If nextLink is not null, then there is a new page to load.​
                    if (nextLink != null)​
                    {​
                        // Load the new page from the next link URI.​
                        response = dsc.Execute<Parent>(nextLink)​
                            as QueryOperationResponse<Parent>;​
                    }​
​
                    // Enumerate the Parent(s) in the response.​
                    foreach (Parent p in response)​
                    {​
                        Console.WriteLine("\tParent Name: {0}", p.Name);​
                        Console.WriteLine("\tChildren Page {0}:", ++innerPageCount);​
                        // Get the next link for the collection of related Children.​
                        DataServiceQueryContinuation<Child> nextChildrenLink =​
                            response.GetContinuation(p.Children);​
​
                        foreach (Child c in p.Children)​
                        {​
                            // Print out the children in the first page.​
                            Console.WriteLine("\t\tChildID: {0} - Name: ${1}",​
                                c.Id, c.Name);​
                        }​
​
                        while (nextChildrenLink != null)​
                        {​
                            Console.WriteLine("\t\t******Load Child******");​
​
                            // Load the next page of Orders.​
                            var childrenResponse = dsc.LoadProperty(p, "Children", nextChildrenLink);​
                            nextChildrenLink = childrenResponse.GetContinuation();​
                            foreach (Child c in childrenResponse)​
                            {​
                                // Print out the orders.​
                                Console.WriteLine("\t\tChildID: {0} - Name: ${1}",​
                                    c.Id, c.Name);​
                            }​
                        }​
                    }​
                }​
​
                // Get the next link, and continue while there is a next link.​
                while ((nextLink = response.GetContinuation()) != null);​
            }​
            catch (DataServiceQueryException ex)​
            {​
                throw new ApplicationException(​
                    "An error occurred during query execution.", ex);​
            }

**Comment by 8over8** [comment]
@KenitoInc firstly, thanks for the reply. My original post does seem to merge the two types of pagination into a single question. For the confusion, I apologise. Regarding usage of PageSize I could see this affecting the result set and being applied. I was not getting next and prev links returned and I do remember there being considerable records in my DB for there to be enough several pages of entity type B. 

My original question was mainly to do with client-side pagination. I still don't understand why $top and $skip were deemed as valid (by the parsing module) but completely ignored when returning data. This is the real crux of my question. Should this have been applied or not and why?

Thanks

Andrew

**Comment by KenitoInc** [comment]
Hey Andrew @8over8 ,
Let's test using the Trippin Service

The query below return ALL people
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People

The query below return the first 2 items
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People?$top=2

The query below return 2 items (It will skip the first 2 items and return the 3rd and 4th)
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People?$top=2&$skip=2

**Comment by 8over8** [comment]
Those examples you have provided will work and I have seen them working. However, the example i gave is using the $top and $skip within a $expand statement e.g:

URL: {server}/odata/As({id}?$expand=Bs($top=5;$skip=0)

The parser parses this with no issues but then ignores the application of $top and $skip for the nested collection.

Is this expected behaviour or not? if so, why?

**Comment by KenitoInc** [comment]
@8over8 
For your specific example

We get ALL Trips associated with Person russellwhyte
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People('russellwhyte')?$expand=Trips

We get the first 2 Trips
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People('russellwhyte')?$expand=Trips($top=2)

We get the 2nd and 3rd Trip
https://services.odata.org/TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People('russellwhyte')?$expand=Trips($top=2;$skip=1)

**Comment by 8over8** [comment]
OK so it's something that I am doing wrong on my side. At least I know it's supported. Thanks

**Comment by KenitoInc** [comment]
> OK so it's something that I am doing wrong on my side. At least I know it's supported. Thanks

Probably! Look at your service again. Am glad I have clarified what you wanted. You can look at this doc for more query options https://docs.microsoft.com/en-us/odata/concepts/queryoptions-usage

**Comment by KenitoInc** [comment]
Hi @cory-hrh 
Did you have a chance to look at the code I shared above? I would like to hear your thought.

**Comment by cory-hrh** [comment]
Hi @KenitoInc 
We haven't yet but we expect to find time to look into this next week.

Just to confirm, is your code using the Client Code Generator or have you written it all manually? As mentioned in the first post we were using the Visual Studio OData Client Generator extension and were seeing this issue and there hasn't been a published update for that generator since then?

**Comment by KenitoInc** [comment]
@cory-hrh I tested this code with the Odata Client Code generator to generate the proxy classes as you did. I think what's different is how you enumerate and consume and your next page links. Look at the code I share and get back to me

**Comment by KenitoInc** [comment]
@cory-hrh Did you get time to test the code I had shared above?

**Comment by KenitoInc** [comment]
@cory-hrh Closing this issue. If there are any issues arising, feel free to reopen it.
