### ISSUE TITLE
Question: Not In

### ISSUE THREAD

**Issue by eduardomgsilva** [OData/odata.net#1478]
Hi,

Is there any feature or planed feature for a Not In operator.?
Because i am trying to exclude a large number of ids from Odata query
 and if is use many "and ne" i reach the odata limit. 
Or is there another way of doing this?

Thank you.

**Comment by xuzhg** [comment]
@eduardomgsilva, can you try the pattern like `?$filter=property in [v1, v2, ...] eq false`?

**Comment by eduardomgsilva** [comment]
@xuzhg  It worked, thank you very much.

**Comment by Sayan751** [comment]
@xuzhg Is there any reason of not supporting `not property in ('v1', 'v2')` instead?

**Comment by Sayan751** [comment]
However I see not tests here: https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs

This raises the question whether the pattern `not(property in ('v1', 'v2'))` is officially supported.

**Comment by Sayan751** [comment]
At least the URI Parser works correctly. This can be seen from this commit: https://github.com/Sayan751/odata.net/commit/26204d55e65384c5d3dc6ae883792edd16cb499b.
