### ISSUE TITLE
oData C# Client return wrong value and duplicate record

### ISSUE THREAD

**Issue by hlymca84** [OData/odata.net#1484]
*Short summary (3-5 sentences) describing the issue.*
I have written OData Controller to get record, This odata call the stored procedure and return the record all working fine when checking with RestClient Call.

When i am calling this api in c# it's giving me same number of record which return from stored procedure but here many record are getting duplicated and many of them are missing.

I don't know where and what i am missing in the call, Here following is the code which i have written to call.

1) have already written Primary key set to the model. 
2) Checked the call in fiddler and here in fiddler record are showing correct.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result
Result should be all record which oData Controller is returning from web api
*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail
  Uri serviceUri = new Uri($"{WebServiceUtil.OdataBaseAddress}/CustomerReach");
            Container _context = new Container(serviceUri);

            string messageText = string.Empty;
            _context.SendingRequest2 += (objSender, objEventArgs) =>
            {
                messageText = string.Format("{0} {1}", objEventArgs.RequestMessage.Method, objEventArgs.RequestMessage.Url);
            };
            _context.BuildingRequest += (o, args) => args.Headers.Add("Authorization", "Bearer " + SecurityUtil.CurrentToken);
            _context.Format.UseJson();

            BodyOperationParameter companyIdParam = new BodyOperationParameter("CompanyId", CurrentContext.CurrentContextCompanyId);
            BodyOperationParameter customerIdParam = new BodyOperationParameter("CustomerId", searchCriteria.CustomerId);
            BodyOperationParameter ContactNameParam = new BodyOperationParameter("ContactName", searchCriteria.ContactName);
            BodyOperationParameter AddressParam = new BodyOperationParameter("Address", searchCriteria.Address);
            BodyOperationParameter BusinessNameParam = new BodyOperationParameter("BusinessName", searchCriteria.BusinessName);
            BodyOperationParameter FromDateParam = new BodyOperationParameter("FromDate", searchCriteria.FromDate);
            BodyOperationParameter ToDateParam = new BodyOperationParameter("ToDate", searchCriteria.ToDate);
        
                    OperationParameter[] operationParameters = { companyIdParam, customerIdParam, ContactNameParam, AddressParam, BusinessNameParam };
                    _customerReachesVms = _context.Execute<Client.BusinessLayer.ODataSupport.Aimm.Common.Model.CustomerReacheLookupVm>(serviceUri, "POST", operationParameters).ToList();
               
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by raheph** [comment]
@hlymca84 Can you please share the response from the fiddler? Does this also happen the first time you run the client app?

**Comment by flakey-bit** [comment]
Double check the key is set correctly in your EDMX (that was the issue for me)

**Comment by hlymca84** [comment]
Yes it has issue with key now it's fixed
