### ISSUE TITLE
Namespace issue with odata client generator for System.Text

### ISSUE THREAD

**Issue by atnegrete** [OData/odata.net#1495]
On this line of the generated CS client file:
 global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();

It complains about 'Text' does not exist in the System namespace. It is confused about which namespace to use. Replacing the above line with this works:

 global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();

But it is not ideal to edit the generated file.

### Assemblies affected

Odata Client Generator 7.5.1

### Reproduce steps

Run custom tool on .tt file, and there exists a namespace already for System

### Expected result

Odata client would generate successfully without build errors.

### Actual result

Build error when running the custom tool on the .tt file

**Comment by ElizabethOkerio** [comment]
@atnegrete,  can you please share the csdl or service endpoint that you used for us to be able to reproduce the issue. Thanks.
