### ISSUE TITLE
Navigation properties through an entity with an Enum key segment does not work.

### ISSUE THREAD

**Issue by jnanneng** [OData/odata.net#1498]
Ex:  …/OData/v4.0/1.0/Company('CRONUS International Ltd.')/Page99441(Type=NS.Page99441.Type'Order',No='1')/Customer_Link

The OData EnumBinder turns the value of the ‘Type’ key segment into a ‘ConstantNode’ with a value of an ODataEnumValue instance. 

When the @odata.Context value of the response attempts to be serialized, an exception is thrown:
The type 'Microsoft.OData.UriParser.ConstantNode' is not supported when converting to a URI literal.

This appears to occur within LiteralFormatter.FormatRawLiteral as it does not support a ‘ConstantNode’, but instead coded to ‘ODataEnumValue’.

### Assemblies affected

Microsoft.OData.* 7.5.0

### Reproduce steps

Define an entity with an enum key which is capable of navigating to another entity.  Issue a request for a navigation property of that entity.

### Expected result

It would succeed.

### Actual result

Error is encountered:  The type 'Microsoft.OData.UriParser.ConstantNode' is not supported when converting to a URI literal.

### Additional detail

The OData EnumBinder turns the value of the enum key segment into a ‘ConstantNode’ with a value of an ODataEnumValue instance. 

When the @odata.Context value of the response attempts to be serialized, an exception is thrown:
The type 'Microsoft.OData.UriParser.ConstantNode' is not supported when converting to a URI literal.

This appears to occur within LiteralFormatter.FormatRawLiteral as it does not support a ‘ConstantNode’, but instead coded to ‘ODataEnumValue’.

**Comment by xuzhg** [comment]
Merged at: c64b89775306a909fdf5e71287d08ba6012ae19c
