### ISSUE TITLE
Adapter between OData and ElasticDB in .Net core

### ISSUE THREAD

**Issue by SaiSingamsetty** [OData/odata.net#1501]
*Short summary (3-5 sentences) describing the issue.*
I am not able to find any support to convert OData queries to ElasticSearch Queries in .Net
Is there any adapter/plugin for this requirement in OData

**Comment by KanishManuja-MS** [comment]
@SaiSingamsetty  I don't have any experience of using OData over ElasticSearch but a quick bing search shows that there is a variety of third-party software such as [this](https://www.cdata.com/drivers/elasticsearch/odata/)  and open-source projects such as [this ](https://github.com/Hevelian/hevelian-olastic).

**Comment by cristipufu** [comment]
I started working on such an adapter, just for future reference if anyone stumbles upon this post: https://github.com/cristipufu/elasticsearch-odata-net
