### ISSUE TITLE
Support groupby with property path length greater than 2

### ISSUE THREAD

**Issue by adzhilyanov** [OData/odata.net#1505]
groupby((SingleValuedProp)) **works**.
groupby((SingleNavProp/SingleValuedProp)) **works**.
groupby((SingleNavProp/SingleNavProp/SingleValuedProp)) **does not work**.
groupby((SingleNavProp/SingleNavProp/SingleNavProp/SingleValuedProp)) **does not work**. 
and so on...

We tracked this down to the OData .Net lib.

### Assemblies affected

*OData .Net 7.6.0*
*OData .WebApi 7.1.0* 

### Reproduce steps

Orders?$apply=groupby((OrderClass/OrderType/Name))

### Expected result

Get results grouped by OrderClass/OrderType/Name

### Actual result

The query specified in the URI is not valid. Could not find a property named 'OrderType' on type 'Namesapce.Order’.

**Comment by madansr7** [comment]
@kosinsky

**Comment by adzhilyanov** [comment]
Hey, I've been a bit busy. I will be able to address them in the beginning of next week. Hope that is ok. Regards!
