### ISSUE TITLE
$select parser returns empty path segment for dotted identfier

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/odata.net#1509]
Parsing $select=Rating,Dotted.Name should throw `ODataException`, but it doesn't. Instead, it returns two `PathSelectItems`: a `PropertySegment` for "Rating" (expected), and an empty segment for the dotted name (unexpected).

### Assemblies affected

Microsoft.OData.Core 7.5.3 with Microsoft.AspNet.OData 7.1.0.

I'm not sure whether the issue is in ODataLib or Web API OData; I haven't debugged that far.

### Reproduce steps

Full repro here: https://github.com/brjohnstmsft/odata-repros/blob/7059b1ce228388564d985e1462331e8565590ef9/SelectTokenizeBug/Repro.cs#L55

### Expected result

Accessing `.SelectExpandClause` for a $select clause with a dotted identifier would throw an `ODataException`, similar to other kinds of $select parser errors.

### Actual result

The parser returns two `PathSelectItems`: a `PropertySegment` for "Rating" (expected), and an empty segment for the dotted name (unexpected).

**Comment by xuzhg** [comment]
Merged at: https://github.com/OData/odata.net/commit/572082374a496b5855f28a9f66145f577029659c
