### ISSUE TITLE
How send request to Asp.Net Core OData api in server side from client side

### ISSUE THREAD

**Issue by adsalnet** [OData/odata.net#1512]
I have an asp.net core api with odata and how can I call this odata from client side (this client is asp.net core mvc)

**Comment by KanishManuja-MS** [comment]
Any http client should be able to call into the Asp.Net Core OData service. If you are writing a dotnet client application to call any odata service, you can use a variety of client libraries including [OData Client](https://www.nuget.org/packages/Microsoft.OData.Client/) or [OData simple client](https://www.nuget.org/packages/Simple.OData.V4.Client/).

**Comment by gathogojr** [comment]
Issue reporter advised on libraries they can use to make calls from a client application to an OData service. No fresh activity since
