### ISSUE TITLE
EDM: Action return type is always nullable?

### ISSUE THREAD

**Issue by NetTecture** [OData/odata.net#1520]
I am building an EdmModel for a code generator that is loading a published odata model. In this model, an action is defined like this:

Unbound import:
< ActionImport Name= "GeoCode" Action="Tools.GeoCode"/ >

With the action as:

< Action Name ="GeoCode">
< Parameter Name="Address" Type="Common.AddressGeoCoded"/>
<  ReturnType Type="Common.AddressGeoCoded"/>
< /Action>

AddressGeoCoded is a complex type:

< ComplexType Name= "AddressGeoCoded" BaseType="Common.Address">

When I check this loaded model in the code generator, I find an IEdmAction that contains an IEdmTypeReference to the return type. This one is nullable. Why? As per schema the return type is not nullable.

  | Name | Value | Type
-- | -- | -- | --
◢ | Return | {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsOperationReturn} | Microsoft.OData.Edm.IEdmOperationReturn {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsOperationReturn}
  | ▶ DeclaringOperation | {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsAction} | Microsoft.OData.Edm.IEdmOperation {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsAction}
  | DirectValueAnnotations | null | System.Collections.Generic.IEnumerable<Microsoft.OData.Edm.Vocabularies.IEdmDirectValueAnnotation>
  | ▶ Element | {Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlOperationReturn} | Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlElement {Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlOperationReturn}
  | InlineVocabularyAnnotations | {Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation[0]} | System.Collections.Generic.IEnumerable<Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation> {Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation[]}
  | ▶ Location | {(1, 58447)} | Microsoft.OData.Edm.EdmLocation {Microsoft.OData.Edm.Csdl.CsdlLocation}
  | ▶ Model | CsdlSemanticsModel("Common,Library,Operations,PropertyCore,ZZZ,ObjektBrief,Tools") | Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsModel
  | ◢ Type | {[Common.AddressGeoCoded Nullable=True]} | Microsoft.OData.Edm.IEdmTypeReference {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsNamedTypeReference}
  | ▶ Definition | {Common.AddressGeoCoded} | Microsoft.OData.Edm.IEdmType {Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsComplexTypeDefinition}
  | DirectValueAnnotations | null | System.Collections.Generic.IEnumerable<Microsoft.OData.Edm.Vocabularies.IEdmDirectValueAnnotation>
  | ▶ Element | {Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlNamedTypeReference} | Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlElement {Microsoft.OData.Edm.Csdl.Parsing.Ast.CsdlNamedTypeReference}
  | InlineVocabularyAnnotations | {Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation[0]} | System.Collections.Generic.IEnumerable<Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation> {Microsoft.OData.Edm.Vocabularies.IEdmVocabularyAnnotation[]}
  | IsNullable | true | bool

This looks like an error to me. I can not generate a non nullable wrapper (i.e. you always get back the value) in the code generator based on the model telling me it is nullable.

For fast repro - the metadata model is public at http://api.obb.tuev-daily.de/odata/$metadata, navigation is easily as per above information.

**Comment by KanishManuja-MS** [comment]
@NetTecture Have you tried explicitly adding IsNullable = False to your model?

**Comment by NetTecture** [comment]
As you can read in the metadata it is not nullable. Period. It is not defined as nullable.

Adding nullable true would manually in the consumer would totally invalidate the idea of reading the metadata document from the internet address of the odata source.

**Comment by KanishManuja-MS** [comment]
@NetTecture Please refer to the spec, the absence of nullable implies nullability is true. You need to add nullable as false, please let me know if missed something. 

https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/csprd05/odata-csdl-xml-v4.01-csprd05.html#_Toc14190374

**Comment by NetTecture** [comment]
Whow Sorry, see it - you are right. Time to use some helper methods. Damn, my mistake.
