### ISSUE TITLE
.NET Foundation

### ISSUE THREAD

**Issue by weitzhandler** [OData/odata.net#1521]
Hi,

I just opened this issue to request that odata.net should be added to the [.NET Foundation](http://www.dotnetfoundation.org).

Thank you!

**Comment by robertmclaws** [comment]
Hello, and thanks for the suggestion! OData is already a part of the .NET Foundation, you can read more about it here: https://www.dotnetfoundation.org/blog/2019/06/03/welcoming-odata-to-the-net-foundation.

I would imagine that will be played up more in the weeks ahead as more things get shipped, and the teams have more time to work on the branding and documentation.

So such, I'm going to go ahead and close this ticket. Thanks!
