### ISSUE TITLE
Type cast path segments are duplicated when serializing nested resources causing high CPU load.

### ISSUE THREAD

**Issue by dmitrylobkov** [OData/odata.net#1538]
When serializing derived types with nested complex\navigation properties TypeSegment-s are being added to ODataWriterCore.CurrentScope.ODataUri.Path on entering a corresponding scope and are never freed on leaving the scope, i.e. the segments are added for every nested resource of every entity being processed.

When dealing with models similar to msgraph beta 'group' (we actually do:), there might be about 20k-30k duplicated type segments on 1k page response serialization. Since the path is constantly being reallocated, it causes huge load on CPU. 

### Assemblies affected

Microsoft.OData.Core  <= 7.6.0

### Reproduce steps

- Define the following entities:
```
public class Entity 
{
   public string Id { get; set; }
}
public class User : Entity 
{
    public Entity[] MemberOf { get; set; }
} 
public class Group : Entity 
{
    /* 25-30 complex\navigation properties */ 
}
```

- Controller action:
```
[ODataRoute("users/{id}/memberof")]
public IActionResult GetMemberOf(string id)
{
   return Ok(Enumerable
             .Range(1, 1000)
             .Select(item => new Group() { Id = item.ToString() })
             .OfType<Entity>());
}

```
- Invoke the controller action
### Expected result
The response should be serialized in several milliseconds.

### Actual result
The response serialization takes more than 20sec on I7-8700, CPU is overloaded.

### Additional detail
Repro source:
[TestProject.zip](https://github.com/OData/odata.net/files/3587124/TestProject.zip)

We've made a quick fix for the issue, the same response is serialized in 100-200 ms. Here is the patch: 
[typecastfix.zip](https://github.com/OData/odata.net/files/3587141/typecastfix.zip)

**Comment by dmitrylobkov** [comment]
@KanishManuja-MS @madansr7 Hi guys) Any change it will be fixed? I believe the issue might affect msgraph services if they are built on top of odata.net.

**Comment by mikepizzo** [comment]
Sorry that we missed this.  Easy win.  Thanks for tracking down the root cause and creating a patch.

PR #1930.
