### ISSUE TITLE
Full Entity Updates are sent to Patch Verb instead of PUT

### ISSUE THREAD

**Issue by groogiam** [OData/odata.net#1539]
Saving changes when **not** using a DataServiceCollection send the full entity data to Patch verb. I don't believe this is the correct semantic. The data should be sent to a PUT as it is a full entity update.

### Assemblies affected

Microsoft.OData.Client.dll 7.6.0

### Reproduce steps

See this post 

https://stackoverflow.com/questions/21412326/what-is-the-correct-way-to-call-patch-from-an-odata-client-in-web-api-2

### Expected result

A full entity update should be sent to a PUT verb not PATCH

### Actual result

All updates are sent to PATCH.

**Comment by NetTecture** [comment]
I am not sure you are right. Odata specs say to prefer Patch to Put and do NOT name any exception.
