### ISSUE TITLE
Is it possible to filter with json field value in a column?

### ISSUE THREAD

**Issue by Smilefounder** [OData/odata.net#1546]
Because in our system ([Mixcore CMS](https://mixcore.org/)), we also using json inside a db column. Is it possible to filter by json field value in a column?

### Assemblies affected

v7.5.3

**Comment by KanishManuja-MS** [comment]
@Smilefounder If you have the json as a string in your model, you can try using operations such as filter. If you have the json as a complex property in your model, you can use its properties to filter.

**Comment by KenitoInc** [comment]
Closing this @Smilefounder 
Feel free to create a new issue if there are any more issues that you have
