### ISSUE TITLE
Prefix issue with GmlWriter

### ISSUE THREAD

**Issue by LimeyChris** [OData/odata.net#1547]
The GmlFormatter Write method is appending the "gml" prefix to the "srsName" attribute. The "srsName" attribute should not have the "gml" prefix.

See GmlWriter.cs, WriteCoordinateSystem method.

### Assemblies affected

7.6.1-beta

### Reproduce steps

```
CoordinateSystem coordinateSystem = CoordinateSystem.Geography(4326);
GeographyPoint point = GeographyPoint.Create(coordinateSystem, 40.1, -83.1, null, null);
GmlFormatter gmlFormatter = GmlFormatter.Create();
var gml = gmlFormatter.Write(point);
```

### Expected result
```
gml = <gml:Point srsName="http://www.opengis.net/def/crs/EPSG/0/4326" xmlns:gml="http://www.opengis.net/gml"><gml:pos>40.1 -83.1</gml:pos></gml:Point>
```

No "gml" prefix for "srsName" attribute.

### Actual result
```
gml = <gml:Point gml:srsName="http://www.opengis.net/def/crs/EPSG/0/4326" xmlns:gml="http://www.opengis.net/gml"><gml:pos>40.1 -83.1</gml:pos></gml:Point>
```

Has "gml" prefix for "srsName" attribute.

**Comment by xuzhg** [comment]
Fixed and merged. Close it. Thanks.
