### ISSUE TITLE
Unable to get navigation property on netcore if it's a Collection

### ISSUE THREAD

**Issue by ityk** [OData/odata.net#1549]
If we define EntitySet object containing List of complex object, it shows up correctly in metadata as  <NavigationProperty Name="Devices" Type="Collection(Microsoft.Online.IntelligentUpdate.Core.Datamodel.WebApi.Asset.DeviceAsset)"/>
We get proper response in Postman, but odata client is unable to deserialize it.

### Assemblies affected

Microsoft.OData.Client" Version="7.6.0"

### Reproduce steps
We create entitySet as builder.EntitySet<UpdatePolicy>("UpdatePolicies").EntityType;
 And class contains a IList<DeviceAsset>
 public class UpdatePolicy
 {	....
    public IList<DeviceAsset> Devices { get; set; }
 }
 
 This informations shows up in metadata as 
<EntityType Abstract="true" Name="UpdatePolicy">
<Key>
<PropertyRef Name="UpdatePolicyId"/>
</Key>
<Property Name="UpdatePolicyId" Nullable="false" Type="Edm.String"/>
<NavigationProperty Name="Devices" Type="Collection(Microsoft.Online.IntelligentUpdate.Core.Datamodel.WebApi.Asset.DeviceAsset)"/>
</EntityType>
I am able to get the response to updatepolicies(id)/Devices in Postman but it fails in odataclient with message 
When writing a JSON response, a user model must be specified and the entity set and entity type must be passed to the ODataMessageWriter.CreateODataResourceWriter method or the ODataResourceSerializationInfo must be set on the ODataResource or ODataResourceSet that is being written."
"   at Microsoft.OData.ODataResourceTypeContext.ValidateAndReturn[T](T value)\r\n   at Microsoft.OData.ODataResourceTypeContext.get_NavigationSourceName()\r\n   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeId()\r\n   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeAndCacheId()\r\n   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.GetId()\r\n   at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()\r\n   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()\r\n   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)\r\n   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__22.MoveNext()\r\n   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()\r\n   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()\r\n   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()\r\n   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()\r\n   at Microsoft.OData.Client.MaterializeAtom.MoveNext()\r\n   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   
### Expected result
Get back List<DeviceAsset>

### Actual result
Get error

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KenitoInc** [comment]
@mikepizzo 
This issue affects where we don't have NavigationPropertyBinding within an Entity Set
For example the code below will throw an exception
var person = dsc.People.ByKey("russellwhyte").GetValue();
dsc.LoadProperty(person, "Trips");

However the code below won't throw an exception
dsc.LoadProperty(person, "Friends");

**Comment by KenitoInc** [comment]
@ityk 
There a few scenarios that could cause this error. Kindly share your metadata so that I can give you a detailed explanation

**Comment by ityk** [comment]
Hi. 
I was able to get it to work by adding Devices call as a function explicitly in my metadata as
<Function Name="Devices" IsBound="true">
<Parameter Name="bindingParameter" Type="Microsoft.Online.IntelligentUpdate.Core.Datamodel.WebApi.UpdatePolicy"/>
<ReturnType Type="Datamodel.WebApi.DeviceAssets"/>
</Function>
<Function Name="DeviceDetails" IsBound="true">
<Parameter Name="bindingParameter" Type="WebApi.UpdatePolicy"/>
<ReturnType Type="Collection(Datamodel.WebApi.Asset.DeviceAsset)"/>
</Function>
<EntityType Name="UpdatePolicy" Abstract="true">
<Key>
<PropertyRef Name="UpdatePolicyId"/>
</Key>
<Property Name="UpdatePolicyId" Type="Edm.String" Nullable="false"/>
<Property Name="CreatedDateTime" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="LastModifiedDateTime" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="Status" Type="Datamodel.WebApi.PolicyStatus" Nullable="false"/>
<Property Name="ETag" Type="Edm.String"/>
<Property Name="PolicyType" Type="Datamodel.Storage.UpdatePolicyType" Nullable="false"/>
<Property Name="EbrakeThreshold" Type="Edm.Single" Nullable="false"/>
<Property Name="AutoPauseEnabled" Type="Edm.Boolean" Nullable="false"/>
<Property Name="PausedReason" Type="Edm.String"/>
<NavigationProperty Name="Devices" Type="Datamodel.WebApi.DeviceAssets"/>
<NavigationProperty Name="DeviceDetails" Type="Collection(Datamodel.WebApi.Asset.DeviceAsset)"/>
</EntityType>
<EntityType Name="DeviceAssets">
<Key>
<PropertyRef Name="AssetId"/>
</Key>
<Property Name="AssetId" Type="Edm.String" Nullable="false"/>
<Property Name="AssetType" Type="Datamodel.WebApi.AssetIdType" Nullable="false"/>
<Property Name="Ids" Type="Collection(Edm.String)"/>
</EntityType>

**Comment by ityk** [comment]
`<EntityType Name="UpdatePolicy" Abstract="true">
<Key>
<PropertyRef Name="UpdatePolicyId"/>
</Key>
<Property Name="UpdatePolicyId" Type="Edm.String" Nullable="false"/>
<Property Name="CreatedDateTime" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="LastModifiedDateTime" Type="Edm.DateTimeOffset" Nullable="false"/>
<Property Name="Status" Type="Datamodel.WebApi.PolicyStatus" Nullable="false"/>
<Property Name="ETag" Type="Edm.String"/>
<Property Name="PolicyType" Type="Datamodel.Storage.UpdatePolicyType" Nullable="false"/>
<Property Name="EbrakeThreshold" Type="Edm.Single" Nullable="false"/>
<Property Name="AutoPauseEnabled" Type="Edm.Boolean" Nullable="false"/>
<Property Name="PausedReason" Type="Edm.String"/>
<NavigationProperty Name="Devices" Type="Datamodel.WebApi.DeviceAssets"/>
<NavigationProperty Name="DeviceDetails" Type="Collection(Datamodel.WebApi.Asset.DeviceAsset)"/>
</EntityType>
<EntityType Name="DeviceAssets">
<Key>
<PropertyRef Name="AssetId"/>
</Key>
<Property Name="AssetId" Type="Edm.String" Nullable="false"/>
<Property Name="AssetType" Type="Datamodel.WebApi.AssetIdType" Nullable="false"/>
<Property Name="Ids" Type="Collection(Edm.String)"/>
</EntityType>
<Function Name="Devices" IsBound="true">
<Parameter Name="bindingParameter" Type="Datamodel.WebApi.UpdatePolicy"/>
<ReturnType Type="Datamodel.WebApi.DeviceAssets"/>
</Function>
<Function Name="DeviceDetails" IsBound="true">
<Parameter Name="bindingParameter" Type="Datamodel.WebApi.UpdatePolicy"/>
<ReturnType Type="Collection(Datamodel.WebApi.Asset.DeviceAsset)"/>`

**Comment by KenitoInc** [comment]
@ityk 
Kindly share the full metadata, the one shared above is incomplete

**Comment by KenitoInc** [comment]
@ityk Closing this issue for now. You can reopen incase there are still pending issues

**Comment by fusyd** [comment]
> @mikepizzo
> This issue affects where we don't have NavigationPropertyBinding within an Entity Set
> For example the code below will throw an exception
> var person = dsc.People.ByKey("russellwhyte").GetValue();
> dsc.LoadProperty(person, "Trips");
> 
> However the code below won't throw an exception
> dsc.LoadProperty(person, "Friends");

Is it a bug or by-design? I played with the client code generated by OData Connected Service (0.11.1), and encountered the same exception. 

```
var context = new Container(new Uri("https://services.odata.org/TripPinRESTierService/"));

// GET https://services.odata.org/TripPinRESTierService/People('scottketchum')/Trips
var trips = await context.People.ByKey("russellwhyte").Trips.ExecuteAsync();

// Microsoft.OData.ODataException: 'When writing a JSON response, a user model must be specified...'
foreach (var trip in trips)
{
    Console.WriteLine(trip.Name);
}
```

**Comment by fusyd** [comment]
@KenitoInc do you have any workaround?
