### ISSUE TITLE
Make library debuggable w/ SourceLink

### ISSUE THREAD

**Issue by robertmclaws** [OData/odata.net#1563]
Need to add [SourceLink](https://github.com/dotnet/sourcelink) to the project and configure .snupkg compliation so that packages deployed to NuGet contain the information necessary to step into the source code during debugging.

Related issue: 
OData.net: #743

**Comment by xuzhg** [comment]
So far, the "https://nuget.smbsrc.net" is not stable, and we can't upload the symbols to this server.

![image](https://user-images.githubusercontent.com/9426627/85827721-afe20480-b73b-11ea-897f-0e303ccd4a87.png)

So, we should take time to upgrade our symbol strategy.
SourceLink is the latest solution and don't rely any symbol server.
Let's move to SourceLink.

**Comment by xuzhg** [comment]
We already enabled source-link and upload the symbols to nuget.org. So, close it.
