### ISSUE TITLE
TryGetAnnotation on OData client fails to retrieve feed metadata annotation

### ISSUE THREAD

**Issue by rschiefer** [OData/odata.net#1572]
TryGetAnnotation on OData client fails to retrieve feed metadata annotation.

### Assemblies affected

Microsoft.OData.Client 7.6.0

### Reproduce steps

Using this tutorial - https://docs.microsoft.com/en-us/odata/client/annotation-support

Add a custom feed metadata annotation using a custom serializer. Validate the the custom annotation is provided with raw OData call in browser. Call TryGetAnnotation with annotation name.

Example of custom serializer - https://gist.github.com/rschiefer/b3abdd3bc4d9eb3fb667e18a5b423bd5

### Expected result

TryGetAnnotation would provide the custom feed metadata annotation value.

### Actual result

It's always empty/blank.

**Comment by marabooy** [comment]
Hi @rschiefer Could you kindly provide me with the CSDL that is being generated from the service and the sample code that you are using to try and read the Annotation. 

I tried to reproduce the issue but I can't seem to reproduce it with the latest version. 

My approach was 
1. Create an asp.net core 3.1 application using the products [tutorial](https://docs.microsoft.com/en-us/odata/webapi/netcore). I made some necessary changes to make it work on 3.1 as listed [here](https://devblogs.microsoft.com/odata/experimenting-with-odata-in-asp-net-core-3-1/)
2. Add my custom annotation to the Client model by modifying the conventional model using [this guide](https://docs.microsoft.com/en-us/odata/odatalib/define-annotations)
```
...
var convModel = builder.GetEdmModel();

            var edmModel = new EdmModel();
            edmModel.AddElements(convModel.SchemaElements);

            // customize model
            var templateType = (EdmEntityType)convModel.SchemaElements.First(schemaElement => schemaElement.Name == "Product");
            var maxCountTerm = new EdmTerm("CoreApi1", "MaxCount", EdmCoreModel.Instance.GetInt32(true));
            var annotation = new EdmVocabularyAnnotation(templateType.FindProperty("Name"), maxCountTerm, new EdmIntegerConstant(10000000L));
            annotation.SetSerializationLocation(edmModel, EdmVocabularyAnnotationSerializationLocation.Inline);
            edmModel.AddVocabularyAnnotation(annotation);
            return edmModel;
...
```
3. Add your custom provider as mentioned in the included gist.
3. Generate code Using codegen as described in the tutorial above
4. Try to read the annotation using the following sample
```
var product= container.Products.ByKey(1).GetValue();
            int annotationValue;
            container.TryGetAnnotation<Func<string>,int>(()=>product.Name, "CoreApi1.MaxCount", out annotationValue);
            Console.WriteLine("Value is {0} ",annotationValue);
```

**Comment by rschiefer** [comment]
I was using 2.1. Can you reproduce it there?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marabooy** [comment]
Will do thanks, are the steps similar to what you did? or is there something else that I should change?

**Comment by rschiefer** [comment]
Yes, I followed the tutorial.

**Comment by marabooy** [comment]
Hi @rschiefer  Could you kindly share your CSDL so i can try to reproduce the Issue.  My current CSDL is shown below and the library is able to read the Annotation and get the value successfully. 

```
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Annotation2_1">
<EntityType Name="Product">
<Key>
<PropertyRef Name="ID"/>
</Key>
<Property Name="ID" Type="Edm.Int32" Nullable="false"/>
<Property Name="Name" Type="Edm.String">
<Annotation Term="CoreApi1.MaxCount" Int="10000000"/>
</Property>
</EntityType>
</Schema>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
<EntityContainer Name="Container">
<EntitySet Name="Products" EntityType="Annotation2_1.Product"/>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>
```

This is the code that I am using to read the annotation. 
```
 var product = container.Products.ByKey(1).GetValue();
            int annotationValue;
            container.TryGetAnnotation<Func<string>,int>(()=>product.Name, "CoreApi1.MaxCount", out annotationValue);
            Console.WriteLine("Value is {0} ",annotationValue);
```

Could you try this sample and let me know if it works for you. To add the annotation to the csdl I use the sample in my earlier response.

**Comment by marabooy** [comment]
@rschiefer Closing this Issue. Feel free to reopen it if the above sample doesn't work for you.
