### ISSUE TITLE
count distinct possible with compound key?

### ISSUE THREAD

**Issue by MolallaComm** [OData/odata.net#1575]
On entity sets with a single key column, i can do something like:

$apply=groupby((Model),aggregate(OntID with countdistinct as GroupCount))

which tells me how many of a specific model I have

My problem comes, how do you do the same thing on an entity set that has a compound key:

$apply=groupby((Type),aggregate(ShelfName,Slot with countdistinct as GroupCount))

I want to group by card type, but count distinct by ShelfName and Slot which are the entity sets "compound" primary key. The above gives are error:

"The query specified in the URI is not valid. 'with' expected at position 34 in 'groupby((Type),aggregate(ShelfName,Slot with countdistinct as GroupCount))'."

Is there a way to do this?

**Comment by xuzhg** [comment]
@kosinsky Can you provide any direction?

**Comment by kosinsky** [comment]
Spec doesn't allow that (SQL doesn't allow COUNT(DISTINCT A,B)). 
`groupby((Type),aggregate(concat(ShelfName, Slot) with countdistinct as GroupCount))`

Another option is `compute()`:
`$apply=compute(concat(ShelfName, Slot) as NewKey)/groupby((Type),aggregate(NewKey with countdistinct as GroupCount))` 

Odata.net supports `compute()` in parsing
PR WebAPI https://github.com/OData/WebApi/pull/1877 (should add support for functions inside aggregate too, if they aren't supported yet)

**Comment by MolallaComm** [comment]
SQL does support it – that is what COUNT(*) is for – it will always give you the count of the items in each group whether it is grouped by one column or several.  I think the proper behavior would be to support multiple columns and always use COUNT(*) instead of COUNT(distinct A) – it is a SQL standard, works in MSSQL, MYSQL, and PGSQL, etc.

I’m not sure exactly how other people are using countdistinct – if you can only use it inside aggregate then I think just changing it to allow multiple properties and using COUNT(*) on the SQL side shouldn’t break anything.  If that isn’t possible, I can see how your proposed compute option might work with the downside of being slightly more complex to generate and not available in nuget yet.

Thanks for your consideration!

**Comment by kosinsky** [comment]
If you need just COUNT(*) you could use $count. For example 
`groupby((Type),aggregate($count as GroupCount))`

You right, In SQL you could simulate count distinct with COUNT(*) and nested queries. The same for OData (to get number of distinct combinations of ShelfName, Slot for each Type)
```
$apply=groupby((Type, ShelfName, Slot))/groupby((Type), aggregate($count as GroupCount))
```

**Comment by KenitoInc** [comment]
Seems the issue was resolved. Closing this issue
