### ISSUE TITLE
OData.net Client throws InvalidOperationException when calling 'Move' on a DataServiceCollection

### ISSUE THREAD

**Issue by davidmilligan** [OData/odata.net#1576]
```
System.InvalidOperationException: Unexpected action 'Move' on the OnCollectionChanged event raised by DataServiceCollection.​
   at Microsoft.OData.Client.BindingObserver.OnDataServiceCollectionChanged(Object collection, NotifyCollectionChangedEventArgs eventArgs)​
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)​
   at System.Collections.ObjectModel.ObservableCollection`1.MoveItem(Int32 oldIndex, Int32 newIndex)​
   at System.Collections.ObjectModel.ObservableCollection`1.Move(Int32 oldIndex, Int32 newIndex)​
```

### Assemblies affected

Microsoft.OData.Client 7.6.1

### Reproduce steps

This issue appears to only be occurring on .net core 3 (we recently migrated from .net 4.7 to .net core 3 and this appears as a regression)

Call the `Move()` method on the DataServiceCollection that is tracking changes (e.g. when attempting to sort the collection for display purposes).

### Expected result

The 'Move' action should just be ignored by the change tracker.

### Actual result

An exception is thrown

### Additional detail

The issue appears to be this swtich statement in https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/Binding/BindingObserver.cs line 378:

```
#if !PORTABLELIB
                case NotifyCollectionChangedAction.Move:
                    // Do Nothing. Added for completeness.
                    break;
#endif

                default:
                    throw new InvalidOperationException(Strings.DataBinding_DataServiceCollectionChangedUnknownActionCollection(eventArgs.Action));
```
The conditional compilation appears to be wrong, because there are platforms besides `!PORTABLELIB` (e.g. .net core) that also have the Move operation, but it would be better to simply get rid of all this code. Why would you throw an exception if the action is unknown? This makes this code incredibly brittle to any future changes or differences between platforms for no good reason or real benefit.

**Comment by xuzhg** [comment]
Merged at c3b63c0b81f94aa4bb15d6603fac95e6c2c33474
