### ISSUE TITLE
Unable to create a new entity with a nested complex type collection

### ISSUE THREAD

**Issue by Sayan751** [OData/odata.net#1581]
I am unable to POST a request for a new entity object creation with a collection of derived complex types, nested in a navigational property, from the generated C# OData client. 

### Assemblies affected

7.6.0

### Reproduce steps

```csharp
/**approx EDM**/
abstract class BaseThing { }

class DerivedThing1 : BaseThing { }

class DerivedThing2 : BaseThing { }

class Configuration {
  public IEnumerable<BaseThing> Things {get; set;}
}
class Entity {
  public Configuration Configuration {get; set;}
}

/**OData Client**/
var entity = new Entity {
  Configuration = new Configuration {
    Things =  new ObservableCollection<BaseThing>(new List<BaseThing>{ new DerivedThing1()}))
  }
};

context.AddToEntities(entity);
context.SaveChanges();
```

### Expected result

Expected the entity to be saved.

### Actual result

> Unexpected error 500 - The type 'Odata.DerivedThing1' of a resource in an expanded link is not compatible with the element type 'Odata.BaseThing' of the expanded link. Entries in an expanded link must have entity
types that are assignable to the element type of the expanded link..

### Additional detail

- The service is working perfectly when POSTed from a REST client, such as Insomnia, or a JS Client. This is happening only with the generated C# client.
- The error is thrown from here: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/WriterValidationUtils.cs#L159-L173

**Comment by Sayan751** [comment]
This works when I do following.

```csharp
var configuration = new Configuration();
configuration.Things.AddRange(new List<BaseThing>{ new DerivedThing1() });
var entity = new Entity {  Configuration = configuration };

context.AddToEntities(entity);
context.SaveChanges();
```

**Comment by ElizabethOkerio** [comment]
Hey @Sayan751, can you please share a link to a repo of your implementation that we can look at and advise accordingly because we have been able to create a new entity with a nested complex type collection.

**Comment by Sayan751** [comment]
@ElizabethOkerio It is bit difficult to provide a reproduction repo. However, I will try to create one, and will get back to you. Sorry for the late reply.

**Comment by ElizabethOkerio** [comment]
Hey @Sayan751, Thanks for getting back. Will really appreciate it if you create one.

**Comment by Sayan751** [comment]
@ElizabethOkerio I will try to create one. Meantime, may I ask you to share your working repo? It is certainly possible that I did it wrong. So, having a correct example would be very helpful.

**Comment by ElizabethOkerio** [comment]
@Sayan751 please check the simplest reproduction of the issue. Let me know if that is what you were trying. (https://github.com/ElizabethOkerio/Issue1581Repro)

**Comment by Sayan751** [comment]
@ElizabethOkerio Thanks you :) Will do

**Comment by ElizabethOkerio** [comment]
@Sayan751, was the link I sent you useful or you are still experiencing the same issue? Please let me know.

**Comment by henning-krause** [comment]
@ElizabethOkerio This issue occurs when you have a complex type without any properties in the hierarchy. The culprit is this line:

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/ClientEdmModel.cs#L331

```cs
 while ((type = c.PlatformHelper.GetBaseType(type)) != null && ClientTypeUtil.GetPropertiesOnType(type, false /*declaredOnly*/).Any());
```
It basically stops the hierarchy walk whenever a complex type without any property is encountered.

I really don't see why that code is there. Can we simply remove the second condition?

**Comment by ElizabethOkerio** [comment]
@henning-krause can you share a sample of the code you are using that throws the exception. Have not been able to reproduce the issue. Have used a complex type with no properties. Thanks.

**Comment by henning-krause** [comment]
@ElizabethOkerio Sure, here you go.
[odata-test.zip](https://github.com/OData/odata.net/files/4407099/odata-test.zip)

The problem arises when a base class has no properties.
