### ISSUE TITLE
Edm.Csdl.GetNamespaceAlias bugs

### ISSUE THREAD

**Issue by syprieur** [OData/odata.net#1587]
Edm.Csdl.GetNamespaceAlias has 2 bugs which severely hinders its usage:
 - the documentation advertises that it returns null if the namespace doesn't have an alias.
However, it throws KeyNotFoundException instead.
 - it crashes with NullReferenceException if the CSDL doesn't define any namespace alias.

### Assemblies affected

All EdmLib.

### Reproduce steps

To reproduce:
 - KeyNotFoundException: call GetNamespaceAlias on an EdmModel which contains at least one namespace with alias, with for argument a namespace without alias or which doesn't exist in the model.
 - NullReferenceException: call GetNamespaceAlias on an EdmModel which doesn't contain any namespace alias definition.

### Expected result

GetNamespaceAlias would return null if there is no alias for the given namespace, as advertised by its documentation.

### Actual result

NullReferenceException or KeyNotFoundException, depending on the scenario described above.

### Additional detail

NullReferenceException is due to the lack of null check after calling GetAnnotationValue's.
KeyNotFoundException is due to the use of VersioningDictionary.Get which throws this exception by design, instead of calling TryGetValue and returning null when applicable.

**Comment by xuzhg** [comment]
Close it
