### ISSUE TITLE
Namespace aliases support in the ODataUriParser

### ISSUE THREAD

**Issue by syprieur** [OData/odata.net#1594]
*Ability to use namespace aliases in URIs given to the ODataUriParser.*

### Assemblies affected

*All.*

### Reproduce steps

*Try to give the OData parser an URI:* 
   https://service.com/entitySet('id')/namespaceAlias.functionName
*Instead of:*
   https://service.com/entitySet('id')/fullNamespace.functionName

### Expected result

*The call would work with namespace aliases, as if the full namespace had been given.*

### Actual result

*The ODataUriParser fails to parse the path, as it doesn't recognize the type/segment.*

**Comment by xuzhg** [comment]
Merged, thanks.
