### ISSUE TITLE
OData Error in AzureAD Graph API

### ISSUE THREAD

**Issue by AviKumarRaj** [OData/odata.net#1600]
*Short summary (3-5 sentences) describing the issue.*

Azure AD Graph Api is not related to odata.net project - but still trying to gather information about this error- when Azure AD AssignLicense Api is called. 

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
Call Azure AD AssignLicenseAPI with valid user.

### Expected result

*What would happen if there wasn't a bug.*
No error.

### Actual result

*What is actually happening.*
Error Msg: 
ODataParameterReader.ReadAsync or ODataParameterReader.Read was called in the 'ResourceSet' state. 'CreateResourceSetReader' must be called in this state, and the created reader must be in the 'Completed' state before the next ODataParameterReader.ReadAsync or ODataParameterReader.Read can be called.

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*
This started failing yesterday.

**Comment by KanishManuja-MS** [comment]
@AviKumarRaj Can you please provide us with more details about the request? 
Interesting thing that you mention is that this started failing yesterday. Did anything change on your end?
AD Graph uses OData and thus the OData Error. You should reach out to the AD Graph team and if you are unable to, we would be happy to help.

**Comment by mikepizzo** [comment]
We've reported this to the AD Graph team and they are investigating.  They did deploy some changes recently, which may have caused this behavior.

**Comment by AviKumarRaj** [comment]
@mikepizzo and @KanishManuja-MS for the response and reaching out to AD team. 
There are no changes done in my end. Please let me know if I can contact ADGraph Api team ? This GitHub project is for "MS Graph API" - not sure if they support "Azure AD Graph API". 
https://github.com/microsoftgraph/microsoft-graph-explorer-api

API used: Azure AD Graph. https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/functions-and-actions#assignLicense

Sample: POST https://graph.windows.net/myorganization/users/{user_id}/assignLicense?api-version=1.6

I am able to manually add license using MS 365 Admin Portal - https://docs.microsoft.com/en-us/office365/admin/manage/assign-licenses-to-users?view=o365-worldwide

**Comment by mikepizzo** [comment]
A fix for this issue on the Azure AD Graph side was identified and merged.  There was a freeze on deployments over the holiday week-end, but it should start to be rolled out soon.

**Comment by AviKumarRaj** [comment]
Thank you @mikepizzo .

**Comment by KenitoInc** [comment]
@AviKumarRaj Was this issue resolved?
If yes, kindly close the issue
