### ISSUE TITLE
Unable to set metadata Xml output indent

### ISSUE THREAD

**Issue by GoneWithWind** [OData/odata.net#1606]
In Microsoft.OData.Core.6.15.0 we are able to control the indent behavior of the metadata Xml output through the ODataMessageWriterSettings.
![image](https://user-images.githubusercontent.com/5491882/70302751-c294fa80-1838-11ea-9b67-1c4b1f740008.png)
But there are no options exposed in Microsoft.OData.Core.7.6.1.0:
https://github.com/OData/odata.net/blob/f7041173b1fa5c4d0b73307f12cabbdc64125b7f/src/Microsoft.OData.Core/Metadata/ODataMetadataWriterUtils.cs#L33

https://github.com/OData/odata.net/blob/f7041173b1fa5c4d0b73307f12cabbdc64125b7f/src/Microsoft.OData.Core/Metadata/ODataMetadataWriterUtils.cs#L58-L71

Is this by design or regression?
### Assemblies affected

OData .Net lib 7.x*

**Comment by odero** [comment]
@GoneWithWind It is by design - because of data size performance, non-indent was found to be better - that's why it was dropped.
