### ISSUE TITLE
AddLink (CreateRef) for new entities does not work with batch operations

### ISSUE THREAD

**Issue by tfabian** [OData/odata.net#1610]
I migrated an OData web service from .Net framework 4.72 (Katana) to Kestrel net core 3.x. The same code works with Microsoft.AspNet.OData (net framework 4.72). It's not possible to add link to a newly created entity in a batch.

Client side code:

```
      container.AddToUsers(user);
      container.AddLink(role, "Users", user);

      container.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset);
```
Startup:

```
      app.UseODataBatching();

      app.UseMvc(routeBuilder =>
      {
        routeBuilder.MapODataServiceRoute("odata", null, edmModel, new DefaultODataBatchHandler());
      });
```
Controller:

```
    [AcceptVerbs("POST", "PUT")]
    public IActionResult CreateRef(string navigationProperty, [FromBody] Uri link)
```
In case of batch operation the uri is "$44". How is it possible to get the ID of the newly created entity? In case of SaveChangesOptions.None it can be extracted from uri, in that case it looks like this:
"https://localhost:44311/Users(158)"

Thx

**Comment by gathogojr** [comment]
Hi @tfabian. I'm currently investigating this issue and I'm hoping you can provide me with more details:

- Which version of Visual Studio are you using?
- Which particular version of .NET Core are you using - 3.0 or 3.1?
- Are you using Entity Framework 6 or Entity Framework Core, and which version in particular?
- How are User and Role classes related - One-to-Many, Many-to-Many, etc? This is relevant for purposes of reproducing the issue. Can you provide a simplified (or redacted) snippet of the two classes?
- The definition for `CreateRef` method you provided above doesn't look syntactically correct - missing the key parameter... Can you ensure the code snippets you provide at least mirror the actual scenario? 
- How did you generate the client proxy file for your OData Service - OData Client Code Generator, OData Connected Service, etc?
- Microsoft.AspNetCore.OData 7.3.0 was released in late December 2019 - can you confirm if the error is observed when using that release?

Thanks

**Comment by tfabian** [comment]
Hi **@gathogojr**,
- Visual Studio 2019 Enterprise version is 16.4.2 
- .NetCore version is 3.1
- EF 6.4
- relationship is many to many

```
  public class User : DomainObject
  {
    public User()
    {
      Roles = new List<Role>();
    }

    public string UserName { get; set; }
    public string Password { get; set; }

    public ICollection<Role> Roles { get; set; }
  }

  public class Role : DomainEntity
  {
    public Role()
    {
      Users = new List<User>();
    }

    public string RoleName { get; set; }

    public ICollection<User> Users { get; set; }
  }

  [Microsoft.OData.Client.Key("Id")]
  public class DomainEntity : IEntity
  {
    [Key]
    public virtual int Id { get; set; }
  }
```
-The definition for CreateRef does not contain key, because I'm extracting it dynamically from [FromBody] Uri link, so it can be int, string or a composite key. The same signature works in .Net Framework 4.72 Microsoft.AspNet.OData 7.1.0. Method argument link should contain url with key, see original comment. You can try it with SaveChangesOptions.None, in that case it is filled correctly.   

- I didn't generate the client proxy. My context class inherits from ODataServiceContext : DataServiceContext.

- I confirm that the error is still in Microsoft.AspNetCore.OData 7.3.0

Note: I don't think that the problem is related to my development environment. The error probably appeared during conversion from net472 to netcoreapp 1/2.x (Microsoft.AspNet.OData => Microsoft.AspNet**Core**.OData). 

Thx

**Comment by gathogojr** [comment]
@tfabian Thank you for the detailed response. I was actually able to reproduce the issue - against 2 different combination of packages: 

- .NET Core 3.1 + Microsoft.AspNetCore.OData 7.3.0
- .NET Framework 4.7.2 + ASP.NET Core 2.1 +Microsoft.AspNetCore.OData 7.3.0

I was also able to confirm it works perfectly against .NET Framework 4.7.2 + Microsoft.AspNet.OData 7.x

Its still early in my investigation but what I have observed so far is that `[FromBody] Uri link` parameter doesn't get populated with a valid Uri when the target is also being added/inserted in the same batch - like in your example above.
Allow me to do some more digging and then get back to you

**Comment by gathogojr** [comment]
@tfabian I have a draft [PR](https://github.com/OData/WebApi/pull/2012) out. You can take an early peek. In the process of adding a couple of tests to verify the described scenario

**Comment by tfabian** [comment]
great thx

**Comment by xuzhg** [comment]
Merged at 82c54cb

**Comment by tfabian** [comment]
Hi, could you write me please the version and name of the nuget package with the relevant fix?

Thx

**Comment by gathogojr** [comment]
Hi @tfabian The nightly below has the changes that fixed the issue. Be on the lookout for a release in the next couple of days.
https://www.myget.org/feed/webapinetcore/package/nuget/Microsoft.AspNetCore.OData/7.3.0-Nightly202002171520#

**Comment by marabooy** [comment]
@tfabian Do close https://github.com/OData/odata.net/issues/1518 if this works for you :)
