### ISSUE TITLE
Error messages returned from an OData V4 service throw an exception and no data is returned

### ISSUE THREAD

**Issue by ihtfp69** [OData/odata.net#1611]
If the odata service returns an error object like below, the library throws a DataServiceRequestException and no data is returned as a result. If the service returns a status code 404, it does not even attempt to parse the error. If I force the status code to 200, it parses the error, sets the Error property of the ChangeOperationResponse, but then changes the status code to 500 and throws the same error as before. In both cases, nothing gets returned.

`{
  "error": {
    "code": "",
    "message": "Unsupported functionality"
}`

### Assemblies affected

Microsoft.OData.Client 7.6.2
SaveResult.cs

Line 349:
	`throw new DataServiceRequestException(Strings.DataServiceException_GeneralError, ex, service);`

### Reproduce steps

Create a query that returns several entities. Make changes to some of them, mark them as updated and call SaveChangesAsync.

### Expected result

It should return a DataServiceResponse with a list of ChangeOperationResponse and it should include those that have their Error property set.

### Actual result

An exception is thrown and nothing at all gets returned except the JSON error message from the first PATCH result that returned an error. The responses from entities that were successfully updated or additional ones that produced errors are lost.

**Comment by KenitoInc** [comment]
@ihtfp69 Have you tried this `SaveChangesAsync(SaveChangesOptions.BatchWithIndependentOperations)`
The `BatchWithIndependentOperations` flag saves each change independently in a batch request and returns a ChangeOperationResponse for all succesful and failed requests

**Comment by KenitoInc** [comment]
@ihtfp69 Did you manage to try out the code above? We would like to close this issue

**Comment by KenitoInc** [comment]
@ihtfp69 Closing this issue for now. You can reopen it if the above code doesn't work for you.

**Comment by ihtfp69** [comment]
@KenitoInc sorry, I never got an email about your comment. I did try every SaveChangesOption and none of them worked. It always throws an exception on the thread instead of returning data.

**Comment by KenitoInc** [comment]
@ihtfp69 Kindly share the sample code you are trying to run
