### ISSUE TITLE
Timeout when using with Dynamics365

### ISSUE THREAD

**Issue by demogog** [OData/odata.net#1612]
When retrieving a small amount of data (e.g. `var cust = context.Customers.FirstOrDefault();`) the operation times out. 

### Assemblies affected

Microsoft.OData.Client version 7.6.2

### Reproduce steps

A task, that retrieves a first customer each 5th second can run for a couple of days or it can fail after 5 minutes. Once it failed with TimeOutException, windows application running the task has to be restarted in order to work again. Accessing OData view Web works just fine. 

### Expected result

Should not time out. 

### Actual result

Normally times out within first couple of hours. 

### Additional detail

Seems to happen on regular basis, but with irregular pattern.

**Comment by ElizabethOkerio** [comment]
@demogog. The <code>DataServiceContext </code> class in <code>Microsoft.OData.Client </code> library has a Timeout property that you can set before you make any request with <code>Microsoft.OData.Client </code>. You can set the timeout value to whichever value you want to ensure that the request does not time out before a response is returned. Normally, if you do not set this value before making a request, the request uses the default timeout value which is 100 seconds. So if you are making a request that will take more than a 100 seconds to return a value then it is important that you set the timeout value like below: 
<pre>
DefaultContainer context = new DefaultContainer(new Uri("https://services.odata.org/v4/TripPinServiceRW/"));
            context.Timeout = 1200000;
var cust = context.Customers.FirstOrDefault();

</pre>

**Comment by ElizabethOkerio** [comment]
Am closing this issue. You can reopen it if this does not solve your issue.

**Comment by demogog** [comment]
@ElizabethOkerio 
Normally a request like this finishes within a couple of milliseconds. Changing the timeout property does not resolve the issue.
