### ISSUE TITLE
Backslashes in string literals in IN expressions need to be escaped but not in other expressions like EQ

### ISSUE THREAD

**Issue by kenneth-hansen** [OData/odata.net#1636]
Backslashes in string literals in IN expressions need to be escaped but not in other expressions like EQ.  So the string in "x eq '\k'" will become "\k" but "x in ('\k')" will throw because \k is not a valid escape sequence.  Conversely the string in "x eq '\\\\'" will become "\\\\" whereas "x in ('\\\\')" becomes "\\".

### Assemblies affected

7.6.2 (but probably all versions).

### Reproduce steps

Use inputs similar to the description above and observe resulting ConstantNodes or exceptions.

### Expected result

Parsing behavior should be consistent for strings.

### Actual result

Strings in IN expressions needs escaping where other places does not.

**Comment by xuzhg** [comment]
Fixed and merged. Thanks.
