### ISSUE TITLE
Support aspnetcore/netfxcore in OData Client

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#164]
For now, OData Client throws an exception if run with aspnetcore/netfxcore:

An exception of type 'System.TypeLoadException' occurred in mscorlib.ni.dll but was not handled in user code
Additional information: Method 'get_Url' in type 'Microsoft.OData.Client.HttpWebRequestMessage' from assembly 'Microsoft.OData.Client, Version=6.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

Related issue: #97.

**Comment by lewischeng-ms** [comment]
As @congysu suggested, consider using [Microsoft.Net.Http.Client](https://github.com/aspnet/httpclient) to replace `HttpWebRequest` and `HttpWebResponse` as it fully supports .NET Core 5.

**Comment by lewischeng-ms** [comment]
For netfxcore, we will track the workitem in #215.

**Comment by congysu** [comment]
VS 2015 RC resolved the issue.
