### ISSUE TITLE
ODataJsonLightBatchBodyContentReaderStream assumes that batch part body is IEEE754Compatible

### ISSUE THREAD

**Issue by xsmerek** [OData/odata.net#1640]
When sending a batch request that includes PATCH on entity with decimal property, the oData .Net lib automatically assumes that body of request item in in IEEE 754 compatible format with regards to actual item `Content-Type` header.

### Assemblies affected

OData .Net lib 7.6.1

### Reproduce steps

https://github.com/xsmerek/BatchDecimalRepro

Steps:

1. Run IIS Express.
2. Send POST request to `http://localhost:52169/odata/$batch`
with header `Content-Type = application/json`
and body 
```
{
    "requests": [
        {
            "url":"/odata/Examples(1)",
            "method":"PATCH",
            "headers":{"Content-Type":"application/json"},
            "body":{
                "Price": 1.3
            },
            "id":"1",
            "atomicityGroup": "g1"
        }
    ]
}
```

Please note that the app uses Microsoft.OData.Core indirectly via Microsoft.AspNetCore.OData but the issue is caused by this library (please see Additional detail for explanation).

### Expected result

Controller should return success HTTP code.

### Actual result

`Microsoft.OData.ODataException: 'Cannot convert a value to target type 'Edm.Decimal' because of conflict between input format string/number and parameter 'IEEE754Compatible' false/true.'`

is thrown in `ODataJsonLightPropertyAndValueDeserializer`, method `ReadPrimitiveValue`.

### Additional detail

The root cause is most likely in [ODataJsonLightBatchBodyContentReaderStream.cs, line 254](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightBatchBodyContentReaderStream.cs#L254) where `jsonWriter` is created with `isIeee754Compatible=true` without regards for actual `Content-Type` header of batch item, hence, item header and body are incompatible.

Please note that if we set `Content-Type` header to `application/json;IEEE754Compatible=true`, the request is successful (even if the item body is not compatible with IEEE 754).

Also, if I send PATCH request with the given body, the request is successful.

**Comment by Sreejithpin** [comment]
@xsmerek , Thanks for reporting this issue. This does look like an issue, will investigate.
