### ISSUE TITLE
Allow Microsoft.OData.Client.Serializer.GetKeyString to receive an IDictionary Object

### ISSUE THREAD

**Issue by KenitoInc** [OData/odata.net#1643]
When working on a fix on issue https://github.com/OData/lab/issues/96 I realized that OData Client's Serializer.GetKeyString receives a DataServiceContext Object and a Concrete Dictionary instead of an IDictionary. Since Dictionary implements IDictionary, we can update the method as follows
public static string GetKeyString(DataServiceContext context, IDictionary<string, object> keys)
{
       // Implementation
}

### Assemblies affected

*Microsoft.OData.Client v7.6.2*

### Reproduce steps

Pass an IDictionary in the ByKey methods of OData Connected Service.

### Expected result

No error is thrown

### Actual result

This error is thrown: cannot convert from 'System.Collections.Generic.IDictionary<string, object>' to 'System.Collections.Generic.Dictionary<string, object>'

**Comment by xuzhg** [comment]
Merged and close it.
