### ISSUE TITLE
$filter in (null) not working

### ISSUE THREAD

**Issue by keatkeat87** [OData/odata.net#1651]
we can do like this $filter=name in ('test1', 'test2') 
but can't put "null" inside the list $filter=name in ('test1', 'test2', null)

error message : 
The query specified in the URI is not valid. String item should be single/double quoted: 'null'."
![image](https://user-images.githubusercontent.com/8691013/73250467-e7cb3700-41f1-11ea-8ab0-b1f28f41890c.png)

### Assemblies affected
*Which assemblies and versions are known to be affected
asp.net core 3.1, odata 7.3 beta

### Reproduce steps
1.git clone https://github.com/keatkeat87/odata-filter-in-null-issue
2.dotnet ef migrations add init
3.dotnet ef database update
4.F5
5.visit /odata/Products?$filter=name in (null)

### Expected result
$filter=name in ('test1', 'test2', null) should work as $filter=name eq 'test1' or name eq 'test2' or name eq null

### Actual result
error

**Comment by xuzhg** [comment]
Merged and close it.
