### ISSUE TITLE
How to create a nested complex property

### ISSUE THREAD

**Issue by ziacik** [OData/odata.net#1668]
Trying to create a nested complex property using `ODataResourceValue` throws an exception.

### Assemblies affected

OData .Net lib 7.5.3, 7.6.3

### Reproduce steps

Trying to create an entity like this (or should I use some other way?)

```c#
var entity = new ODataResource
{
	Properties = new[]
	{
		new ODataProperty
		{
			Name = "complex",
			Value = new ODataResourceValue
			{
				Properties = new []
				{
					new ODataProperty
					{
						Name = "inner",
						Value = "value"
					}
				}
			}
		}
	}
};
```

### Expected result

An entity, something like this: `{ complex: { inner: 'value' } }`.

### Actual result

Throws an `ODataException`: `The value of a property in ODataResource cannot be of type ODataResourceValue or collection of ODataResourceValue.`

### Additional detail

Not sure if I'm creating the entity right, since this seems to be a pretty basic scenario. Could you point me to the right direction?

**Comment by habbes** [comment]
@ziacik thank you for the question.

I think you can only directly set the `Value` of a property to primitives (types which can be wrapped by `ODataPrimitiveValue`).

Follow this guide for more details on working with entities and complex types: https://docs.microsoft.com/en-us/odata/odatalib/merge-complex-and-entity

If you're trying to write a payload consisting of an entity with a nested complex type, you could do:

```c#
// Init the entity instance.
    ODataResource entityResource = new ODataResource()
    {
    Properties = new ODataProperty[]
        {...}
    }
    // Create the ODataNestedResourceInfo for the complex property.
    ODataNestedResourceInfo complexPropertyInfo= new ODataNestedResourceInfo()
   {
      Name = "complex",
      IsCollection = false
    };
    ODataResource complexResource = new ODataResource()
    {
        Properties = new ODataProperty[]
        {
            new ODataProperty { Name = "inner", Value = "value" }
        }
    };

    writer.WriteStart(entityResource); // write the entity resource
    writer.WriteStart(complexProperty); // write the resource info. 
    writer.WriteStart(complexResource); // write then resource.
    writer.WriteEnd(); // end the complex resource.
    writer.WriteEnd(); // end the nested resource info
    writer.WriteEnd(); // end the entity resource

```

**Comment by Sreejithpin** [comment]
ODataResourceValue is designed for instance annotation, please see the above example to see how to use a nested complex property
