### ISSUE TITLE
Issue with oData V4 DateTimeOffset filter

### ISSUE THREAD

**Issue by VikingRedleg** [OData/odata.net#167]
I'm trying to filter a date field in an OData call by values which are either NULL or Greater Than the current date. I have tried all of the different things I could find on the internet. So far nothing works. It seems like it will work with a day-barrier, so things with an expiration date of yesterday don't show up but things with an expiration date of tomorrow will. However, if I have an expiration that's within an hour of the current time, it seems like neither of the results show up. For example: right now is 08:58. If one item expires at 08:00 and one expires at 09:00, neither will show up in my results.

I have reviewed the time zone information and the results coming back have the same time zone I'm setting for my filter.

Filter string template for date:

`ExpirationDate eq null or ExpirationDate gt cast({0}, Edm.DateTimeOffset)) and Variations/any()`

Code to fill it in C#:

``` C#
    var utcOffset = TimeZone.CurrentTimeZone.GetUtcOffset(DateTime.Now);
    var timeStamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss");
    var utcInfo1 = (utcOffset < TimeSpan.Zero) ? "-" : "+";
    var utcInfo2 = utcOffset.ToString(@"hh\:mm");
    _filterBuilder.Append(String.Format(_filterCORE, timeStamp + utcInfo1 + utcInfo2));
```

The above code is the original string I was attempting, without any of the changes I made to try and tweak it and get it working. I'm pretty sure UtcNow is not the right time value to be using for this query but I could be wrong. Code is C#.  _filterCORE is the variable for the format string above.

What do I need to do to this filter to get results within an hour or minutes or seconds of the time an item is set to expire?

**Comment by congysu** [comment]
@VikingRedleg Can you describe how service side is implemented?  The following seems work:
http://services.odata.org/V4/(S(lktkfz2i25co3ezoqdhbri0c))/TripPinServiceRW/Me/Trips?$filter=StartsAt%20gt%202014-01-31T23:59:00Z

**Comment by VikingRedleg** [comment]
The service is an ASP.NET ODATA WebAPI.  The controller is like this:

```C#
[EnableQuery(PageSize=25,MaxExpansionDepth=5,MaxNodeCount=800)]
public IHttpActionResult Get()
{
return OK(db.TableNames);
}
```

In the table TableNames, the dates are stored as SmallDateTime, which I've heard can have some impact.

**Comment by VikingRedleg** [comment]
The service side looks like a basic text-book OData WebApi service.  I did not see anything special about it, but I also did not write it.  

I do know that the database it is querying stores the dates as smalldatetime, and I don't know if that makes a difference.

**Comment by xuzhg** [comment]
@VikingRedleg It will be great to show us more codes to investigate? For example your business model, table schema, model builder, etc. Thanks

**Comment by VikingRedleg** [comment]
What do you want to see?  I don't think businessmodel is relevant here.  I showed the code that's filling in the date field for the query, the part of the query that's having the problem, mentioned the datatype of the field in the database, and we're not using code-first for any of this.  The rest of the query works fine - it's only when a row has the ExpirationDate assigned we have problems.

Assume the table TableNames is like this:
int **Id** (PK)
int FkId
varchar Value1
varchar Value2
... 
varchar Value20
smalldatetime  ExpirationDate

Table Variations
int **Id** (PK)
int TableNamesId (FK)
varchar Value1
varchar Value2

And my query could be searching for any or all of those fields.  ExpirationDate is the only one for which the results are not currently accurate.  I'm including a schema for Variations because it's in my  query chunk above.

**Comment by VikingRedleg** [comment]
Any more wisdom regarding this issue?

**Comment by xuzhg** [comment]
Hi, @VikingRedleg 

I created a project to test it. [Here](https://github.com/xuzhg/WebApiSample/tree/master/DateTimeOffsetWithEfTest) it is.

It seems that I can't find the issue you mentioned. Would you please run and test the console project and give us more feedback? Thanks.

**Comment by xuzhg** [comment]
@VikingRedleg , Do you still need help? Are we ok to close this issue?

**Comment by VikingRedleg** [comment]
Yeah I think we can close this issue.  It's been 3 years so I don't think I'm currently experiencing the problem and I have no further updates for you.
