### ISSUE TITLE
odata startup in Visual Studio NuGet Package Manager is very slow

### ISSUE THREAD

**Issue by johnataylor** [OData/odata.net#168]
Initializing odata appears to add 5 or 6 seconds to the initial startup cost for opening the NuGet Package Manager in Visual Studio.

This is a one time cost, but it is still a very high cost and in addition to the subsequent network calls that are made.

Is there any way to minimize these costs?

We are using odata 5.6.1

**Comment by congysu** [comment]
Customized the `DataServiceContext.ResolveType`
```c#
public Func<string, Type> ResolveType { get; set; }
```
The first parameter is a namespace qualified type name.  The return value is a CLR Type.
As long as we can get the assembly having the OData user CLR types, we can search the type from the name.

The net40 OData Client has an issue of searching assemblies in the app domain, with its default implementation.  Though, the portable OData client does not have this issue.
```c#
	#if !ASTORIA_LIGHT && !PORTABLELIB
	// searching only loaded assemblies, not referenced assemblies
	foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
	#else
	foreach (Assembly assembly in new Assembly[] { userType.GetAssembly(), contextType.GetAssembly() }.Distinct())
	#endif
```
https://github.com/OData/odata.net/blob/ODATAV3/WCFDataService/Client/System/Data/Services/Client/Metadata/ClientTypeCache.cs#L100-L129
