### ISSUE TITLE
GetReadStreamAsync not available with NoTracking - No way to get Streams with NoTracking

### ISSUE THREAD

**Issue by norcino** [OData/odata.net#1692]
It is not possible to consume streams when connecting to a read only API with MergeOption set to NoTracking.

### Assemblies affected

Microsoft.OData.Client 7.6.3

### Reproduce steps

1) Create a Container (service reference)
2) Set the MergeOptions to NoTracking
3) Load an entity which supports streams

at this stage if you try to get the stream for the given entity it will fail, even if you try to attach it

```
var stream = (await apiReference.GetReadStreamAsync(qqml, new DataServiceRequestArgs())).Stream;
var sr = new StreamReader(stream).ReadToEnd();
Console.WriteLine(sr);
```

### Expected result

1) I would expect to be able to get a stream by Id of the entity which is not possible
2) I would like to disable tracking for memory and performance benefit, given that I don't need it for a read only api. Along with it I would still like to be able to consume streams.

### Actual result

1) Is not possible to get a stream straight away (not documented at least)
2) When getting a stream for an entity not tracked, even if you try to manually track it, it throws an exception as shown below.

When the entity is not attached (NoTracking):

> System.InvalidOperationException: 'The context is not currently tracking the entity.'

When the entity is manually attached:

> System.ArgumentException: 'This operation requires that the specified entity be a Media Link Entry and that the ReadStreamUri be available. However, the specified entity either is not a Media Link Entry or does not have a valid ReadStreamUri value. If the entity is a Media Link Entry, re-query the data service for this entity to obtain a valid ReadStreamUri value. '

### Notes
I think this is important because for me would not be worth enable tracking for all requests only to support a minimal percentage of requests targeting streams.

**Comment by marabooy** [comment]
@norcino  This is a limitation in the current code. We are happy to accept any contributions on the above as well.

**Comment by marabooy** [comment]
@norcino Would you be fine with a solution that tracks the stream entities only. You can later remove the tracked entities once you have consumed the stream.

**Comment by norcino** [comment]
@marabooy Ideally I would keep things as simple as possible. Therefore I rather allow the streaming without the need to track the entity.
I cannot see how tracking would help in a read-only API while accessing streams.
Maybe the underlying code makes easier to still require the entity to be tracked, I am not sure about that, I can only speak as a user.
