### ISSUE TITLE
$metadata payload change odata.context base host url

### ISSUE THREAD

**Issue by ccdevcreative** [OData/odata.net#1694]
Hi there,
For api hosted (on premise) behind a load balancer or api gateway, the uri in the payload for document services and entity response (@odata.context,@odata.link), is the uri on the from the hosted server and not the url from the api gateway(etc).

I found a way to change the url on the entity responses metadata,but not for the document services...

Question: There are some alternative for change this url to the hosted base url?

**Comment by marabooy** [comment]
@ccdevcreative Yes it is possible to set the base url if you are using the odata core api. If you are willing to provide more info we would be happy to answer. 

``` 
ODataMessageWriterSettings settings = new ODataMessageWriterSettings();
settings.ODataUri = new ODataUri
{
    ServiceRoot = new Uri("https://services.odata.org/V4/OData/OData.svc/")
};
ODataMessageWriter writer = new ODataMessageWriter((IODataResponseMessage)message, settings);
writer.WriteServiceDocument(serviceDocument);
```
https://docs.microsoft.com/en-us/odata/odatalib/write-payload#write-service-document

**Comment by ccdevcreative** [comment]
Hi @marabooy 
Thanks so much for answer my comments...

I was able to write the services document payload in a file, but what i need is to have the same out 
![image](https://user-images.githubusercontent.com/31016910/76540565-ad8fbf00-6458-11ea-8adb-7692f197ba18.png)


But, **what i need is to replicate the same in the services document response** 
![image](https://user-images.githubusercontent.com/31016910/76540727-ed56a680-6458-11ea-8cf2-e00e389075d5.png)


I'm linking here a simple sample dot net core api project (with the default weather controller and entity)... for you can check and see what i'm missing
https://github.com/ccdevcreative/ODataOnPremise.git

Thanks so much again...

**Comment by ccdevcreative** [comment]
BTW I could change the @odata.context for the entities payload just adding to lines of code in the beginning of every action method.. 

![image](https://user-images.githubusercontent.com/31016910/76541596-3c510b80-645a-11ea-81c5-8ae1c8043d36.png)

Maybe this could help somebody....

**Comment by ccdevcreative** [comment]
@marabooy

**Comment by gyula-uszkai** [comment]
Very helpfull answer.
I used
Request.Host = new Microsoft.AspNetCore.Http.HostString("localhost:44323");
Request.Scheme = "https";            
Request.PathBase = "/demo";

To get 
{"@odata.context":"https://localhost:44323/demo/odata/$metadata#Books(Reviews())","value":[{"Id":1,"ISBN":"978-0-321-87758-1","Title":"Essential C#5.0","Author":"Mark Michaelis","Price":59.99,"Location":{"City":"Redmond","Street":"156TH AVE NE"},"Reviews":[{"Id":1,"Comment":"First Comment"}]}],"@odata.nextLink":"https://localhost:44323/demo/odata/Books?$expand=reviews&$skip=1"}

**Comment by KenitoInc** [comment]
A suggested workaround works. Closing this issue
