### ISSUE TITLE
Unchase DataServiceContext

### ISSUE THREAD

**Issue by nick-webbgh** [OData/odata.net#1698]
I'm trying to add a Document Attachment record via an Unchase Connected Service to a Microsoft Dynamics NAV database in C# (Visual Studio Professional 2017), (see code below):-

string lstrFileName = @"C:\Users\user.name\Documents\PDF\BCTest\Test Attachment 3.pdf";
System.IO.FileInfo lfi = new System.IO.FileInfo(lstrFileName);
NAV.API_Document_Attachment lobjDA = NAV.API_Document_Attachment.CreateAPI_Document_Attachment(5900, "SO000006", "Order", 0, 1);
lobjDA.AttachedDate = DateTime.Now;
lobjDA.FileName = lfi.Name;
lobjDA.FileExtension = lfi.Extension.Replace(".", string.Empty);
lobjDA.FileType = "2";
objContext.AddToAPI_Document_Attachment(lobjDA);
objContext.SaveChanges();
… but when it gets to SaveChanges, I get: "{\"error\":{\"code\":\"Application_DialogException\",\"message\":\"Please attach a document first.\"}}"

How do I programmatically attach a document?

**Comment by marabooy** [comment]
@nick-webbgh Could you provide a sample and more information?

**Comment by nick-webbgh** [comment]
Sample code is above. The PDF is just any file you've got lying about.

NAV details below:-
Version: Platform 14.0.29530.0 + Application 29537 (GB Dynamics NAV 14.0)

Anything else you need?

**Comment by nick-webbgh** [comment]
Here's the metdata.
[TestEndpointMetadata01_xml.zip](https://github.com/OData/odata.net/files/4313726/TestEndpointMetadata01_xml.zip)

**Comment by marabooy** [comment]
Thanks @nick-webbgh Let me try it out and get back to you.

**Comment by nick-webbgh** [comment]
Thanks in advance @marabooy .

**Comment by nick-webbgh** [comment]
I had the response below on another forum:
There is a field Document Reference ID in table Document Attachment. You need to stream the file to that field first before you can insert record to document attachment. See attached new cut of the metadata with the DocumentReferenceID field included.
[TestEndpointMetadata01_xml.zip](https://github.com/OData/odata.net/files/4337913/TestEndpointMetadata01_xml.zip)

**Comment by nick-webbgh** [comment]
It sees the DocumentReferenceID field as a Media type in C#, which in turn has a Content property of type DataServiceStreamLink. I have added these extra 2 lines of code:-

System.Guid lobjGuid = System.Guid.NewGuid();
lobjDA.DocumentReferenceID = NAV.Media.CreateMedia(lobjGuid);

I'm guessing the next step is to load the contents of the attachment-file into some sort of MemoryStream or byte array and somehow bind it to lobjDA.DocumentReferenceID.Content

Currently struggling with this.
Any thoughts / sample code would be appreciated?

**Comment by marabooy** [comment]
@nick-webbgh Just checked out the code metadata and for the Lob could you expose that as an EDM type stream. This will allow the generated code to have this property and you can set it as a memory stream.

**Comment by marabooy** [comment]
@nick-webbgh  could you try this 
```
objContext.AddToAPI_Document_Attachment(lobjDA);
 Stream    mediaEntry = this.GetStream(); // your method that gets the attatchment stream 
            context.SetSaveStream(lobjDA, , mediaEntry, true, new DataServiceRequestArgs { ContentType = "content-type-here" });
            await context.SaveChangesAsync();
```

**Comment by nick-webbgh** [comment]
@marabooy . Thanks for your help, but I've tried all 4 overloads of SetSaveStream but they're all erroring (see comments in code below). All the errors happen when SaveChanges is called. Despite all this I can't help thinking I'm close to a solution. Am I doing something silly wrong?

const int SHTABLEID = 5900;
string lstrFileName = @"C:\Users\nick.webb\Documents\PDF\BCTest\Test Attachment 3.pdf";
System.IO.FileInfo lfi = new System.IO.FileInfo(lstrFileName);

Bell.NAV.API_Document_Attachment lobjDA = Bell.NAV.API_Document_Attachment.CreateAPI_Document_Attachment(SHTABLEID, "SO000006", "Order", 0, 1);
lobjDA.AttachedDate = DateTime.Now;
lobjDA.FileName = lfi.Name;
lobjDA.FileExtension = lfi.Extension.Replace(".", string.Empty);
lobjDA.FileType = "2";
FileStream lobjFS = new FileStream(lstrFileName, FileMode.Open);

var ms = new MemoryStream();
lobjFS.CopyTo(ms);

System.Guid lobjGuid = System.Guid.NewGuid();
lobjDA.DocumentReferenceID = Bell.NAV.Media.CreateMedia(lobjGuid);

gobjDSC_Bell.AddToAPI_Document_Attachment(lobjDA);

// Overload 1 of 4
// gobjDSC_Bell.SetSaveStream(lobjDA, ms, true, new DataServiceRequestArgs { ContentType = "application/pdf" });
// Error: Invalid Request Body

// Overload 2 of 4
// gobjDSC_Bell.SetSaveStream(lobjDA, ms, true, "application/pdf", "Test Attachment 3.pdf");
// Error: Invalid Request Body

// Overload 3 of 4
// gobjDSC_Bell.SetSaveStream(lobjDA, "DocumentReferenceID", ms, true, new DataServiceRequestArgs { ContentType = "application/pdf" });
// Error: Please attach a document first.

// Overload 4 of 4
gobjDSC_Bell.SetSaveStream(lobjDA, "DocumentReferenceID", ms, true, "application/pdf");
// Error: Please attach a document first.

gobjDSC_Bell.SaveChanges();

**Comment by nick-webbgh** [comment]
The question I'm asking myself is: Which object should I be saving the stream to? See hierarchy below:
lobjDA : NAV.API_Document_Attachment
lobjDA.DocumentReferenceID : NAV.Media
lobjDA.DocumentReferenceID.Content : DataServiceStreamLink

**Comment by nick-webbgh** [comment]
> @nick-webbgh Just checked out the code metadata and for the Lob could you expose that as an EDM type stream. This will allow the generated code to have this property and you can set it as a memory stream. Sharing some samples for using streams but not sure how you may make it work with Nav.

What is Lob?

**Comment by marabooy** [comment]
@nick-webbgh I believe it should be this one `lobjDA.DocumentReferenceID.Content`.

**Comment by nick-webbgh** [comment]
@marabooy, OK, so I targeted that property:-
gobjDSC_Bell.SetSaveStream(lobjDA.DocumentReferenceID.Content, ms, true, new DataServiceRequestArgs { ContentType = "application/pdf" });

... and now I get: 'Value cannot be null. Parameter name: entity' Sure enough the Content property is null. As the Content property is of type: DataServiceStreamLink and there doesn't appear to be a way of instantiating it in the conventional way 
(e.g.) lobjDA.DocumentReferenceID.Content = new DataServiceStreamLink();
error CS1729: 'DataServiceStreamLink' does not contain a constructor that takes 0 arguments

… I'm stuck in a chicken & egg stalemate. Any thoughts? Thanks again for your continued support.

**Comment by marabooy** [comment]
@nick-webbgh Kindly allow me some time to try and fully recreate the issue. I should have something in the course of tomorrow.

**Comment by nick-webbgh** [comment]
@marabooy Thanks again.

**Comment by marabooy** [comment]
@nick-webbgh How flexible is nav for the following endpoint? Is it possible to change it into an action? That only takes the content this might allow us to use the `DataServiceActionQuery` for this.
@xuzhg  Any Ideas of something else he could try?

**Comment by nick-webbgh** [comment]
I download the XML metadata from a Dynamics NAV URL. In Visual Studio, I perform an Add / Update Unchase Connected Service and it auto-generates the Reference.cs code. I then call the appropriate objects / properties / methods (see code already posted) . Does this answer your question?

**Comment by marabooy** [comment]
Yes it does, after my investigation it seems that the way the odata writer is writing the output may be different from the way the server is expecting it.

**Comment by nick-webbgh** [comment]
Does this mean I'm fighting a losing battle?

**Comment by marabooy** [comment]
Not exactly. Have you tried to interact with it over say postman or another tool?

**Comment by nick-webbgh** [comment]
I've tried postman as a diagnostics step:-

https://community.postman.com/t/create-a-microsoft-dynamics-nav-document-attachment-record-using-postman/11383

The problem with using another tool is this is part of an existing solution that already uses an Unchase Connected Service extensively. It's only the Document Attachment that's not working.

**Comment by marabooy** [comment]
@nick-webbgh maybe you could try using form fields to see if thats supported. 
I would also like to suggest a workaround of using the OdataWriter directly to write the stream directly to a stream that you can then post using HTTP client or any other client.

https://docs.microsoft.com/en-us/odata/odatalib/write-payload#write-entity on how to write the entitity. the entity in the example is defined as an odata resource. 
```

ODataMessageWriter writer = new ODataMessageWriter((IODataResponseMessage)message, settings, model);
IEdmEntitySet entitySet = model.FindDeclaredEntitySet("Customers"); // the entity set with the attachments 
ODataWriter odataWriter = writer.CreateODataResourceWriter(entitySet);
ODataResource entity = new ODataResource
{
    Properties = new[]
    {
        new ODataProperty
        {
            Name = "FileName",
            Value = "filename.pdf"
        },
        new ODataProperty
        {
            Name = "DocumentReferenceID",
            Value = "refid"
        } // add other properties
    }
};
odataWriter.WriteStart(entity);
// writting the stream 

 odataWriter.WriteStart(new ODataStreamPropertyInfo
                {
                    Name = "Content", // from the generated code 
                });

using (Stream binaryStream = writer.CreateBinaryWriteStream())
{
                   fileStream.CopyTo(binaryStream);
                    binaryStream.Flush();
 } // stream must be disposed before continuing

 odataWriter.WriteEnd();  // stream property

odataWriter.WriteEnd();

```

**Comment by marabooy** [comment]
for the message in the first step you can use something similar to the one we have in the test cases https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/InMemoryMessage.cs#L13 and to initialize it use ` var messsage = new InMemoryMessage { Stream= streamYouWillReadLaterToGetPayloadForService}; `

**Comment by nick-webbgh** [comment]
I'm still struggling with this, Here's the code I've got so far. I'm stumped at:-
Name = "Content", // from the generated code?

`private void TryODataMessageWriter()
{

    string lstrURI = @"https://someurl/odataV4/Company('AcmeProducts')/";
    Uri lobjUri = new Uri(lstrURI);
    gobjDSC = new NAV.NAV(lobjUri); // from Unchase autogenerated code
    gobjDSC.Credentials = new NetworkCredential("Some.Body", "Q199ejrwUjBrXC3dlP-j94~ztzkW/GQMP^HTud2hGn0=");

    string lstrFileName = @"C:\SomeFolder\Test.pdf";
    System.IO.FileInfo lfi = new System.IO.FileInfo(lstrFileName);

    var settings = new ODataMessageWriterSettings();

    ODataUri lobjOU = new ODataUri();
    lobjOU.ServiceRoot = gobjDSC.BaseUri;
    settings.ODataUri = lobjOU;

    FileStream lobjFS = new FileStream(lstrFileName, FileMode.Open, FileAccess.Read);
    InMemoryMessage message = new InMemoryMessage { Stream = lobjFS };
    
    IEdmModel lobjIEM = gobjDSC.Format.LoadServiceModel();
    ODataMessageWriter writer = new ODataMessageWriter((IODataResponseMessage)message, settings, lobjIEM);
    IEdmEntitySet entitySet = lobjIEM.FindDeclaredEntitySet("API_Document_Attachment"); // the entity set with the attachments 
    ODataWriter odataWriter = writer.CreateODataResourceWriter(entitySet);

    System.Nullable<global::System.DateTimeOffset> lobjDTO = DateTime.Now;

    System.Guid lobjGuid = System.Guid.NewGuid();
    NAV.Media lobjAttachment = NAV.Media.CreateMedia(lobjGuid);
    lobjAttachment.Mime_Type = "application/pdf";
    
    ODataResource entity = new ODataResource
    {
        Properties = new[]
        {
            new ODataProperty
            {
                Name = "TableID",
                Value = SHTABLEID
            },
            new ODataProperty
            {
                Name = "No",
                Value = "SO000006"
            },
            new ODataProperty
            {
                Name = "DocumentType",
                Value = "Order"
            },
            new ODataProperty
            {
                Name = "LineNo",
                Value = 0
            },
            new ODataProperty
            {
                Name = "ID",
                Value = 1
            },
            new ODataProperty
            {
                Name = "FileName",
                Value = lfi.Name
            },
            new ODataProperty
            {
                Name = "AttachedDate",
                Value = lobjDTO
            },
            new ODataProperty
            {
                Name = "FileExtension",
                Value = lfi.Extension.Replace(".", string.Empty)
            },
            new ODataProperty
            {
                Name = "FileType",
                Value = "2"
            }
            
            // This property caused error: An ODataPrimitiveValue was instantiated with a value of type 'NAV.Media'.
            // ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types.
            //,
            //new ODataProperty
            //{
            //    Name = "DocumentReferenceID",
            //    Value = lobjAttachment
            //}
        }
    };
    
    odataWriter.WriteStart(entity);

    // writing the stream
    
    // THIS IS WHERE I'M STUMPED, AS BEFORE I HAVE TO POPULATE THE DOCUMENTREFERENCEID PROPERTY AND ITS CONTENT PROPERTY
    
    //ODataStreamPropertyInfo lobjOSPI = new ODataStreamPropertyInfo();
    //lobjOSPI.ContentType = "application/pdf";
    //lobjOSPI.Name = "DocumentReferenceID";
    
    odataWriter.WriteStart(new ODataStreamPropertyInfo
    {
        Name = "Content", // from the generated code ????
    });

    using (Stream binaryStream = odataWriter.CreateBinaryWriteStream())
    {
        lobjFS.CopyTo(binaryStream);
        binaryStream.Flush();
    } // stream must be disposed before continuing

    odataWriter.WriteEnd();  // stream property

    odataWriter.WriteEnd();
}
`

**Comment by marabooy** [comment]
Hi  @nick-webbgh  after digging through the streams  it seems that the code for the document attachment  misses something essential and this is due to the metadata missing a key annotation that is needed. 

![image](https://user-images.githubusercontent.com/1511024/80199065-96341c00-8629-11ea-945c-6bd497d3637c.png)

To make this work you will need to edit the metadata to add the has stream option at the top as this is missing. 
![image](https://user-images.githubusercontent.com/1511024/80200443-4fdfbc80-862b-11ea-8726-7fc4f77c1e51.png)

Or add this annotation to the generated code to make it work `    [global::Microsoft.OData.Client.HasStream()]`
![image](https://user-images.githubusercontent.com/1511024/80200536-700f7b80-862b-11ea-9d03-4fe3fd63eba6.png)

Personally I prefer editing the metadata to do this. 
Once done you can save the object using the following code

```

objContext.AddToAPI_Document_Attachment(document);
 Stream    mediaEntry = this.GetStream(); // your method that gets the attatchment stream 
            objContext.SetSaveStream(document, , mediaEntry, true, new DataServiceRequestArgs { ContentType = "content-type-here" });
            await objContext.SaveChangesAsync();
```


Sorry for taking time to reply but I needed to dig up to find out how this works in dynamics and in odata

**Comment by marabooy** [comment]
Closing this, do let me know if this fix doesn't work.
