### ISSUE TITLE
DataServiceStreamLink

### ISSUE THREAD

**Issue by nick-webbgh** [OData/odata.net#1704]
So, I've defined a custom table in an AL Extension (for Dynamics NAV) with just 2 columns:-
field(50002; SvcOrdNum; Code[20]) {}
field(50003; AttachmentPath; Blob) {}

As you can see, the second field is defined as a Blob. This is because it needs to hold path strings longer than 250 characters, so data-type: [Text] won't do. I was advised, the way round this limitation, is to use data-type: [Blob]. I deployed the extension, created a Web Service round it (via an API Page), downloaded the metadata and used it to create an Unchase Connected Service in Visual Studio 2017 Professional. When I look at the AttachmentPath property of the relevant class, it is defined as a Microsoft.OData.Client.DataServiceStreamLink. How do I store a long path (e.g.) '\\someserver\someshare\somefolder\somesubfolder\someverylonglonglonglonglonglong.pdf' to a property of type: DataServiceStreamLink? Any sample code would be greatly appreciated?

**Comment by marabooy** [comment]
Hi @nick-webbgh 

```
         NAV.NAV container = new NAV.NAV(new Uri("URL TO NAV"));
            Stream stream = new MemoryStream(Encoding.ASCII.GetBytes("long loong path"));
            stream.Position = 0; // rewind stream
            var doc = new Document(); // object you want to save with the stream links
            container.AddToDocs(doc); // add it to the correct container
            container.SetSaveStream(doc,"AttachmentPath", stream1,true,"text/plain");
            container.SetSaveStream(doc,"2ndPropertyName", anotherStreamNotShown, true,"text/plain");
            await container.SaveChangesAsync();
```

**Comment by marabooy** [comment]
Hi @nick-webbgh do let me know if this works. Closing the issue for now.
