### ISSUE TITLE
Update ODataLib description in nuget.org

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#171]
`OData .NET library is open source at http://odata.codeplex.com`
should be
`OData .NET library is open source at http://github.com/odata`
http://www.nuget.org/packages/Microsoft.OData.Core/
http://www.nuget.org/packages/Microsoft.OData.Edm/
http://www.nuget.org/packages/Microsoft.Spatial/

Also in http://odata.codeplex.com, should have some text to mention the source code and issues moved to GitHub.

**Comment by LaylaLiu** [comment]
Fixed by https://github.com/OData/odata.net/commit/48bd6979f9af1ac0dc06cae5a1ed19f2e89e42ef
