### ISSUE TITLE
Fix Warnings on OData Core

### ISSUE THREAD

**Issue by KenitoInc** [OData/odata.net#1710]
*Description.*
When building odata locally or on ADO, we are getting very many warnings. We need to clean up our codebase.

*List of warnings*

\Microsoft.OData.Core\UriParser\Binders\InBinder.cs(243,1):   warning : SA1513 : CSharp.Layout : Statements or elements wrapped in curly   brackets must be followed by a blank line.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(263,1):   warning : SA1611 : CSharp.Documentation : The documentation header must   contain param tags matching the element's parameter list.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(263,1):   warning : SA1615 : CSharp.Documentation : The documentation header must   contain a returns tag since the element has a return value.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(263,1):   warning : SA1618 : CSharp.Documentation : The documentation header must   contain typeparam tags matching the generic types for the method.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(169,1):   warning : SA1515 : CSharp.Layout : A single-line comment must be preceded by   a blank line or another single-line comment, or must be the first item in its   scope. To ignore this error when commenting out a line of code, begin the   comment with '////' rather than '//'.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(263,1):   warning : SA1202 : CSharp.Ordering : All private methods must be placed after   all internal methods.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(15,1):   warning : SA1208 : CSharp.Ordering : System using directives must be placed   before all other using directives.
\Microsoft.OData.Core\UriParser\Parsers\FunctionOverloadResolver.cs(14,1):   warning : SA1209 : CSharp.Ordering : Using alias directives must be placed   after all using namespace directives.
\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs(922,1):   warning : SA1615 : CSharp.Documentation : The documentation header must   contain a returns tag since the element has a return value.
\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs(842,1):   warning : SA1515 : CSharp.Layout : A single-line comment must be preceded by   a blank line or another single-line comment, or must be the first item in its   scope. To ignore this error when commenting out a line of code, begin the   comment with '////' rather than '//'.
\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs(1767,1):   warning : SA1108 : CSharp.Readability : A comment may not be placed within   the bracketed statement.
\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs(1867,13,1867,19):   warning : SA1000 : CSharp.Spacing : The spacing around the keyword 'foreach'   is invalid.
\Microsoft.OData.Core\UriParser\Resolver\ODataUriResolver.cs(141,13,141,19):   warning : SA1000 : CSharp.Spacing : The spacing around the keyword 'foreach'   is invalid.
\Microsoft.OData.Core\UriParser\Resolver\ODataUriResolver.cs(458,13,458,19):   warning : SA1000 : CSharp.Spacing : The spacing around the keyword 'foreach'   is invalid.
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(20,26,20,75):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(34,26,34,75):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(49,25,49,74):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(66,25,66,74):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(80,26,80,75):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(94,73,94,122):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(108,73,108,122):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(122,73,122,122):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(137,73,137,122):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(148,13,148,62):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(152,25,152,74):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(162,13,162,62):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(166,26,166,75):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(173,13,173,62):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(177,26,177,75):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(184,13,184,62):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\JsonLight\ODataSimplifiedOptionsTests.cs(188,25,188,74):   warning CS0618:   'ODataSimplifiedOptions.EnableWritingODataAnnotationWithoutPrefix' is   obsolete: 'Deprecated. Use Get/SetOmitODataPrefix()'
\Microsoft.OData.Core\IntegrationTests\Writer\InstanceAnnotationWriterIntegrationTests.cs(795,53,795,112):   warning CS0618: 'ODataMessageWriter.CreateODataDeltaWriter(IEdmEntitySetBase,   IEdmEntityType)' is obsolete: 'Use CreateODataDeltaResourceSetWriter.'
\Microsoft.OData.Core\UriParser\Extensions\Binders\ApplyBinderTests.cs(74,28,74,49):   warning CS0618: 'AggregateTransformationNode.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'
\Microsoft.OData.Core\UriParser\Extensions\Binders\ApplyBinderTests.cs(75,59,75,80):   warning CS0618: 'AggregateTransformationNode.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'
\Microsoft.OData.Core\UriParser\Parsers\SelectExpandOptionParserTests.cs(557,79,557,100):   warning CS0618: 'AggregateToken.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'
\Microsoft.OData.Core\UriParser\Parsers\SelectExpandOptionParserTests.cs(612,79,612,100):   warning CS0618: 'AggregateToken.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'
\Microsoft.OData.Core\ScenarioTests\UriParser\SelectExpandFunctionalTests.cs(1564,26,1564,129):   warning CS0618: 'AggregateTransformationNode.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'
\Microsoft.OData.Core\ScenarioTests\UriParser\SelectExpandFunctionalTests.cs(1581,26,1581,129):   warning CS0618: 'AggregateTransformationNode.Expressions' is obsolete: 'Use   AggregateExpressions for all aggregation expressions or   AggregateExpressions.OfType<AggregateExpressionToken>()  for aggregate(..) expressions only.'

### Assemblies affected
OData.Tests.E2E sln
OData.Tests.NetStandard.VS2017 sln

### Reproduce steps
Clean and build a solution on VS2017

### Expected result

No warnings

### Actual result

Too many warnings

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@KenitoInc Please consider to do some investigation about the fxcop. So far, ODL use the FxCop legacy, but, maybe it's time to move to : FxCop analysis. See detail at: https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers?view=vs-2019

**Comment by KenitoInc** [comment]
Several PRs fixing warnings have been merged. This is ongoing work though
#1823 #1808
