### ISSUE TITLE
Null validation logic differentiates between collection property with primitive values and collection property with complex values

### ISSUE THREAD

**Issue by t-bzhan** [OData/odata.net#1715]
I've observed that there are some difference between the null validation logic for collection property with primitive values and collection property with complex values. While a JSON request payload is received with the collection property explicitly set to 'null', the behavior is not unified.

For collection property with primitive values, it will complain:

>  A null value was found for the property named 'XXX', which has the expected type 'Collection(Edm.String)[Nullable=False]'. The expected type 'Collection(Edm.String)[Nullable=False]' does not allow null values.

While for collection property with complex values, it will complain:

> A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the contents of the property 'XXX'; however, a 'StartArray' node was expected

### Assemblies affected
Microsoft.AspNetCore.OData 7.3.0

### Reproduce steps
Using below code snippet:
```
using System.Collections.Generic;
using System.IO;
using System.Text;
using Microsoft.AspNet.OData.Builder;
using Microsoft.AspNet.OData.Formatter.Deserialization;
using Microsoft.OData;
using Microsoft.OData.Edm;

namespace ODataTest
{
    public class Org
    {
        public List<Policy> Policies { get; set; }
    }

    public class Policy
    {
        public int Order { get; set; }

        public string Describtion { get; set; }
    }

    public class Org1
    {
        public List<string> Members { get; set; }
    }

    class Program
    {
        static void TestCollectionComplex()
        {
            ODataModelBuilder builder = new ODataModelBuilder();
            ComplexTypeConfiguration<Org> orgType = builder.ComplexType<Org>();
            orgType.CollectionProperty<Policy>(x => x.Policies);

            IEdmModel model = builder.GetEdmModel();

            Stream stream = new MemoryStream(Encoding.UTF8.GetBytes("{" +
            "  \"Policies\": null" +
            "}"));

            IODataRequestMessage requestMessage = new InMemoryMessage() { Stream = stream };
            requestMessage.SetHeader("Content-Type", "application/json");
            ODataMessageReader reader = new ODataMessageReader(
                                                requestMessage,
                                                new ODataMessageReaderSettings()
                                                {
                                                    ReadUntypedAsString = true,
                                                    Validations = ValidationKinds.All
                                                },
                                                model);

            var odataReader = reader.CreateODataResourceReader(model.FindDeclaredType("ODataTest.Org") as IEdmStructuredType);
            var topLevelResource = odataReader.ReadResourceOrResourceSet() as ODataResourceWrapper;
        }

        static void TestCollectionString()
        {
            ODataModelBuilder builder = new ODataModelBuilder();
            ComplexTypeConfiguration<Org1> orgT1ype = builder.ComplexType<Org1>();
            orgT1ype.CollectionProperty<string>(x => x.Members);

            IEdmModel model = builder.GetEdmModel();
            Stream stream1 = new MemoryStream(Encoding.UTF8.GetBytes("{" +
            "  \"Members\": null" +
            "}"));

            IODataRequestMessage requestMessage = new InMemoryMessage() { Stream = stream1 };
            requestMessage.SetHeader("Content-Type", "application/json");
            ODataMessageReader reader = new ODataMessageReader(
                                                requestMessage,
                                                new ODataMessageReaderSettings()
                                                {
                                                    ReadUntypedAsString = true,
                                                    Validations = ValidationKinds.All
                                                },
                                                model);

            var odataReader = reader.CreateODataResourceReader(model.FindDeclaredType("ODataTest.Org1") as IEdmStructuredType);
            var topLevelResource = odataReader.ReadResourceOrResourceSet() as ODataResourceWrapper;
        }

        static void Main(string[] args)
        {
            TestCollectionComplex();
            //TestCollectionString();
        }
    }
}
```

### Expected result

Both TestCollectionComplex and TestCollectionString method would throw ODataException complains that 

> A null value was found for the property named 'XXX', which has the expected type 'Collection(XXX)[Nullable=False]'. The expected type 'Collection(XXX)[Nullable=False]' does not allow null values

### Actual result

TestCollectionComplex throw exception that complains:

> 'A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the contents of the property 'Policies'; however, a 'StartArray' node was expected.'

### Additional detail
Call stack for TestCollectionComplex：
This exception was originally thrown at this call stack:
    _

> Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ValidateExpandedNestedResourceInfoPropertyValue(Microsoft.OData.Json.IJsonReader, bool?, string)
>     Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(Microsoft.OData.JsonLight.IODataJsonLightReaderResourceState, string, bool)
>     Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent.AnonymousMethod__0(Microsoft.OData.JsonLight.ODataJsonLightDeserializer.PropertyParsingResult, string)
>     Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(Microsoft.OData.PropertyAndAnnotationCollector, System.Func<string, object>, System.Action<Microsoft.OData.JsonLight.ODataJsonLightDeserializer.PropertyParsingResult, string>)
>     Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(Microsoft.OData.JsonLight.IODataJsonLightReaderResourceState)
>     Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
>     Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(Microsoft.OData.PropertyAndAnnotationCollector, Microsoft.OData.SelectedPropertiesNode)
>     Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(Microsoft.OData.PropertyAndAnnotationCollector)
>     Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
>     Microsoft.OData.ODataReaderCore.ReadImplementation()
>     ...
>     [Call Stack Truncated]

_

**Comment by habbes** [comment]
Hi @t-bzhan, thanks for raising this issue. We would love to take a contribution if you have time to submit a pull request.

**Comment by t-bzhan** [comment]
@habbes It is really a pity that I did not have enough time and strong domain knowledge to fix that for the moment, :). Is there any workaround to address this?
