### ISSUE TITLE
OData: Incompatible type kinds were found. Found type kind 'Primitive' instead of the expected kind 'None'

### ISSUE THREAD

**Issue by suwblk** [OData/odata.net#1721]
*MS Excel 2016  OData: Incompatible type kinds were found. Found type kind 'Primitive' instead of the expected kind 'None'*

*OData .Net lib 7.x*

### Reproduce steps
MS Excel version 16.0.11929.20436
Get Data -> From Other Sources -> From OData Feed.
Give the url : https://somedomain:8080/aaaaaaaaa/ProjectionTest1.svc/EntitySetName?$format=json
This same url works fine when entered in the browser. 
**CSDL file does not have top level elements with duplicating names.**

### Expected result

Data should be extracted in to excel correctly

### Actual result

It gives the error 
OData: Incompatible type kinds were found. Found type kind 'Primitive' instead of the expected kind 'None'

### Additional detail
![Excel Get Data From Other Forms](https://user-images.githubusercontent.com/41049983/77531524-15aebe00-6eb9-11ea-8b5e-3dffe6d62f64.png)
![No duplicates CDSL](https://user-images.githubusercontent.com/41049983/77531532-18a9ae80-6eb9-11ea-9d12-38d2b31eb398.png)
![OData Excel issue](https://user-images.githubusercontent.com/41049983/77531536-19424500-6eb9-11ea-8dcf-03544b178678.png)

**Comment by KenitoInc** [comment]
@suwblk If possible provide a trace of the request and response: the excel and browser requests. Also share the full schema.

**Comment by suwblk** [comment]
Hi @KenitoInc ,
How can I obtain a trace of the request and response in OData Provider in excel. I will share the full schema. 
With the further investigations I realized below. 
1. Pointed local environment to the databases of the test environments that generate the issue. http:/localhost:8080 call retrieves data.
2. test environments with https://host:48080 gives the Odata error. 

[GitHubCSDL.txt](https://github.com/OData/odata.net/files/4413217/GitHubCSDL.txt)

**Comment by suwblk** [comment]
Hi @KenitoInc ,

Do you have any update on this ?

**Comment by KenitoInc** [comment]
@suwblk I am getting an error at `<Member Name="Id*" Value="4" />`
Otherwise the metadata looks fine. I can generate proxy classes using the metadata.
Based on your investigation, my guess is that there is something wrong with your service.
In addition, your test environment uses `https` while your local environment uses `http`. Ensure your service is configured properly to use https

**Comment by suwblk** [comment]
Hi @KenitoInc ,
Thank you for the reply. 
We have correctly handled the https requests. Locally deployed apps have http protocol. Also some other services do generate correct results. 
This is really a very strange error. 
I hope you could have a second look at the CSDL and see if there is anything suspicious ?

KR Suwblk

**Comment by suwblk** [comment]
hi @KenitoInc & @KanishManuja-MS  ,

@KenitoInc 
I figured out the problem, MS Excel has an internal cached which caused the issue not to be resolved even after the CSDL was modified to have unique element names. After the cache was cleared it worked fine. Thanks for your reply.

@KanishManuja-MS  : I referred to your answer for issue https://github.com/OData/odata.net/issues/1445.

**"OData protocol does not allow duplicate names for top-level elements in the same namespace. If you call Validate on the model, it should fail."**

1. Could you please let me know where I can find a documentation which has this particular validation restriction? 
2. How can I validate a CSDL based on the standard OData protocols specifications. ?

Thank you !
Suwblk

**Comment by KenitoInc** [comment]
@suwblk Closing this issue
