### ISSUE TITLE
ODataReader fails to read response message without @odata.context

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#1723]
When specifying the system query option $format=application/json;odata.metadata=none, the returned response doesn't have @odata.context annotation. Attempting to read such response with ODataReader results in ODataException: The required instance annotation 'odata.context' was not found at the beginning of a response payload.

### Assemblies affected

Microsoft.OData.Core 7.6.1

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KenitoInc** [comment]
@korygin metadata=none is not an interoperable payload settings since it strips necessary information required for interpreting an odata response payload.
