### ISSUE TITLE
 ODataReader: high CPU usage and slow performance when reading larger OData payloads

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#1725]
High CPU usage and slow performance when reading larger OData payloads.

### Assemblies affected

Microsoft.OData.Core 7.6.1

### Reproduce steps

During profiling of an OData client app we have noticed a significantly degraded performance and high CPU usage when reading larger OData payloads. I have attached a zip file with sample EDM model, payload and unit test to showcase the problem. Reading the ~ 500Kb resource set payload with 1000 resources in it takes approximately 3.5 - 4 secs. 

[ODataReaderPerformance.zip](https://github.com/OData/odata.net/files/4404214/ODataReaderPerformance.zip)

### Actual result

*What is actually happening.*

![image](https://user-images.githubusercontent.com/14077250/77930458-e90ff300-7278-11ea-9ce1-6e0b6d3fdd6e.png)

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KenitoInc** [comment]
@korygin We are investigating this. We will get back later.
