### ISSUE TITLE
[FromODataUri] parses string as double

### ISSUE THREAD

**Issue by mkonars** [OData/odata.net#1730]
I am using FromODataUri attribute on a string parameter with value "5e80b9ccf5adf530540bbba4". It is incorrectly parsed to double value '5E+80'

```
https://localhost:44376/odata/Place(5e80b9ccf5adf530540bbba4)

[HttpGet]
[Route("odata/Place({key})")]
public async Task<Place> GetOne([FromODataUri]string key)
{
       return await placeService.Get(key);
}
```
I have traced it from the model binder to

`ODataUriUtils.ConvertFromUriLiteral("5e80b9ccf5adf530540bbba4", ODataVersion.V4);
`
which further parses the value to `ExpressionTokenKind.DoubleLiteral` in `ExpressionLexer.cs` instead of a string type.

Am I doing something wrong or is this a bug?

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

Microsoft.AspNetCore.OData --version 7.4.0-beta

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by gathogojr** [comment]
@mkonars Did you try the following?
https://localhost:44376/odata/Place('5e80b9ccf5adf530540bbba4')

**Comment by mkonars** [comment]
Adding single quotes helps with proper parsing, but when I add them, instead of this route

```
[Route("odata/Place({key})")]
public Place GetOne([FromODataUri]string key)
```

this one is called:

```
[Route("odata/Place")]
public IEnumerable<Place> Get()
```

**Comment by gathogojr** [comment]
@mkonars For the routing issue, we'd have to look at how you're configuring your service.
I see you're using attribute routing. Can you consider using `ODataRoute` in place or `Route`? Our advice to people is to use OData routing when creating OData services, especially if you're implementing OData controllers (by deriving from `ODataController`).
Checkout out this reference https://docs.microsoft.com/en-us/odata/webapi/attribute-routing
In addition, convention-based and attribute-based routes don't always play well together.

**Comment by mkonars** [comment]
@gathogojr It does work with `ODataRoute`. Thank you for explanation.
