### ISSUE TITLE
Convert BaseEntityType to interface

### ISSUE THREAD

**Issue by weitzhandler** [OData/odata.net#1735]
Currently, all entities in MS OData client are based on `BaseEntityType` - a concrete class lying in an external assembly.
This is very limiting, as it can't be marked as partial, and requires OData users to base their types on it rather than POCO classes.

Please introduce an interface `IBaseEntityType`, and have `BaseEntityType` implement it.
Throughout the entire library, only require the interface `IBaseEntityType`, rather than the concrete class.
The `BaseEntityType` should remain there for backwards compatibility or for other scenarios.
All other features that we might want to add in the future can be accomplished with extension methods or external services or using DI.

### Assemblies affected

Microsoft.OData.Client

### Reproduce steps

`BaseEntityType` should be an interface, not a concrete class, to allow for multi-inheritance.

### Expected result

We should be able to use our own entity base types.

###

This first needs to be dealt in this repo, then, the it can be addressed in the generator as well: https://github.com/OData/ODataConnectedService/issues/88.

**Comment by gathogojr** [comment]
@weitzhandler Thank you the question. We would appreciate a PR contribution if you're in a position to

**Comment by weitzhandler** [comment]
Hey John and thanks for your reply!
I actually created [a branch]() with this change, but due to #1560, I'm unable to actually test this. I'm wondering how you guys are building this repo at all, I made a PR for that one too, it's at #1561.

**Comment by weitzhandler** [comment]
Can't seem to run the tests - opened #1736.

**Comment by gathogojr** [comment]
@weitzhandler Creating a PR will trigger Azure DevOps to run the tests and report status to GitHub...

**Comment by weitzhandler** [comment]
#1741
