### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by weitzhandler** [OData/odata.net#1736]
When trying to run the tests on the master branch (Run all), I get the following error for all of them:

> System.IO.FileLoadException : Could not load file or assembly 'Microsoft.OData.Client, Version=7.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

### Reproduce steps

Clone code, launch `OData.sln` form the root folder and build project, and run the tests.

### Expected result

Tests should run

### Actual result

The tests in `Microsoft.OData.Client.Tests` all fail for the above message. The rest of the tests are skipped.

**Comment by gathogojr** [comment]
@weitzhandler See if this resource can help you with the strong naming issue https://docs.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature
README also has instructions on how to run the tests with strong name feature disabled

**Comment by weitzhandler** [comment]
I used the readme you suggested to me the other day in the [ODataConnectedService](https://github.com/OData/ODataConnectedService#faq).
