### ISSUE TITLE
Understanding Routing OData 7.4

### ISSUE THREAD

**Issue by rbrynteson** [OData/odata.net#1739]
Very new to the world of EF Core and OData.  Came from a .NET 4.x and WebAPI land so trying to accomplish similar tasks and getting hung up on some of the OData / EDM pieces.

Following this guide: https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/

The scenario is that I have a SQL instance that is being used for a multi-tenant application.  Within each table we have a CustomerId field that corresponds each record to the underlying customer.  So previously we would write all of our get commands similar to the following:

GET /EndpointName/   <-  Return all records for admin purposes
GET /EndpointName/CustomerID   <- Return all records for that customer
GET /EndpointName/CustomerID/ID    <- Return just that single record for that customer

There is all sorts of auth handling as tokens in the Headers.

So we turned our attention to trying to make this work in EF Core/Odata 7.4 as it supports endpoint routing.

So following along in the blog above, I had to go to my existing class that was reverse engineered and add a [Key] for the primary key as that wasn't discovered.

```C#
public partial class AuditRecords
 {
        [Key]
        public int AuditId { get; set; }
        public int CustomerId { get; set; }
        public int LoginId { get; set; }
        public string AuditText { get; set; }
        public DateTime? AuditDate { get; set; }
        public bool? NotificationSent { get; set; }
}
```

I updated my Startup.cs to include:

```C#
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.Select().Filter().OrderBy().Count().MaxTop(10);
                endpoints.MapODataRoute("odata", "odata", GetEdmModel());
            });

private IEdmModel GetEdmModel()
        {
            var odataBuilder = new ODataConventionModelBuilder();
            odataBuilder.EntitySet<AuditRecords>("AuditRecords");

            return odataBuilder.GetEdmModel();
        }
```

Went to an existing controller, removed the [ApiController] and [Route("AuditRecords")] from the top.  I then ran a:

GET /AuditRecords/

And got all records.  Where it quickly fell apart is the routing to the other two endpoints.  So I tried a combination of [HttpGet("{CustomerId}")] like before and nothing worked.  So I swapped out ControllerBase to ODataController and found then I could get these two to work by doing a:

[ODataRoute("AuditRecords")]  <-- Returned all like I wanted.

[ODataRoute("AuditRecords/{customerId}")]   <-  Returns all with a single customerID

But if I try to then add [ODataRoute("AuditRecords/{customerId}/{id}")] the entire controller dies and I get a "The path template 'AuditRecords/{customerId}/{id}' on the action 'GetAuditRecords' in controller 'AuditRecords' is not a valid OData path template.

So after banging my head on the desk for a while I switched over to non-EDM method as described in the above blog post and it works fine.  The problem of course is, when in non-EDM you lose count, patch and some of the formatting that odata has.

So my question is, can I even accomplish what I'm trying to do above in an EDM model?  I saw you can build the OdataRoute like this instead:

[ODataRoute("({customerId})")] I can accomplish it.  If I try to do a [ODataRoute("({customerId},{id})")] then I get an error that I don't have enough keys in my class.  So I add a second key, then the request with only one request stops working.

Been reading the docs and EDM Routing doesn't seem to make much sense to me.

**Comment by xuzhg** [comment]
@rbrynteson the route template in ODataRouteAttribute should follow up OData Uri convention. For detail OData Uri convention, you can refer to: http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html. In a short, `[ODataRoute("AuditRecords/{customerId}/{id}")] ` is not a valid OData route template. I am wondering what's the scenario for an {id} after {customerId}?

**Comment by rbrynteson** [comment]
@xuzhg so the general idea is that AuditRecords/{customerId}/ would return all records from this table assigned to this customer Id, whereas AuditRecords/{customerId}/{id} is instead returning a single record, not an array.

**Comment by xuzhg** [comment]
@rbrynteson An entity is uniquely identified within an entity set by its key. So, "AuditRecords is an entity set, "customerId" is the key, 'AuditRecords/{customerId}' would return an unique entity, not another collection (records).
