### ISSUE TITLE
Release notes missing and with incorrect references

### ISSUE THREAD

**Issue by evilB** [OData/odata.net#1752]
*Short summary (3-5 sentences) describing the issue.*
I was trying to find out information on a potential bug, and i found that the 
release notes for Microsoft.OData.Core 7.6.4 are missing from the page:
https://docs.microsoft.com/en-us/odata/changelog/odatalib-7x

The release notes link from the nuget repository is also broken
(https://odata.github.io/odata.net/v7/#ODL-7.6.4) and similar for older versions

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

7.6.4

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

go to page https://docs.microsoft.com/en-us/odata/changelog/odatalib-7x
see that the release notes are not there

and go to page 
https://www.nuget.org/packages/Microsoft.OData.Core/7.6.4 
and see that the release notes link doesn't work

### Expected result

Release notes would be accessible

### Actual result

Release notes are not accessible

**Comment by KanishManuja-MS** [comment]
Fixed.
