### ISSUE TITLE
Strange Timeout behavior when requesting entities from D365

### ISSUE THREAD

**Issue by obutov** [OData/odata.net#1753]
When certain D365 entities take longer than 5 minutes to return, the OData client fails to receive any response. 

### Assemblies affected

"Microsoft.OData.Client" version="7.6.2"

### Reproduce steps

Generate OData client proxy by consuming D365 edmx file. 
Set context timeout to 10 minutes
Request a slow-performing entity from D365 (e.g. entity that takes longer than 5 minutes to return the response). For example, _context.CustomersV2.Execute();
The response never arrives and request times out after 10 minutes.
Set timeout to 30 minutes or 60 minutes - the result would be the same. 
### Expected result

The response should be received and processed by OData client, even if it takes more than 5 minutes for D365 to send the response. 

### Actual result

OData client seems to fail to properly receive and process any long-running responses (that take longer than 5 minutes).

### Additional detail

N/A

**Comment by marabooy** [comment]
Hi could you try and use fiddler or a trace client to see what is happening? I suspect that the request could be closed before the response comes in.

**Comment by obutov** [comment]
I used fiddler to trace the request, but could not see any response. The request is sent to D365, but then it just "sits" there. Even when the client throws the context timeout, nothing happens on the fiddler side. When I send a request using Postman, the response arrives after 8-9 minutes. When I send it using OData client, nothing happens. It almost seems like there is some kind of "internal" timeout that doesn't bubble up properly, nor can it be adjusted. Just a wild speculation at this point.

**Comment by ElizabethOkerio** [comment]
@obutov The <code>DataServiceContext </code> class in <code>Microsoft.OData.Client </code> library has a Timeout property that you can set before you make any request with <code>Microsoft.OData.Client </code>. You can set the timeout value to whichever value you want to ensure that the request does not time out before a response is returned. Normally, if you do not set this value before making a request, the request uses the default timeout value which is 100 seconds. So if you are making a request that will take more than a 100 seconds to return a value then it is important that you set the timeout value like below: 
<pre>
DefaultContainer context = new DefaultContainer(new Uri("https://services.odata.org/v4/TripPinServiceRW/"));
            context.Timeout = 1200000;
var cust = context.Customers.FirstOrDefault();

</pre>

**Comment by ElizabethOkerio** [comment]
Closing this issue. Feel free to reopen it if this does not solve your issue. Thanks.

**Comment by obutov** [comment]
As I describe in the issue, I’m already setting the context timeout to 10 minutes. The problem is that if D365 sends a response after 8 minutes, the client doesn’t seem to receive anything, so, naturally, it times out after 10 minutes. If D355 send a response after 4 minutes, the client receives and processes it without any issues.
