### ISSUE TITLE
OData Client 7.6.4 is getting this error "In OData, a top-level error object must have exactly one property with name 'error'"

### ISSUE THREAD

**Issue by ImGonaRot** [OData/odata.net#1756]
OData Client 7.6.4

When I upgraded the Microsoft.OData.Client from 7.6.3 to 7.6.4 I am receiving the following error when I try to serialize an ODataError object into the Response "Content" and the OData client tries to deserialize the response.

On client 7.6.3 it works fine.

NOTE: I am listing the OData service code that can be used to test the exception from the service. 
           This is not a server side issue and only occurs when updating the client to 7.6.4

> Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.InvalidOperationException: An error occurred while processing this request. ---> Microsoft.OData.ODataException: A property with name 'ErrorCode' was found in the error object when reading a top-level error. In OData, a top-level error object must have exactly one property with name 'error'.
> at Microsoft.OData.JsonLight.ODataJsonLightErrorDeserializer.ReadTopLevelErrorImplementation () [0x00028] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.JsonLight.ODataJsonLightErrorDeserializer.ReadTopLevelError () [0x0001e] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.JsonLight.ODataJsonLightInputContext.ReadError () [0x00007] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.ODataMessageReader+<>c.b__68_0 (Microsoft.OData.ODataInputContext context) [0x00000] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.ODataMessageReader.ReadFromInput[T] (System.Func`2[T,TResult] readFunc, Microsoft.OData.ODataPayloadKind[] payloadKinds) [0x00030] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.ODataMessageReader.ReadError () [0x00006] in <3821c67bef1a4240aa87fa2afb20b4a9>:0 
> at Microsoft.OData.Client.BaseSaveResult.GetResponseText (System.Func`1[TResult] getResponseStream, System.Net.HttpStatusCode statusCode) [0x00084] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.BaseSaveResult.HandleResponse (Microsoft.OData.Client.RequestInfo requestInfo, System.Net.HttpStatusCode statusCode, System.String responseVersion, System.Func`1[TResult] getResponseStream, System.Boolean throwOnFailure, System.Version& parsedResponseVersion) [0x00037] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.QueryResult.CompletedRequest () [0x0006c] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.BaseAsyncResult.HandleCompleted () [0x0002a] in <37fe22d142124247b7abcad9baf83ea0>:0 
> --- End of inner exception stack trace ---
> at Microsoft.OData.Client.BaseAsyncResult.EndExecute[T] (System.Object source, System.String method, System.IAsyncResult asyncResult) [0x0014c] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement] (System.Object source, System.String method, System.IAsyncResult asyncResult) [0x00002] in <37fe22d142124247b7abcad9baf83ea0>:0 
> --- End of inner exception stack trace ---
> at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement] (System.Object source, System.String method, System.IAsyncResult asyncResult) [0x00037] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.DataServiceRequest.EndExecute[TElement] (System.Object source, Microsoft.OData.Client.DataServiceContext context, System.String method, System.IAsyncResult asyncResult) [0x000a5] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.DataServiceContext.EndExecute[TElement] (System.IAsyncResult asyncResult) [0x0000c] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at Microsoft.OData.Client.DataServiceActionQuerySingle`1[T].EndGetValue (System.IAsyncResult asyncResult) [0x0000c] in <37fe22d142124247b7abcad9baf83ea0>:0 
> at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:534 
> --- End of stack trace from previous location where exception was thrown ---
> 

Code I use on the OData service side for the "test".
```c#
// Add this to the Application_Start() inside the global asx if using ASP.NET non-core
HttpConfiguration config = GlobalConfiguration.Configuration;
config.Filters.Add(new TestExceptionFilterAttribute());


public class TestExceptionFilterAttribute : ExceptionFilterAttribute
{
	public override void OnException(HttpActionExecutedContext context)
	{
		HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.BadRequest);
		response.RequestMessage = context.Request;
		ODataError oDataError = new ODataError();

		if (context.Exception is OperationCanceledException && (context.Exception as OperationCanceledException).CancellationToken.IsCancellationRequested)
		{
			// eat this exception because user closed the web service while they were getting data                
			return;
		}
		else if (context.Exception is ValidationException)
		{
			oDataError.ErrorCode = "Validation";
			oDataError.Message = context.Exception.Message;
		}
		else if (context.Exception is DbEntityValidationException)
		{
			DbEntityValidationException dbVex = context.Exception as DbEntityValidationException;
			StringBuilder errorMessage = new StringBuilder();

			foreach (DbValidationError validationError in dbVex.EntityValidationErrors.FirstOrDefault().ValidationErrors)
			{
				errorMessage.AppendLine(validationError.ErrorMessage);
			}

			oDataError.ErrorCode = "Validation";
			oDataError.Message = errorMessage.ToString();
		}
		else if (context.Exception is SqlException && (context.Exception as SqlException).Number >= 50000)
		{
			// this is a SQL validation error
			oDataError.ErrorCode = "Validation";
			oDataError.Message = context.Exception.Message;
		}
		else
		{
			// we only care about the top most exception
			Exception tempError = context.Exception;
			string errorMessage = tempError.Message;
			while (tempError.InnerException != null)
			{
				tempError = tempError.InnerException;
				errorMessage = tempError.Message;
			}

			oDataError.ErrorCode = "Exception";
			oDataError.Message = errorMessage;

			// log the exception
				
			}
		}

		response.Content = new StringContent(JsonConvert.SerializeObject(oDataError));
		context.Response = response;
	}
}
	
	
// Use this to test ValidationException
throw new ValidationException("This is a validation test message!");

```

**Comment by maxvella** [comment]
Getting the same error. Problem seems to be linked to the ODataJsonLightErrorDeserializer

I'm getting the following stack trace:

   at Microsoft.OData.JsonLight.ODataJsonLightErrorDeserializer.ReadTopLevelErrorImplementation()
   at Microsoft.OData.JsonLight.ODataJsonLightErrorDeserializer.ReadTopLevelError()
   at Microsoft.OData.JsonLight.ODataJsonLightInputContext.ReadError()
   at Microsoft.OData.ODataMessageReader.<>c.<ReadError>b__68_0(ODataInputContext context)
   at Microsoft.OData.ODataMessageReader.ReadFromInput[T](Func`2 readFunc, ODataPayloadKind[] payloadKinds)
   at Microsoft.OData.ODataMessageReader.ReadError()
   at Microsoft.OData.Client.BaseSaveResult.GetResponseText(Func`1 getResponseStream, HttpStatusCode statusCode)
   at Microsoft.OData.Client.BaseSaveResult.HandleResponse(RequestInfo requestInfo, HttpStatusCode statusCode, String responseVersion, Func`1 getResponseStream, Boolean throwOnFailure, Version& parsedResponseVersion)
   at Microsoft.OData.Client.SaveResult.HandleOperationResponseData(IODataResponseMessage responseMsg, Stream responseStream)
   at Microsoft.OData.Client.SaveResult.FinishCurrentChange(PerRequest pereq)
   at Microsoft.OData.Client.BaseSaveResult.AsyncEndRead(Task task, Object asyncState)

**Comment by tomaszbroniewski** [comment]
I'm getting the similar error but with 'innerError' indication (OData Client 7.6.4)

> ODataException: A property with name 'innerError' was found in the error value of a top-level error. In OData, a top-level error value can only have properties with name 'code', 'message', or 'innererror', or custom instance annotations.

**Comment by paulodero** [comment]
> I'm getting the similar error but with 'innerError' indication (OData Client 7.6.4)
> 
> > ODataException: A property with name 'innerError' was found in the error value of a top-level error. In OData, a top-level error value can only have properties with name 'code', 'message', or 'innererror', or custom instance annotations.

This was fixed. Should work well in the next release.
