### ISSUE TITLE
Getting $metadata as JSON

### ISSUE THREAD

**Issue by cilerler** [OData/odata.net#1771]
I would like to be able to retrieve $metadata as JSON, is there a way to do that?

Thanks in advance.

```HTTP
@host = localhost:5000
@baseUrl = http://{{host}}/odata

### @name GetMetadata
GET {{baseUrl}}/$metadata HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name GetMetadataAsJson
GET {{baseUrl}}/$metadata&$format=json HTTP/1.1
Host: {{host}}
Cache-Control: no-cache
```

**Comment by odero** [comment]
There's work currently ongoing for this feature https://github.com/OData/odata.net/pull/1757
Delivery timelines for this feature release are still TBD. If this answers your question feel free to close the issue
