### ISSUE TITLE
How to generate "ODATA" url from oracle database using sql query or plsql ?

### ISSUE THREAD

**Issue by rambabu3381** [OData/odata.net#1772]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KenitoInc** [comment]
Closing this.
Feel free to create a new issue if there are any more questions to be answered.
