### ISSUE TITLE
An error writing OData delta links

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#1776]
An OData writer fails with "A synchronous operation was called on an asynchronous writer. Calls on a writer instance must be either all synchronous or all asynchronous." when writing delta links even if the asynchronous writing method is used. 

### Assemblies affected

Microsoft.OData.Core, Version=7.6.4.0

### Reproduce steps

[ODataDeltaWriterTest.zip](https://github.com/OData/odata.net/files/4634990/ODataDeltaWriterTest.zip)

### Expected result

*What would happen if there wasn't a bug.*
OData delta link is written into the delta payload

### Actual result
An error is thrown:
"A synchronous operation was called on an asynchronous writer. Calls on a writer instance must be either all synchronous or all asynchronous."

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by mikepizzo** [comment]
confirmed fixed by #1770 -- thanks for the great repro!
