### ISSUE TITLE
Unrecognized 'Edm.Geography' literal

### ISSUE THREAD

**Issue by chadcampbell** [OData/odata.net#178]
Hello,

I have a url that looks like the following:
```
http://localhost:8089/MyApp/Search?i=index-name&q=*&f=(geo.distance(latLong,%20geography%27POINT(47.12995075666307%20-102.12890625)%27)%20le%20213.57)
```

I am attempting to parse the above into a `FilterClause` using the following:
```
FilterClause filters = ODataUriParser.ParseFilter(expression, model, type);
```

The above line throws an error that says:
```
Unrecognized 'Edm.Geography' literal 'geography'POINT(47.12995075666307 -102.12890625)'' at '23' in '(geo.distance(latLong, geography'POINT(47.12995075666307 -102.12890625)') le 213.57)'.
```

Oddly, the following works just fine though:
```
http://localhost:8089/MyApp/Search?i=index-name&q=*&f=(geo.distance(latLong,%20geography%27POINT(38.9803624372554%20-77.05879211425781)%27)%20le%202.01)
```

The only difference I can see is in the geo coordinates themselves.

**Comment by karataliu** [comment]
@chadcampbell  I think that's because the second parameter latitude has a value of -102.128, which exceed the range of latitude, then the parser would fail in this case. I think the problem here is that the message is not that clear to indicate this issue, we'll take a look at this.

**Comment by LaylaLiu** [comment]
@chadcampbell. Thanks for reporting this issue. I will close this issue right now. If you have more update on this issue or if you have still questions about this issue, please reopen it.
