### ISSUE TITLE
Objects with same collection names of object don't get populated after calling sequential expand

### ISSUE THREAD

**Issue by TripleNico** [OData/odata.net#1780]
What i'm currently experiencing is that objects that have the same name will not be populated after a sequential call. Let me explain it with code(not tested below):

Say i have several objects

```vb
Private Order as MyOrder
Private Customer as MyCustomer 

Public class MyOrder
    Public name as string
    Public customer as MyCustomer
end class

public class MyCustomer
    Public name as string
    Public Orders as collection(of MyOrder)
end class
```

Now i setup the Query objects with the Expand setting this is where it goes wrong:
```vb
Private dsqCustomers As DataServiceQuery(Of MyCustomer) = DataServiceContext.Orders.Expand("Orders")
Private dsqOrders As DataServiceQuery(Of MyOrder) = DataServiceContext.Customers.Expand("Customer")
```

Then when i call dsqCustomers.Execute on the DataServiceQuery objects i noticed that in the dsqOrders collection the .Customer objects are empty and viceversa so when i first call dsqOrders.Execute then the .Orders collection is empty. It seems like it is going from because the names are the same of the object types?

If i look at the data with WireShark i can see that the data is being send but it is not populated.

**Comment by xuzhg** [comment]
@TripleNico 

Should the code 
```vb
Private dsqOrders As DataServiceQuery(Of MyOrder) = DataServiceContext.Customers.Expand("Customer")```

 be 

```vb
Private dsqOrders As DataServiceQuery(Of MyOrder) = DataServiceContext.Orders.Expand("Customer")
```

**Comment by TripleNico** [comment]
Thanks for pointing that out, is was a copy paste mistake. I adjusted the original post.

The problem i experience is that both of the query's use collections with the same objects in them. So `DataServiceContext.Customers` is of type `Customer `which has a collection in of type `Order`. Object looks like` Customer.Collection(Of Orders)`

`DataServiceContext.Orders` is of type `Order `which has a an object in of type `Customer`. Object looks like `Order.Customer`

Now when i first call the query `DataServiceQuery.Customers.Execute` and then shortly after `DataServiceQuery.Orders.Execute` than the `Order.Customer` object is empty in the `DataServiceQuery.Orders`

And vice versa:
When i first call the query `DataServiceQuery.Orders.Execute` and then shortly after `DataServiceQuery.Customers.Execute` than the `Customer.Orders` collection is empty in the `DataServiceQuery.Customers`

If i create new instances of the `DataServiceQuery` before each .execute than i don't experience this issue.

When i look at the data with Wireshark i can see that the data is all there in the IP packet. So the serialization is going wrong?

**Comment by KenitoInc** [comment]
Hey @TripleNico 
From your code, it seems there are some values being lost when merging entities.
We need to set the MergeOption property in your context. See doc below
https://docs.microsoft.com/en-us/dotnet/api/microsoft.odata.client.dataservicecontext.mergeoption

So in your code, add the code below before the queries
```csharp
DataServiceContext.MergeOption = MergeOption.PreserveChanges;
```
Get back to me if that works for you.

**Comment by TripleNico** [comment]
Thanks for the tip. Changed it and at first tests it seems to work properly now!

**Comment by KenitoInc** [comment]
@TripleNico Let me close this issue for now. Incase you have more issues, you can reopen or create a new issue

**Comment by TripleNico** [comment]
Thanks, will do!
