### ISSUE TITLE
How to add headers in a Named OData Client 

### ISSUE THREAD

**Issue by dcadlereii** [OData/odata.net#1781]
I am trying to set up an ASP.NET Core 3.1x Web App and use the Properties part of the line dsc.Configurations.Prioperties says that it doesn't exist. I assume a change has been made in the Microsoft.Odata.Client and the docs just have not been updated.

How do I add headers for a named Odata client?
 In my Startup.cs --> ConfigureServices method, I am trying to set up a named client following the example shown in the document at https://docs.microsoft.com/en-us/odata/client/using-extensions. The example shows the following;

services.AddODataClient("TripPin")
    .ConfigureODataClient(dsc =>
    {
        dsc.BaseUri = new Uri("https://services.odata.org/v4/(S(lqbvtwide0ngdev54adgc0lu))/TripPinServiceRW/");

        // Github API versioning
        dsc.Configurations.Properties.Add("User-Agent", "ODataClientFactory-Sample"));
    });

However, the Properties part of the line dsc.Configurations.Prioperties says that it doesn't exist. I assume a change has been made in the Microsoft.Odata.Client and the docs just have not been updated.

How do I add headers for a named Odata client?

### Assemblies affected

Microsoft.OData.Client v7.6.4

### Reproduce steps

Create an ASP.NET Core 3.x Web Application.
Add the Data Service Connection as described in https://docs.microsoft.com/en-us/odata/client/getting-started
In startup.cs -- COnfigureServices method, add the code listed in the Named Client section here https://docs.microsoft.com/en-us/odata/client/using-extensions#named-clients
Note that the .Properties has a red squiggle and says DataServiceClientConfigurations does not have a definition for 'Properties'.

### Expected result

I expected that the code from the docs would work and allow me to add a header.

### Actual result

Code is failing as the "Properties" does not exist.

**Comment by xuzhg** [comment]
@dcadlereii It looks a regression. The `Properties` property was removed in recently release.

**Comment by ElizabethOkerio** [comment]
@dcadlereii you can add headers like: 

<code>
services.AddODataClient("TripPin").ConfigureODataClient(dsc =>
            {
                dsc.BaseUri = new Uri("https://services.odata.org/v4/(S(lqbvtwide0ngdev54adgc0lu))/TripPinServiceRW/");
            }).AddProperty("User-Agent", "ODataClientFactory-Sample");
</code> 

Please let me know if this solves your issue.

**Comment by dcadlereii** [comment]
@ElizabethOkerio yes, that works. thx.
