### ISSUE TITLE
PlatformNotSupportedException on Blazor Client Side

### ISSUE THREAD

**Issue by manureini** [OData/odata.net#1784]
Hello ;)

I use the following code directly in the main method in a Blazor Client Side Projekt:

```csharp
var container = new DataServiceContext(new Uri("http://localhost:5000/api/"));   
var query = container.CreateQuery<User>("User");
 var data = query.ToAsync();
data.Wait();
var dataArray = data.Result.ToArray();
```

The ToAsync() Method is from issue #1335:
https://github.com/OData/odata.net/issues/1335#issuecomment-569089087

I assume that I need to pass a custom HttpClient somehow to the DataServiceContext, so it can work with Blazor. But I can't find a way to do it right now.

### Assemblies affected
Assembly Microsoft.OData.Client, Version=7.6.4.0

### Reproduce steps
Start the Application

### Expected result
No crash

### Actual result
System.PlatformNotSupportedException: Operation is not supported on this platform.

### Additional detail
The exception is throws by the System.Net.WebProxy.CreateDefaultProxy() method.

I think it's causes by this line:
https://github.com/OData/odata.net/blob/182964dd4de0d9271d7e749ff3afde898430326c/src/Microsoft.OData.Client/Serialization/HttpWebRequestMessage.cs#L486

Stacktrace:

<details>

> 
> blazor.webassembly.js:1   at PIS.Program.Main (System.String[] args) [0x00059] in C:\GitHub\pis\PIS\PIS\Program.cs:24 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint (System.String assemblyName, System.String[] args) <0x2ecce88 + 0x0012c> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 ---> (Inner Exception #0) System.PlatformNotSupportedException: Operation is not supported on this platform.
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.WebProxy.CreateDefaultProxy () <0x31c1a10 + 0x00008> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetSystemWebProxy () <0x31c1778 + 0x00000> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetDefaultProxy_UsingOldMonoCode () <0x31c16d0 + 0x00000> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetSection () <0x31c14d0 + 0x0002a> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.WebRequest.get_InternalDefaultWebProxy () <0x31c1218 + 0x00034> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.HttpWebRequest..ctor (System.Uri uri) <0x31bcbd0 + 0x000b6> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.HttpRequestCreator.Create (System.Uri uri) <0x31bc210 + 0x00004> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.WebRequest.Create (System.Uri requestUri, System.Boolean useUriBase) <0x31aaff8 + 0x00116> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Net.WebRequest.Create (System.Uri requestUri) <0x31aac20 + 0x00024> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.HttpWebRequestMessage.CreateRequest (System.String method, System.Uri requestUrl, Microsoft.OData.Client.DataServiceClientRequestMessageArgs args) <0x31b3d48 + 0x00006> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.HttpWebRequestMessage..ctor (Microsoft.OData.Client.DataServiceClientRequestMessageArgs args) <0x31b3780 + 0x0006e> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.DataServiceClientFormat.LoadServiceModelFromNetwork () <0x318edb0 + 0x00128> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.DataServiceClientFormat.get_ServiceModel () <0x317c1c0 + 0x0003c> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.RequestInfo..ctor (Microsoft.OData.Client.DataServiceContext context) <0x317be48 + 0x00068> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult (System.Object source, Microsoft.OData.Client.DataServiceContext context, System.AsyncCallback callback, System.Object state, System.String method) <0x316c7e0 + 0x00024> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.DataServiceRequest.BeginExecute (System.Object source, Microsoft.OData.Client.DataServiceContext context, System.AsyncCallback callback, System.Object state, System.String method) <0x3164750 + 0x00018> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.OData.Client.DataServiceQuery`1[TElement].BeginExecute (System.AsyncCallback callback, System.Object state) <0x3164548 + 0x0005a> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at PIS.Extensions.ToAsync[T] (System.Linq.IQueryable`1[T] query) [0x00054] in C:\GitHub\pis\PIS\PIS\Extensions.cs:22 <---
> 

</details>

**Comment by mikepizzo** [comment]
See also #1786

**Comment by victorperez2911** [comment]
Hi @xuzhg 

Any news on this?

**Comment by tomasfabian** [comment]
WebRequest.Create is used in several places, This throws PlatformNotSupportedException, too: 
```C#
await dataServiceContext.SaveChangesAsync();
```

**Comment by tomasfabian** [comment]
I have good news! I found this package `Microsoft.OData.Extensions.Client` and thanks to it I was able to intercept `dataServiceContext.Configurations.RequestPipeline.OnMessageCreating `:

```C#
var httpClient = new HttpClient {BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)};

builder.Services.AddTransient(sp => httpClient);

builder.Services.AddODataClient().AddHttpClient(httpClient);
```
```C#
var dataServiceContext = ClientFactory.CreateClient<ODataServiceContext>(NavigationManager.ToAbsoluteUri("/"));
```

This works with GeneratedEdmModel, now I have to figure out how to call this asynchronously in WASM:
```C#
Format.LoadServiceModel = () => GetServiceModel(GetMetadataUri());
```
```C#
    //public async Task<IEdmModel> GetServiceModel(Uri metadataUri)
    public IEdmModel GetServiceModel(Uri metadataUri)
    {
      var stream = httpClient.GetStreamAsync(metadataUri).Result; //System.Threading.SynchronizationLockException: Cannot wait on monitors on this runtime.

      //var stream = await httpClient.GetStreamAsync(metadataUri);

      using (var reader = XmlReader.Create(stream))
      {
        return CsdlReader.Parse(reader);
      }

      // this works in NETCOREAPPs
      //var request = WebRequest.CreateHttp(metadataUri);

      //using (var response = request.GetResponse())
      //using (var stream = response.GetResponseStream())
      //using (var reader = XmlReader.Create(stream))
      //{
      //  return Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
      //}
    }
```
Any ideas? 

@odero, @mikepizzo, @mumbi-o  what do you think about this solution? Maybe an async version of `LoadServiceModel` will be needed. 

Thank you Tomas Fabian

**Comment by tomasfabian** [comment]
As a "work around" I'm pre-fetching IEdmModel in `Program.Main` and injecting it into `DataServiceContext`.

**Comment by LeroyK** [comment]
Looks like Microsoft.OData.Extensions.Client 1.0.1 is not compatible with Microsoft.OData.Client 7.7.0, because abstract properties were added to DataServiceClientRequestMessage. The major version number of Microsoft.OData.Client should have been increased instead of the minor version number, since this is a breaking API change.

**Comment by tomasfabian** [comment]
I wasn't able to use constructor injection for injecting dependencies into DataServiceContext, because `DefaultODataClientActivator.CreateClient<T>` uses:
```C#
T instance = (T) Activator.CreateInstance(typeof (T), (object) serviceRoot);
```

@LeroyK Ouch I originally tried it with Microsoft.OData.Client 7.6.4. With version 7.7.0 it throws the following exception:

_Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Type Microsoft.OData.Extensions.Client.HttpClientRequestMessage has invalid vtable method slot 12 with method none
System.TypeLoadException: Type Microsoft.OData.Extensions.Client.HttpClientRequestMessage has invalid vtable method slot 12 with method none
  at Microsoft.OData.Client.RequestInfo.CreateRequestMessage (Microsoft.OData.Client.BuildingRequestEventArgs requestMessageArgs) <0x459b258 + 0x00148> in <filename unknown>:0 
  at Microsoft.OData.Client.ODataRequestMessageWrapper.CreateRequestMessageWrapper (Microsoft.OData.Client.BuildingRequestEventArgs requestMessageArgs, Microsoft.OData.Client.RequestInfo requestInfo) <0x459a9a0 + 0x0000e> in <filename unknown>:0 
  at Microsoft.OData.Client.ODataMessageWritingHelper.CreateRequestMessage (Microsoft.OData.Client.BuildingRequestEventArgs requestMessageArgs) <0x459a468 + 0x0000a> in <filename unknown>:0 
  at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult (System.Object source, Microsoft.OData.Client.DataServiceContext context, System.AsyncCallback callback, System.Object state, System.String method) <0x4580b00 + 0x00192> in <filename unknown>:0 
  at Microsoft.OData.Client.DataServiceRequest.BeginExecute (System.Object source, Microsoft.OData.Client.DataServiceContext context, System.AsyncCallback callback, System.Object state, System.String method) <0x457b940 + 0x00016> in <filename unknown>:0 
  at Microsoft.OData.Client.DataServiceQuery`1[TElement].BeginExecute (System.AsyncCallback callback, System.Object state) <0x457b728 + 0x00060> in <filename unknown>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncImpl (System.Func`3[T1,T2,TResult] beginMethod, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) <0x457b048 + 0x00188> in <filename unknown>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsync (System.Func`3[T1,T2,TResult] beginMethod, System.Func`2[T,TResult] endMethod, System.Object state) <0x457a9c0 + 0x00014> in <filename unknown>:0 
  at Microsoft.OData.Client.DataServiceQuery`1[TElement].ExecuteAsync () <0x457a1f8 + 0x0002c> in <filename unknown>:0 
  at_

**Comment by victorperez2911** [comment]
I noticed that version 7.7.0 of this library, this error no longer happens.

**Comment by rahul7720** [comment]
> I noticed that version 7.7.0 of this library, this error no longer happens.

It happens in Version 7.7.1
https://github.com/OData/Extensions/issues/46

**Comment by victorperez2911** [comment]
Hello

I don't know if it's something I haven't done correctly yet, but I still have the same exception in version 7.8.1 of the Package.

I'm testing on a fresh app, using Blazor Wasm .NET 5.0.

![image](https://user-images.githubusercontent.com/11770654/103035302-cc71c480-4545-11eb-8959-5c2692437d17.png)

![image](https://user-images.githubusercontent.com/11770654/103035223-a2b89d80-4545-11eb-95bf-1eda8a3489dc.png)

```C#
    private async Task IncrementCount()
    {
        
        Default.Container container = CosmosProODataServiceClientFactory();

        var Teste = container.USUARIOS_CLIENTE.FirstOrDefault();

    }

 private static Default.Container CosmosProODataServiceClientFactory()
    {
        var ODataUrl = new Uri("https://{serverAdress}/odata");

        Default.Container container = new Default.Container(ODataUrl);

        container.BuildingRequest += Container_BuildingRequest;
        container.SendingRequest2 += Container_SendingRequest2;
        container.ReceivingResponse += Container_ReceivingResponse;


        return container;

    }

private static void Container_BuildingRequest(object sender, Microsoft.OData.Client.BuildingRequestEventArgs e)
    {
        e.Headers.Add("Authorization", "Bearer f7b15b4c-5d45-eb11-841a-00155d0cb303");
        e.Headers.Add("api-version", "1.0");
    }

```
![image](https://user-images.githubusercontent.com/11770654/103035430-0f339c80-4546-11eb-8456-67c6d08f876b.png)

Has anyone had the same problem?

@ElizabethOkerio

**Comment by tomasfabian** [comment]
I had the same issue. I found out that you can solve it by overriding the default WebRequest mode in this way
```C#
  public class ODataServiceContext : DataServiceContext
  {
    public ODataServiceContext(Uri serviceRoot)
      : base(serviceRoot, ODataProtocolVersion.V4)
    {
      HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;
    }
  }
```

**Comment by victorperez2911** [comment]
tks @tomasfabian

In my test app, I Changed my container factory to this.

```C#
 private Default.Container CosmosProODataServiceClientFactory()
    {
        var ODataUrl = new Uri("https://portal.cosmospro.com.br:9191/odata");

        Default.Container container = new Default.Container(ODataUrl);

        container.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;

        container.BuildingRequest += Container_BuildingRequest;
        //container.SendingRequest2 += Container_SendingRequest2;
        //container.ReceivingResponse += Container_ReceivingResponse;


        return container;

    }
```

And the error change to "Cannot wait on monitors on this runtime."

![image](https://user-images.githubusercontent.com/11770654/103311823-21a44f00-49fa-11eb-824e-62ed87b6ba7f.png)

**Comment by TaylorWatson** [comment]
Hello, this looks like the SVG loading is causing WASM to freak out. I'll look into pulling the SVG another way and push a fix.
