### ISSUE TITLE
Extra Properties not advertised in Metadata if added to Payload are not serialized unless it is exposed as OpenType

### ISSUE THREAD

**Issue by hotchandanisagar** [OData/odata.net#179]
11.4.1.3 Handling of Properties Not Advertised in Metadata
Clients MUST be prepared to receive additional properties in an entity or complex type instance that are not advertised in metadata, even for types not marked as open. By using PATCH when updating entities, clients can ensure that such properties values are not lost if omitted from the update request. 
 
Possible workaround was to do disable the EnableFullValidation setting but ciurrently wouldn’t enable you to add extra properties to payload during serialization.

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs#L190 
For now, only open type would allow extra properties in serialization.
 
There does not seem to be support in the ODL and WebAPI.

**Comment by karataliu** [comment]
@hotchandanisagar  Thanks for the investigation. 

I think you've got the right [place] (https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/JsonLight/ODataJsonLightPropertySerializer.cs#L190), looks like we can check EnableFullValidation flag and bypass such validation here. Would you please send a pull request for this?

**Comment by congysu** [comment]
The PR https://github.com/OData/odata.net/pull/218.
