### ISSUE TITLE
How do I get rid of the address here

### ISSUE THREAD

**Issue by ClementeGao** [OData/odata.net#1804]
![image](https://user-images.githubusercontent.com/16145998/84113072-7bdcc300-aa5c-11ea-844c-bfa292977a52.png)

**Comment by xuzhg** [comment]
1) OData context URI is the important part of the response.
You can set the base address to replace the context uri address.

2) If you do not want the context URI in the payload, you can use the `odata.metadata=none`.

**Comment by xuzhg** [comment]
@ClementeGao Does your problem get resolved? Would you please leave some comments that can help us with the same questions?
