### ISSUE TITLE
update the OptionalParameterTerm to use namespace alias

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#1818]
OData spec says:

5.1 Alias
A schema MAY specify an alias which MUST be a simple identifier.

If a schema specifies an alias, the alias MUST be used instead of the namespace within qualified names throughout the document to identify model elements of that schema. A mixed use of namespace-qualified names and alias-qualified names is not allowed.

So, the metadata like "https://github.com/OData/odata.net/blob/c6876f23b78f21407aedeb7e2d985b117d04d3f3/test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs#L475" should use "Core" alias for the "Org.OData.Core.V1", if we define the "Core" as alias for "Org.OData.Core.V1".

**Comment by ElizabethOkerio** [comment]
was fixed by this PR: https://github.com/OData/odata.net/pull/2159
