### ISSUE TITLE
Retrieving metadata / schema for query

### ISSUE THREAD

**Issue by mvklingeren** [OData/odata.net#183]
I'm writing a client that queries a OData source, but after receiving the data for the query, i would like to store it in a (relational, sql) database.

Is it possible to only get the metadata for the query i'm making (instead of whole the EDMX)?

Would it be possible, to get only the information needed, ie:
http://services.odata.org/V4/northwind/northwind.svc/$metadata?('Customers?$select=CustomerID')

**Comment by karataliu** [comment]
@mvklingeren
Please also refer to https://github.com/OData/odata.net/issues/181 , this is called Metadata Service in OData spec. ODataLib hasn't supported it yet, and we've put It into backlog.

**Comment by mvklingeren** [comment]
I did find that part in the specs but the ~/metadata/$metadata confused me..

Thank you. This item can now be closed.

**Comment by congysu** [comment]
@mvklingeren Thank you for reporting the issue.  Your contribution is very welcome, e.g., a pull request to the work item #88, or #181.
