### ISSUE TITLE
Avoid extra allocation in Microsoft.OData.Json.JsonReader.ConsumeTokenToString(int)

### ISSUE THREAD

**Issue by aozeng-MS** [OData/odata.net#1845]
[Microsoft.OData.Json.JsonReader.ConsumeTokenToString(int)](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonReader.cs#L1225) is allocates a new string that will be appended to a StringBuilder.

The extra allocation can be avoided by directly copy the string to the StringBuilder via StringBuilder.Append(char[]? value, int startIndex, int charCount).

This change would reduce a non-trivial amount of LOH allocations for our service.

### Assemblies affected

 Microsoft.OData.Core.dll, Versions larger than or equal to 6.10.0.

### Reproduce steps
N/A
### Expected result

Less LOH allocations and smaller memory footprint. For our specific scenario, a 15% reduction in LOH allocation is expected.

### Actual result
N/A
### Additional detail
N/A

**Comment by Sreejithpin** [comment]
Great Itea, thanks. Would you like to contribute to Odata by creating a new ConsumeTokenToStringBuilder method which used stringbuilder and appends to existing stringbuilder? Will be happy to help you to set up if you would like to contribute, else we can put it in our backlog and work on it.

**Comment by aozeng-MS** [comment]
I am working on a PR but am having some issues with running the build.cmd script. Would love to get help for setting up.
Thanks!

**Comment by Sreejithpin** [comment]
Sure, Are you able to build the project from visual studio without build.cmd ?
Let me know when you are free to sit and we can do that
