### ISSUE TITLE
ODataError.ToString() method outputs JSON that is not compliant with OData spec

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#1850]
ODataError.ToString() method outputs JSON that is not compliant with OData spec

### Assemblies affected

Microsoft.OData.Core, Version=7.6.4.0

### Reproduce steps

The following code
`
var error = new ODataError(){ Message = "Error" };
var json = error.ToString();
`

outputs the following JSON:

{"error":{"code":"","message":"Error","target":"","details":{},"innererror":{} }}

Note that empty "details" property is written as an object but according to OData spec (and ODataError class) it is an array. The _ODataMessageReader_ fails to read such error payloads.

### Expected result
Empty OData error details property is serialized as JSON array.

```json
{
  "error": {
    "code": "error code",
    "message": "Unsupported functionality",
    "target": "query",
    "details": [
      {
        "code": "",
        "target": "target",
        "message": "message"
      }
    ],
    "innererror": {
      "trace": [],
      "context": {}
    }
  }
}
```
### Actual result

*What is actually happening.*
```json
{"error":{"code":"","message":"Error","target":"","details":{},"innererror":{} }}
```

**Comment by marabooy** [comment]
@korygin This is a known issue that will be fixed in a future major  release. The main issue tracking this behavior is https://github.com/OData/odata.net/issues/1421 so allow me to close this as a duplicate.
