### ISSUE TITLE
Method 'get_Timeout' in type 'Microsoft.OData.Extensions.Client.HttpClientRequestMessage' from assembly 'Microsoft.OData.Extensions.Client, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.":"Microsoft.OData.Extensions.Client.HttpClientRequestMessage"}

### ISSUE THREAD

**Issue by UM001** [OData/odata.net#1856]
I get after upgrade 7.6.4 to 7.7.0 this error:

Method 'get_Timeout' in type 'Microsoft.OData.Extensions.Client.HttpClientRequestMessage' from assembly 'Microsoft.OData.Extensions.Client, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.":"Microsoft.OData.Extensions.Client.HttpClientRequestMessage"}

I have also seen this issue here:
https://github.com/OData/Extensions/issues/42

**Comment by xuzhg** [comment]
@UM001 I'd like to update you that the OData/Extensions#42 got resolved after merging the PR at: https://github.com/OData/Extensions/pull/43.  So far, the fix is not in the official release.

**Comment by UM001** [comment]
Still have the problem in 7.7.1. But fixed it with:

`            services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies().Where(x => x.FullName.Contains("MyName")));
            //^$TO-DO: might be optimized for only own assemblies`

**Comment by UM001** [comment]
Sorry, issue is still there in 7.7.1. Reverting back again to 7.6.4

**Comment by HugzM** [comment]
I confirm issue is still there in 7.7.2 any update on when this is supposed to be fixed ?

**Comment by ElizabethOkerio** [comment]
@UM001  and @HugzM  this works fine in v 1.0.6 of the extension. Please update the extension and let us know. Also feel free to reopen the issue if the issue persists.
