### ISSUE TITLE
$metadata endpoint not found when AddService<IEdmModel> used on MapODataRoute

### ISSUE THREAD

**Issue by alexej-fuss** [OData/odata.net#1861]
I need to generate a EdmModel on each request, based on ClaimsPrincipal. After some tests i figured out. that the http request to $metadata endpoint returns 404.

### Assemblies affected

    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.1" />
    <PackageReference Include="Microsoft.OData.Core" Version="7.7.0" />

### Reproduce steps

Create netcoreapp3.1 Api

public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddControllers();
            services.AddOData();
        }

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
           
            app.UseRouting();
           app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.EnableDependencyInjection();
                endpoints.Count().Filter().OrderBy().Expand().Select().MaxTop(int.MaxValue);
                //endpoints.MapODataRoute("odata", "api", GetEdmModel(app.ApplicationServices)); --> works
                endpoints.MapODataRoute("odata", "api", odataBuilder =>
                {
                    odataBuilder.AddService<IEdmModel>(Microsoft.OData.ServiceLifetime.Singleton, sp => GetEdmModel(app.ApplicationServices)); // --> http  404
                });

            });
        }

        private IEdmModel GetEdmModel(IServiceProvider applicationServices)
        {
  
            var builder = new ODataConventionModelBuilder(applicationServices);
            var model = builder.GetEdmModel();
            return model;
        }
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result
request to $metadata endpoint returns model
http://localhost:43333/api/$metadata

<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container" />
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>

*What would happen if there wasn't a bug.*

### Actual result

http://localhost:43333/api/$metadata
HTTP ERROR 404

**Comment by xuzhg** [comment]
@alexej-fuss 

Internally, The working version as  `//endpoints.MapODataRoute("odata", "api", GetEdmModel(app.ApplicationServices)); --> works` is because the routing convention is registered also, see the following code snippet:

```C#
public static ODataRoute MapODataServiceRoute(this IRouteBuilder builder, string routeName,
            string routePrefix, IEdmModel model)
        {
            return builder.MapODataServiceRoute(routeName, routePrefix, containerBuilder =>
                containerBuilder.AddService(Microsoft.OData.ServiceLifetime.Singleton, sp => model)
                       .AddService<IEnumerable<IODataRoutingConvention>>(Microsoft.OData.ServiceLifetime.Singleton, sp =>
                           ODataRoutingConventions.CreateDefaultWithAttributeRouting(routeName, builder)));
        }
```

So, if you copy `.AddService<IEnumerable<IODataRoutingConvention>>(Microsoft.OData.ServiceLifetime.Singleton, sp =>
                           ODataRoutingConventions.CreateDefaultWithAttributeRouting(routeName, builder)))` into your "not working" version, i think it should work as expected.

Let me know if that can't work.

**Comment by alexej-fuss** [comment]
@xuzhg 

yes, this line helps: 
`AddService(Microsoft.OData.ServiceLifetime.Singleton, (Func<IServiceProvider, IEnumerable<IODataRoutingConvention>>)((IServiceProvider sp) => ODataRoutingConventions.CreateDefaultWithAttributeRouting(routeName, builder.ServiceProvider)));`

my final configuration looks like:

 `
app.UseEndpoints(endpoints =>

            {
                endpoints.MapControllers();
                endpoints.EnableDependencyInjection();
                endpoints.Count().Filter().OrderBy().Expand().Select().MaxTop(int.MaxValue);
                endpoints.MapODataRoute("odata", "api", odataBuilder =>
                {
                    odataBuilder.AddService<EdmModelBuilder>(Microsoft.OData.ServiceLifetime.Singleton);
                    odataBuilder.AddService<IEdmModel>(Microsoft.OData.ServiceLifetime.Scoped,
                        serviceProvider =>
                        {
                            var httpRequestScope = serviceProvider.GetRequiredService<HttpRequestScope>();
                            return  serviceProvider.GetService<EdmModelBuilder>().GetEdmModel(app.ApplicationServices, httpRequestScope.HttpRequest.HttpContext.User);
                        });
                    odataBuilder.AddService<IEnumerable<IODataRoutingConvention>>(Microsoft.OData.ServiceLifetime.Singleton, sp => ODataRoutingConventions.CreateDefaultWithAttributeRouting("odata", endpoints.ServiceProvider));
                });
            });
`
Thanks!
