### ISSUE TITLE
Add Microsoft.OData.Client.Portable.csproj to *.Full.sln

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#187]
Consider to add Microsoft.OData.Client.Portable.csproj to the *.Full.sln
For now, the *.Full.sln does not include this project:
https://github.com/OData/odata.net/blob/master/sln/Microsoft.OData.Full.sln

**Comment by lewischeng-ms** [comment]
This project has already been contained in Microsoft.OData.CodeGen.sln and is not dependency of any projects in Microsoft.OData.Full.sln.
