### ISSUE TITLE
ExpandBinder throws on $expand ending in fully qualified type

### ISSUE THREAD

**Issue by kmcinnomate** [OData/odata.net#1870]
When using a URL with an $expand that ends in a fully qualified type name, similar to example 40 from [OData Version 4.01. Part 2: URL Conventions](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html) - i.e. http://host/service/Orders?$expand=Customer/Model.VipCustomer - the ExpandBinder throws an ODataException.

As the conventions state: "For to-many relationships only Model.VipCustomer instances would be inlined" for this example. So it should be valid.

### Assemblies affected

Microsoft.OData.Core 7.7.1 and earlier

### Reproduce steps

Add this test to ExpandBinderTests.cs:

```
        [Fact]
        public void BindingOnTreeWithWithTypeTokenDoesNotThrow()
        {
            // Arrange: $expand=MyPeople/Fully.Qualified.Namespace.Employee
            NonSystemToken innerSegment = new NonSystemToken("Fully.Qualified.Namespace.Employee", null, null);
            NonSystemToken navProp = new NonSystemToken("MyPeople", null, innerSegment);
            ExpandToken expandToken = new ExpandToken(new ExpandTermToken[] { new ExpandTermToken(navProp) });

            // Act & Assert
            var binderForDog = new SelectExpandBinder(this.V4configuration, new ODataPathInfo(HardCodedTestModel.GetDogType(), null), null);
            var result = binderForDog.Bind(expandToken, null);
        }

```

### Expected result

The test would run successfully (even though it doesn't assert anything useful).

### Actual result

The test throws this exception:

```
  Message: 
    Microsoft.OData.ODataException : Found a path traversing multiple navigation properties. Please rephrase the query such that each expand path contains only type segments and navigation properties.
  Stack Trace: 
    SelectExpandBinder.GenerateExpandItem(ExpandTermToken tokenIn) line 362
    SelectEnumerableIterator`2.MoveNext()
    WhereEnumerableIterator`1.MoveNext()
    List`1.InsertRange(Int32 index, IEnumerable`1 collection)
    List`1.AddRange(IEnumerable`1 collection)
    SelectExpandBinder.Bind(ExpandToken expandToken, SelectToken selectToken) line 120
    ExpandBinderTests.BindingOnTreeWithWithTypeTokenDoesNotThrow() line 45

```

**Comment by xuzhg** [comment]
@gathogojr This is the feature gap that we should fix it.

**Comment by adixon501** [comment]
Any updates on this bug?

**Comment by adixon501** [comment]
@mikepizzo any news on this bug?
