### ISSUE TITLE
OData library doesn't honor Prefer header send as "prefer"

### ISSUE THREAD

**Issue by sshriyansh** [OData/odata.net#1882]
**Description of the issue**
When request headers containing prefer header is passed as "prefer"(not "Prefer") to the extension method of IODataRequestMessage class, and then if it is used to get the MaxPage size using object o of implemetation class of `IODataRequestMessage` as shown below:-
`int maxPagesize =  o.PreferHeader().MaxPageSize`, then it returns null. However when the header is changed to "Prefer", it works as expected.

**Expections** 
Headers are case-insensitive and OData library should honour the PreferHeader in any case. It shouldn't expect them to work in a particular format.

**Comment by Sreejithpin** [comment]
Thanks for raising this issue. We will investigate and fix the 'prefer' and other headers that are case sensitive
