### ISSUE TITLE
Performance: OData.metadata=full is very CPU intensive

### ISSUE THREAD

**Issue by joaocpaiva** [OData/odata.net#1885]
Recently found a large increase in CPU in one of our DCs and root caused that to requests that accept odata.metadata=full.

The number of requests with odata.metadata=full increased from 1.13% to 3.4% and as result, the CPU cost of Microsoft.OData.ODataWriterCore!WriteEnd jumped exponentially from ~1.3% to ~13.5%. This is a huge increase.

If more clients started requesting odata.metadata=full that would quickly blow up the service costs.

### Assemblies affected
Microsoft.OData.ODataWriterCore.dll 7.7.1

### Reproduce steps
Multiple requests with odata.metadata=full. Incoming URI and other details provided offline.

### Expected result
CPU cost should grow linearly, in the worst case.

### Actual result
CPU cost grows exponentially, which suggests opportunity to significantly optimize this code path.

![image](https://user-images.githubusercontent.com/24846248/93276758-50f9bd80-f775-11ea-8a10-856980dff3b2.png)

**Comment by gathogojr** [comment]
Fixed by [1888](https://github.com/OData/odata.net/pull/1888)
