### ISSUE TITLE
An unknown function with name 'matchesPattern' was found

### ISSUE THREAD

**Issue by StefanoVuerich** [OData/odata.net#1901]
I'm using Microsoft.AspNet.OData.

I'm trying to use $filter=matchesPattern(Property, '%pattern%') but I'm receiving Exception: Microsoft.OData.ODataException: 'An unknown function with name 'matchesPattern' was found. This may also be a function import or a key lookup on a navigation property, which is not allowed.'

Is 'matchesPattern' function not supported?

It is a [specification ](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_matchesPattern)of OData v4 protocol

**Comment by marabooy** [comment]
@StefanoVuerich Thank you for reporting this, This would be a great feature to have and we would like to welcome  any contributions if you are open to contribute.

**Comment by Arithmomaniac** [comment]
I am willing to take this PR in my spare time (#OneMicrosoft), as it's a prerequisite for working on https://github.com/OData/AspNetCoreOData/issues/331 .
