### ISSUE TITLE
 Looking for a recent and Working Example of oData v4 client against oData v3 API

### ISSUE THREAD

**Issue by DanRegalia** [OData/odata.net#1909]
I'm building a .net core Console app in C# against a v3 API. The goal is to add the $metadata to the project via a connected service (done), then query it..  I have an authentication system that is used that requires a username, pw and api code, that creates a token that I can use to query the data on the server. 

When I download the new .net client, and look for anything relevant to .net core 3.1, there is nothing out there.  The documentation sites are between 3 and 6 years old, and doesn't line up to current development platforms.

I'm pretty much lost.  I can get the service reference added, resources.cs builds out, but after that, nothing in the interfaces for VS2019 matches anything on the Microsoft website when it comes to making a client that will allow me to do a simple query into a datatable against a table resource in the API. 

At this point, any help is appreciated.  A link to a relevant resource would be amazing, a sample application would be magnificent.

**Comment by ElizabethOkerio** [comment]
@DanRegalia https://docs.microsoft.com/en-us/odata/connectedservice/getting-started. Please let us know whether this document is of help to you.

**Comment by KenitoInc** [comment]
@DanRegalia Did the link to the doc solve your issue?

**Comment by KenitoInc** [comment]
Closing this due to inativity
