### ISSUE TITLE
vanilla dotnet core 3.1 project with Microsoft.OData.Edm requires explicit package reference to System.Text.Json

### ISSUE THREAD

**Issue by chrisspre** [OData/odata.net#1918]
A vanilla dotnet core project 

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.OData.Edm" Version="7.7.2" />
  </ItemGroup>
</Project>
```
will fail to compile with error:

```
Assembly 'Microsoft.OData.Edm' with identity 'Microsoft.OData.Edm, Version=7.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Text.Json' with identity 'System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 
```

That seems to indicate that netcoreapp3.1 is implicitly referencing `System.Text.Json 4.0.1.0` but `Microsoft.OData.Edm` requires `4.0.1.2`

### Assemblies affected

Microsoft.OData.Edm 7.7.2

### Reproduce steps

- create new netcoreapp3.1 console project `dotnet new console`
- add package reference dotnet add package Microsoft.OData.Edm
- build `dotnet build`

### Additional detail

This can be easily fixed by adding an explicit reference to System.Text.Json but the out of box experience is suboptimal.

**Comment by xuzhg** [comment]
@chrisspre "<PackageReference Include="Microsoft.OData.Edm" Version="7.7.2" />" is necessary in your project? 

You don't need that in .csproj, right?

**Comment by chrisspre** [comment]
Sam, not sure I understand the question. To which "" are you referring?

The problematic .csproj has only one PackageReference , the one to Microsoft.OData.Edand and that creates the error.
Adding a second PackageReference to System.Text.Json version 4.0.1.2 fixes it. But that seems suboptimal to me.

**Comment by xuzhg** [comment]
@chrisspre Oh, I mis-took the "Edm" lib as "Text.Json“ lib. 

For "System.Text.Json" version, it's known issue, and I also investigated and had a PR to fix that, see detail at: https://github.com/OData/odata.net/pull/1880

It seems that PR can't fix it?  Do you have other recommendation?

**Comment by xuzhg** [comment]
@chrisspre As i tested, 
if i target on .net 5, it doesn't output error. 

`<TargetFramework>net5.0</TargetFramework>`

if i target on .netcoreapp3.1, it shows the error.

`<TargetFramework>netcoreapp3.1</TargetFramework>`

Can you test it and give me a update?

**Comment by chrisspre** [comment]
Yes, I can confirm 
With <TargetFramework>net5.0</TargetFramework> and only <PackageReference Include="Microsoft.OData.Edm" Version="7.7.2" />  no problem

With  <TargetFramework>netcoreapp3.1</TargetFramework> and only <PackageReference Include="Microsoft.OData.Edm" Version="7.7.2" />  error CS1705:

Adding  <PackageReference Include="System.Text.Json" Version="4.7.2" /> to the later fixes the error. 

installed versions:  5.0.100-rc.1.20452.10 and 3.1.403

**Comment by xuzhg** [comment]
@chrisspre Would you please confirm that "Microsoft.OData.Edm 7.7.2-Nightly202011111838" is working at your side for .NET Core APP 3.1

Here's the feed for nightly :  https://www.myget.org/F/odlnightly/api/v3/index.json

**Comment by chrisspre** [comment]
I can confirm 7.7.2-Nightly202011111838 works fine without the additional `<PackageReference Include="System.Text.Json" Version="4.7.2" />` on both frameworks.
