### ISSUE TITLE
ODataComplexValue replacement !

### ISSUE THREAD

**Issue by ve9u** [OData/odata.net#1947]
`ODataComplexValue` removed from 7.X version. I am going through the docs and I got confused because, 

in [this ](https://docs.microsoft.com/en-us/odata/odatalib/merge-complex-and-entity) article `ODataResource` suggested as replacement.

```c#
   ODataResource complexResource = new ODataResource()
    {
        Properties = new ODataProperty[]
        {
            new ODataProperty { Name = "Address", Value = "Zixing Road" },
            new ODataProperty { Name = "City", Value = "Shanghai" }
        }
    };

    writer.WriteStart(complexResource);
    writer.WriteEnd();
```

in [this](https://docs.microsoft.com/en-us/odata/odatalib/resource-value) proposal it is mentioned that `ODataResourceValue` could be the replacement.

Could anybody help me to understand the best alternative for `ODataComplexValue`?

**Comment by xuzhg** [comment]
@ve9u Yes, that's a little bit confusing. 

in [this](https://docs.microsoft.com/en-us/odata/odatalib/resource-value) proposal, it's the original design that we want to give a customer an alternative way to replace "ODataResource" if that resource doesn't have the “navigation property". However, for some reasons, the finial design changed. 

Now, "ODataResourceValue" is limit to use in OData instance annotation. For the payload, please use "ODataResource".

**Comment by ve9u** [comment]
Thanks a lot for the response.
