### ISSUE TITLE
Update nuspec for nightly/vNext

### ISSUE THREAD

**Issue by karataliu** [OData/odata.net#196]
1. Currently nightly build version is 6.12.0-beta-Nightly20150518, which is incorrect, should be 6.12.0-Nightly20150518.
2. For vNext, should use following approach for defining dependencies:

``` xml
<group targetFramework="DNX4.5.1">
```

**Comment by lewischeng-ms** [comment]
@karataliu where did you find this name? `DNX4.5.1`

**Comment by karataliu** [comment]
Please refer to the nuspec files under .dnx\packages, such as EntityFramework/Microsoft.AspNet.Http.
