### ISSUE TITLE
Keeping production available

### ISSUE THREAD

**Issue by mvklingeren** [OData/odata.net#198]
is Odata.net able to handle large ammounts of traffic via the odata uri's
while keeping the application online, and the DB (im using EF) stays available?

If it's able to do this; how does it do this?

**Comment by congysu** [comment]
@mvklingeren Can you elaborate your user scenario more?  Thanks.

**Comment by mvklingeren** [comment]
@congysu if we're running heavy queries on the production DB, to extract large amounts of data (gigabytes) in a automated way.

Does odata.net / mvc prfioritize requests, traffic, so our application continues to work? >> and if it does, how does this work internally?

**Comment by xuzhg** [comment]
@mvklingeren  Do you still need help? Are we ok to close this issue?

**Comment by mvklingeren** [comment]
@xuzhg yes, after 4years - that's ok!
