### ISSUE TITLE
How to Hide Odata Meta Data in root url of OData API

### ISSUE THREAD

**Issue by tespheakdeyesoftix** [OData/odata.net#1986]
Hi,
Is this possible to hide all available API endpoint in our Odata api?
For example:
After we run odata server then enter our api url to browser address bar like this:

http://localhost:18739/api

then it will show list of our endpoint that we set Edm Model builder.

{"@odata.context":"http://localhost:18739/api/$metadata","value":[{"name":"Student","kind":"EntitySet","url":"Student"}]}

We don't want public user to see it for some reasons.

Thanks,

**Comment by gathogojr** [comment]
Based on OData protocol, the service document is exposed at the root of the service by default. You could create a routing convention where you can set it to return a NotFound or whatever you'd like to be returned if a request to the service root is made. If you'd wish to hide both the service document and the metadata, you can hide the `MetadataController` from the controller provider.
