### ISSUE TITLE
EdmModel specific namespaces in metadata

### ISSUE THREAD

**Issue by xpr0gamers** [OData/odata.net#2001]
For a specific scenario (connect SAP UI5 SmartTable with Odata Metadata) I need to define annotations to properties of an entity type. 
```C#
var oProp = ((EdmEntityType)oModel.FindType(
  typeof(Mitarbeiter).Namespace + "." + nameof(Mitarbeiter))).FindProperty("Vorname");

oModel.DirectValueAnnotationsManager.SetAnnotationValue(oProp, "test", "label",
 new EdmStringConstant(EdmCoreModel.Instance.GetString(true), "Car of employees"));
```

This is the result:
![image](https://user-images.githubusercontent.com/25172624/108353401-66718880-71e8-11eb-8d52-ca046d2fd4b5.png)

Is it possible to change this result to:
**<Property .... test:label=”Car of employess” ..../>**

**Comment by mikepizzo** [comment]
Note that "DirectValue" annotations (represented as attributes in the model elemnt) are an old style of annotation (from OData V1-V2) that are not compliant with OData V4 protocol. They are still supported in the library for legacy reasons, but you should move to using OData V4 standard "Vocabulary Annotations" for standard compliance.

Do you have a reason that you need to represent these as "direct value" annotations (as xml-namespaced attributes within the element)?

**Comment by xpr0gamers** [comment]
Hello @mikepizzo ,
thank you for your answer. As frontend, I am using a website including the JavaScript sapui5 library from sap. This library has a built-in component named "Smart Table". This component analyze the metadata of a specific entity type and build on top a html table (https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable). The analyzer search for the direct value annotation "sap:label="Posting Date" and use this for the column description.

**Comment by KenitoInc** [comment]
Closing this.
Feel free to create a new issue if there are any more questions to be answered.
