### ISSUE TITLE
unable to send `$format` parameter

### ISSUE THREAD

**Issue by mikekberg** [OData/odata.net#202]
I'm consuming a service that uses the "$format" query string parameter to switch the layout of how the JSON data is returned.

I am unable to pass this parameter to the context. Using .AddQueryOption("$format", "CustomJSON") yields and error to set the format in the context object but there are no setter anywhere in the format object.

**Comment by LaylaLiu** [comment]
@mikekberg 
OData client doesn't support custom format right now. So you cannot send the request by AddQueryOption("$format", "CustomJson").
Client will consider it as an invalid media type. Even if you use response pipeline to set the media type resolver, client still fails when materializing the response payload. It will report "not supported content type" error.

**Comment by mikepizzo** [comment]
Behavior is by design, as OData Client doesn't support custom formats.
