### ISSUE TITLE
For an Odata API the DataMember name is not reflecting in the API response

### ISSUE THREAD

**Issue by Vasumithra23** [OData/odata.net#2027]
Hi,

I have a C# class called students.cs with the below property:

 **[DataMember(Name = "dept_no")]
  public byte DeptNo { get; set; }**

The problem is that I am getting DeptNo instead of dept_no in the API response.If I disable the pagesize its working fine else not. Can you help me with this issue?

Thanks.

**Comment by xuzhg** [comment]
@Vasumithra23 It seems it's duplicated in Web API repo?

**Comment by xuzhg** [comment]
Closed as duplicated https://github.com/OData/WebApi/issues/2443
