### ISSUE TITLE
If Expand("Nav($select=Prop)") is used, the request will require full metadata

### ISSUE THREAD

**Issue by dingeins** [OData/odata.net#203]
For example:

```
context.People.Expand("Trips($select=TripId)").Execute();
```

Fiddler shows that the `Accept: application/json;odata.metadata=full` header is added to the request.

Is it by design? Does it make sense to require full metadata in this case? Is the type annotation in the response necessary for materializing the response? 

Similar behavior is found when using the `AddQueryOption` API.

**Comment by mikepizzo** [comment]
Not sure why DataServiceContext is specifying full metadata for this case, but the only impact should be to performance.
