### ISSUE TITLE
EdmLib should support default values for annotations.

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#2040]
OData Vocabulary annotations support applying a term defined with a default value without specifying a value.

EdmLib requires a value be specified as part of the annotation.

### Assemblies affected

EdmLib.dll

### Reproduce steps

Terms defined with a DefaultValue (for example, "Tag" terms) do not need to specify a value when applied.  The following term, from the Core vocabulary, is such an example:
~~~xml
      <Term Name="IsURL" Type="Core.Tag" Nullable="false" DefaultValue="true" AppliesTo="Property Term">
        <Annotation Term="Core.Description" String="Properties and terms annotated with this term MUST contain a valid URL" />
        <Annotation Term="Core.RequiresType" String="Edm.String" />
      </Term>
~~~

You should be able to use the term as:

~~~xml
      <Property Name="MyHomePage" Type="Edm.String">
          <Annotation Term="IsUrl"/>
      </Property>
 ~~~

(note: there is no value specified for the annotation)

### Expected result

EdmLib should be able to parse this and return the "IsUrl" annotation with a value of "true" (taken from the DefaultValue defined for the term).

### Actual result

Error that the annotation element must have a value.

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/pull/2173
