### ISSUE TITLE
Serialization of EdmModel

### ISSUE THREAD

**Issue by StephaneMartignier** [OData/odata.net#2065]
Hi everyone,

I encountered an issue but I'm not sure if it's a bug or a known behaviour (can't find anything).

So we use the Orleans project and in one of our grain in the state we store an EdmModel. The issue is that Orleans raise an error during the serialization of the EdmModel (using Newtonsoft). So I was like, ok, let's find out what I've done wrong when buidling the Edm (it's constructed "by hand" because we don't have the models (created by users)).

To check what was happening I try to serialize the Edm myself and encountered the following :
```
Self referencing loop detected for property 'DeclaringType' with type 'Microsoft.OData.Edm.EdmEntityType'. Path 'SchemaElements[0].DeclaredKey[0]'.
```

So I was like, ok. I've done something bad and it's why the serialisation is not working, But after commenting my code to narrow the issue, I was left with the following :

```
            var model = new EdmModel();

            try
            {
                var test = JsonConvert.SerializeObject(model);
            }
            catch (Exception e)
            {
                var poney = 1;
            }

            try
            {
                var test = JsonConvert.SerializeObject(model, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
            }
            catch (Exception e)
            {
                var poney = 2;
            }
```

And it's still raising an error.
```
Self referencing loop detected for property 'Model' with type 'Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsModel'. Path 'ReferencedModels[1].SchemaElements[0]'
```
And for the second an OutOfMemory.

So I'm asking if there is a way to serialize an EdmModel to Json ? Because if it is what we can do is storing the EdmModel as string in the state of the grain and making serializaion/deserialization in the Getter/Settter.

Or maybe with Xml?

Thanks a lot for the help and the inputs :)

**Comment by StephaneMartignier** [comment]
Again, thanks for the help, I close this issue

**Comment by xuzhg** [comment]
@StephaneMartignier FYI,  CSDL JSON reader/writer API only exists in .NETStandard 2.0 or higher.

So, if you are targeting for example .NET 4.5, there's no CSDL JSON reader/writer APIs.

Here's the link for your reference:

* JSON reader: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Csdl/CsdlReader.Json.cs#L42-L55
* JSON writer: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Csdl/CsdlWriter.cs#L53-L66

**Comment by rwb196884** [comment]
Is there a way to write the `ODataServiceDocument` too?
