### ISSUE TITLE
JsonWriter does not use ICharArrayPool when writing strings

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2074]
The [JsonWriter](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs) contains an `ArrayPool` property of type [ICharArrayPool](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Buffers/ICharArrayPool.cs). It's supposed to pass this array pool to the `JsonValueUtils` `Write*` methods that write a string value. The array pool is used to rent a char buffer that's used when escaping a string or expanding binary data to base64. [If the array pool is not provided, then a new char array will be allocated instead.](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Buffers/BufferUtils.cs#L51-L65). 
The following methods in `JsonValueUtils` accept an `ICharArrayPool arrayPool` parameter:

- [WriteValue](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonValueUtils.cs#L317-L322) that accepts a `string` value
- [WriteValue](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonValueUtils.cs#L343) that accepts a `byte[]` value
- [WriteEscapedJsonString](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonValueUtils.cs#L394-L399)

We can see that the `JsonWriter` correctly passed the `ArrayPool` when writing a binary string: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs#L408

However, in the following cases, it's not passing the `ArrayPool` parameter:
- https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs#L218
- https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs#L282-L283
- https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs#L322-L323
- https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Json/JsonWriter.cs#L398

### Assemblies affected

Microsoft.OData.Core 7.x

### Reproduce steps

N/A (see linked code snippets)

### Expected result

```c#
JsonValueUtils.WriteEscapedJsonString(this.writer, name, this.stringEscapeOption, this.wrappedBuffer, this.ArrayPool);
```
```c#
JsonValueUtils.WriteValue(this.writer, value, this.stringEscapeOption, this.wrappedBuffer, this.ArrayPool);
```
### Actual result

```c#
JsonValueUtils.WriteEscapedJsonString(this.writer, name, this.stringEscapeOption, this.wrappedBuffer);
```
```c#
JsonValueUtils.WriteValue(this.writer, value, this.stringEscapeOption, this.wrappedBuffer);
```

### Additional detail

There are possibly other places where the array pool is not being used as intended, but these are the cases I stumbled upon.

I believe that array pool is meant to be an optimization to avoid memory allocations. However, since the buffer is re-used during the entire lifetime of the writer instance, and it's only used when a string needs to be escaped, this fix will probably not result in any significant performance improvement (it's also use for writing base64, but there it's already used as intended). But if the user goes through the effort of providing an array pool to the writer, we should utilize it as intended.

**Comment by gathogojr** [comment]
Fixed by #2093
