### ISSUE TITLE
Context URL does not include STAR (*) when no selectors are specified

### ISSUE THREAD

**Issue by cryogen** [OData/odata.net#2081]
*As reported in https://github.com/OData/WebApi/issues/2088, the context URL is incorrect causing issues with Excel and Power BI*

### Assemblies affected

*Microsoft.OData.Core 7.x*

### Reproduce steps

*Start the OData sample project AspNetCore3xODataSample.Web
Open Excel
Go To Data -> Get Data -> From Other Sources -> OData Feed
Enter the URL to your application http://{host}/odata/Customers?$select=Name&$expand=Order*

### Expected result

*Excel has no issue in bringing back data from the OData API*

### Actual result

*An error is shown "The odata.context url 'http://{host}/odata/$metadata#Customers(Name,Order())' is invalid"*

### Additional detail

*My interpretation of the OData specification suggests that the STAR (*) character is required when there are no selectors specified. I have a fix that I can PR if this is accepted as an issue*

**Comment by Sreejithpin** [comment]
Thanks for the issue and thanks for offering the PR. It would be great if you can put  a PR for this . Thanks again

**Comment by DaleyKD** [comment]
@cryogen : Did you ever find a work around for this? We recently updated our nugets, and it broke our customers who used our OData API for Power BI.

**Comment by cryogen** [comment]
@DaleyKD Sorry, I don't actually remember. I know that we did fix it on our end but I can't remember how and I no longer work in the job that needed this
