### ISSUE TITLE
Filter with nested values causes (condition) == true Expression when property is primitive

### ISSUE THREAD

**Issue by RodrigoRodriguesX10** [OData/odata.net#2104]
Nested filter creates an `(condition) == true` expression, which makes generated query wrong.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

I'm using OData v7.5.8

Imagine the simple scenario we have 

```cs
class Parent { public int Id { get; set; } public string Name { get; set; } }

class Child { public int Id { get; set; } public Parent Parent { get; set; } }
```

When querying over Child with ?$filter=Parent/Name+eq+'Parent' using ODataQueryOptions.ApplyTo:

```
var query = queryOptions.ApplyTo(childQueryable);
```

The DebugExpression view for Where will be:
```
.Lambda #Lambda1<System.Func`2[MyProject.Entities.Child,System.Boolean]>(MyProject.Entities.Child $$it)
{
    .If ($$it.Parent == null) {
        null
    } .Else {
        ($$it.Parent).Name
    } == .Constant<Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]>(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty
}
```
It is similar to write `.Where(c => c.Parent?.Name == "Parent")`

But when I try to make the same query for Id like ?$filter=Parent/Id+eq+10, which is primitive, the result is:

```
.Lambda #Lambda1<System.Func`2[MyProject.Entities.Child,System.Boolean]>(MyProject.Entities.Child $$it)
{
  .If ($$it.Parent == null) {
        null
    } .Else {
        (System.Nullable`1[System.Int32])($$it.Parent).Id
    } == (System.Nullable`1[System.Int32]).Constant<Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]>(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty == 
    .Constant<System.Nullable`1[System.Boolean]>(True)
}
```

It is similar to `.Where(c => (c.Parent?.Id == 10) == true)` which is a weird behavior.

This problem can causes wrong queries for ORM that has not expression fixers like NHibernate (I know that EF fixes this expression internally, but it should be a normal behavior, not a fix). The same expression occurs when you apply to a simple List<>.

### Expected result

Query without comparison for condition with True, which is redundant, expression should contains condition like non-primitive values (parent/name for example).

### Actual result

Query generate an expression with (condition) == true when the nested property is primitive

#### My own solution

I write the following expression fixer :

```cs
    public class FixBooleanWithBinaryExpressionVisitor : ExpressionVisitor
    {
        protected bool IsRecursing = false;

        public override Expression Visit(Expression node)
        {
            // top node
            if (!this.IsRecursing)
            {
                this.IsRecursing = true;
                return base.Visit(node);
            }
            if (node is BinaryExpression binExp)
                return this.VisitBinary(binExp);
            if (node?.NodeType == ExpressionType.Convert && node is UnaryExpression unExp)
                return VisitConvert(unExp);

            return base.Visit(node);
        }

        protected Expression VisitConvert(UnaryExpression node)
        {
            if (node.Operand.Type == typeof(bool) || node.Operand.Type == typeof(bool?))
                return Visit(node.Operand);
            return base.VisitUnary(node);
        }

        protected override Expression VisitBinary(BinaryExpression node)
        {
            switch (node.NodeType)
            {
                case ExpressionType.Equal:
                    var overwrite = false;
                    if (node.Left is BinaryExpression leftExp && node.Right is ConstantExpression constExp && (constExp.Value is bool || constExp.Value is bool?))
                    {
                        node = leftExp;
                        overwrite = true;
                    }
                    var left = Visit(node.Left);
                    var right = Visit(node.Right);
                    node = overwrite ? Expression.AndAlso(left, right) : Expression.Equal(left, right, false, node.Method);
                    break;
            }
            return node;
        }
    }
```

After calling ApplyTo, I can write:

```
var fix = new FixBooleanWithBinaryExpressionVisitor();
var fixedExpression = fix.Visit(query.Expression);
var newQuery = query.Provider.CreateQuery(fixedExpression);
```

**Comment by gathogojr** [comment]
Thank you @RodrigoRodriguesX10 for reporting this issue. Can you try using the `HandleNullPropagation` option on the EnableQuery attribute?

**Comment by RodrigoRodriguesX10** [comment]
> Thank you @RodrigoRodriguesX10 for reporting this issue. Can you try using the `HandleNullPropagation` option on the EnableQuery attribute?

I dont using EnableQuery attribute, just using ODataQueryOptions from action's parameter.

But calling: `queryOptions.ApplyTo(queryable, new ODataQuerySettings() { HandleNullPropagation = HandleNullPropagationOption.False })` worked for me.

Thanks
