### ISSUE TITLE
URI containing key predicate generated incorrectly for functions returning from entity sets.

### ISSUE THREAD

**Issue by RobTF** [OData/odata.net#2112]
When using the OData client against a function which returns a collection of entities from an entity set, filtering on the key property generates a URI which appears invalid.

### Assemblies affected

* 7.8.2
* 7.8.3
* 7.9.0

#### EDM Model declaration
```
var users = builder.EntitySet<Account>("Accounts")
    .EntityType
    .Function("Users")
    .ReturnsCollectionViaEntitySetPath<User>("bindingParameter");
```

#### Action methods in Web API
```
[HttpGet("Accounts({accountId})/Users()")]
[EnableQuery(PageSize = 200)]
public async Task<IQueryable<User>> UsersByAccount(Guid accountId)
{
    IQueryable<User> query = some_method_returns_iqueryable();
    return Ok(query);
}
```

#### Client code
```
public IQueryable<User> GetInAccount(Guid accountId)
{
    var keyPath = _odataContainer.Accounts.GetKeyPath(accountId.ToString());
    var account = new DataServiceQuerySingle<Account>(_odataContainer.Accounts.Context, keyPath);
    return account.CreateFunctionQuery<User>("Users", true);
}
```

#### Query
```
var accountId = Guid.NewGuid();
var userId = Guid.NewGuid();
var query = client.GetInAccount(accountId).Where(pr => pr.Id == userId);
```
This attempts to GET from `http://host/v1/Accounts(999a9d53-4d9c-41a4-8c6f-447ccd3e167b)/(b17f3486-5405-4365-bc8e-21f06a445ab2)/Users()`

Making the filter more complicated results in the predicate being promoted to a $filter which works;
e.g.
```
var accountId = Guid.NewGuid();
var userId = Guid.NewGuid();
var query = client.GetInAccount(accountId).Where(pr => pr.Id == userId || pr.Id == userId);
```
Attempts to GET from `http://host/v1/Accounts(5d09fd7f-f3c6-4d2f-92d0-2395e88b6004)/Users()?$filter=id eq 97b457fa-d06a-447e-8d24-49ea89a70606 or id eq 97b457fa-d06a-447e-8d24-49ea89a70606`

### Expected result

Unsure, something like;
`http://host/v1/Accounts(999a9d53-4d9c-41a4-8c6f-447ccd3e167b)/Users()(b17f3486-5405-4365-bc8e-21f06a445ab2)`
Or to simply always promote to $filter.

### Actual result

Invalid URI is being generated, e.g.
`http://host/v1/Accounts(999a9d53-4d9c-41a4-8c6f-447ccd3e167b)/(b17f3486-5405-4365-bc8e-21f06a445ab2)/Users()`

### Additional detail

None

**Comment by ElizabethOkerio** [comment]
@RobTF can you please share the metadata for your endpoint

**Comment by xuzhg** [comment]
@RobTF Would you please share us the metadata?

**Comment by RobTF** [comment]
Hi @xuzhg apologies I lost track of this. We changed our implementation so the metadata won't be any good now. I'll put together a base-case this week for you.

**Comment by KenitoInc** [comment]
@RobTF Is this still an issue?

**Comment by KenitoInc** [comment]
Closing this @RobTF
