### ISSUE TITLE
How to avoid exposing properties in an entity to client?

### ISSUE THREAD

**Issue by shagilt** [OData/odata.net#2116]
Say we have an entity which has property ETag. When I add this entity to EdmModelBuilder, I want to avoid adding  ETag property in the schema so that we can hide this property from client. 
We need to define this in the entity because we want to read the ETag from storage layer.
IS there a way to hide properties of an entity from client?

```
Public class PhoneEntity
{
        /// <summary>
        /// Gets or sets the ETag
        /// </summary>
        [ConcurrencyCheck]
        [DataMember]
        string ETag { get; set; }
 
        // Other properties 
}
```

**Comment by ElizabethOkerio** [comment]
@shagilt you can call ignore method to ignore property from the type if using OData WEB API..

**Comment by shagilt** [comment]
Note that our storage still has this property
If I use [Ignore], its not part of entity. In that case, how storage will read this property when it is defined in the entity?

What I want is to have a property in the entity definition but at the same time hide/remove this from property from schema.

**Comment by shagilt** [comment]
This is what I did and it worked.

Use Ignore() to remove ETAG from metadata
```
                var builder = new ODataConventionModelBuilder();
                var config = builder.EntitySet<Phone>("Phones");
                //Remove these properties in schema(hide from client).
                config.EntityType.Ignore(x => x.Etag); // Hide Etag
```

**Comment by KenitoInc** [comment]
It seems the issue was resolved
