### ISSUE TITLE
Missing enumerable reducing before caching causes major performance degradation

### ISSUE THREAD

**Issue by nsarris** [OData/odata.net#2122]
https://github.com/OData/odata.net/blob/acf4f43625770edd91576f627f9ce7a790104334/src/Microsoft.OData.Edm/Csdl/Semantics/CsdlSemanticsNavigationSource.cs#L137

An attempt to improve performance was commited in the last version by caching FindNavigationPropertyBindings.FindNavigationPropertyBindings. Unfortunately instead of caching the materialized list of results the enumerable was cached resulting in even more performance degradation. 

This fix is to simple add .ToList() on the enumerable.

**Comment by habbes** [comment]
Thanks @nsarris for reporting this. We'll look into this and patch it (cc @Sreejithpin )
