### ISSUE TITLE
Performance - expensive allocations due to ODataUri.Clone()

### ISSUE THREAD

**Issue by joaocpaiva** [OData/odata.net#2163]
ODataUri.Clone() is costing 1.72% in allocations.

![image](https://user-images.githubusercontent.com/24846248/130269745-f3882c20-fe31-4f3c-951a-4a3f32f73ace.png)

Do we need to clone **ODataUri** every time we enter the scope in **ODataWriterCore**? I suppose this is needed for mutability, since the code is modifying it? Though I wonder if there is an opportunity to change/refactor the code to avoid or reduce the need of this expensive allocation?

### Assemblies affected

Microsoft.OData.Core 7.8.3

### Reproduce steps

Exercise Microsoft.OData.ODataWriterCore.EnterScope() method

### Expected result

Less number of allocations.

### Actual result

Excessive number of allocations.

@mikepizzo @Sreejithpin @chrisspre

**Comment by habbes** [comment]
@joaocpaiva removing the cloning is not straightfoward change since we don't want changes made to the uri to affect the parent scope. However I'm still looking into this. The method also seems to create new instances of ODataPath a well. I'm wondering whether you `ODataPath` is also red on your profile. Do you think having used structs would help?

**Comment by joaocpaiva** [comment]
> @joaocpaiva removing the cloning is not straightfoward change since we don't want changes made to the uri to affect the parent scope. However I'm still looking into this. The method also seems to create new instances of ODataPath a well. I'm wondering whether you `ODataPath` is also red on your profile.
> 
> One thing I'd want to explore is whether making `ODataUri` a struct would have positive impact. We would need to take special consideration before deciding to make this a struct (https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct). But given that it's sealed and doesn't implement any interface, it could a worthwhile opportunity to explore even if we don't end up taking that route. What do you think?

Yeah struct does not seem a good fit for this scenario. The cost of ODataPath is relatively small right now, 0.11% though if that was a easy fix, 0.11% is worth it.

If there is not a simple fix or refactor to reduce these allocations, lets leave this for now. We can revisit it again later on.

**Comment by chrisspre** [comment]
My understanding is that this is efficient in System.Text.Json because these are designed from ground up that way. If I remember this right, a JsonElement is essentially only two indices into a larger (consecutive) array. Cloning this is cheap because one only needs to copy two integers or so. But I would guess the efficiency comes soewhat from immutability and memory access.
ODataUri is a heavy object compared to this with a dozen or so members (mostly reference types) that are themselves mutable and should therefore be cloned (they are not as far as I can see). 
With all that said, I don't think the actual cloning is expensive, it is the amount of times it gets cloned. Making this a struct would also mean the 12+ pointers would be copied even more often.

Nonetheless, it would be interesting to measure the effect .

**Comment by joaocpaiva** [comment]
> My understanding is that this is efficient in System.Text.Json because these are designed from ground up that way. If I remember this right, a JsonElement is essentially only two indices into a larger (consecutive) array. Cloning this is cheap because one only needs to copy two integers or so. But I would guess the efficiency comes soewhat from immutability and memory access.
> ODataUri is a heavy object compared to this with a dozen or so members (mostly reference types) that are themselves mutable and should therefore be cloned (they are not as far as I can see).
> With all that said, I don't think the actual cloning is expensive, it is the amount of times it gets cloned. Making this a struct would also mean the 12+ pointers would be copied even more often.
> 
> Nonetheless, it would be interesting to measure the effect .

Indeed @chrisspre this clone is only expensive because it happens way too many times. However, if the places where ODataUri is cloned are the only places where we mutate the object, and we could effectively use as a ref readonly struct, cloning this as a struct in the stack would be worth trying and benchmark, On the other hand, if we need to pass this struct around, and cannot use **ref**, the number of copies will increase significantly as you mentioned and for sure offset any savings from fixing this allocation.

**Comment by habbes** [comment]
@joaocpaiva @chrisspre while investigating other allocations, I stumbled upon something suspicious about the `ODataUri`. It seems to account for a large number of `Dictionary` instances, namely `Dictionary<string, string>`:
![image](https://user-images.githubusercontent.com/8460169/132756002-2c2e82c0-c97d-4163-881f-f31f1b971fa3.png)

 and `Dictionary<string, SingleValueNode>`:
 
![image](https://user-images.githubusercontent.com/8460169/132756425-433f203e-746c-4857-b2e4-d463ed075208.png)

I'm not sure how CPR computes the Inclusive and Exclusive size values, whether the size of an object includes the size of the objects it references, or just its inline size. So I don't if these two dictionaries explain the inclusive size of the `ODataUri`. These two dictionaries are properties for the `ParameterAliasAccessor` class, which is used a property type on `ODataUri`.

The suspicious thing is that when `Clone()` is called, the `ParamterAliasAccessor` reference is copied to the newly created `ODataUri`:

```c#
public ODataUri Clone()
{
            return new ODataUri()
            {
                /** redacted **/

                ParameterAliasValueAccessor = ParameterAliasValueAccessor,
                
                /** redacted **/
            };
 }
```

However, calling the default constructor `new ODataUri()` also creates a new `ParameterAliasValueAccessor` and dictionay:

```c#
/// <summary>
/// Initializes a new instance of the <see cref="ODataUri"/> class.
/// </summary>
public ODataUri()
{
      IDictionary<string, string> dictionary = new Dictionary<string, string>(StringComparer.Ordinal);
      this.ParameterAliasValueAccessor = new ParameterAliasValueAccessor(dictionary);
}
```

So essentially, each time `Clone()` is called, a new instance of `ParameterAliasValueAccessor` with 2 new dictionaries is created and immediately replaced by the `ParameterAliasValuesAccessor` of the uri being cloned. So this a massive waste that'll be hopefully quick and easy to fix.

**Comment by joaocpaiva** [comment]
> @joaocpaiva @chrisspre while investigating other allocations, I stumbled upon something suspicious about the `ODataUri`. It seems to account for a large number of `Dictionary` instances, namely `Dictionary<string, string>`:
> ![image](https://user-images.githubusercontent.com/8460169/132756002-2c2e82c0-c97d-4163-881f-f31f1b971fa3.png)
> 
> and `Dictionary<string, SingleValueNode>`:
> 
> ![image](https://user-images.githubusercontent.com/8460169/132756425-433f203e-746c-4857-b2e4-d463ed075208.png)
> 
> I'm not sure how CPR computes the Inclusive and Exclusive size values, whether the size of an object includes the size of the objects it references, or just its inline size. So I don't if these two dictionaries explain the inclusive size of the `ODataUri`. These two dictionaries are properties for the `ParameterAliasAccessor` class, which is used a property type on `ODataUri`.
> 
> The suspicious thing is that when `Clone()` is called, the `ParamterAliasAccessor` reference is copied to the newly created `ODataUri`:
> 
> ```cs
> public ODataUri Clone()
> {
>             return new ODataUri()
>             {
>                 /** redacted **/
> 
>                 ParameterAliasValueAccessor = ParameterAliasValueAccessor,
>                 
>                 /** redacted **/
>             };
>  }
> ```
> 
> However, calling the default constructor `new ODataUri()` also creates a new `ParameterAliasValueAccessor` and dictionay:
> 
> ```cs
> /// <summary>
> /// Initializes a new instance of the <see cref="ODataUri"/> class.
> /// </summary>
> public ODataUri()
> {
>       IDictionary<string, string> dictionary = new Dictionary<string, string>(StringComparer.Ordinal);
>       this.ParameterAliasValueAccessor = new ParameterAliasValueAccessor(dictionary);
> }
> ```
> 
> So essentially, each time `Clone()` is called, a new instance of `ParameterAliasValueAccessor` with 2 new dictionaries is created and immediately replaced by the `ParameterAliasValuesAccessor` of the uri being cloned. So this a massive waste that'll be hopefully quick and easy to fix.

Haha very good catch!! And low hanging fruit. The Clone() should definitely  skip the default constructor.
