### ISSUE TITLE
Performance - DuplicatePropertyNameCheck costing 1.5% of allocations

### ISSUE THREAD

**Issue by joaocpaiva** [OData/odata.net#2180]
This object is costing 1.5% of allocations in AGS. This relative cost will increase once AGS starts using OData 7.9.1 because there are other heavy allocations fixed in that version.

Most of the allocation cost comes from initializing and resizing the internal **propertyState** dictionary. 

Would it be possible to reuse instances (ideally a single instance) of **DuplicatePropertyNameChecker** throughout the lifetime of each response being serialized? Right now multiple instances are created per response. If we were able to reuse the same instance, throughout the response, it will significantly reduce the number of allocations these allocations.

An object pool would be another option, but better than a pool would be creating create a single instance of **DuplicatePropertyNameChecker** for each response, if that was viable/possible.

![image](https://user-images.githubusercontent.com/24846248/132600437-302e7c5f-b6a5-43e3-a112-06578c3797b6.png)

![image](https://user-images.githubusercontent.com/24846248/132600456-91fe542a-fdc3-44b9-bb25-b939292a34b5.png)

### Assemblies affected

Microsoft.OData.Core 7.9.1

### Reproduce steps

Write a response using **ODataMessageWriter**

### Expected result

Allocation cost of DuplicatePropertyNameChecker should be close to 0% at scale.

### Actual result

Allocation cost of DuplicatePropertyNameChecker is roughly 1.5% at scale.

@habbes

**Comment by habbes** [comment]
@joaocpaiva based on your screenshot, the resizing seems to account for most of the allocations. Do you know how many properties are being serialized per response on average? Maybe we could reduce this cost by specifying a capacity when creating the dictionary since (I assume) we know the total number of properties that can be added to the dictionary cc @KenitoInc

**Comment by joaocpaiva** [comment]
> Note that it's also possible to disable duplicate property name checking in the ODataMessageWriterSettings. In this case, the framework doesn't track duplicate property names (no dictionary is created).
> 
> It would be interesting to know whether AGS _ever_ gets the exception for duplicate property names (at least in production) and, if so, how it handles it.
> 
> Perhaps we could have duplicate property name checking enabled in debug/pre-production but disabled in production?

@mikepizzo is there a specific exception that OData writer raises if there is a duplicate property? I don't think we are handling this gracefully in AGS anyway, so we should probably look to disable it ...
