### ISSUE TITLE
Filtering for Nullable value types and Nullable reference types produces different results

### ISSUE THREAD

**Issue by SviatoslavBachynskyi** [OData/odata.net#2218]
Filtering by Nullable value types produces queries that cannot be translated by MongoDriver and possibly ORMs like EntityFramework

### Assemblies affected

Microsoft.AspNetCore.OData lib 8.0.3*

### Reproduce steps

1. Call endpoint with `$filter=nullableInt eq 123`
where nullableInt is property
`int? NullableInt { get; set; }`

### Expected result

preduces expression similar to this:
`document => document.NullableInt == 123`

### Actual result
produces experession similar to this:
`document => (document.NullableInt == 123) == (bool? true)`

```
'(.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>)
.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>(Classes.Document $$it) {
    ($$it.NullableInt == (System.Nullable`1[System.Int32]).Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty)
    == .Constant<System.Nullable`1[System.Boolean]>(True)
}
```

### Additional detail

It causes problems with MongoDb driver, but I might do the same for ORMs like EntityFramework. MongoDb doesn't support Filtering with bool? and throws an exception. The only way to make it work is to apply filters for data loaded in memory.
A similar issue is happening with DateTime? and DateTimeOffset?, it returns bool? as the result of the comparison.

Additionally, it is unclear why filtering for string produces normal query. This comparison to `(bool? true)` is a redundant step.

`document => document.NullableString == "123"`

```
'(.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>)

.Lambda #Lambda1<System.Func`2[Classes.Document,System.Boolean]>(Classes.Document $$it) {
    $$it.NullableString == .Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty
}
```

**Comment by habbes** [comment]
@SviatoslavBachynskyi OData queries support nullable types. This issue sounds like a limitation with the MongoDb driver and not with the OData library.

If the MongoDb driver does not support nullable types, and if your use-case does not require the primitive types to be nullable, maybe you can edit your model and make the properties non-nullable.

The reason it generates a "normal" query for strings is because strings in C# can be `null` since they are reference types.

**Comment by SviatoslavBachynskyi** [comment]
MongoDb driver supports nullable type. If I manually put query document.NullableInt == 123, it will work and mongoDb Driver will return results. 
(document.NullableInt == 123) == (bool? true) is not supported by MongoDb Driver because it doesn't compare documentProperty, it compares result of the comparison with ((bool?) true)

**Comment by SviatoslavBachynskyi** [comment]
it's still an odd query and there is no way to fix it on MongoDb driver side or in my project

**Comment by habbes** [comment]
@SviatoslavBachynskyi we have had some issues related to null-check propagation with different versions of EF. To improve compatibility between EF classic and EF Core, we do have some hard-coded checks to decide whether or not to apply a null-check. Maybe such your scenario would benefit from being treated as EF classic (see related issues).

In case that doesn't work, we are also working on making our query expression generation logic to be more extensible and allowing for custom implementations (see https://github.com/OData/AspNetCoreOData/pull/296)

Possibly related issues:
- https://github.com/OData/WebApi/pull/2142
- https://github.com/OData/WebApi/issues/2508
- https://github.com/OData/WebApi/issues/2537

**Comment by habbes** [comment]
@SviatoslavBachynskyi could you share a sample repro project that we can use to investigate?

**Comment by SviatoslavBachynskyi** [comment]
https://github.com/SviatoslavBachynskyi/ODataMongoDB/tree/master
a simple example to reproduce the issue

I can confirm that EF Core handles those `== (bool? true)` comparisons well but they are braking MongoDbDriver

**Comment by habbes** [comment]
@SviatoslavBachynskyi it seems that setting the `ODataQuerySettings.HandleNullPropagation` to `HandleNullPropagationOption.False` fixes the issue.

@KenitoInc @SviatoslavBachynskyi is it possible to configure this option when configuring OData? If so, could you share a sample?

**Comment by habbes** [comment]
@SviatoslavBachynskyi 
You can configure the null propagation handling the `[EnableQuery]` attribute. I have tried modifying the `[EnableQuery]` on your Get action as follows:
```c#
[HttpGet]
[EnableQuery(HandleNullPropagation = HandleNullPropagationOption.False)]
public IQueryable<TestEntity> Get() {
// ...
}
```
and I was able to make the query against the nullable int field successfully. Thanks @xuzhg for the tip.

Let me know if this works for you.

**Comment by ElizabethOkerio** [comment]
A workaround was provided but the user didn't respond. Am closing the issue but feel free to reopen if still experiencing the issue.

**Comment by SviatoslavBachynskyi** [comment]
Thank you @habbes @ElizabethOkerio!
I tested the provided solution and it worked.
