### ISSUE TITLE
Impossible to run tests with VS2019 Community

### ISSUE THREAD

**Issue by JBBianchi** [OData/odata.net#2227]
Unable to execute tests with VS2019 Community ?

### Reproduce steps

- Install VS2019 community
- Edit `build.ps1`, replace `Enterprise` with `Community`
- Open an admin PowerShell console
- Run `dotnet restore \sln\OData.sln`
- Run `dotnet restore \sln\OData.E2E.sln`
- Run `.\build.cmd` 

### Expected result

The builds/tests to work

### Actual result

Build errors

### Additional detail

[msbuild.log](https://neuroglia.io/msbuild.txt)

**Comment by corranrogue9** [comment]
I have merged a PR and created [this](https://github.com/OData/odata.net/pull/2297) PR to address these build issues. If you follow the steps in the new file `OData.E2E.md` from that PR, you should be able to build and run most of the tests. A few caveats:
1. With the community version of Visual Studio, during step 1 of the instructions, these components will not be found (this is fine, you can proceed without them):
-- TimeTravel
-- Snapshot
-- FrontEnd
-- LiveUnitTesting
2. Until the PR is merged, between steps 5 and 6 of the instructions you will need to run the `git checkout corranrogue9/onboarding2` command to pick up the changes
3. A number of tests will fail (<2000). This work is being tracked [here](https://github.com/OData/odata.net/issues/2295)

Please try the instructions from the PR and let me know if you continue to have issues.

**Comment by corranrogue9** [comment]
I'm going to close this issue, please re-open it or file a new one if you continue having problems with VS Community versions
