### ISSUE TITLE
Case sensitive handing on Materializer

### ISSUE THREAD

**Issue by wilsonson** [OData/odata.net#2230]
Used OData Service to generate classes, but the materializer cannot find the property name and therefore throwing exception: "The expected property 'xxxxx could not be found while processing an entry. Check for null before accessing this property."

After digging, the ODataEntityMaterializer.GetPropertyOrThrow method compares the property name in case sensitive mode.
However, the generated class by OData Service will name the property in camel case, and therefore the property name cannot be matched.

Does the case sensitive comparison is expected behavior ?

### Assemblies affected

ODat.Client 7.9.3

**Comment by gathogojr** [comment]
@wilsonson Do you have a repro you can share? Everything worked okay when I tried to reproduce it

**Comment by gathogojr** [comment]
Unable to reproduce the issue and no feedback on follow up
