### ISSUE TITLE
XML comment error

### ISSUE THREAD

**Issue by Casimodo72** [OData/odata.net#224]
Hi, I'm getting the following errors for two method XML comments:

/// <exception cref="Error.ArgumentNull">Throws if input segments is null.</exception>

3>C:\Dev\Lib\ODataNet\src\Microsoft.OData.Core\UriParser\SemanticAst\ODataPath.cs(37,30,37,48): error CS1574: XML comment has cref attribute 'ArgumentNull' that could not be resolved
3>C:\Dev\Lib\ODataNet\src\Microsoft.OData.Core\UriParser\SemanticAst\ODataPath.cs(52,30,52,48): error CS1574: XML comment has cref attribute 'ArgumentNull' that could not be resolved

Using master branch head 6.12.0

Regards, Kasimier Buchcik

**Comment by congysu** [comment]
@Casimodo72 Which version of Visual Studio are you using?

**Comment by Casimodo72** [comment]
VS 2015 RC Enterprise

**Comment by xuzhg** [comment]
Fixed by merging PR #330. Thanks @Dishan006 .
