### ISSUE TITLE
Function cannot be applied to an enumeration-typed argument

### ISSUE THREAD

**Issue by JBBianchi** [OData/odata.net#2241]
Trying to apply a filter function such as `tolower` to a dictionary or dynamic property path results in an unwanted error `The query specified in the URI is not valid. The 'tolower' function cannot be applied to an enumeration-typed argument.`

### Assemblies affected

Microsoft.OData.Core, all versions

### Reproduce steps

1. Clone https://github.com/JBBianchi/ODataFnNotAppliable
2. Start the project
3. Query with filter
3.1. Filtering with no function is working:  Navigate to `https://localhost:44328/odata/products?$filter=name/en%20eq%20%27Scarf%27`)
3.2.1. Filtering with a function throws an error: Navigate to `https://localhost:44328/odata/products?$filter=tolower(name/en)%20eq%20%27scarf%27`
3.2.2. See the error
```json
{
  "error":{
    "code":"",
    "message":"The query specified in the URI is not valid. The 'tolower' function cannot be applied to an enumeration-typed argument.",
    "details":[
      
    ],
    "innererror":{
      "message":"The 'tolower' function cannot be applied to an enumeration-typed argument.",
      "type":"Microsoft.OData.ODataException",
      "stacktrace":"   at Microsoft.AspNetCore.OData.Query.Expressions.ExpressionBinderBase.ValidateAllStringArguments(String functionName, Expression[] arguments)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.ExpressionBinderBase.BindToLower(SingleValueFunctionCallNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.ExpressionBinderBase.BindSingleValueFunctionCallNode(SingleValueFunctionCallNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindConvertNode(ConvertNode convertNode)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindFilterClause(FilterBinder binder, FilterClause filterClause, Type filterType)\r\n   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(IQueryable baseQuery, FilterClause filterClause, Type filterType, ODataQueryContext context, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNetCore.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)"
    }
  }
}
```

### Expected result

The list to be filtered

### Actual result

An error is thrown

### Additional detail

Related to
https://github.com/OData/WebApi/issues/1180
https://github.com/OData/WebApi/issues/2173
https://github.com/OData/AspNetCoreOData/issues/325

I noticed that for the expression `name/en eq 'Scarf'`, the [left hand binary operator](https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs#L462) (`name\eq`) is a `Convert` node resulting in a string (Convert>SingleValueOpenPropertyAccess>SingleComplexNode>ResourceRangeVariableReference).

In the case of the expression `tolower(name/en) eq 'scarf'`, the function parameter (also `name\eq`) [is bound](https://github.com/OData/AspNetCoreOData/blob/89ea8a0c473787884584ec4003d58afe97d9b7cf/src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs#L576) to `SingleValueOpenPropertyAccess`, skipping the "`Convert` step" (SingleValueOpenPropertyAccess>SingleComplexNode>ResourceRangeVariableReference) which results in a conditional object instead of a string as expected in [ValidateAllStringArguments](https://github.com/OData/AspNetCoreOData/blob/89ea8a0c473787884584ec4003d58afe97d9b7cf/src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs#L780).

From what I understand, the `left` and `right` types of a binary operation are "promoted" in the [BinaryOperatorBinder](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/UriParser/Binders/BinaryOperatorBinder.cs#L52) so each side have a matching type. In our case, that's where the chain `SingleValueOpenPropertyAccess>SingleComplexNode>ResourceRangeVariableReference` get wrapped in a `Convert` node.

The same should happen when binding the function `arguments` to the their expected type in the [FunctionCallBinder](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs#L292). This process is supposedly made by [TypePromoteArguments](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs#L320) after checking [if the function have a ReturnType](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs#L318). 

The first thing that seems off to me is to base an arguments type conversion on the return type of the function instead of the expected types of the arguments, and, the second thing is that for `tolower` the return type is null when it should be string. This results in ignoring the `Convert` step. [Commenting the `if (signature.ReturnType != null)` condition](https://github.com/neuroglia-io/odata.net/commit/b49f1c3c6a151a87b28d0562c1aad5b2ad21aec5) induces the conversion, thus making the filter work. I guess that unfortunately, this requires a more indepth understanding of the whole process because this condition is probably there for a reason. As this condition seems to exist since [FunctionCallBinder](https://github.com/OData/odata.net/blob/3445a856c7c2498036235516a31966cf1f53e45a/src/Microsoft.OData.Core/UriParser/Binders/FunctionCallBinder.cs) has been created, I cannot find the said reason in a commit comment.

I wanted to make a [PR of a fix](https://github.com/neuroglia-io/odata.net/commit/8f7876f0f9ca5854fe30e479bfe838a344141824) but I'm still stuck as I'm unable to launch tests #2227.

**Comment by ElizabethOkerio** [comment]
@JBBianchi Please continue with the PR then we help with the tests.
