### ISSUE TITLE
Support a json serialization for $batch

### ISSUE THREAD

**Issue by rgregg** [OData/odata.net#226]
Serializing $batch requests into multipart/mixed and application/http makes it hard for developers to consume the $batch API. HTTP serialization is typically handled by a library that won't expose generic methods to serialize/deserialize HTTP streams in a reusable way. Getting multipart/mixed right is a challenge as well.

To make $batch more accessible, supporting a JSON serialization would be a great step that would reduce the complexity of using $batch to support batch scenarios.

**Comment by congysu** [comment]
@markdstafford How do you think?

**Comment by schmidtaa** [comment]
It's now in proposed OASIS spec, see https://issues.oasis-open.org/browse/ODATA-1051
OData team, when we can expect this proposal implemented in the client library?

**Comment by xuzhg** [comment]
See PR: https://github.com/OData/odata.net/pull/951

**Comment by biaol-odata** [comment]
The PR introducing JSON Batch in OData Core: https://github.com/OData/odata.net/pull/992
Release: https://www.nuget.org/packages/Microsoft.OData.Core/7.4.0-beta2

This issue can be closed now.

**Comment by biaol-odata** [comment]
keep it open for doc, client work, etc.

**Comment by biaol-odata** [comment]
Doc is tracked in PR: https://github.com/OData/odata.net/pull/1033
Client work is tracked by #1034.

This issue can be closed now.

**Comment by VenuMadhavPerumalla** [comment]
@biaol-odata - I have a use case where batch response should always be a multipart/mixed content. Is there a way to return multipart content even though json content is requested ?
