### ISSUE TITLE
A Name (Simple Identifier) that starts with an underscore is validated as invalid when in fact it is valid according to the OASIS OData V4 specification

### ISSUE THREAD

**Issue by BuzzyLizzy** [OData/odata.net#2269]
There is an erroneous interpretation of OData V4 in the Microsoft OData.net library. This is related to the pattern used to validate a "Name" which is defined as a "Simple Identifier" that starts with an underscore is being validated as invalid by the IEdmModel.Validate(). This is incorrect, a Simple Identifier may start with an underscore, please see explanation below.

### Assemblies affected

OData .Net lib 7.9.4 (Nuget package version for Microsoft.Odata.Core and Microsoft.OData.Edm)

### Reproduce steps

Create a Name of a Property in an EntityTpe in a V4 contract that starts with an underscore, parse it with the CsdlReader.TryParse and get as output an IEdmModel, on this run the IEdmModel.Validate(), the validation will fail. An error message is generated for example:
"(16, 10): The specified name is not allowed: '_Name'."

### Expected result

A Name (Simple Identifier) that starts with an underscore is validated as allowed.

### Actual result

A Name (Simple Identifier) that starts with an underscore is validated as not allowed.

### Additional detail

When we have a Property name that starts with an underscore the IEdmModel.Validate() reports this as an invalid name when we call IEdmModel.Validate(). According to OData V4 a Simple Identifier that starts with an underscore is a valid Simple Identifier, therefore a valid Property naem. To confirm this please see in this document of OASIS the pattern for a Simple Identifier includes strings starting with an underscore: https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/os/schemas/edm.xsd
<xs:simpleType name="TSimpleIdentifier"> <xs:restriction base="xs:NCName"> <xs:maxLength value="128"/>  <xs:pattern value="[\p{L}\p{Nl}_][\p{L}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Pc}\p{Cf}]{0,}"/> </xs:restriction> </xs:simpleType>
Also in this text in the V4 specification it is written the following: A simple identifier is a Unicode character sequence with the following restrictions: It consists of at least one and at most 128 Unicode characters (code points). The first character MUST be the underscore character (U+005F) or any character in the Unicode category “Letter (L)” or “Letter number (Nl)”. The remaining characters MUST be the underscore character (U+005F) or any character in the Unicode category “Letter (L)”, “Letter number (Nl)”, “Decimal number (Nd)”, “Non-spacing mark (Mn)”, “Combining spacing mark (Mc)”, “Connector punctuation (Pc)”, and “Other, format (Cf)”. Non-normatively speaking it starts with a letter or underscore, followed by at most 127 letters, underscores or digits.
In the Microsoft Microsoft.AspNet.OData library the following code is being used to test for a valid name (see EdmUtil class): 
```csharp
private const string StartCharacterExp = @"[\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}]";
private const string OtherCharacterExp = @"[\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Lm}\p{Nl}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Cf}]";
private const string NameExp = StartCharacterExp + OtherCharacterExp + "{0,}";
// private static Regex ValidDottedName=new Regex(@&quot;^&quot;+NameExp+@&quot;(\.&quot;+NameExp+@&quot;){0,}$&quot;,RegexOptions.Singleline);
private static Regex UndottedNameValidator = PlatformHelper.CreateCompiled(@&quot;^&quot; + NameExp + @&quot;$&quot;, RegexOptions.Singleline);
```
Notice the "StartCharacterExp" in the .Net code does not include an underscore, this is not in line with the OData V4 specification. We urgently need a work-around for this please.

**Comment by elize-vdr** [comment]
Hi, I created Pull request 2275 for this, not seeing it being reviewed. My first time submitting PR on an open source project, not sure if I did it right. How do I get someone to review it please?
