### ISSUE TITLE
ODataCollectionDeserializer should enable users to get out odata/custom instance annotations

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#228]
Related pull request #166 

We can add a ODataCollection class like ODataFeed for Complex, Primitive and Enum.
Add new ODataCollectionDeserializerStatus, etc.

**Comment by congysu** [comment]
@chinese007 OData client does not read `@odata.nextlink` in a top level complex type collection, for now.

**Comment by chinese007** [comment]
@congysu Thanks for the information. Do we have a pull request to track that?
