### ISSUE TITLE
Microsoft.Data.OData 5.8.5 Changelog

### ISSUE THREAD

**Issue by michael-baker** [OData/odata.net#2282]
Not an issue - but a question.

NuGet lists a 5.8.5 version of Microsoft.Data.OData, Microsoft.Data.Edm etc but there is no release notes or change log that I can find. Nor can I find a tag for 5.8.5 in this repository. Where is the release documentation?

### Assemblies affected
Microsoft.Data.Edm
Microsoft.Data.OData
Microsoft.Data.Services
Microsoft.Data.Client

**Comment by xuzhg** [comment]
added here: https://docs.microsoft.com/en-us/odata/changelog/odatalib-5x

thanks.
