### ISSUE TITLE
ODL should support property and dynamic property template.

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#23]
So far, ODL supports key and function parameter template. for example:

~/Customers({key}}/Default.MyFunction(p1={p1})

However, ODL should support property and dynamic property template, for example:

~/Customers({key})/{property}
~/Customers({key})/{dynamicProperty}

**Comment by karataliu** [comment]
committed as https://github.com/OData/odata.net/commit/ffb59b3281af773db818202ebd559dc919bb4985
