### ISSUE TITLE
Could not load type 'Microsoft.OData.Core.ODataVersion' from assembly 'Microsoft.OData.Core, Version=7.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### ISSUE THREAD

**Issue by raghud3** [OData/odata.net#2312]
We are trying to upgrade the Microsoft Spatial and OData library in our project but getting the error as "Could not load type 'Microsoft.OData.Core.ODataVersion' from assembly 'Microsoft.OData.Core, Version=7.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'" at line  getting the error on last line (GlobalConfiguration.Configure(WebApiConfig.Register);).

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*
S.No.	DLL Name	      Current Version	                       Upgraded Version
1.		Microsoft.Spatial	        6.14.0	                                7.9.4
2. 		Microsoft.OData.Core	6.14.0	                                7.9.4
3. 		Microsoft.Bcl.AsyncInterfaces	1.1.1   	                         5.0.0
4. 		Microsoft.Odata.Edm		6.14.0	                        7.9.4
5.		System.Runtime.CompilerServices.Unsafe	4.5.3  	4.6.0
6.		Microsoft.AspNet.OData	5.8.0	                                       7.5.12

### Reproduce steps

Upgrade the above versions of dll and getting the error on last line (GlobalConfiguration.Configure(WebApiConfig.Register);)
 protected void Application_Start()
        {
            GlobalDependencyRegistrar.Register();
            AreaRegistration.RegisterAllAreas();
            **GlobalConfiguration.Configure(WebApiConfig.Register);**
        }
public static class WebApiConfig
	{
		public static void Register(HttpConfiguration config)
		{
			config.EnableDependencyInjection();

			config.CustomMapODataServiceRoute("odata", "odata");

			config.AddODataQueryFilter();
		}
	}
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result
It should not error out and API should return the result.
*What would happen if there wasn't a bug.*

### Actual result
Error.
*What is actually happening.*

### Additional detail
Any help is very much appreciated.
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by raghud3** [comment]
Team, can some-one help here? Any suggestion to move forward would be appreciated?

**Comment by xuzhg** [comment]
@raghud3 can 'clean and rebuild all' work for you?

**Comment by raghud3** [comment]
Thanks for your response Sam, I have tried clean and re-build all for the whole project, still facing the same error. Could you please suggest further steps which can help me move ahead with the upgrade?

**Comment by xuzhg** [comment]
@raghud3 I do think one of your projects still refers to the old version dll. Can you double-check your whole projects and the referenced projects. Otherwise, please set up some time and let me review the structure of your project?

**Comment by raghud3** [comment]
Thanks for your response Sam, could you share your email ID and availability for call tomorrow, 17th February, Thursday? I will setup a zoom/team meeting accordingly.

**Comment by raghud3** [comment]
Thanks Sam for joining on call with us, really appreciate your time and guidance.
**Root Cause:** For the issue reported here, one of the dll was old in our project, after removing the old dll reference it got resolved.
Sam did help us in resolving a subsequent issue where the pathhandler parse method was failing to parse the error. He suggested two approaches one is to use service to create the model object and another one to use dependency injection to populate the EdmModel.
Thanks Sam for going above and beyond to help us.

**Comment by raghud3** [comment]
Closing this case with previous comment. thanks
