### ISSUE TITLE
ByKey generates Search url instead of Get url

### ISSUE THREAD

**Issue by AtulBhartia** [OData/odata.net#2320]
*After we upgraded Microsoft.Data.Services package to 5.8.5 from 5.8.4, we noticed some calls were translating into search requests instead of Get when client was making call using Entity.ByKey. This does not always repro. After we reverted the lib to 5.8.4 the issue was resolved*

### Assemblies affected

Microsoft.Data.Services.Client 5.8.5
Microsoft.Data.OData 5.8.5
Microsoft.Data.Edm 5.8.5
System.Spatial 5.8.5

### Reproduce steps
client makes a call to destination service using ByKey and passing the key
DataServiceContext.DataServiceQuery<Entity>.ByKey("6fc58610-2912-4f80-8fe2-44a83c7691e8").GetValueAsync();

### Expected result

expected url
ServiceName/Entity(guid'6fc58610-2912-4f80-8fe2-44a83c7691e8')

### Actual result
ServiceName/Entity()?$filter=Key eq guid'6fc58610-2912-4f80-8fe2-44a83c7691e8'

**Comment by habbes** [comment]
Hi @AtulBhartia the 5.x versions of OData libraries are no longer supported or maintained. Is there any particular reason you moved from 5.8.4 to 5.8.5? Like any particular feature or bug fix that you wanted to take advantage of in 5.8.5? If not, maybe you could go back to 5.8.4 or check whether later versions > 5.8.5 or 6.x have fixed the issue you currently face (Note that 6.x versions also no longer receive regular updates).
