### ISSUE TITLE
Add Support for ASP.NET API Versioning

### ISSUE THREAD

**Issue by Grauenwolf** [OData/odata.net#2326]
Due to the changes in OData 8, we lost the ability to use ASP.NET API Versioning. This is rather important for APIs that mix REST and OData style endpoints.

https://github.com/dotnet/aspnet-api-versioning/issues/677

**Comment by Grauenwolf** [comment]
Note: For versioning OData 8 alone, see https://devblogs.microsoft.com/odata/api-versioning-extension-with-asp-net-core-odata-8/

**Comment by commonsensesoftware** [comment]
@Grauenwolf as just announced in dotnet/aspnet-api-versioning#677, official support is coming and is also here. pop on over for more details.

**Comment by KenitoInc** [comment]
Fixed https://github.com/dotnet/aspnet-api-versioning/releases/tag/v6.0.0
