### ISSUE TITLE
Different behavior when passing default ODataQuerySettings vs not passing it (ODataQueryOptions.ApplyTo)

### ISSUE THREAD

**Issue by joukevandermaas** [OData/odata.net#2332]
The following two samples may produce different results:

```
void ApplyQuery<T>(IQueryable<T> query, ODataQueryOptions<T> options)
{
    options.ApplyTo(query).Count();
    options.ApplyTo(query, new ODataQuerySettings()).Count();
}
```

Specifically the former fails when there is a subquery on a collection, while the latter does not, something like:

```
$filter=MyProp/any(f: f Eq 'something')
```

### Assemblies affected

Odata.net 8.0.7 on dotnet 6.0.

### Reproduce steps

Have a type with a collection:

```
class MyClasss { public ICollection<string> MyProp { get; set; }
```

then perform the filter above using `ApplyTo`.

### Expected result

The default (not providing settings) and the default settings (not setting any properties) should behave the same.

### Actual result

The default (not providing settings) gives an exception, while the default settings (not setting any properties) correctly applies the filter.

The exception message:

```
Cannot compare elements of type 'System.Collections.Generic.ICollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. Only primitive types, enumeration types and entity types are supported.
```

### Additional detail

This was found when updating from Odata 7.x, presumably some default behavior changed in 8.0 but it is very hard to find any information on this (if it exists).

**Comment by KenitoInc** [comment]
We made some changes in v8.0.8 which may have fixed this issue. Kindly try v8.0.8 and confirm if it resolves your issue.
Release notes https://github.com/OData/AspNetCoreOData/releases/tag/8.0.8

**Comment by joukevandermaas** [comment]
@KenitoInc seems like it works fine in 8.0.8. Thanks!
