### ISSUE TITLE
Performance when expanding

### ISSUE THREAD

**Issue by CShelton11** [OData/odata.net#2333]
*When expanding to parent or child entities, there can be significant performance issues.  It would be nice if there were auto expand funxtiinality to mitigate this issue.  Example - if i have?$expand=table1 then having this setting turned on would automatically cause the queryable to be rewritten to say queryable.include("table1").  This would go a long ways to solving the expansiin performance issue when using lazy loading.*

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by KenitoInc** [comment]
Kindly share a detailed repro and the generated expression or sql query so that we can investigate this issue.

**Comment by KenitoInc** [comment]
Closed due to inactivity
