### ISSUE TITLE
Enable T4 to support VS2015

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#234]

**Comment by congysu** [comment]
The 'OData v4 Client Code Generator' is Visual Gallery: https://visualstudiogallery.msdn.microsoft.com/9b786c0e-79d1-4a50-89a5-125e57475937

**Comment by AdamCaviness** [comment]
This is marked as resolved but I've yet to see the extension updated on the VS gallery.  Any ETA?

**Comment by congysu** [comment]
VS Extension updated to support VS2015: https://visualstudiogallery.msdn.microsoft.com/9b786c0e-79d1-4a50-89a5-125e57475937
