### ISSUE TITLE
[.NET Native] Rewrite PlatformHelper.GetMethod(name, types) for OData client

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#237]
Current implementation would result in exception "TypeHandles are not supported for types that return true for ContainsGenericParameters." when OData client runs on .NET Native runtime.

The root cause is `TypeInfo.IsAssignableFrom` does not support type with generic argument(s) in .NET Native.

If this issue is recognized as a .NET bug, then we don't have to do anything in our client;
otherwise we need to rewrite `PlatformHelper.GetMethod(name, types)`.

**Comment by lewischeng-ms** [comment]
Option 1: https://github.com/lewischeng-ms/odata.net/blob/uwp/src/PlatformHelper.cs#L993-L1035

Drawback: Cannot handle case like comparing argument of type Base<T> and Derived<T>

**Comment by lewischeng-ms** [comment]
(Preferred) Option 2: Sample: https://github.com/lewischeng-ms/odata.net/blob/uwp/src/Microsoft.OData.Client/DataServiceQueryOfT.cs#L28-L36

Need to carefully construct the Lambda expression to retrieve the `MethodInfo`.

If option 2 is not viable, go to option 1.

**Comment by MattWhilden** [comment]
When .NET Native shipped a year ago this API was pretty broken. Since then we've rewritten a big chunk of that code path and I'd expect all of this to more or less work calling TypeInfo.IsAssignableFrom.

If you're on Update 3+ and still having issues, we'd love to know about it.

**Comment by mikepizzo** [comment]
Thanks @MattWhilden.  This appears to be addressed.

**Comment by MattWhilden** [comment]
Wonderful news! Let us know if you notice any other hiccups. Happy to help.
