### ISSUE TITLE
LinQ syntax: Array.Contain() doesn't encode & character

### ISSUE THREAD

**Issue by qcnguyen** [OData/odata.net#2405]
When using Microsoft.OData.Client , with LinQ syntax, the generated RequestUri doesn't encode "&" character, thus when server receive the request, it can't parse query and throw exception "Request Found an unbalanced bracket expression"

### Assemblies affected

Microsoft.OData.Client 7.11.0 and earlier versions

### Reproduce steps

```
using Microsoft.OData.Client;
using System;
using System.Linq;
namespace OData
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var arr = new string[]
            {
                "a & b"
            };
            var ctx = new DataServiceContext(new Uri("http://localhost"));

            var queryWithEqualityFilter = ctx.CreateQuery<Model>(nameof(Model)).Where(x => x.Name == arr[0]) as DataServiceRequest;
            Console.WriteLine(queryWithEqualityFilter.RequestUri); 
            //WORK FINE: Output: http://localhost/Model?$filter=Name eq 'a %26 b'

            var queryWithContainFilter = ctx.CreateQuery<Model>(nameof(Model)).Where(x => arr.Contains(x.Name)) as DataServiceRequest;
            Console.WriteLine(queryWithContainFilter.RequestUri); 
            //ISSUE HAPPEN: Output: http://localhost/Model?$filter=Name in ('a & b')
        }
    }
    public class Model
    {
        public string Name { get; set; }
    }
}
```

### Expected result

The last line should be similar to equality filter, it should encode the & character, such as http://localhost/Model?$filter=Name in ('a %26 b')

### Actual result

It doesn't encode & character: http://localhost/Model?$filter=Name in ('a & b')

**Comment by gathogojr** [comment]
Support for translating `Contains` function to `in` on OData URL was introduced in https://github.com/OData/odata.net/pull/1868
To check if special characters are escaped
