### ISSUE TITLE
Is there any plan to suppose OData-Temporal-Ext?

### ISSUE THREAD

**Issue by woojunfeng** [OData/odata.net#2414]
Hi team,

Is there any plan to suppose  [Querying Temporal Data](https://docs.oasis-open.org/odata/odata-temporal-ext/v4.0/cs01/odata-temporal-ext-v4.0-cs01.html#sec_QueryingTemporalData)?

thanks

**Comment by habbes** [comment]
Hi @woojunfeng there's no near-term plan to provide support for that. However, we are open to community contributions.

**Comment by habbes** [comment]
Closing this issue. Feel free to re-open if you have any follow-ups.
