### ISSUE TITLE
Expose HttpClientHandler of the underlying request

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2417]
Customer would like to override the server certificate validation logic. Since the PR to allow injecting a custom `HttpClient` is on hold, we can consider exposing the `HttpClientHandler` and other components of the underlying request to the public API.

With `HttpWebRequestMessage`, the underlying `HttpWebRequest` is accessible via a public property, making it possible to override some behaviour, including certificate validation.

With `HttpClientRequestMessage`, the underlying request, client and handler are private or internal.

### Assemblies affected

Microsoft.OData.Client 7.11.0

**Comment by ElizabethOkerio** [comment]
fixed by this: https://github.com/OData/odata.net/pull/2431
