### ISSUE TITLE
Parsing doesn't support hassubset with parenExpr parameter?

### ISSUE THREAD

**Issue by frankshearar** [OData/odata.net#2426]
I tried to parse "filter=hassubset(AcquiredCapabilities, ('ConferenceAssignment', 'Office365'))" and I get an exception thrown saying "')' or operator expected at position 55 in 'hassubset(AcquiredCapabilities, ('ConferenceAssignment', 'Office365'))'". From what I can see in the [ABNF](https://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt) a hasSubsetMethodCallExpr takes takes two commonExpr, a commonExpr can be a parenExpr, and a parenExpr = OPEN BWS commonExpr BWS CLOSE.

[The test cases](https://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-testcases.xml) suggest that the query is valid (see the TestCase tags with Name="5.1.1.6.1 hassubset").

### Assemblies affected

Microsoft.OData.Core 7.6.4

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

The filter would successfully parse. The spec does not explain the semantics of a parenExpr - is it a tuple? a synonym for a list? - but I'd expect the resulting AST to contain something representing the parenExpr.

### Actual result

The parser rejects what is apparently (according to my reading of the ABNF, at least) a valid OData query.

**Comment by frankshearar** [comment]
* Turns out I'd forgotten that hassubset isn't supported by that version of Microsoft.OData.Core, so the problem is more "not hooking 'custom' functions up properly". I _suspect_ therefore that it's on me (as implementor of hassubset) to make sure that the function signatures supplied support both collections and parenExprs.

**Comment by ElizabethOkerio** [comment]
feel free to reopen if you need any assistance
