### ISSUE TITLE
$select=a($expand=b) is not accepted

### ISSUE THREAD

**Issue by ificator** [OData/odata.net#2432]
According to the [OData ABNF](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt) the following is allowed, but it's rejected by `SelectExpandOptionParser`:

```
?$select=complex($expand=containednav)
```

### Assemblies affected

Microsoft.OData.Core 7.10.0

### Reproduce steps

Define a model like:
Singleton -> Complex Type -> Contained Navigation

Query the singleton and select/expand the complex type and navigation:
```
.../singleton?$select=complexType($expand=containedNavigation)
```

### Expected result

The request should parse correctly

### Actual result

The request fails to parse, stating:
```
Term '($expand=transcripts)' is not valid in a $select or $expand expression.
```

### Additional detail

The relevant ABNF is:
```
selectOption   = selectOptionPC
               / compute / select / expand / aliasAndValue
```

Queries like `$select=a($select=b)` work, but sub-expands do not.

Looking at `SelectExpandOptionParser.BuildSelectTermToken` I can see that just about every select option is mentioned in the switch EXCEPT for `expand`. It seems pretty trivial to add, but I'd like to understand if it was deliberately excluded in case there was a good reason for it.

**Comment by ificator** [comment]
I just noticed this in the [4.01 protocol documentation](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect):

*Allowed system query options are `$select` and `$compute` respectively for complex properties, plus `$filter`, `$search`, `$count`, `$orderby`, `$skip`, and `$top` for collection-valued properties.*

So now I'm confused because that seems to contradict the ABNF. I hope the ABNF is right because if it's not queries to expand a navigation property within a complex type are horrible:
```
?$select=complex($select=prop1,prop2)&$expand=complex/nav1
```

It's much nicer to write:
```
?$select=complex($select=prop1,prop2;$expand=nav1)
```

**Comment by xuzhg** [comment]
@ificator There was a discussion about '?$select=complex($expand=containednav)'. 

Current implementation and exception are by design,  and we considered 

`?$select=complex($expand=containednav)`  is same as 
`?$select=complex&$expand=complex/containednav`. 

@mikepizzo
