### ISSUE TITLE
Missing key when using reference URIs in Batch with $parameter

### ISSUE THREAD

**Issue by HHDanim** [OData/odata.net#2442]
I'd like to create two entities within a single changeset and also have the `Child` be linked to its corresponding `Parent`. The client generates a request that contains the reference URI `"Parent@odata.bind": "$1"` for the `Child.Parent` property.  When the action method `Post(Child child)` is called on the `ChildController` the key of the nested `Parent` object is always 0. If a fully qualified URL is supplied instead of "$1", e.g. "http://localhost:5254/odata/Parents(123)", the id is set correctly to 123.

### Assemblies affected

Microsoft.OData.Core 7.12.0

### Reproduce steps

Please have a look at this [repository](https://github.com/HHDanim/ODataBatchReferenceUriExample) which contains a sample Project and more information about the issue in the [Readme](https://github.com/HHDanim/ODataBatchReferenceUriExample/blob/master/Readme.md)  .

I use the following sample request to demonstrate the issue:

```txt
Content-Type:application/json
Accept:application/json
OData-MaxVersion:4.0
OData-Version:4.0
```

```json
{
  "requests": [
    {
      "id": "1",
      "method": "POST",
      "url": "http://localhost:5254/odata/Parents",
      "headers": {
        "OData-Version": "4.0",
        "Content-Type": "application/json;odata.metadata=minimal",
        "Accept": "application/json;odata.metadata=minimal"
      },
      "body": {}
    },
    {
      "id": "2",
      "method": "POST",
      "url": "http://localhost:5254/odata/Children",
      "headers": {
        "OData-Version": "4.0",
        "Content-Type": "application/json;odata.metadata=minimal",
        "Accept": "application/json;odata.metadata=minimal"
      },
      "body": {
        "Parent@odata.bind": "$1"
      }
    }
  ]
}
```
Accoding to [Reference URIs in an operation](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api#reference-uris-in-an-operation) this should be a valid request.

### Expected result

The `Child` object passed in to the `Post()` action method of the `ChildrenController` should look like this:

```cs
{
   ChildId: 0,
   ParentId: null,
   Parent: {
      ParentId: 123  // <----- expected
   }
}
```

### Actual result

```cs
{
   ChildId: 0,
   ParentId: null,
   Parent: {
      ParentId: 0  // <----- actual
   }
}
```

### Additional detail

I traced the calls down to the method `ODataJsonLightDeserializer.ReadAndValidateAnnotationStringValueAsUriAsync()`:

```cs
internal async Task<Uri> ReadAndValidateAnnotationStringValueAsUriAsync(string annotationName)
{
	string stringValue = await this.ReadAndValidateAnnotationStringValueAsync(annotationName)
		.ConfigureAwait(false);
	return this.ReadingResponse ? this.ProcessUriFromPayload(stringValue) : new Uri(stringValue, UriKind.RelativeOrAbsolute);
}
```

`ReadAndValidateAnnotationStringValueAsync(annotationName)` returns "$1" and `ReadingResponse` is false for my request. So a new `Uri`object with url "$1" is constructed, which is not a valid OData Uri an does not contain any entity key. I suspect that to be the reason why I always get the default value 0 for the `ParentId` property.

If I change the code to execute `this.ProcessUriFromPayload(stringValue)` instead, it returns the desired URL "http://localhost:5254/odata/Parents(123)" and the `ParentId` value is set to 123.

Is this not working as one would expect or am I getting something wrong? Thank you for any comments on this!

**Comment by gathogojr** [comment]
In addition could you specify which version on OData WebApi library you're using? You could also share a repro

**Comment by HHDanim** [comment]
Hi @gathogojr, thank you for having a look at this.

> Hi @HHDanim. Thank you for reporting this issue. Quick question, do the controller actions for the Post requests return the location of the newly created entities?

This is the reply for the request. Location headers are present and contain the key:

```json
{
    "responses": [
        {
            "id": "1",
            "status": 201,
            "headers": {
                "location": "http://localhost:5254/odata/Parents(123)",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5254/odata/$metadata#Parents/$entity",
                "ParentId": 123
            }
        },
        {
            "id": "2",
            "status": 201,
            "headers": {
                "location": "http://localhost:5254/odata/Children(1)",
                "content-type": "application/json; odata.metadata=minimal; odata.streaming=true",
                "odata-version": "4.0"
            },
            "body": {
                "@odata.context": "http://localhost:5254/odata/$metadata#Children/$entity",
                "ChildId": 1,
                "ParentId": null
            }
        }
    ]
}
```


> In addition could you specify which version on OData WebApi library you're using? You could also share a repro

I am using Microsoft.AspNetCore.OData 8.0.10.
You can find a small project in this [repository](https://github.com/HHDanim/ODataBatchReferenceUriExample).
