### ISSUE TITLE
ODataUriParser should allow duplicate non-OData query options

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/odata.net#245]
Our Web API exposes both OData and custom query options. Some of our query options allow duplicate values, but `ODataUriParser` throws an exception when it detects any duplicate query options (not just standard OData query options). This requires us to maintain a lot of code to work around this issue that we would rather not have to maintain.

ODataLib should have no opinions on whether it is valid to have duplicate custom query options. A Dictionary should only be used to hold OData query options, not custom query options (see `ODataUriParser.InitQueryOptionDic`).

**Comment by TomDu** [comment]
Non-OData query options are now exposed as a key-value list  in [`CustomODataQueryOptions`](https://github.com/TomDu/odata.net/blob/670abe58ddfaa64202ce770fe529cc2e92f8ab19/src/Microsoft.OData.Core/UriParser/ODataUriParser.cs#L181-L195).
