### ISSUE TITLE
ODataMessageWriter writes incorrect output when the writer does not implement IJsonStreamWriter

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2451]
ODataMessageWriter uses an `IJsonWriter` implementation to write JSON output. To write stream data (e.g. binary data or to pipe streams), OData provides an additional interface `IJsonStreamWriter` that exposes `StartStreamValueScope` and `StartTextWriterScope` which return a `Stream` and `TextWriter` respectively that the caller can write directly to.

The default `JsonWriter` implements both `IJsonWriter` and `IJsonStreamWriter`. When you write to the `Stream` returned by `JsonWriter.StartStreamScope`, the binary data will be converted internally into base64-encoded string by `JsonWriter` before being written to the final destination.

ODataMessageWriter does not require the `IJsonWriter` to also implement `IJsonStreamWriter`.  If you provide an `IJsonWriter` implementation that *does not* implement `IJsonStreamWriter`, then OData writer will fall back to a workaround that writes equivalent output using just the methods available on `IJsonWriter`. This would be less efficient, but the output should ideally be the same as if you had used an `IJsonStreamWriter`.

However, the fallback implementation is implemented differently in different places and does not always match the same output that you get with `IJsonStreamWriter.StartStreamValueScope`.

In [`ODataJsonLightWriter.StartBinaryStream()`](https://github.com/OData/odata.net/blob/277e17f8c688514a11ca77e93d78830b09fb88e9/src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs#L377), if the JSON writer is not `IJsonStreamWriter`, then it creates a memory stream (`jsonLightOutputContext.BinaryValueStream`) instead and returns it. Then in [`EndBinaryStream()`](https://github.com/OData/odata.net/blob/277e17f8c688514a11ca77e93d78830b09fb88e9/src/Microsoft.OData.Core/JsonLight/ODataJsonLightWriter.cs#L933), it converts the stream into a byte array and writes that using `jsonWriter.WriteValue`. The `IJsonWriter` will write the byte array as base64-encoded string. This is the expected behaviour.

In [`ODataJsonLightValueSerializer.WriteStreamValue`](https://github.com/OData/odata.net/blob/277e17f8c688514a11ca77e93d78830b09fb88e9/src/Microsoft.OData.Core/JsonLight/ODataJsonLightValueSerializer.cs#L377), the stream is read into a string using a `StreamReader` then written to the `IJsonWriter.WriterPrimitiveValue` which simply writes the string as-is. The `StreamReader` encodes the bytes into utf-8 string by default. Hence the written output is different from the base64-encoded string that you'd get with `IJsonStreamWriter`.

### Assemblies affected

Microsoft.OData.Core 7.12

### Reproduce steps

It's not easy to reproduce this in production because the default built-in `JsonWriter` already implements `IJsonStreamWriter`, so the issue doesn't occur unless the user provides a custom `IJsonWriter` implementation.

But you can reproduce it in tests/locally by modifying the `JsonWriter` definition such that it does not implement `IJsonStreamWriter` e.g.:

```diff
- class JsonWriter : IJsonStreamWriter, IJsonStreamWriterAsync
+ class JsonWriter : IJsonWriter, IJsonWriterAsync
```
Then run the following test: [`ODataJsonLightValueSerializerAsyncTests.WriteStreamValueAsync_WritesStreamValue`](https://github.com/OData/odata.net/blob/277e17f8c688514a11ca77e93d78830b09fb88e9/test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightValueSerializerAsyncTests.cs#L460). 

### Expected result

The test should pass.

### Actual result

The test fails:

![image](https://user-images.githubusercontent.com/8460169/177265443-0f578722-791b-484e-8ae1-b66817840b21.png)

### Additional detail

An easy fix to this issue would be to change the implementation in `ODataJsonLightValueSerializer.WriterStreamValue/Async` to read the stream into a byte array instead of a string, i.e.:

```diff
- this.JsonWriter.WritePrimitiveValue(new StreamReader(streamValue.Stream).ReadToEnd());
+ this.JsonWriter.WritePrimitiveValue(streamValue.Stream.ToArray());
```

If the existing behaviour was intentional (or if there are customers who happen to rely on this "feature"), then this would be a breaking change.

**Comment by gathogojr** [comment]
Fixed by #2416
