### ISSUE TITLE
Untyped JSON

### ISSUE THREAD

**Issue by kumarseetharaman** [OData/odata.net#248]
Definition of opentype extension:

```xml
<EntityType Name="OpenTypeExtension" OpenType="true">
      <Key><PropertyRef Name="Key"/></Key>
      <Property Name=“Key" Type="Edm.String"/>
</EntityType>
```

Support needed for the following cases:
 
Case 1:
```
POST https://{serviceroot}/Entities('Id')/extensions
{
   @odata.type: "OpenTypeExtension",
   "Key" : "Value1",
   "InlineComplexType" :
	{
         	“Prop1": "Val1",
 	 	“Prop2": "Val2",
                ...
	},	
}
```

Case 2. 
```
POST https://{serviceroot}/Entities('Id')/extensions
{
   @odata.type: "OpenTypeExtension",
   "Key" : "Value1",   
   "ArrayOfComplexTypes" : [
	{
         	"Street": "123 Main street",
 	 	"State": "WA",
         	"Zip": "98001"
	},
         	{
         	 "Street": "345 Elm street",
 	 	 "State": "LA",
         	 "Zip": "90001"
	},
         	{
         	 "Street": "789 Cedar street",
 	 	 "State": "LA",
         	 "Zip": "90002"
	}
      ]
}
```

**Comment by kumarseetharaman** [comment]
Definition got cut off for some reason - including it:
Definition of opentype extension:

<EntityType Name="OpenTypeExtension" OpenType="true">
      <Key><PropertyRef Name="Key"/></Key>
      <Property Name=“Key" Type="Edm.String"/>
   </EntityType>

**Comment by congysu** [comment]
This is for untyped json support.

Task list:
* Add ODataUntypedValue to object model #315
* Write untyped json property for entry #317
* Write untyped json property for feed, complex type #319
* Optional - Add an untype json property in a feed #318
* Read untyped json property for entry #320
* Read untyped json property for feed, complex type #321

**Comment by zlatko-michailov** [comment]
Please assign #315 and #317 to me. 

#319 and #318 should work, but we need to write tests in order to close them.

**Comment by challenh** [comment]
That is supported now, test cases can be found at https://github.com/OData/odata.net/blob/ODataV4-7.x/test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightEntryAndFeedDeserializerUndeclaredTests.cs
