### ISSUE TITLE
Containment with multiple expand levels not working

### ISSUE THREAD

**Issue by HenkHui** [OData/odata.net#249]
I have a problem with contained entities as described by me on Stackoverflow:

http://stackoverflow.com/questions/30999657/odata-containment-with-multiple-expand-levels-not-working

Is this an issue in the containment implementation or am I doing something wrong?

**Comment by congysu** [comment]
`messageType` does not have a binding to specify it belongs to which entity set.  Either use your workaround, or change the messageType to be contained as well.

**Comment by AlanWong-MS** [comment]
Closing as issue has aged and congysu provided a response. Please re-open if issue persists. Thanks!
