### ISSUE TITLE
Current Nuget build 7.12.3 seems to be published as debug build

### ISSUE THREAD

**Issue by henning-krause** [OData/odata.net#2510]
I created a benchmark program to test the speed of my ODATA service and got this output from benchmark.net (my program was compiled in "Release" mode):

```
Assembly odata which defines benchmarks references non-optimized Microsoft.OData.Client
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.WithOptions(ConfigOptions.DisableOptimizationsValidator)'.
Assembly odata which defines benchmarks references non-optimized Microsoft.OData.Edm
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.WithOptions(ConfigOptions.DisableOptimizationsValidator)'.
Assembly odata which defines benchmarks references non-optimized Microsoft.OData.Core
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.WithOptions(ConfigOptions.DisableOptimizationsValidator)'.
```

And when decompiling the DLLs I find this line in the decompiled code:
```cs
[assembly: AssemblyConfiguration("Debug")]
```

Indeed, compared to version 7.12.2, the performance dropped noticable.

Can it be that the latest release was compiled in "Debug" mode?

### Assemblies affected

Microsoft.OData.Client
Microsoft.OData.Edm
Microsoft.OData.Core

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

* Create a program that uses odata and use version 7.12.3. 
* Measure the speed of the pogram
* Downgrade to 7.12.2
* Notice that the performance improves.

### Expected result

* No performance regression

### Actual result

* Performance drops significantly

**Comment by habbes** [comment]
@henning-krause thanks for reporting this. Let us investigate this and revert back.

**Comment by habbes** [comment]
@henning-krause version 7.12.4 has been released.
