### ISSUE TITLE
oData Client "JIT compile method" error when build to IOS device

### ISSUE THREAD

**Issue by FirewizzNL** [OData/odata.net#2513]
When using the ODAta client and build to an IOS device ARM64 the code crashes because an "JIT COMPILE" error. This is caused because the IOS compiler (nano) builds AOT(ahead of time).
Info:
 - https://learn.microsoft.com/nl-nl/xamarin/ios/internals/limitations
 - https://www.mono-project.com/docs/advanced/aot/#full-aot

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*
Microsoft.OData.Client
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/Microsoft.OData.Client.cs

### Reproduce steps
Simple oData GET, using library on release build IOS using:
```
var context = new Container(new Uri("API _URI"));
var employee = context.Employees.Where(e => e.Id == 433).Single();
```

### Expected result
OData returning the result. Which it does in debug/simulator, but not when compiled as release.

### Actual result
Error/Exception:
`Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_EmployeeModel_int(EcotouchApi.Models.EcoTouchDbModels.EmployeeModel,int)' while running in aot-only mode.`

*What is actually happening.*
Attemptint a JIT compile method in AOT mode.

### Additional detail
This is not only here, I see multiple issues regarding JIT compile in AOT mode without proper solutions.

**Comment by habbes** [comment]
I think this is due to the IL that we generate at runtime during materialization/projection of `ODataResource` response payloads into the user defined CLR objects. I don't think there's an easy way around this. I think it may be possible to run the generated IL through an interpreter instead of a JIT compiler, haven't looked into the feasibility of this, but I can find out and revert back. But even if feasible, it may have other limitations (e.g. performance).

**Comment by FirewizzNL** [comment]
https://github.com/dotnet/maui/issues/10312

**Comment by habbes** [comment]
@FirewizzNL I've gone through the linked thread on .NET MAUI and it appears that the issue was resolved when you enabled the interpreter, is that correct?

**Comment by FirewizzNL** [comment]
Yes that is true.

**Comment by habbes** [comment]
Awesome, the solution was much simpler than I anticipated, I was experimenting with using the [`Expression.Compile(preferInterpretation: bool)`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=net-6.0#system-linq-expressions-expression-1-compile(system-boolean)) overload.

**Comment by habbes** [comment]
Closing this issue since it has been resolved.
