### ISSUE TITLE
CsdlWriter.TryWriteCsdl does not flush xml writer

### ISSUE THREAD

**Issue by groogiam** [OData/odata.net#2522]
CsdlWriter.TryWriteCsdl does not flush xml writer. This may be by design but it caused some confusion recently and want to verify the expected functionality. If it is by design then perhaps the xml comment should be updated to reflect this.

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

Microsoft.OData.Edm.dll 7.12.3

### Reproduce steps

```csharp
        var sb = new StringBuilder();
        using var xw = XmlWriter.Create(sb, new XmlWriterSettings
        {
            Encoding = Encoding.UTF8,
            Indent = true,
            OmitXmlDeclaration = true,
            ConformanceLevel = ConformanceLevel.Fragment
        });
        
        var success = CsdlWriter.TryWriteCsdl(model, xw, CsdlTarget.OData, out var errors);

        if (!success)
        {
            return null;
        }

        xw.Flush(); //this is required and seems like it really should not be

        return sb.ToString();
```

### Expected result

The TryWriteCsdl method would flush the XmlWriter

### Actual result

TryWriteCsdl is not flushing the XmlWriter

**Comment by habbes** [comment]
@gathogojr  @groogiam  While I am not opposed to a PR "fixing" this issue, I'm not convinced that this is an issue. It is common for Write methods not to flush the writer. The fact that the sample code above is declaring the `XmlWriter` with a `using` keyword means that it will be disposed at the end of method, when the local scope exits. So there should be no expectation that the contents would have been flushed before then unless the user explicitly calls `Flush`. If the user wants to guarantee that the written contents are available in the destination stream at a certain point, it is more reliable to manually flush or using a `using` block with a limited scope.

We might "fix" this particular request by forcing `CsdlWriter.TryWriteCsdl()` to flush, but this will be inconsistent with other `Write` methods in the library and .NET. The `XmlWriter`'s own Write APIs are not guaranteed to flush. Same goes for StreamWriter and other writers. The issue would face the same issue if they used those writers and would have to explicitly flush.

Again, not opposed to the proposed "fix", but I think it's safer to not have the expectations that Write methods are guaranteed to flush.

cc @corranrogue9

**Comment by groogiam** [comment]
I think the disconnect for me here was using the newer C# 8 using syntax which does not dispose until the end of the method rather than using an explicit using block. If not flushing the stream is consistent with other `Write` methods in this library and .NET then I understand leaving the code as is.
