### ISSUE TITLE
ArgumentException in Microsoft.OData.Client 7.12.3 and 7.12.4

### ISSUE THREAD

**Issue by KristianHebert** [OData/odata.net#2531]
Since version 7.12.3 we have gotten an ArgumentException: Incorrect number of arguments supplied for call to method 'Boolean ProjectionCheckValueForPathIsNull.
Apparantly the error arises because we have the following Select:
```
await ((DataServiceQuery<DivisionData>)container.Divisions.Where(d => d.DivisionId == id)
            .Select(d => new DivisionData
            {
                Division = d,
                EmailTemplateName = d.EmailTemplate == null ? null : d.EmailTemplate.Name,
                Keys = d.D2bKeys.Select(p => ValueTuple.Create(p.KeyVersion, p.KeyDate))
            })).ExecuteAsync();
```
The trinary operator is the culprit, but this worked in version 7.12.2 and earlier.
### Assemblies affected

It works when we have Microsoft.Odata.Client 7.12.2 or earlier installed.
We get the error when we have 7.12.3 or 7.12.4 installed.

### Reproduce steps

Any query we make with conditional access as above, wil reproduce the error.

### Expected result

We expect the query to be performed and a result to be returned.

### Actual result

We get an exception.

### Additional detail

Exception details:
  Message: 
Test method TestOtxDataAccess.OData.DivisionDaoTest.TestGetDivision threw exception: 
System.ArgumentException: Incorrect number of arguments supplied for call to method 'Boolean ProjectionCheckValueForPathIsNull(System.Object, System.Type, System.Object, Microsoft.OData.Client.Materialization.IODataMaterializerContext)' (Parameter 'method')

  Stack Trace: 
ExpressionUtils.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)
Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
Expression.Call(MethodInfo method, Expression[] arguments)
DynamicProxyMethodGenerator.WrapOriginalMethodWithExpression(MethodBase method, Expression[] arguments)
DynamicProxyMethodGenerator.GetCallWrapper(MethodBase method, Expression[] arguments)
ProjectionPlanCompiler.CallMaterializerWithType(String methodName, Type[] typeArguments, Expression[] arguments)
ProjectionPlanCompiler.CallMaterializer(String methodName, Expression[] arguments)
ProjectionPlanCompiler.CallCheckValueForPathIsNull(Expression entry, Expression entryType, ProjectionPath path)
ProjectionPlanCompiler.RebindConditionalNullCheck(ConditionalExpression conditional, MatchNullCheckResult nullCheck)
ProjectionPlanCompiler.VisitConditional(ConditionalExpression conditional)
ALinqExpressionVisitor.Visit(Expression exp)
ProjectionPlanCompiler.Visit(Expression exp)
ALinqExpressionVisitor.VisitMemberAssignment(MemberAssignment assignment)
ALinqExpressionVisitor.VisitBinding(MemberBinding binding)
ALinqExpressionVisitor.VisitBindingList(ReadOnlyCollection`1 original)
ALinqExpressionVisitor.VisitMemberInit(MemberInitExpression init)
ProjectionPlanCompiler.VisitMemberInit(MemberInitExpression init)
ALinqExpressionVisitor.Visit(Expression exp)
ProjectionPlanCompiler.Visit(Expression exp)
ProjectionPlanCompiler.VisitLambda(LambdaExpression lambda)
ALinqExpressionVisitor.Visit(Expression exp)
ProjectionPlanCompiler.Visit(Expression exp)
ProjectionPlanCompiler.CompilePlan(LambdaExpression projection, Dictionary`2 normalizerRewrites, IODataMaterializerContext materializerContext)
ODataEntityMaterializer.CreatePlan(QueryComponents queryComponents, IODataMaterializerContext materializerContext)
ODataEntityMaterializer.ctor(IODataMaterializerContext materializerContext, EntityTrackingAdapter entityTrackingAdapter, QueryComponents queryComponents, Type expectedType, ProjectionPlan materializeEntryPlan)
ODataReaderEntityMaterializer.ctor(ODataMessageReader odataMessageReader, ODataReaderWrapper reader, IODataMaterializerContext materializerContext, EntityTrackingAdapter entityTrackingAdapter, QueryComponents queryComponents, Type expectedType, ProjectionPlan materializeEntryPlan)
ODataMaterializer.CreateMaterializerForMessage(IODataResponseMessage responseMessage, ResponseInfo responseInfo, Type materializerType, QueryComponents queryComponents, ProjectionPlan plan, ODataPayloadKind payloadKind, MaterializerCache materializerCache)
MaterializeAtom.ctor(ResponseInfo responseInfo, QueryComponents queryComponents, ProjectionPlan plan, IODataResponseMessage responseMessage, ODataPayloadKind payloadKind, MaterializerCache materializerCache)
DataServiceRequest.Materialize(ResponseInfo responseInfo, QueryComponents queryComponents, ProjectionPlan plan, String contentType, IODataResponseMessage message, ODataPayloadKind expectedPayloadKind, MaterializerCache materializerCache)
QueryResult.CreateMaterializer(ProjectionPlan plan, ODataPayloadKind payloadKind)
QueryResult.ProcessResult[TElement](ProjectionPlan plan)
DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)
DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)
TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
DivisionDao.GetDivisionViewAsync(Int32 id, Container container) line 56
DivisionDao.GetDivisionAsync_(Int32 id) line 40
OtxObjectCache.InternalGetOrCreateAsync[T](String region, Int32 timeout, CachingPolicy cachingPolicy, Func`1 createMethod, Object[] key)
DivisionDao.GetDivisionAsync(Int32 id) line 39
DivisionDaoTest.TestGetDivision(Int32 id, Int32 expectedCustomerId, String expectedName, Nullable`1 expectedKeyVersion, Boolean expectedIsActive) line 45
ThreadOperations.ExecuteWithAbortSafety(Action action)

**Comment by habbes** [comment]
I suspect this may have something to do with the changes I made to the materializer that required the materializer context to be passed to every method.

**Comment by mikepizzo** [comment]
Clement to investigate whether we are calling instances of changed methods through reflection.

**Comment by habbes** [comment]
Hi @KristianHebert I have not been able to reproduce the issue on my end. I have tried creating a requests similar to yours, with a ternary operator checking for null, with an embedded `Select()` call, etc. However, they return the expected results on my end. E.g.:

```c#
var uri = new Uri("https://services.odata.org/V4/(S(3jjpqgfjmnsmsy4twnnqedz3))/TripPinServiceRW");
var ctx = new DefaultContainer(uri);

var airports = await (ctx.Airports.Where(a => a.Name != null).Select(a =>
new AirportResult
{
    Airport = a,
    Name = a.Name,
    Address = a.Location == null ? null : a.Location.Address,
}) as DataServiceQuery<AirportResult>).ExecuteAsync();

foreach (var a in airports)
{
    Console.WriteLine($"{a.Name}, {a.Address}. {a.Airport.IataCode}");
}
```

Could you share more info about your setup, maybe show how your making that call in a larger context, or share more information about your model and proxy classes. If you can share a self-contained program that fails or a step-by-step process that reproduces the error, that would also be great.

**Comment by habbes** [comment]
I've managed to reproduce the error when doing the null check against a navigation property. It seems it will fail if the object is an instance of an entity type, but it does not fail if it's a complex type.

**Comment by KristianHebert** [comment]
Great, you don't need anything from me then?

**Comment by premiaware** [comment]
i have update from 7.12.2 to 7.14.1 and i have this issue:

using this query;
from comuni in _containerPrimario.Comuni
   where comuni.ID == ID
   select new ComuneProvinciaBridge
   {
       Comune = new ComuniBridge
       {
           ID = comuni.ID,
           Denominazione = comuni.Denominazione
       },
       Provincia = new ProvinceBridge
       {
           ID = comuni.Province.ID,
           Denominazione = comuni.Province.Denominazione,
           Sigla = comuni.Province.Sigla
       }
   }

{"Incorrect number of arguments supplied for call to method 'System.Object ProjectionGetEntry(System.Object, System.String, Microsoft.OData.Client.Materialization.IODataMaterializerContext)'\r\nParameter name: method"}

"   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)\r\n   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)\r\n   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.GetDeepestEntry(Expression[] path)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.RebindEntityMemberInit(MemberInitExpression init)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.VisitMemberInit(MemberInitExpression init)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.VisitMemberAssignment(MemberAssignment assignment)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.VisitBinding(MemberBinding binding)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.VisitBindingList(ReadOnlyCollection`1 original)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.VisitMemberInit(MemberInitExpression init)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.VisitMemberInit(MemberInitExpression init)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.VisitLambda(LambdaExpression lambda)\r\n   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)\r\n   at Microsoft.OData.Client.ProjectionPlanCompiler.CompilePlan(LambdaExpression projection, Dictionary`2 normalizerRewrites, IODataMaterializerContext materializerContext)\r\n   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.CreatePlan(QueryComponents queryComponents, IODataMaterializerContext materializerContext)\r\n   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer..ctor(IODataMaterializerContext materializerContext, EntityTrackingAdapter entityTrackingAdapter, QueryComponents queryComponents, Type expectedType, ProjectionPlan materializeEntryPlan)\r\n   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer..ctor(ODataMessageReader odataMessageReader, ODataReaderWrapper reader, IODataMaterializerContext materializerContext, EntityTrackingAdapter entityTrackingAdapter, QueryComponents queryComponents, Type expectedType, ProjectionPlan materializeEntryPlan)\r\n   at Microsoft.OData.Client.Materialization.ODataMaterializer.CreateMaterializerForMessage(IODataResponseMessage responseMessage, ResponseInfo responseInfo, Type materializerType, QueryComponents queryComponents, ProjectionPlan plan, ODataPayloadKind payloadKind, MaterializerCache materializerCache)\r\n   at Microsoft.OData.Client.MaterializeAtom..ctor(ResponseInfo responseInfo, QueryComponents queryComponents, ProjectionPlan plan, IODataResponseMessage responseMessage, ODataPayloadKind payloadKind, MaterializerCache materializerCache)\r\n   at Microsoft.OData.Client.QueryResult.CreateMaterializer(ProjectionPlan plan, ODataPayloadKind payloadKind)\r\n   at Microsoft.OData.Client.QueryResult.ProcessResult[TElement](ProjectionPlan plan)\r\n   at Microsoft.OData.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)\r\n   at Microsoft.OData.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location ---\r\n   at AppData.Services.DataRepository.<>c__DisplayClass353_0.<<TrovaComuneAsync>b__0>d.MoveNext() in C:\\Work\\UniversalApps\\FastHomeMobile\\FastHomeMobile.LogicUI\\DataServices\\ComuniRegioniNazioni.cs:line 336\r\n   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()\r\n   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()\r\n   at Polly.AsyncPolicy.<ExecuteAsync>d__12.MoveNext()\r\n   at AppData.Services.DataRepository.<TrovaComuneAsync>d__353.MoveNext() in C:\\Work\\UniversalApps\\FastHomeMobile\\FastHomeMobile.LogicUI\\DataServices\\ComuniRegioniNazioni.cs:line 305"

**using 7.12.2 all working OK!**
