### ISSUE TITLE
Microsoft.OData.UriParser.ODataUriResolver!FindSchemaElements running hot on CPU

### ISSUE THREAD

**Issue by joaocpaiva** [OData/odata.net#2534]
This callstack is taking up to 6% on CPU, in many regions.

We already did meaningful improvements to this code path in OData but it is still too expensive. There seems to be a lot of room to reduce CPU from this callstack. Are we doing O(n) searches in FindAcrossModels that can be cached and become O(1) operations?

This callstack has huge potential to cut down CPU and reflect to COGs (i.e., running less number of VMs for the same traffic).

![image](https://user-images.githubusercontent.com/24846248/197061548-7c191c7b-912d-4b3f-9c4d-3d6531a9e625.png)

### Assemblies affected

Microsoft.OData.Core lib 7.12.2

### Reproduce steps

A variety of requests that all go through Microsoft.OData.UriParser.ODataUriParser!ParsePath

### Expected result

Using much less CPU to parse requests

### Actual result

Using up to 6% of CPU to parse requests

cc: @habbes

**Comment by habbes** [comment]
Looking at the `ODataUriResolver.FindAcrossModels` method, it is doing a full scan of the all the schema elements in the model and referenced models to find all results that match the input name. I think the model's `model.FindDeclaredType()` would be more efficient.

This is probably called by `ODataPathParser.TryCreateTypeSegment`->`UriEdmHelpers.FindTypeFromModel` -> `ODataUriResolver.ResolveType`. 

`ODataUriResolver.ResolveType` has the following implementation:

```c#
public virtual IEdmSchemaType ResolveType(IEdmModel model, string typeName)
{
    IEdmSchemaType type = model.FindType(typeName);
    if (type != null || !EnableCaseInsensitive)
    {
        return type;
    }

    IList<IEdmSchemaType> results = FindAcrossModels<IEdmSchemaType>(model, typeName, /*caseInsensitive*/ true);

    if (results == null || results.Count == 0)
    {
        return null;
    }

    if (results.Count > 1)
    {
        throw new ODataException(Strings.UriParserMetadata_MultipleMatchingTypesFound(typeName));
    }

    return results[0];
}
```

If it's getting to `ODataUriResolver.FindAcrossModels`, then the first if statement is returning false. This means the type wasn't found with `model.FindType()` and the case-insensitivity has been enabled.

So, first question would be whether you have case-insensitive mode enabled @joaocpaiva 

The other thing is that `FindAcrossModels` does a full scan to find all matches and throws an exception if there are more than 1 match. So, even if it we'd short-circuit the search when it finds a duplicate, we'd still have the worst case in the ideal case where there are no duplicates.

Should we cache the results with a normalized case-insensitive key?

**Comment by joaocpaiva** [comment]
We do have case-insensitive enabled.

2 scenarios that can exercise this path:
- garbage input, i.e., something that doesn't exist in schema nor is an existing dynamic property of an open type
- all dynamic properties of open types, e.g., /users/clement/myDynamicProperty

Maybe adding an optional feature to use a case-insensitive cache (built upfront) which include types from referenced models?
