### ISSUE TITLE
[Feature] Add support for ExplicitOperationBindings

### ISSUE THREAD

**Issue by irvinesunday** [OData/odata.net#2543]
By default, we do not bind operations to non-containment navigation properties. We, however, have certain scenarios where we might need this binding. There were deliberations around this and the following was proposed by @mikepizzo 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/40403681/199009227-40b1e3e6-24c8-43eb-8a77-4a7827ead132.png)

However, in order to use the annotation `ExplicitOperationBindings`, we need the `ModelElementPath` expression defined in the edm library to be able to represent an EDM model element path.

### Assemblies affected

Microsoft.OData.Edm `7.10.0`

### Reproduce steps

None. This is a new feature request.

### Expected result

To be able to retrieve the value expressed by the `ModelElementPath` expression. 
Open questions:
1. Are we able to retrieve the target EDM element? 
2. If the target EDM element is a navigation property, can we also retrieve its declaring entity type?

### Actual result

None. This is a new feature request.

### Additional detail

Related to: https://github.com/microsoft/OpenAPI.NET.OData/issues/232

**Comment by mikepizzo** [comment]
While adding support for IEdmModelElementPath is a good improvement, note that the initial proposal for this particular application (constraining actions/functions to particular paths) has evolved. The [final proposal](https://issues.oasis-open.org/browse/ODATA-1538#) does not require model element path:

```xml
<Term Name="RequiresExplicitBinding" Type="Core.Tag" DefaultValue="true" AppliesTo="Action, Function">
  <Annotation Name="Description" Edm.String="This bound action or function is only available on model elements annotated with the ExplicitOperationBinding term."/>
</Term>

<Term Name="ExplicitOperationBindings" Type="Collection(Edm.String)"> 
   <Annotation Name="Description" Edm.String="The qualified names of explicitly bound operations that are supported on the target model element. These bindings are in addition to any bindings to the type of the target model element not annotated with RequiresExplicitBinding"/> 
</Term>

```

**Comment by irvinesunday** [comment]
The proposal will have to officially be approved and the new Terms added to the `OData.Edm` lib before they can be used, correct?

**Comment by mikepizzo** [comment]
The proposal has been approved. We are working on implementing.

**Comment by mikepizzo** [comment]
Updated comment since the approved vocabulary terms don't require IEdmModelElementPath.

**Comment by mikepizzo** [comment]
Link to related OASIS PR: https://github.com/oasis-tcs/odata-vocabularies/pull/214.

**Comment by habbes** [comment]
@irvinesunday @mikepizzo @lisicase seems like the `ExplicitOperationBindings` and `RequiresExplicitBinding` terms have already been added to the Edm library by this PR: https://github.com/OData/odata.net/pull/2614
Seeing that `IEdmModelElementPath` is no longer required for this feature, is there any additional work pending for this task or is it good to go?

**Comment by irvinesunday** [comment]
@habbes @mikepizzo @lisicase thanks a bunch for this fix. We have already implemented this and gotten unblocked ❤
