### ISSUE TITLE
Install/update of nightly nuget package fails

### ISSUE THREAD

**Issue by Casimodo72** [OData/odata.net#255]
Hi, I'm not able to update (or install newly) the nightly packages for some time now (1-2 weeks).
I thought maybe it's temporary thingy, but it just does not want to go away for me.

I'm in a VS 2015 RC Enterprise, Framework 4.5.1, ASP.NET  MVC/WebAPI/OData project and have "Microsoft.AspNet.OData 5.7.0-beta-150629-Nightly" installed.
Also using the nightly ASP stack packages, which are up-to-date here as of today. 

E.g. when trying to install Microsoft.OData.Core (6.13.0-Nightly20150629):

Unable to find a version of 'Microsoft.OData.Edm' that is compatible with 'Microsoft.OData.Core 6.13.0-Nightly20150629 constraint: Microsoft.OData.Edm (= 6.13.0-beta-Nightly20150629)

Trying to install just Microsoft.Spatial (6.13.0-Nightly20150629):

Unable to find a version of 'Microsoft.OData.Core' that is compatible with 'Microsoft.AspNet.OData 5.7.0-beta-150629-Nightly constraint: Microsoft.OData.Core (≥ 6.11.0 && < 7.0.0)', 'Microsoft.OData.Client 6.12.0-Nightly20150511 constraint: Microsoft.OData.Core (= 6.12.0-Nightly20150511)'

Here I also wonder why a dependency to Microsoft.OData.Client pops up.

Is there maybe something in the ASP stack (nightly) that produces some indirect dependencies so that we cannot use the current ODataLib?

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment]
Maybe my conflict is due to the following: why are there beta and non-beta packages?
"6.13.0-Nightly20150629"
"6.13.0-**beta**-Nightly20150629"

**Comment by Casimodo72** [comment]
NuGet (https://www.myget.org/F/aspnetwebstacknightly/) displays for Microsoft.OData.Core 6.13.0-Nightly20150629 the following (would be nice if the NuGet info was copy&paste -able):
Dependencies
Any,Version=v0.0
Microsoft.Spatial (=6.13.0-**beta**-Nightly20150629)
Microsoft.OData.Edm (= 6.13.0-**beta**-Nightly20150629)

But the version displayed for those packages does not have the "beta".

**Comment by Casimodo72** [comment]
Upgrade of packages still not working. I wonder how you guys expect foreign feedback if one cannot install the current nightly packages ;-)
So let my try this again. I'm using
NuGet V 3.0.60602.486 installed on 2015-06-04
VS 2015 RC Enterprise
Newest nightly ASP Web Stack packags installed

Today the package manager shows this error when trying to upgrade to "Microsoft.OData.Client 6.13.0-Nightly20150713":

Unable to find a version of 'Microsoft.OData.Core' that is compatible 
with 'Microsoft.AspNet.OData 5.7.0-beta-150713-Nightly 
constraint: Microsoft.OData.Core (= 6.11.0 && < 7.0.0)', 
'Microsoft.OData.Client 6.13.0-Nightly20150713 
constraint: Microsoft.OData.Core (= 6.13.0-**rc**-Nightly20150713)' 

This is the same issue as before. NuGet shows versions without the **rc** and under package dependencies *with* the **rc**. Thus it can't resolve the dependencies.

Am I the only one on this planet who is confronted with this issue?

**Comment by Casimodo72** [comment]
With the install failing for me, I can't build with the latest OData Web Api package.
See https://github.com/OData/WebApi/issues/433

**Comment by Casimodo72** [comment]
Reproducible steps:

1) Use VS 2015 RC

2) Create a new web project (MVC, WEB API)

3) Change project from .NET 4.5 to .NET 4.5.1

4) Try to install Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly using package source: https://www.myget.org/F/aspnetwebstacknightly/

5) The following error occurs:
Attempting to gather dependencies information for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with respect to project 'Ga.Web', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
Resolved actions to install package 'Microsoft.AspNet.OData.5.7.0-beta-150713-Nightly'
Unable to find metadata of Microsoft.OData.Client 6.12.0-Nightly20150611

Note that the installation works fine if one uses .NET 4.5 instead of .NET 4.5.1. I'm using 4.5.1 and it worked a month ago for me, but not anymore.

**Comment by Casimodo72** [comment]
Ok, issue solved. I wrote in the other thread about my solution: Essentially never ever again trying to use the ODataLib nightly packages and a mixture of .NET framework version and dependency behavior.

**Comment by congysu** [comment]
Change the dependency: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Build.NuGet/Microsoft.OData.Core.Nightly.Release.nuspec#L18-L19

**Comment by LianwMS** [comment]
Close with a7542ad5e83e06256cb71780c2cedebfcd77853b submitted

**Comment by Casimodo72** [comment]
@congysu: Thanks for the fix! This really healed the issue. I can now upgrade from both package sources :-)
