### ISSUE TITLE
Using OData client, attempting to delete link for m:m relationship deletes table instead

### ISSUE THREAD

**Issue by stebay** [OData/odata.net#256]
Using the Microsoft OData (v4) client and the T4-generated client code, links to a related entity can be created by adding to the collection property on the entity for the related entity (using a DataServiceCollection for change tracking).  However trying to remove a link (in the same way one would with the entity framework) instead results in the client issuing a request to delete the related entity, rather than removing the link.

The following SQL Server 2012 tables are used in the code below (main columns only)
- tblTestRestaurant
  - RestaurantID (int, PK)
  - RestaurantName (nvarchar(80))
  - TS (timestamp)
- tblTestDish
  - DishID (int, PK)
  - DishName (nvarchar(50))
  - TS (timestamp)
- tblTestRestaurantDish
  - RestaurantID (int, FK to RestaurantID in tblTestRestaurant)
  - DishID (int, FK to DishID in tblTestDish)

The following code reproduces the issue.

``` C#
// ctx is the OData T4-generated client DataServiceContext
var ctx = GetCtx();

// add restaurant
var restaurant = new tblTestRestaurant()
{
    RestaurantID = 1,
    RestaurantName = "TestRestaurant1"
};
ctx.AddTotblTestRestaurant(restaurant);

// add dish
var dishToAdd = new tblTestDish()
{
    DishID = 1,
    DishName = "TestDish1"
};
ctx.AddTotblTestDish(dishToAdd);

// save
ctx.SaveChanges(SaveChangesOptions.BatchWithSingleChangeset);

// get restaurant and related dishes, tracked
ctx = GetCtx();
var rest = new DataServiceCollection<tblTestRestaurant>(ctx.tblTestRestaurant.Expand(e => e.tblTestDishes).Where(r => r.RestaurantName == "TestRestaurant1"));

// get dish
var dish = new DataServiceCollection<tblTestDish>(ctx.tblTestDish.Where(d => d.DishName == "TestDish1"));

// assign dish to restaurant
rest.First().tblTestDishes.Add(dish.First());
// save
ctx.SaveChanges(SaveChangesOptions.BatchWithSingleChangeset);

ctx = GetCtx();
// get restaurant and related dishes, tracked
rest = new DataServiceCollection<tblTestRestaurant>(ctx.tblTestRestaurant.Expand(e => e.tblTestDishes).Where(r => r.RestaurantName == "TestRestaurant1"));

// get dish
dish = new DataServiceCollection<tblTestDish>(ctx.tblTestDish.Where(d => d.DishName == "TestDish1"));

// remove dish from restaurant
rest.First().tblTestDishes.Remove(dish.First());

// fails, underlying (server) error is 
// The DELETE statement conflicted with the REFERENCE constraint \"FK_tblTestRestaurantDish_tblTestDish\".
// i.e. it is trying to delete the tblDish, not the tblTestRestaurantDish
ctx.SaveChanges(SaveChangesOptions.BatchWithSingleChangeset);
```

Looking at the request generated by the client for the last SaveChanges (using Fiddler) it is attempting to delete a tblTestDish (the rest of the batch request ommitted for brevity here)

```
DELETE http://developer4:8080/odata/tblTestDish(1) HTTP/1.1
If-Match: W/"YmluYXJ5J0FBQUFBQUFBcGpZPSc="
OData-Version: 4.0
OData-MaxVersion: 4.0
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services
```

I would expect a DELETE to the following URL:

```
http://developer4:8080/odata/tblTestRestaurant(1)/tblTestDishes/$ref$id=http://developer4:8080/odata/tblTestDish(1) 
```

**Comment by congysu** [comment]
@stebay You can use `DeleteLink`
```c#
dsc.DeleteLink(person, "Friends", oneFriend);
```
http://odata.github.io/odata.net/

**Comment by stebay** [comment]
Thanks - I am currently using DeleteLink as a work-around.

I would expect the semantics of removing an object from a collection property to mean that I want to remove the relationship, and not delete the object - that's how it works for example in the Entity Framework.

In OO semantics if I remove an object from a collection, but another object has a reference to it then it wouldn't be deleted (garbage-collected).

**Comment by mikepizzo** [comment]
RemoveLink was designed to perform the behavior you expect, in order that we could use Remove() to delete the actual object. Perhaps we should have used Remove() to remove the link and added a Delete() (or equivalent) to do the delete. Unfortunately, there's no good way to fix this as it would be a breaking change to change this at this point.
