### ISSUE TITLE
Query with $select causes error 500 but works in a browser

### ISSUE THREAD

**Issue by koldomon** [OData/odata.net#2567]
I try to query Navision with OData, but when I include a $select, the query return Error 500. When I try the exact same query in a browser, the expected result is returned. I have no clue if this is a problem of the client or the server or what's happening at all.

### Assemblies affected
Microsoft.OData.Client: 7.12.5
Microsoft.OData.Core: 7.12.5
Microsoft.OData.Edm: 7.12.5
Microsoft.OData.Extensions.Client: 1.0.6
Microsoft.OData.Extensions.Client.Abstract: 1.0.6

### Reproduce steps
`var client = new NAV(svcRoot, ODataProtocolVersion.V4); //NAV is generated with "OData Connected Service"
var query3 = client.Abholbescheide.OrderBy(x => x.Customer_No).Take(10).Select(x => new { x.Customer_No, x.EAR_Status_Text });
Log.Debug(query3.ToString()); // prints http://%secret%/Abholbescheide?$orderby=Customer_No&$top=10&$select=Customer_No,EAR_Status_Text

var list3 = query3.ToList();
Log.Information($"Abholbescheide: {list3.Count} Items");`

### Expected result

should return a list with 10 items (only with [Customer_No] and [EAR_Status_Text]

### Actual result

Exception thrown: 'Microsoft.OData.Client.DataServiceQueryException' in Microsoft.OData.Client.dll
An error occurred while processing this request.

[15:00:13 ERR] An error occurred while processing this request.
Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request.
 ---> Microsoft.OData.Client.DataServiceClientException: {"error":{"code":"","message":"An error has occurred."}}
 ---> Microsoft.OData.ODataErrorException: An error was read from the payload. See the 'Error' property for more details.
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.OData.Client.DataServiceQuery`1.Execute()
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at %secret%.Program.Main(String[] args) in C:\code\test

### Additional detail

when i take the output of query1.ToString() and paste it to the browser, I get the expected results. 

i captured the traffic with wireshark.

this is the ouput from the browser-query:
`GET %secret%/Abholbescheide?$orderby=Customer_No&$top=10&$select=Customer_No,EAR_Status_Text HTTP/1.1
Host: %secret%
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,de;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Authorization: %secret%
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-GPC: 1

HTTP/1.1 200 OK
Content-Length: 1854
Content-Type: application/json; odata.metadata=minimal
Server: Microsoft-HTTPAPI/2.0
request-id: %secret%
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Date
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Server
Access-Control-Expose-Headers: OData-Version
OData-Version: 4.0
Date: Wed, 30 Nov 2022 13:59:37 GMT`

and this is the output from my program:
`GET %secret%/Abholbescheide?$orderby=Customer_No&$top=10&$select=Customer_No,EAR_Status_Text HTTP/1.1
Host: %secret%
OData-Version: 4.0
OData-MaxVersion: 4.0
Accept: application/json;odata.metadata=full
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.12.5
Connection: Keep-Alive
Authorization: %secret%

HTTP/1.1 500 Internal Server Error
Content-Length: 56
Content-Type: application/json; odata.metadata=full; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
request-id: %secret%
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Date
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Server
Access-Control-Expose-Headers: OData-Version
OData-Version: 4.0
Date: Wed, 30 Nov 2022 14:00:31 GMT

{"error":{"code":"","message":"An error has occurred."}}`

**Comment by ElizabethOkerio** [comment]
@koldomon Have tries the exact same thing using the TriPin Service and it works fine: 
`var client = new DefaultContainer(new Uri("https://services.odata.org/V4/(S(0mpmczwt30cfue3l0k42hhmm))/TripPinServiceRW/"), ODataProtocolVersion.V4);
var query3 = client.People.OrderBy(x => x.FirstName).Take(5).Select(x => new { x.FirstName, x.LastName });
var queryString = query3.ToString();`

This is the query string that gets generated: https://services.odata.org/V4/(S(0mpmczwt30cfue3l0k42hhmm))/TripPinServiceRW/People?$orderby=FirstName&$top=5&$select=FirstName,LastName

Is it possible to share a repro of what you have? a sample model maybe?

**Comment by ElizabethOkerio** [comment]
TODO: check odata-metadata=minimal/full on the app request and if it could be causing the issue..

**Comment by koldomon** [comment]
> @koldomon Have tried the exact same thing using the [TriPin](https://services.odata.org/V4/(S(lt3ps51whtxzlxxridx5n5sp))/TripPinServiceRW/) Service and it works fine: `var client = new DefaultContainer(new Uri("https://services.odata.org/V4/(S(0mpmczwt30cfue3l0k42hhmm))/TripPinServiceRW/"), ODataProtocolVersion.V4); var query3 = client.People.OrderBy(x => x.FirstName).Take(5).Select(x => new { x.FirstName, x.LastName }); var queryString = query3.ToString();`
> 
> This is the query string that gets generated: https://services.odata.org/V4/(S(0mpmczwt30cfue3l0k42hhmm))/TripPinServiceRW/People?$orderby=FirstName&$top=5&$select=FirstName,LastName
> 
> And the request gets processed ok.
> 
> Is it possible to share a repro of what you have? a sample model maybe?

@ElizabethOkerio I'm sorry, but I can not share more infomation without leaking information from my company. But in general, all I did is using the OData Connected Service (in VS2022) wich is working fine. I can query the data, so in general it is working. 

I'm also investigating on the Navision side - I personaly think the problem arises there. I'll document the result here if we find a problem on the Navision service.

It would be great if you could find out if the "odata-metadata" has something to do with it or causing any change in behaviour, just to make sure. 

Thanks in forehand

**Comment by uffelauesen** [comment]
@ElizabethOkerio @koldomon 
It is most likely related to odata.metadata=full
You can reproduce it on TripPin service with the following query...

`/People('russellwhyte')?$expand=Trips($select=Description)`

It succeeds in a browser (effectivly using odata.metadata=minimal), but fails from C# client as it uses odata.metadata=full.

C# query for testing:

```
            var q = (from p in ctx.People
                     where p.UserName == "russellwhyte"
                     select new Person
                     {
                         Friends = new DataServiceCollection<Person>(
                             from f in p.Friends
                             select new Person
                             {
                                 Trips = new DataServiceCollection<Trip>(from t in f.Trips
                                         select new Trip 
                                         { 
                                             Description = t.Description
                                         })
                             }),
                     }) as DataServiceQuery<Person>;

```

**Comment by koldomon** [comment]
Thank you @uffelauesen for finding the same issue on a diffrent OData Service. Based on your feedback I did a little study on the source-code and did some tests in my environment. Here are the results

[DataServiceClientFormat.cs - Line 361](https://github.com/OData/odata.net/blob/0770ead80960d31581ae66f1a00488bc29bac085/src/Microsoft.OData.Client/DataServiceClientFormat.cs#L361)

```
        private static string ChooseMediaType(bool hasSelectQueryOption)
        {
            if (hasSelectQueryOption)
            {
                return MimeApplicationJsonODataLightWithAllMetadata;
            }

            return MimeApplicationJsonODataLight;
        }
```
seems to be the issue. I changed the code to the following and everything works fine:

```
        private static string ChooseMediaType(bool hasSelectQueryOption)
        {
            //if (hasSelectQueryOption)
            //{
            //    return MimeApplicationJsonODataLightWithAllMetadata;
            //}

            //return MimeApplicationJsonODataLight;
            if (hasSelectQueryOption)
            {
                return MimeApplicationJsonODataLight;
            }
            return MimeApplicationJsonODataLightWithAllMetadata;
        }
```

the question I have is: should the `if (hasSelectQueryOption)` be changed to `if (!hasSelectQueryOption)`. In my understanding - if you DON'T select a subset, then the header should include a "odata.metadata=full", otherwise it should be set a "odata.metadata=minimal". 

@ElizabethOkerio could you please give us feedback on that question.

**Comment by johnwc** [comment]
@ElizabethOkerio is this backlog item been completed, we are facing the same issue where we need to manually set the format.

**Comment by koldomon** [comment]
> @ElizabethOkerio is this backlog item been completed, we are facing the same issue where we need to manually set the format.

hi @johnwc. The implementation is right to the Odata-Standard, but it seems some servers did some other stuff. For me the simple solution was to hook to the "SendRequest2"-Event and replace the Accept-Header. 

in ctor
`        EventHandler<SendingRequest2EventArgs> Correctheader = ((sender, args) => { });
        this.NavConnector.SendingRequest2 += CorrectContentTypeHeaderOnSelect;
`
and here the handler
`    
private void CorrectContentTypeHeaderOnSelect(object? sender, SendingRequest2EventArgs args)
{
        if (args.RequestMessage.Url.Query.Contains("$select"))
        {
            var acceptHeader = args.RequestMessage.GetHeader("Accept");
            if ((acceptHeader is not null) && (acceptHeader.Equals(MimeApplicationJsonODataLightWithAllMetadata)))
            {
                args.RequestMessage.SetHeader("Accept", MimeApplicationJsonODataLight);
            }
        }
}
`
and some constants
`    
    private const string MimeApplicationJsonODataLight = "application/json;odata.metadata=minimal";
    private const string MimeApplicationJsonODataLightWithAllMetadata = "application/json;odata.metadata=full";
`

**Comment by johnwc** [comment]
@koldomon that is what we are doing already for the interim, but it would be better to allow developer more control of headers in case of servers that are not compliant.
