### ISSUE TITLE
V3 service.dll needs handle undeclared collection properties

### ISSUE THREAD

**Issue by challenh** [OData/odata.net#257]
V3 ODL supports *reading* undeclared collection properties starting from 5.6.4, but service.dll doesn't handle it well : 
(1) when service.dll  is able to read and proceed it, service.dll will try to write undeclared collection properties  which is not supported yet. 
(2) so previously http 400 is explicitly thrown when checking & reading undeclared collection properties,  now this step can pass, then later on a write attempt will cause http 500.

**Comment by congysu** [comment]
This is a Flag enum type.  We might need to add a new flag, instead of re-defining behavior for existing flags.

**Comment by congysu** [comment]
The Flag enum is: ODataUndeclaredPropertyBehaviorKinds
https://github.com/OData/odata.net/blob/ODATAV3/ODataLib/OData/Desktop/.Net4.0/Microsoft/Data/OData/ODataUndeclaredPropertyBehaviorKinds.cs#L30

**Comment by challenh** [comment]
close it. https://github.com/OData/odata.net/commit/f1934b38346cc328bfdd2db9757c0be2c7c16942
