### ISSUE TITLE
Core.Description in Capabilities metadata is resolved as unresolved term.

### ISSUE THREAD

**Issue by karataliu** [OData/odata.net#258]
```
<Annotation Term="Core.Description"><String> The Capabilities vocabulary aims to provide a way for service authors to describe certain capabilities of an OData Service. </String></Annotation>
```

**Comment by congysu** [comment]
The capability vocabulary xml should include a model reference to core vocabulary: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Vocabularies/CapabilitiesVocabularies.xml
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/vocabularies/Org.OData.Capabilities.V1.xml

**Comment by xuzhg** [comment]
Fixed. Thanks.
