### ISSUE TITLE
How to add a parameter to GetReadStream

### ISSUE THREAD

**Issue by reencafesas** [OData/odata.net#2586]
Hello, currently when making the request 

var attachment = _serviceLayer.Attachments2.Where(cursor => cursor.AbsoluteEntry.Equals(line.U_AbsEntry)).FirstOrDefault();

_serviceLayer.Attachments2.Context.GetReadStream(attachment)

the result of the generated URL is:
https://IP:PORT/b1s/v2/Attachments2(1111)/$value

The url is fine, but I need to add a parameter to this request, expecting as a result:

https://IP:PORT/b1s/v2/Attachments2(1111)/$value?filename='image.png'

I couldn't add this parameter in any way as it must go after $value, for now I had to manage this change from the BuildingRequest, is there any direct way to do this?

THANKS

**Comment by gathogojr** [comment]
@reencafesas There isn't a direct way to add a parameter to the URL. You may need to ride on the `BuildingRequest` hook like you're doing now. If you'd be okay with passing the value as a header, you could ride on the `GetReaderStream` overload that accepts a `DataServiceRequestArgs` parameter and use the `Slug` property or pass it as a custom header.

**Comment by gathogojr** [comment]
@reencafesas I'll go ahead and close this issue seeing that there's a hook that allows you to manipulate the request URI and you can also use the proposed workarounds...
