### ISSUE TITLE
Trouble Geting Blazor WebAssembly with OData Client working

### ISSUE THREAD

**Issue by ti994a7** [OData/odata.net#2608]
I've tried following the instruction to use the Odata Client with a WebAssembly project at https://learn.microsoft.com/en-us/odata/client/using-blazor-wasm-with-odata-client, both using the Connected Service and POCOs, and I haven't been able to get either one working.  With the connected service I am getting an System.PlatformNotSupportedException.  I've tried creating new projects connecting to the https://services.odata.org/V4/TripPinServiceRW/$metadata service, but haven't had any luck.  Can anyone point me in the right direction, or have a working example repository?

**Comment by xuzhg** [comment]
@ElizabethOkerio Do you have a sample?

**Comment by ElizabethOkerio** [comment]
Are you setting this ~ `.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient`;

**Comment by habbes** [comment]
@ti994a7 ensure you use the `HttpRequestTransportMode.HttpClient` as @ElizabethOkerio  as suggested:

```csharp
dataServiceContext.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient
```
Also ensure to only use the async APIs (e.g. `ExecuteAsync`) because synchronous network I/O is not supported in the browser.

**Comment by gathogojr** [comment]
@ti994a7 One common issue when consuming an OData service from a Blazor WebAssembly App is requests being blocked by CORS (Cross-Origin Requests) policy. When that happens, you may observe a `PlatformNotSupportedException` and that can be confusing. It's likely that's what you're dealing with here.

Please try the following:

1. Add the cross-origin sharing services to the service collection;
    ```csharp
    services.AddCors();
    // Or builder.Services.AddCors(); // depending on your framework version
    ```
3. Add CORS middleware to your application pipeline to allow cross doman requests.
    **This must be done after adding the routing middleware and before the authentication middleware!**
    ```csharp
    app.UseRouting();
    app.UseCors(
        options => options
        .AllowAnyOrigin()
        .AllowAnyMethod()
        .AllowAnyHeader());
    // ...
    // app.UseAuthentication();
    // ...
   ```
    You can be more specific about the requests that you want to allow:
    ```csharp
    app.UseRouting();
    app.UseCors(
        options => options
        .WithOrigins("http://localhost:5001") // Where http://localhost:5001 represents the client application domain
        .AllowAnyMethod()
        .AllowAnyHeader());
    // ...
    // app.UseAuthentication();
    // ...
   ```

Please let me know if this helps...
