### ISSUE TITLE
System.TimeOnly' is not supported by the client library

### ISSUE THREAD

**Issue by mchudie** [OData/odata.net#2613]
Microsoft.OData.Client 7.14.0
System.TimeOnly' is not supported by the client library

**Comment by KenitoInc** [comment]
@mchudie 
What are you trying to do with `System.TimeOnly` in `OData client`?

**Comment by xuzhg** [comment]
System.TimeOnly and System.DateOnly is introduced in .NET 6. If we want to support them, we have to update the target framework on .NET 6. (It's also related to the topic: SUPPORT POLICY).

@mchudie by the way, OData has the Date and TimeOfDay struct that you can use. Any problem to use those types?

**Comment by gathogojr** [comment]
Closing issue since justification was not provided and lack of follow-through...

**Comment by xuzhg** [comment]
https://github.com/OData/odata.net/pull/3078 supports the DateOnly and TimeOnly in OData.Core and We'd move forward to fully support it in OData.Client and OData Connected Service.
