### ISSUE TITLE
Add support for default namespace core vocab

### ISSUE THREAD

**Issue by baywet** [OData/odata.net#2626]
The [default namespace](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.md#DefaultNamespace) core vocab is not supported today.

### Assemblies affected

1.3 and down

### Reproduce steps

N/A

### Expected result

Tag/Term to be supported

### Actual result

N/A

**Comment by xuzhg** [comment]
@lisicase It seems related to your previous commit. Would you mind creating a PR to fix it also?

**Comment by lisicase** [comment]
@baywet From what I can tell, the vocabulary term is listed [here](https://github.com/OData/odata.net/blob/e3a63342c853810a5fa0013a9ccf3cec2da2fec5/src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml#L328). Is there something additional you're asking for?

**Comment by baywet** [comment]
Thanks, I guess we got confused on how to access the information and were expecting a dedicated property on the context like other core vocab.
But this is something we don't need anymore as AGS is not using that vocab anyway.
Closing
