### ISSUE TITLE
Complex/Structural payload conversion

### ISSUE THREAD

**Issue by AlpineJBoehnen** [OData/odata.net#2633]
Just have a question, any current plans to support payload conversion of complex or structural types with ODataPayloadValueConverter? If not any suggestions on how I could go about converting a structural type (NodaTime Instant in this case) to a simple string? Thanks.

**Comment by xuzhg** [comment]
@AlpineJBoehnen Do you want to serialize a complex into a string JSON? Would you please share more details about your requirement?

**Comment by AlpineJBoehnen** [comment]
@xuzhg I apologize for the lack of clarity in my original message. Allow me to rephrase: My goal is to replace a complex property with a different type that can accept any value. Specifically, I wish to substitute a NodaTime Instant or a NetTopologySuite Geometry (or any other data type) with a string value of my choosing. This string could take the form of a date ("09/15/2021", "2021-09-15T15:30:00.000Z"), or even a plain string of text ("This is a string"), for instance. I believe this can be accomplished for Primitives with ODataPayloadValueConverter, unless I am mistaken.

**Comment by xuzhg** [comment]
@AlpineJBoehnen Take a look at the implementation at : https://github.com/xuzhg/mydotnetconf 
Emails and Branches are string value from DB, but we can serialize them as collection of string and collection of complex. You can do the reverse. Let me know if that's not help.

**Comment by habbes** [comment]
@AlpineJBoehnen how are you currently representing these types in your CSDL or IEdmModel? Are they represented as strings (`Edm.String`) or complex types? And what type do you want them to have in the model? As strings, complex types or other primitive types?

**Comment by AlpineJBoehnen** [comment]
Thank you for your suggestion @xuzhg, the code I found in that repository seems a sufficient solution for structural and primitive types; however, I cannot get that to work for complex types.

Hi @habbes, here is a simplification of my project that demonstrates my model and the desired output:

IEdmModel:
``` cs
ODataConventionModelBuilder builder = new();

var zoo = builder.EntitySet<Zoo>("Zoo").EntityType;
var animal = builder.EntitySet<Animal>("Animals").EntityType;

return builder.GetEdmModel();
```

Metadata:
``` xml
<EntityType Name="Zoo">
  <Key>
    <PropertyRef Name="id"/>
  </Key>
  <Property Name="id" Type="Edm.Guid" Nullable="false"/>
  <Property Name="name" Type="Edm.String" Nullable="false"/>
  <Property Name="complex" Type="Models.MyComplex" Nullable="false"/> <!--I want this to be Edm.String-->
  <NavigationProperty Name="animals" Type="Collection(Models.Animal)"/>
</EntityType>
<EntityType Name="Animal">
  <Key>
    <PropertyRef Name="id"/>
  </Key>
  <Property Name="id" Type="Edm.Guid" Nullable="false"/>
  <Property Name="name" Type="Edm.String" Nullable="false"/>
  <Property Name="zooId" Type="Edm.Guid" Nullable="false"/>
</EntityType>
<ComplexType Name="MyComplex">
  <Property Name="name" Type="Edm.String" Nullable="false"/>
  <Property Name="value" Type="Edm.Int32" Nullable="false"/>
</ComplexType>
```

Current output:
``` json
{
    "@odata.context": "https://localhost:63616/$metadata#Zoo",
    "value": [
        {
            "id": "1c665977-cee4-4e6b-868e-7ce9d3a43ffe",
            "name": "client zoo",
            "complex": {
                "name": "complex",
                "value": 123
            }
        }
    ]
}
```

Desired output:
``` json
{
    "@odata.context": "https://localhost:63616/$metadata#Zoo",
    "value": [
        {
            "id": "1c665977-cee4-4e6b-868e-7ce9d3a43ffe",
            "name": "client zoo",
            "complex": "complex 123 extra"
        }
    ]
}
```

I have tried to use ODataPayloadValueConverter, but this is only for primitives.
The [solution that xuzhg suggested](https://github.com/xuzhg/mydotnetconf/blob/main/OData/OData.WebApi/Extensions/MyResourceSerializer.cs) seemed like it was going to work but CreateStructuralProperty() of my ODataResourceSerializer never entered with a complex property as the argument (which makes sense given the method name). I may have failed to find the code excerpt that xuzhg was referring to, however.

Thanks for your time and suggestions.

**Comment by habbes** [comment]
@AlpineJBoehnen what if you define the `Complex` property in your `Zoo` class as a string? Then create a different property that's complex but ignore it in the OData model builder. And the you can use getters and setters to perform the conversion to the desired output:

```c#
public class Zoo
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public ICollection<Animal> Animals { get; set; } = new List<Animal>();
    public string Complex
    {
        get
        {
             return GetDesiredStringRepresentationFromActualComplexProperty();
        }
        set
        {
            DeserializeStringRepresentationIntoComplexProperty(value);
        }
    }
    [IgnoreDataMember]
    public MyComplex ActualComplex = new MyComplex();
}
```

I believe that's the approach suggested by @xuzhg.

If you want your complex property to be treated as strings by the serializer, my guess would be that you would need to register a custom `IODataTypeMapper` and override the `GetEdmTypeReference(IEdmModel model, Type clrType)` to return `Edm.String` for the class that corresponds to your complex type:

```c#
// customer type mapper
class CustomODataTypeMapper : DefaultODataTypeMapper
{
    public override IEdmTypeReference GetEdmTypeReference(IEdmModel model, Type clrType)
    {
        if (clrType == typeof(MyComplex))
        {
            // custom handling
        }

        return base.GetEdmTypeReference(model, clrType);
    }
}

// register the type mapper on your model
IEdmModel myModel = modelBuilder.GetEdmModel();
myModel.SetTypeMapper(new CustomODataTypeMapper());
```

I haven't tried this approach to see how far it goes. But I'd be curious why you did consider the approach suggest first.

**Comment by AlpineJBoehnen** [comment]
@habbes I have settled on using the computed property approach suggested by both of you. My motivation for seeking a solution that involved serialization with OData was twofold, I hoped to reduce repetition in my models and believed that serialization would still allow for filtering of the property in my query. Thank you both very much for your help.
