### ISSUE TITLE
Support declared Edm.Untyped property serialization using ODataPrimitiveValue

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#2659]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*
Suppose we have the following OData property:

```xml

<Property Name="Data" Type="Edm.Untyped" />
```

In mapping, we have the following C# property:

```C#
public object Data {get;set;}
```

So, if we have a resource instance, the value of `Data` could be anything. 

```C#
Person p = new Person();
p.Data = 42; // or 
p.Data = null; // or
p.Data = true;
```

So, How can we serialize them in the ODL?  

The existing codes need to create 'ODataUntypedValue' to serialize Declared Edm.Untyped property as:

```C#
new ODataProperty {
  Name = "Data",
  Value = new ODataUntypedValue ...
}
```

But, It's better to support to create 'ODataPrimitiveValue ' to serialize Declared Edm.Untyped property as:
```C#
new ODataProperty {
  Name = "Data",
  Value = new ODataPrimitiveValue { Value = 42... }
}
```

**Comment by KenitoInc** [comment]
What if `Data` is not a primitive value?
