### ISSUE TITLE
DataServiceContext Caching Issue

### ISSUE THREAD

**Issue by akristanto** [OData/odata.net#2702]
*Short summary (3-5 sentences) describing the issue.*

We have a scenario where a client uses the same OData client to do a Search call followed by a Get call on the same entity. Search is not supported on large properties so a null value is returned and cached in the OData client then the Get call returns null for that property since the default MergeOption.AppendOnly does not overwrite the cache. Our current workaround is creating a new OData client instance per request as that was recommended in the past.

Could the OData team provide more clarity and recommendations for the following:
1.	Is there a reason MergeOption.AppendOnly is the default since in this case, the Get request still goes through the network only to return what is in the cache?
2.	Is there any performance analysis on recreating a new OData client instance per request?
3.	Would changing the MergeOption to OverwriteChanges or NoTracking make sense for this scenario? In what cases would be best to use those MergeOptions? What are the potential drawbacks? Is there performance analysis around this as well?
4.	Is creating a new OData client instance per request still the recommended fix?

### Assemblies affected

OData .Net lib 7.12.5

### Reproduce steps

Using the same DataServiceContext, do a search followed by a get on an entity with [LargeProperty] 

### Expected result

value of the large property is populated

### Actual result

value of the large property is null

**Comment by akristanto** [comment]
Response from @corranrogue9 through email:
1.	This seems like a bug to me, or we are both misunderstanding the purpose of the AppendOnly option. I would think the default should be PreserveChanges (more on this below in 3), but we are unlikely to change the default at this point in case a customer has taken a dependency on this for some reason.
2.	Yes, please do not create a new OData client instance per request. This will result in terrible performance.
3.	I think what you actually want is PreserveChanges, but I could be wrong. I think OverwriteChanges and NoTracking both negate the benefits of caching, while PreserveChanges should treat the cache as a proper cache (i.e. setting dirty bits and flushing where applicable). I'm uncertain if this is exactly correct, but I think this is what you want. If PreserveChanges does not work to get the null values from the search to be returned for GET calls, then I don't suggest using OverwriteChanges or NoTracking because they will avoid the cache; while we don't have a performance analysis around this, effectively disabling the cache is likely not what you want.
4.	If PreserveChanges doesn't work and you need a work around, I think have one instance for $search requests and one instance for GET requests. So, rather than one instance per request, have 2 instances total.

**Comment by akristanto** [comment]
Thanks for the response Garrett!

2. Is there performance analysis on this? We had done small local testing showing no significant impact on performance when creating multiple OData client instances. Also, your recommendation conflicts with a recommendation from the OData team earlier this year to create a new OData client instance per request described in this bug: https://msazure.visualstudio.com/Intune/_workitems/edit/15379206 
Could you ensure what the correct recommendation is?
3. Thanks for the recommendation for PreserveChanges. It did work in this scenario. Is this recommended over creating multiple OData client instances?

**Comment by gathogojr** [comment]
@akristanto I'll try and respond to the questions you raised

1. There's a behaviour that may not be so obvious with respect to the default `MergeOption` setting of the `DataServiceContext`.
    Let's suppose you perform a `$search` request and an entity with an `Id` of x is returned.
    Then, against the same instance of `DataServiceContext` you performed the `$search` request, you make a `GET` request for the entity with `Id` x but this time you expand a navigation property.
    Because we return the cached entity, (and assuming the `$search` request didn't have an `$expand` expression), any subsequent request for the same entity against the same `DataServiceContext` will return the materialized object from the very first instance of the entity that was returned - the one that didn't have the navigation property expanded. For this reason, you may want to perform the `GET` request on a new instance of the `DataServiceContext`.
 
    **Illustration:**
    ```csharp
    var dataServiceContext = new Default.Container(new Uri("http://localhost:5000"));
     
    var productSearchEnumerator = dataServiceContext.Execute<Product>(
        new Uri("http://localhost:5000/Products?$search=calorie")).GetEnumerator();
    if (productSearchEnumerator.MoveNext())
    {
        var matchedProduct = productSearchEnumerator.Current;
     
        // The "Supplier" property in the materialized "product" object below will forever be null
        // since the cached entity (that didn't have Supplier expanded) from the $search request will be returned
        var product = dataServiceContext.Products.ByKey(matchedProduct.Id).Expand("Supplier").GetValue();
    }
    ```

2. You could carry out an analysis on your service or application to determine if new-ing up an instance of `DataServiceContext` has a significant impact on performance and memory usage, taking into consideration the background I provided in (1) above. Alternatively, you could adopt any of the proposal in (3) below to safely use the same instance of `DataServiceContext`.
 
3. You could modify the `MergeOption` setting to what suits your scenario best:

    - You can turn off tracking when performing the `$search` request (`MergeOption.NoTracking`) and restore tracking when performing the `GET` request (`MergeOption.AppendOnly` – default).

 
        **Illustration:**

        ```csharp
        var dataServiceContext = new Default.Container(new Uri("http://localhost:5000"));
        var defaultMergeOption = dataServiceContext.MergeOption;
         
        dataServiceContext.MergeOption = MergeOption.NoTracking;
        var productSearchEnumerator = dataServiceContext.Execute<Product>(
            new Uri("http://localhost:5000/Products?$search=calorie")).GetEnumerator();
        if (productSearchEnumerator.MoveNext())
        {
            var matchedProduct = productSearchEnumerator.Current;
         
            // The "Supplier" property in the materialized "product" object below will be populated
            dataServiceContext.MergeOption = defaultMergeOption;
            var product = dataServiceContext.Products.ByKey(matchedProduct.Id).Expand("Supplier").GetValue();
        }
        ```
 
    - You can choose to overwrite the cached object by applying the `MergeOption.OverwriteChanges` option.
 
        **Illustration:**

        ```csharp
        var dataServiceContext = new Default.Container(new Uri("http://localhost:5000"));
         
        var productSearchEnumerator = dataServiceContext.Execute<Product>(
            new Uri("http://localhost:5000/Products?$search=calorie")).GetEnumerator();
        if (productSearchEnumerator.MoveNext())
        {
            var matchedProduct = productSearchEnumerator.Current;
         
            // The "Supplier" property in the materialized "product" object below will be populated
            // but changes (if any) that might have been made to the cached entity
            // would be overwritten
            dataServiceContext.MergeOption = MergeOption.OverwriteChanges;
            var product = dataServiceContext.Products.ByKey(matchedProduct.Id).Expand("Supplier").GetValue();
        }
        ```
 
    - You can choose to perverse changes to the cached object or overwrite it if it hasn’t been modified by applying the `MergeOption.PreverveChanges` option.
 
        **Illustration:**

        ```csharp
        var dataServiceContext = new Default.Container(new Uri("http://localhost:5000"));
         
        var productSearchEnumerator = dataServiceContext.Execute<Product>(
            new Uri("http://localhost:5008/Products?$search=calorie")).GetEnumerator();
        if (productSearchEnumerator.MoveNext())
        {
            var matchedProduct = productSearchEnumerator.Current;
         
            // The "Supplier" property in the materialized "product" object below will be populated
            // only if no changes have been made to the cached entity
            dataServiceContext.MergeOption = MergeOption.PreserveChanges;
            var product = dataServiceContext.Products.ByKey(matchedProduct.Id).Expand("Supplier").GetValue();
        }
        ```
 
    I’d advise you to assess the options based on your scenario and analyze the impact on performance and memory usage. I don’t have any stats I can share now.
 
4. In respect to principle of least surprise, new-ing up an instance of `DataServiceContext` might be considered the easiest and most straight forward but depending on your scenario and your requirements, I have outlined other options in (3) above that you could try out.

**Comment by wachugamaina** [comment]
Different options explained in detail.

**Comment by akristanto** [comment]
@gathogojr would it make sense to set the default for all uses of the DataServiceContext to use MergeOptions.PreserveChanges to prevent having to recreate an instance of DataServiceContext?
