### ISSUE TITLE
Special characters in query param

### ISSUE THREAD

**Issue by Robelind** [OData/odata.net#2767]
### Assemblies affected

Microsoft.OData.Client 7.18.0

### Reproduce steps

```
public class Test
{
}

DataServiceContext context = new DataServiceContext(new Uri("http://localhost"));
DataServiceQuery<Test> query = context.CreateQuery<Test>("Tests").AddQueryOption("param", "123-456");

```
### Expected result

`query.RequestUri` would be `http://localhost/Tests?param=123%2d456`

### Actual result

`query.RequestUri` is `http://localhost/Tests?param=123-456`,
which leads to that only `123` reaches the controller.

### Additional detail

Trying to do the escaping yourself doesn't help:

```
DataServiceContext context = new DataServiceContext(new Uri("http://localhost"));
DataServiceQuery<Test> query = context.CreateQuery<Test>("Tests").AddQueryOption("param", $"123{Uri.HexEscape('-')}456");

```
`query.RequestUri` is still `http://localhost/Tests?param=123-456`

**Comment by gathogojr** [comment]
@Robelind Also try the following:
```csharp
DataServiceQuery<Test> query = context.CreateQuery<Test>("Tests").AddQueryOption("param", "123%2d456");
```

**Comment by Robelind** [comment]
> @Robelind Did you try
> 
> ```cs
> DataServiceQuery<Test> query = context.CreateQuery<Test>("Tests").AddQueryOption("param", "'123-456'");
> ```
> 
> Note the single quotes - `'123-456'`

This works. Where can I find this documented?

**Comment by gathogojr** [comment]
@Robelind Actually, this will give you unexpected result. The `param` string argument will include the single quotes, i.e., `'123-456'`:
![image](https://github.com/OData/odata.net/assets/28291332/fca8477b-47df-4340-98f6-2a339d3ecadc)
I don't think that's what you want...

If on the other hand you adopt what I proposed in this https://github.com/OData/odata.net/issues/2767#issuecomment-1755781504, the `param` string argument has a value of `123-456`:
![image](https://github.com/OData/odata.net/assets/28291332/fd8f7ec2-c43b-4e3e-a953-03509c3c7784)

What I suspect is that `Uri.HexEscape('-')` is not doing what you're expecting it to. Can you confirm independently whether it encodes the `-` character?

**Comment by gathogojr** [comment]
> > @Robelind Did you try
> > ```
> > DataServiceQuery<Test> query = context.CreateQuery<Test>("Tests").AddQueryOption("param", "'123-456'");
> > ```
> > 
> > 
> > Note the single quotes - `'123-456'`
> 
> This works. Where can I find this documented?

@Robelind Actually, this will give you unexpected result. The `param` string argument will include the single quotes, i.e., `'123-456'`:
![image](https://github.com/OData/odata.net/assets/28291332/fca8477b-47df-4340-98f6-2a339d3ecadc)
I don't think that's what you want...

If on the other hand you adopt what I proposed in this https://github.com/OData/odata.net/issues/2767#issuecomment-1755781504, the `param` string argument has a value of `123-456`:
![image](https://github.com/OData/odata.net/assets/28291332/fd8f7ec2-c43b-4e3e-a953-03509c3c7784)

What I suspect is that `Uri.HexEscape('-')` is not doing what you're expecting it to. Can you confirm independently whether it encodes the `-` character?
