### ISSUE TITLE
Method InBinder.ProcessSingleQuotedStringItem throws ODataException

### ISSUE THREAD

**Issue by paku-he** [OData/odata.net#2771]
Method _NormalizeStringCollectionItems_ (which internally calls method _ProcessSingleQuotedStringItem_) throws ODataException with message "String item should be single/double quoted" if string item has three single quotes at the end. 
Please have a look at test FilterAndOrderByFunctionalTests.FilterWithInOperationWithParensStringCollection_EscapedSingleQuote 
![image](https://github.com/OData/odata.net/assets/148212325/08aa7c4c-244b-450c-867e-950c9673c35a)
Currently in the test literal xyz has three single quotes and test passes however if we put three single quotes at the end of literal def 
![image](https://github.com/OData/odata.net/assets/148212325/d5af6af6-874d-4b01-b322-490bf04662aa)
then exception is thrown: 
![image](https://github.com/OData/odata.net/assets/148212325/2fa9d21c-68ad-4d1f-b110-b7f2a3d8f32a)

### Assemblies affected

Class InBinder is placed in project Microsoft.OData.Core

### Expected result

Literal 'def''' is completely in line with OData URL syntax , that is: single quotes within string literals are represented as two consecutive single quotes (https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html) .
![image](https://github.com/OData/odata.net/assets/148212325/0f581b14-56cd-4441-a94e-8255a0cc360a)

In my opinion exception should not be thrown.

### Additional detail

I guess way to solve this is to change method _ProcessSingleQuotedStringItem_ i.e. line 304 should be changed 
![image](https://github.com/OData/odata.net/assets/148212325/5f97cd89-46ec-4938-9cc7-e353d89ec20a)

In my opinion it should be like that: 
![image](https://github.com/OData/odata.net/assets/148212325/c806899c-76fd-40e0-9e59-4722529ba33d)

**Comment by gathogojr** [comment]
Thanks @paku-he for reporting the issue. Seems like you were able to figure out the cause. We welcome pull request contribution if possible.

**Comment by paku-he** [comment]
Thank you very much for the reply. 
I have prepared pull request with my resolution (https://github.com/OData/odata.net/pull/2773) . 

I would like to add that problem happens if string item, with ''' at the end, is not the last item in the collection (red underline). 
Thus in case like at the picture below , where _problematic_ string item is the last in collection , exception is not thrown.
![image](https://github.com/OData/odata.net/assets/148212325/b9ac2dfc-884e-4ade-a2bd-43d5da9c5725)

However if string item is not the last one in collection, like at the picture below (red underline), exception is thrown 
![image](https://github.com/OData/odata.net/assets/148212325/86678b30-a49d-409c-b11e-f17ae28743df)
