### ISSUE TITLE
Update deprecated dependency Microsoft.Bcl.AsyncInterfaces (get rid of the NuGet warning)

### ISSUE THREAD

**Issue by kapsiR** [OData/odata.net#2780]
Since Microsoft.Bcl.AsyncInterfaces v5.0.0 is deprecated, the libs should reference the latest v7.0.0 instead.

### Assemblies affected

OData .Net lib 7.18.0

### Reproduce steps

NuGet brings up a deprecation warning.

### Expected result

Don't reference a deprecated/unsupported library.

### Actual result

![grafik](https://github.com/OData/odata.net/assets/7165033/2297972f-61d8-4ae3-aa8c-74d84f8a714d)

### Additional details

This will change the supported target frameworks from `net461` to `net462`.

**Comment by corranrogue9** [comment]
It appears that `7.0.0` depends on core versions that we support. @gathogojr will confirm that we can safely upgrade the package across all of our support .NET verisons.
