### ISSUE TITLE
Proposal to drop support for unsupported frameworks in next major release

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2817]
In the next major release (ODL 8), we should drop support for unsupported .NET and .NET Core frameworks. I propose that we also drop support for .NET Framework 4.8 despite still being maintained.

**Comment by robertmclaws** [comment]
I concur. There are plenty of versions of OData that support .NET 4.8. Moving forward OData Restier will only be supporting .NET 8 and later.

OData would be much less complicated if all the 20+ year legacy code was removed. And I mean all of it.

As an aside, I would also recommend you guys skip v8 and go straight to v9 for OData libraries across the board. You folks have gotten yourselves into a lot of trouble with the v7 vs v8 versions relating to .NET Framework support and breaking changes. Moving to v9 would let you have 1 ASP.NET Core-based framework moving forward, and it would align with shipping .NET 9 quite nicely.

**Comment by xuzhg** [comment]
I think we fixed this. Please let me know any concerns.
