### ISSUE TITLE
OData Client can't load the related entities when calling a function with expand

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#285]
The related stackoverflow: http://stackoverflow.com/questions/31622205/microsoft-odata-client-not-loading-related-entities-when-calling-a-function-with.

**Comment by xuzhg** [comment]
I have a test, it seems it's our OData client bug.
For example:

`
var result = container.Customers.ByKey(1).RefreshCustomer().Expand("Category");
var customer = result.GetValueAsync().Result;
`
The `Category` property in `customer` instance is null.

However, the fiddler catches the following request

`
GET /odata/Customers(1)/Default.RefreshCustomer()?$expand=Category HTTP/1.1
`

and got the following response:

```C#
HTTP/1.1 200 OK
Content-Length: 263
Content-Type: application/json; odata.metadata=minimal; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
OData-Version: 4.0
Date: Mon, 27 Jul 2015 03:07:16 GMT

{
  "@odata.context":"http://localhost:12345/odata/$metadata#Customers/$entity","CustomerId":1,"CustomerName":"Mike","FavoriteColor":"Red","Location":{
    "Country":"CN","City":"Shanghai"
  },"Category":{
    "CategoryId":101,"CategoryType":"General"
  }
}
```

**Comment by CrazyViper** [comment]
The problem became actual when RefreshCustomer() impltmtntation on the client side came to this: 
```
return this.CreateFunctionQuery(...);
```
but in t4 template v.2.0 it was:
```
return CreateQuery(...);
```
So I suppose that the problem somewhere in CreateFunctionQuery implementation. Select also dont work after function call.

**Comment by xuzhg** [comment]
@CrazyViper 
After investigation, it seems it can work after I do the following:

1. Remove all operation and make the express clause with `Expand` run first
2. Add global configuration:

```C#
container.MergeOption = MergeOption.OverwriteChanges;
```

So. close it.

**Comment by avjabalpur** [comment]
I am getting following issue 

The Id cannot be computed, since the navigation source 'Identifiers' cannot be resolved to a known entity set from model.
And my query is 


![image](https://user-images.githubusercontent.com/6541087/65235765-e2980600-daf4-11e9-8a7a-24f96b9ef6b9.png)

also I have added MergeOption in my config 
![image](https://user-images.githubusercontent.com/6541087/65235855-09eed300-daf5-11e9-8b0e-b6362df1ac5d.png)

Thanks in Advance
