### ISSUE TITLE
Mitigate ArgumentOutOfRangeException when the typename in context URL is not fully qualified

### ISSUE THREAD

**Issue by gathogojr** [OData/odata.net#2891]
When the typename in the context URL is not fully qualified, an `ArgumentOutOfRangeException` is thrown when trying to materialize the payload. The exception happens when trying to split the typename into namespace and type name (unqualified).

### Assemblies affected

- Microsoft.OData.Client 7.20.0
- Microsoft.OData.Core 7.20.0

### Reproduce steps

Try to materialize a payload with a context URL containing unqualified typename as follows:
```json
{
    "@odata.context": "http://localhost:5150/$metadata#BookInfo",
    "NoOfPages": 2878,
    "NoOfWords": 81180
}
```
where,
- `BookInfo` is a complex type

### Expected result

An `ODataException` with a descriptive error message is thrown.

### Actual result

An `ArgumentOutOfRangeException` with the message `length ('-1') must be a non-negative value. (Parameter 'length'). Actual value was -1.` is thrown.

### Additional detail

Payload is materialized successfully if the typename is fully qualified as follows:
```json
{
    "@odata.context": "http://localhost:5150/$metadata#Ns.Models.BookInfo",
    "NoOfPages": 2878,
    "NoOfWords": 81180
}
```

Related issue https://github.com/OData/odata.net/issues/2889

**Comment by xuzhg** [comment]
#2890 is saying the same thing.

**Comment by gathogojr** [comment]
@xuzhg Having gone through #2890, I don't see how this issue is saying the same thing.
