### ISSUE TITLE
Querying by primary key throws exception if element doesn't exist

### ISSUE THREAD

**Issue by joecarl** [OData/odata.net#2893]
Since I can't reopen a closed issue, this is an intentional duplicate of #1072.
 
If the predicate expression in a query only contains Key properties, the query is generated using the key query expression and that throws an exception when no element is found.
The workaround is to add a dummy `true` expression in the condition (eg : `true && item.Id == XXX`). (Thanks @slnetgit for this suggestion).
This forces a `$filter` query to be generated instead of a Primary key request

### Assemblies affected

7.x*

### Reproduce steps

```csharp
[Key("Id"), EntitySet("MyEntitySet")]
public class MyEntity
{
	public int Id { get; set; }	
}

// This generates the following Uri: https://mydomain.tld/myprefix/MyEntitySet(1000)
// This throws an exception if no element with Id 1000 exists (and it should just return null)
var result = ctx.MyEntitySet.Where(p => p.Id == 1000).SingleOrDefault();

// Workaround:
// This generates the following Uri: https://mydomain.tld/myprefix/MyEntitySet?$filter=Id eq 1000
// Which results in null value (which is expected behavior, nice)
var result = ctx.MyEntitySet.Where(p => p.Id == 1000 && true).SingleOrDefault(); 
```

### Expected result

Querying by an Expression like
```csharp
var result = ctx.MyEntitySet.Where(p => p.Id == 1000).SingleOrDefault();
```
Should return either a result or null, but never an exception.
(as implied by the Notation of the Expression)

### Actual result

An exception is thrown if the element doesn't exist

**Comment by gathogojr** [comment]
Hi @joecarl. This is a known issue and there's a flag you can use to have the expression with the key property translated into a `$filter` expression:
```csharp
ctx.KeyComparisonGeneratesFilterQuery = true;
var result = ctx.MyEntitySet.Where(p => p.Id == 1000).SingleOrDefault();
// Expression will be translated to: https://mydomain.tld/myprefix/MyEntitySet?$filter=Id eq 1000
```

In ODL 8, we'll change the behaviour to default to generating the `$filter` expression and retain the flag so it's possible to toggle back the old behaviour if necessary.
