### ISSUE TITLE
Error with $filter in nested $expand #446

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#292]
Copy Web API issue: https://github.com/OData/WebApi/issues/446

**Comment by chinadragon0515** [comment]
Test with http://services.odata.org/V4/(S(ev4b5pzy2xowavfax1wz3yle))/TripPinServiceRW//People?$expand=Trips($expand=PlanItems($filter=ConfirmationCode%20eq%20%27JH58493%27);$filter=startswith(Name,%27Trip%20in%20US%27))&$select=UserName

Nested expand works well.
