### ISSUE TITLE
Exception thrown when trying to create EdmTargetPath from string path that contains type casts

### ISSUE THREAD

**Issue by millicentachieng** [OData/odata.net#2921]
An exception is thrown when I try to create an EdmTargetPath from a path that contains type casts.

### Assemblies affected
Microsoft.OData.Edm, Version=7.20.0

### Reproduce steps
The target path `Microsoft.OData.Service.Sample.TrippinInMemory.Models.Container/Airports/Location/EmergencyAuthority/AddressInfo/Microsoft.OData.Service.Sample.TrippinInMemory.Models.EventLocation` is generated from the CSDL found [here](https://[raw.githubusercontent.com/microsoft/OpenAPI.NET.OData/master/test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml](https://raw.githubusercontent.com/microsoft/OpenAPI.NET.OData/master/test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml))

Method called:

`model.GetTargetPath(targetPath)`

### Expected result

No exception is thrown and a valid EdmTargetPath is returned

### Actual result

Exception is thrown 
`Encountered invalid type cast. 'Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsProperty' is not assignable from 'Microsoft.OData.Service.Sample.TrippinInMemory.Models.EventLocation`

**Comment by KenitoInc** [comment]
When validating Type casts, when one type is a collection e.g `/EntityContainer/EntitySet/ComplexCollectionProperty/NS.DerivedType` We are not calling `AsElementType` on the collection type, hence validation is failing.

Code https://github.com/OData/odata.net/blob/8f17bb2e215e9e8c3239ac9953b513c882df1edc/src/Microsoft.OData.Edm/ExtensionMethods/TargetPathHelper.cs#L221
