### ISSUE TITLE
OData multilevel expand with paging

### ISSUE THREAD

**Issue by jbockle** [OData/odata.net#293]
When performing a multi level expand with paging enabled on the OData api, the OData 
entity@odata.nextlink does not contain expand options.

example:
`http://server/api/Entity?$expand=RelatedEntity1($expand=RelatedEntity2)`
if paging is set to 20 entities on RelatedEntity1, the first 20 will show expansion on RelatedEntity2, the `RelatedEntity1@odata.nextLink` will not contain $expand=RelatedEntity2, it will appear like the below example:
`"RelatedEntity1@odata.nextLink":"http://server/api/Entity(1)/RelatedEntity1?$skip=20"`

**Comment by TomDu** [comment]
Hi @jbockle , I tried to reproduce the issue with our OData sample service but didn't find the problem.

Example:
`http://services.odata.org/v4/(S(bqvcvfqb3rgue1j2if4mpwip))/TripPinServiceRW/People?$expand=Friends($expand=Trips)`
Then we get
`@odata.nextLink: "http://services.odata.org/V4/(S(bqvcvfqb3rgue1j2if4mpwip))/TripPinServiceRW/People?%24expand=Friends(%24expand%3dTrips)&%24skiptoken=8"`

You can also try again and let us know if you confront any issues.

**Comment by TomDu** [comment]
Hi @jbockle , we temporarily closed this issue, but if you still meet this problem you can reopen it and let us know, thanks.
