### ISSUE TITLE
Support navigation properties and operation returns without EntitySet binding

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#295]
Currently we do not support navigation properties with no navigation target binding and operations returning entites that do not belong to any EntitySet. This is mainly due to that the context URL builder cannot generate correct context URL for those cases. Also some validations in the serialization and EDM prevent this.

[PROTOCOL 10.2](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398267):

If the entities in the response are not bound to a single entity set, such as from a function or action with no entity set path, a function import or action import with no specified entity set, or a navigation property with no navigation property binding, the context URL specifies the type of the returned entity collection.

**Comment by LianwMS** [comment]
submit with 79eddec91b9117364eabf1f50f6e6300a336bd46 and close
