### ISSUE TITLE
Support $expand=*

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#298]
Uri parser does not support it.  Copy issue from https://github.com/OData/WebApi/issues/463

**Comment by congysu** [comment]
expand * is not support for now: https://github.com/congysu/odata.github.io/blob/matrix/_posts/2015-07-22-spec_stack_matrix.md

**Comment by chinadragon0515** [comment]
From specification in this URL http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html
System Query Option $expand
The $expand system query option specifies the related resources to be included in line with retrieved resources.
What follows is a (non-normative) snippet from [OData-ABNF] that describes the syntax of $expand:
expand            = '$expand' EQ expandItem *( COMMA expandItem )

expandItem        = STAR [ ref / OPEN levels CLOSE ]
                  / expandPath
                    [ ref   [ OPEN expandRefOption   
                           *( SEMI expandRefOption   ) CLOSE ]
                    / count [ OPEN expandCountOption
                           *( SEMI expandCountOption ) CLOSE ]
                    /         OPEN expandOption
                           *( SEMI expandOption      ) CLOSE 
                    ]

expandPath        = [ ( qualifiedEntityTypeName
                      / qualifiedComplexTypeName 
                      ) "/" ] 
                    *( ( complexProperty / complexColProperty ) "/" 
                       [ qualifiedComplexTypeName "/" ] )
                    navigationProperty 
                    [ "/" qualifiedEntityTypeName ]

expandCountOption = filter
                  / search

expandRefOption   = expandCountOption
                  / orderby
                  / skip 
                  / top 
                  / inlinecount

expandOption      = expandRefOption
                  / select 
                  / expand
                  / levels

It is also possible to expand all declared and dynamic navigation properties using a star (*). To retrieve references to all related entities use */$ref, and to expand all related entities with a certain distance use the star operator with the $levels option. The star operator can be combined with explicitly named navigation properties, which take precedence over the star operator.

**Comment by chinadragon0515** [comment]
Based on the specification, 
For star in expand, this will be supported,
$expand=*
$expand=EntitySet($expand=*)
$expand=*/$ref (This will be supported when we add $ref full support for expand)
$expand=*,EntitySet
$expand=EntitySet,*
Parenthesized set of expand options for star expand option supported are $level

And this will throw exception,
$expand=*($expand=EntitySet)
$expand=*($expand=*)
$expand=*/$count 

Parenthesized set of expand options for star expand option which will cause exception are  $filter, $select, $orderby, $skip, $top, $count, $search, and $expand.

**Comment by chinadragon0515** [comment]
Pull request is merged, close the issue.
