### ISSUE TITLE
V3 test cases to investigate

### ISSUE THREAD

**Issue by bixu-ms** [OData/odata.net#304]
Astoria.Test.Taupo.Protocol.Actions.xml.suite
Astoria.Test.Taupo.Protocol.Actions.1.xml.suite
Astoria.Test.Taupo.Protocol.Actions.2.xml.suite
Astoria.Test.Taupo.Protocol.Actions.3.xml.suite
Astoria.Test.Taupo.Protocol.Actions.4.xml.suite
Astoria.Test.Taupo.Protocol.Actions.5.xml.suite
Astoria.Test.Taupo.Protocol.Actions.6.xml.suite
Astoria.Test.Taupo.Protocol.Actions.7.xml.suite
Astoria.Test.Taupo.Protocol.Actions.8.xml.suite
Astoria.Test.Taupo.Protocol.Actions.9.xml.suite
Astoria.Test.Taupo.Protocol.Actions.10.xml.suite
Astoria.Test.Taupo.Protocol.Actions.11.xml.suite
Astoria.Test.Taupo.Protocol.Actions.12.xml.suite
storia.Test.Taupo.Protocol.Create.Versioning.9.xml.suite
storia.Test.Taupo.Protocol.Patch.Versioning.3.xml.suite
storia.Test.Taupo.Protocol.Query.18.xml.suite
storia.Test.Taupo.Protocol.Query.AnyAllError.4.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.CUD.Silverlight.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.MLE.CrossFeature.Silverlight.5.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.MLE.CrossFeature.Silverlight.6.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.1.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.2.xml.suite
Astoria.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.3.xml.suite
Astoria.Test.Taupo.Client.RelationshipLink.Silverlight.xml.suite
Astoria.Test.Taupo.Client.RelationshipLink.Silverlight.1.xml.suite
storia.Test.Taupo.Client.MLE.Silverlight.xml.suite
storia.Test.Taupo.Protocol.Query.18.xml.suite
storia.Test.Taupo.Protocol.Query.AnyAllError.4.xml.suite

**Comment by LaylaLiu** [comment]
Fixed by tfs commit
