### ISSUE TITLE
V3 test cases to ignore

### ISSUE THREAD

**Issue by bixu-ms** [OData/odata.net#305]
Astoria.Test.Taupo.Client.Query.Silverlight.xml.suite
Astoria.Test.Taupo.Client.Query.Silverlight.1.xml.suite
Astoria.Test.Taupo.Client.Query.Silverlight.2.xml.suite
Astoria.Test.Taupo.Client.Query.Silverlight.3.xml.suite
Astoria.Test.Taupo.Protocol.Create.1.xml.suite
Astoria.Test.Taupo.Protocol.Create.3.xml.suite
Astoria.Test.Taupo.Protocol.Create.8.xml.suite
Astoria.Test.Taupo.Protocol.Create.Versioning.7.xml.suite
Astoria.Test.Taupo.Protocol.Metadata.4.xml.suite
Astoria.Test.Taupo.Protocol.Metadata.9.xml.suite
Astoria.Test.Taupo.Protocol.Query.xml.suite
Astoria.Test.Taupo.Protocol.Query.2.xml.suite
Astoria.Test.Taupo.Protocol.Query.4.xml.suite
Astoria.Test.Taupo.Protocol.Query.5.xml.suite
Astoria.Test.Taupo.Protocol.Query.7.xml.suite
Astoria.Test.Taupo.Protocol.Query.8.xml.suite
Astoria.Test.Taupo.Protocol.Query.9.xml.suite
Astoria.Test.Taupo.Protocol.Query.11.xml.suite
Astoria.Test.Taupo.Protocol.Query.12.xml.suite
Astoria.Test.Taupo.Protocol.Query.13.xml.suite
Astoria.Test.Taupo.Protocol.Query.14.xml.suite
Astoria.Test.Taupo.Protocol.Query.15.xml.suite
Astoria.Test.Taupo.Protocol.Query.16.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.1.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.2.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.3.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.5.xml.suite
Astoria.Test.Taupo.Protocol.Query.AnyAllError.6.xml.suite
Astoria.Test.Taupo.Server.Actions.xml.suite
Astoria.Test.Taupo.Server.Regression.xml.suite
ODataWriterTests.xml.suite
ODataWriterTests.Silverlight.xml.suite
storia.Test.Taupo.Client.NamedStreams.CUD.Silverlight.xml.suite
storia.Test.Taupo.Client.RelationshipLink.3.xml.suite
storia.Test.Taupo.Client.MLE.Silverlight.xml.suite
storia.Test.Taupo.Client.NamedStreams.MLE.CrossFeature.Silverlight.5.xml.suite
storia.Test.Taupo.Client.NamedStreams.MLE.CrossFeature.Silverlight.6.xml.suite
storia.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.xml.suite
storia.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.1.xml.suite
storia.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.2.xml.suite
storia.Test.Taupo.Client.NamedStreams.Scenarios.Silverlight.3.xml.suite
storia.Test.Taupo.Client.RelationshipLink.Silverlight.xml.suite
storia.Test.Taupo.Client.RelationshipLink.Silverlight.1.xml.suite
EdmLibTests.DP.Astoria.Tests.NetFX_4.0.V3.Silverlight.xml.suite

**Comment by LaylaLiu** [comment]
Fixed by tfs commit
