### ISSUE TITLE
Cannot upgrade from 7.20.0 to 8.0.1, new version does not target .NET Standard

### ISSUE THREAD

**Issue by Mek7** [OData/odata.net#3073]
I have a C Sharp Class Library that is multi-targeting net4.8 and netstandard2.1
It references Microsoft.OData.Core 7.20.0 via nuget package, and also the other libs such as Microsoft.Spatial, Microsoft.OData.Client and Microsoft.OData.Edm
All of version 7.20.0
When upgraded to 8.0.1, there are errors:

NU1202	Package Microsoft.OData.Core 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Core 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.Spatial 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.Spatial 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.OData.Client 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Client 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.OData.Edm 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Edm 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

Considering that these are class libraries, why do they target a specific .NET version, and not .NET Standard?

### Assemblies affected
Microsoft.OData.Core
Microsoft.Spatial
Microsoft.OData.Client
Microsoft.OData.Edm

### Reproduce steps

Create a C Sharp Class Library that is multi-targeting net4.8 and netstandard2.1
Via nuget, install Microsoft.OData.Core 7.20.0, and also the other libs such as Microsoft.Spatial, Microsoft.OData.Client and Microsoft.OData.Edm - all of version 7.20.0
Then edit project file - the PackageReference elements, set versions of all 4 nuget packages to 8.0.1 and reload project. Observe errors as described above.

### Expected result

No errors.

### Actual result

NU1202	Package Microsoft.OData.Core 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Core 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.Spatial 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.Spatial 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.OData.Client 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Client 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

NU1202	Package Microsoft.OData.Edm 8.0.1 is not compatible with net48 (.NETFramework,Version=v4.8). Package Microsoft.OData.Edm 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

**Comment by robertmclaws** [comment]
Just so you are aware, AFAIK this is not a bug. The OData team made a specific decision to only target .NET 8.0 and later moving forward. If you want to support older frameworks you need to stay on v7.

**Comment by Mek7** [comment]
I always thought that when you have a class library, it should target .NET Standard and when you have a program or website, it should target a specific .NET version. So this pattern does not apply anymore? Should I make all my projects in solution target .NET 8 regardless of if it is a class library or a program? Otherwise I won't be able to consume these OData libraries in my code. The multi-targeting is in place only temporarily because the big solution is being migrated from net48 to net8.0 and netstandard2.1.

**Comment by robertmclaws** [comment]
Targeting .NET standard 2.0 or 2.1 severely limits the number of APIs that are available for you to use, since .NET Standard 2.1 has not evolved anymore. That system was really in place to maintain compatibility between the various .NET runtimes that were out there.

Now there is really only one main runtime, so that compatibility layer is mostly unnecessary.

From a migration standpoint, you should not be importing OData into "core" library projects, it should only be in the service layer. OData Client libraries should only be used in end-targeted applications, which should not be on the .NET Framework if the service is on .NET 8.0.

It sounds to me like you have 2 options: Go back to v7, or just take a few minutes and rip out the .NET Framework 4.8 from your solution. I would probably pick the latter if I were in your shoes.

HTH!

**Comment by Mek7** [comment]
I have OData libraries referenced from a Claaa library project because there are more "service" projects in my solution that need OData so this was easier.
Yes, at the end all projects will target .NET 8, but for now there are some huge ASP.NET projects and it is a challenge to migrate them.
Thank you for your explanation, I understand and close this issue.
