### ISSUE TITLE
ODL is being packaged with the wrong framework

### ISSUE THREAD

**Issue by robertmclaws** [OData/odata.net#3088]
The new .NET 8 assemblies are still being packages with .nuspec files instead of letting SDK-style project files do the work. Those .nuspac files have not been updated, so natively-compiled .NET 8 assemblies are being incorrectly delivered into .netstandard2.0 folders in the NuGet package.

### Assemblies affected

ODL 8.x

### Reproduce steps

- Open the Microsoft.Data.Edm.csproj file and see that it targets .NET 8.0 exclusively.
- Open the NuSpec file and see that the .NET 8 assembly is incorrectly packaged into the .NET Standard 2.0 folder.

### Expected result

The SDK-style projects would manage the different `<TargetFrameworks>` supported and add their compiled assets to the NuGet package appropriately.

### Actual result

Features that are not supported by .NET Standard 2.0 are being compiled into incorrectly-constructed NuGet packages that may be causing issues downstream.

**Comment by WanjohiSammy** [comment]
@robertmclaws 

Thanks for opening this ticket. Is this issue related to the way `.NETStandard2.0` has been added as a dependency target framework in [Microsoft.OData.Edm.Release.nuspec](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec)

**Comment by WanjohiSammy** [comment]
@robertmclaws Was this only noted on the `Microsoft.Data.Edm` project or all the projects in ODL including `Microsoft.OData.Core`, `Microsoft.OData.Client` and `Microsoft.Spatial`

**Comment by robertmclaws** [comment]
All of them.

The proper solution here would be to move common Package properties into a Directory.build.props file, and then move library-specific package details into the SDK-style project itself, then delete the .nuspec files from the repo.

Here's a great example: https://github.com/OData/RESTier/blob/main/src/Directory.Build.props

HTH!

**Comment by robertmclaws** [comment]
Also 

> @robertmclaws
> 
> Thanks for opening this ticket. Is this issue related to the way `.NETStandard2.0` has been added as a dependency target framework in [Microsoft.OData.Edm.Release.nuspec](https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Build.NuGet/Microsoft.OData.Edm.Release.nuspec)

It didn't look like it was "added", it looked like it has always been there.

if you folks are still wanting to support .NET Standard 2.0 (or 2.1), then it's as easy as adding those to the <TargetFrameworks> tag and letting the build process sort out how that information gets added to the NuGet package.

Happy to jump on a call or anything if you need help sorting it out. :)
