### ISSUE TITLE
Unable to use Expand(Expression) on Navigation Property

### ISSUE THREAD

**Issue by cbrianball** [OData/odata.net#3095]
Using DataServiceContext.CreateQuery<>(), I can query my OData Endpoint with most operations except the overload of `Expand` that takes an expression. If I use the overload that takes a string, it works correctly.

The exception I am getting is `System.NotSupported Excpetion: The expression 'x => x.<NavigationPropertyName>' is not a valid expression for navigation path. The only supported operations inside the lambda expression body are MemberAccess and TypeAs...`

Looking at my model (via `$metadata`), it shows that the entity does have a navigation property by that name. I cannot include source code link or screenshots. I am hoping this is something simple I am overlooking.

### Assemblies affected

Microsoft.OData.Client v8.x

### Reproduce steps

1. Create a model and endpoints that expose an EntitySet where each item in the set has a navigation property to a collection of entities.
2. Use DataServiceContext.CreateQuery<>() to generate a query and use `Expand(x => x.<navigation property name>)`
3. Execute the query
4. Exception described above is thrown 

### Expected result

Query executes correctly and returns expected data. This is what happens when `.Expand(string)` is used.

### Actual result

Exception described above is thrown

### Additional detail

<none>

**Comment by WanjohiSammy** [comment]
@cbrianball Thanks for noting this. Could you try [nameof](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof) as we investigate this further. For example:

```cs
.Expand(x => nameof(x.<navigation prop name>))
```

**Comment by WanjohiSammy** [comment]
@cbrianball 
I am not able to reproduce this issue. Could you share code or an example that is failing to help with the repro.

Below is the code that I have used to test and is working as expected. It is using [TripPin Service](https://services.odata.org/TripPinRESTierService/(S(4dte2qgkqy1lkpudzkpnk4om))/$metadata)
```cs
using Trippin;

var container = new Container(new Uri("https://services.odata.org/TripPinRESTierService/(S(4dte2qgkqy1lkpudzkpnk4om))"));

var people = container.People.Expand(p => p.Friends).ToList();
foreach (var person in people)
{
    Console.WriteLine($"{person.FirstName} {person.LastName}");
    foreach (var friend in person.Friends)
    {
        Console.WriteLine($"  {friend.FirstName} {friend.LastName}");
    }
}
```

**Comment by cbrianball** [comment]
> @cbrianball Thanks for noting this. Could you try [nameof](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof) as we investigate this further. For example:
> 
> ```cs
> .Expand(x => nameof(x.<navigation prop name>))
> ```

I tried this and it did not work. If I just pass in `nameof(...)`, that does work and it's the workaround I've gone with for now.

When I build my query and debug and look at the query object itself, I am seeing the same error message. None of my breakpoints are being hit that would happens when there's a network call, so I suspect, it's before the EDM has even been retrieved from the server.

I also step through with the debugger and verified that the body of the lambda expression is of type MemberAccess, so I am doing what the error message claims I'm not doing.

I'm going to try to find time to come up with a reproduceable example that I can share (and maybe even figure it out in the process of making that example).

A little more info on my scenario:
- I am NOT adding an OData service reference
- I am creating an instance of `DataServiceContext` directly and invoke `CreateQuery` when I want to create an OData query
- My entity types are in a Shared Project (not a class library), both the client and the server reference the shared project.

**Comment by cbrianball** [comment]
I was using `Microsoft.OData.Client` 8.1.0. I upgraded to 8.2.2 (and I also tested 8.2.0) and the issue is not present in either of those versions, so it is just an issue with.

I did some more testing and the issue exists when referencing the following versions of `Microsoft.OData.Client`: `8.0.1`, `8.0.2`, and `8.1.0`. I did not test anything before `8.0.0`.

Here is an example unit test that demonstrates the issue. Note: any URL can be used as the issue is noticeable before any network calls are made.

```c#
public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        var context = new DataServiceContext(new Uri(...));
        var fooQuery = context.CreateQuery<Foo>("odata/foos");

        fooQuery = fooQuery.Expand(f => f.Bars);
       // step through the code and look at `fooQuery` at this point and you will see the error in the debug view for any of the above listed versions
        Assert.True(true);
    }
}

public class Foo
{
    public Guid Id { get; set; }
    public ICollection<Bar> Bars { get; set; } = [];
}

public class Bar
{
    public Guid Id { get; set; }
}
```
