### ISSUE TITLE
ConvertFromUriLiteral and ConvertToUriLiteral do not round trip

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#311]
if an input is a double 1, call convert to uri literal, and then convert from, it will get an int 1.

**Comment by congysu** [comment]
Call the overload with model.

**Comment by congysu** [comment]
json.net serializes a `double d = 1;` into `1.0`, instead of `1`.  Consider fix the issue.

**Comment by mikepizzo** [comment]
Closing as it does not seem to have been an issue for customers. Will re-visit based on any user feedback.
