### ISSUE TITLE
Breaking change in 8.2.0

### ISSUE THREAD

**Issue by syprieur** [OData/odata.net#3123]
The 8.2.0 OData upgrade contained a breaking change via [Fix/1744 isof unquoted type params issue](https://github.com/OData/odata.net/pull/3108/files#diff-4353a0066027cf1ccd9e21c7ddfda66c1b86615190edba076336ccc1e28cdd88)

A side-effect of this PR seems to be new case-sensitivity.
Example: `?$filter=cast(stringProperty, edm.int64) lt 1`

This used to work in 8.1.0, but now throws an `ODataException` in 8.2.0:
_"Cast or IsOf Function must have a type in its argument"_

Note that with the proper case, the filter still works in 8.2.0:
`?$filter=cast(stringProperty, Edm.Int64) lt 1`

**Comment by WanjohiSammy** [comment]
@syprieur Thanks for pointing this out. I have tested the scenario with versions `8.1.0` and `8.0.0`, but I am still getting the same error. Could you please confirm if it used to work previously as we continue to investigate?

You can find a repo below to repro the issue with different ODL versions. The ODL version in this repo is 8.0.0, but you can update it to **8.1.0** or even **8.2.0**:

https://github.com/WanjohiSammy/ODLTests.git

**Comment by syprieur** [comment]
With your test setup, simply using an `ODataUriParser` with `UnqualifiedODataUriResolver` instead of an `ODataQueryOptionParser` repros with `string filterQuery = "cast(ID, edm.int64) lt 1";`

``` cs
            var parser = new ODataUriParser(HardCodedTestModel.TestModel, new Uri($"/People?$filter={filterQuery}", UriKind.Relative))
            {
                Resolver = new UnqualifiedODataUriResolver()
                {
                    EnableCaseInsensitive = true,
                },
                UrlKeyDelimiter = ODataUrlKeyDelimiter.Slash,
            };
            parser.Settings.MaximumExpansionDepth = 2;
            parser.ParsePath();
            var filter = parser.ParseFilter();
```

Results matrix:

| filterQuery/OData Version | 8.1.0 | 8.2.0 |
| - | - | - |
| "cast(ID, edm.int64) lt 1" | Ok | Throws |
| "cast(ID, edm.Int64) lt 1" | Ok | Ok |

**Comment by WanjohiSammy** [comment]
Thanks @syprieur for adding further repro steps.

**Comment by WanjohiSammy** [comment]
Resolved. 

https://github.com/OData/odata.net/releases/tag/8.2.2
