### ISSUE TITLE
Write untyped json property for entry

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#317]
Add a flag, such as `SupportUntypedJson` to enum `UndeclaredPropertyBehaviorKinds`.
Add the enum to `ODataMessageWriterSettings.cs`.
In `WriteProperty` of `ODataJsonLightPropertySerializer.cs`, add logic to write `ODataUntypedValue`.

``` c#
JsonWriter.WriteName(wirePropertyName);
JsonWriter.WriteValue(value);
```

Add a few test cases for untyped json in `ODataJsonLightEntryAndFeedSerializerTests.cs`.

``` c#
var entry = new ODataEntry
{
  TypeName = "ns.Customer",
  Properties = new[]
  {
    new ODataProperty { Name = "Id", Value = new ODataPrimitiveValue(0) },
    new ODataProperty { Name = "Untyped", Value = new ODataUntypedValue(@"{""k1"":""v1""}") }
  }
}

writer.WriteStart(entry);
writer.WriteEnd();
```

Output should be - indentation is for demo propose:

``` json
{
  "odata.metadata": "...",
  "Id": 0,
  "Untyped": {
    "k1":"v1"
  }
}
```

**Comment by AlanWong-MS** [comment]
Closing as this has been addressed by #436.
