### ISSUE TITLE
[T4] CodeGen may not work if another extension which contains Microsoft.OData.Edm.dll of a different version has been installed.

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#328]
If you install Microsoft Cosmos ScopeStudio first, which contains Microsoft.OData.Edm.dll (6.3.0) in its extension folder. Then, you install OData Client Code Generator 2.4.0, and try to generate the client proxy file for some service. It may report following error or warning

Error   1   A namespace cannot directly contain members such as fields or methods   c:\Users\layliu\Documents\Visual Studio 2013\Projects\ConsoleApplication9\ConsoleApplication9\ODataClient1.cs   1   1   ConsoleApplication9
Warning 2   Multiple assembly references match 'Microsoft.OData.Client.dll' under Extensions directories.  Using 'C:\USERS\LAYLIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\MICROSOFT\SCOPESTUDIO\1.8.0000.3\Microsoft.OData.Client.dll'.    c:\Users\layliu\Documents\Visual Studio 2013\Projects\ConsoleApplication9\ConsoleApplication9\ODataClient1.tt   0   0   ConsoleApplication9
Warning 3   Multiple assembly references match 'Microsoft.OData.Core.dll' under Extensions directories.  Using 'C:\USERS\LAYLIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\MICROSOFT\SCOPESTUDIO\1.8.0000.3\Microsoft.OData.Core.dll'.    c:\Users\layliu\Documents\Visual Studio 2013\Projects\ConsoleApplication9\ConsoleApplication9\ODataClient1.tt   0   0   ConsoleApplication9
Warning 4   Multiple assembly references match 'Microsoft.OData.Edm.dll' under Extensions directories.  Using 'C:\USERS\LAYLIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\MICROSOFT\SCOPESTUDIO\1.8.0000.3\Microsoft.OData.Edm.dll'.  c:\Users\layliu\Documents\Visual Studio 2013\Projects\ConsoleApplication9\ConsoleApplication9\ODataClient1.tt   0   0   ConsoleApplication9
Warning 5   Multiple assembly references match 'Microsoft.Spatial.dll' under Extensions directories.  Using 'C:\USERS\LAYLIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\MICROSOFT\SCOPESTUDIO\1.8.0000.3\Microsoft.Spatial.dll'.  c:\Users\layliu\Documents\Visual Studio 2013\Projects\ConsoleApplication9\ConsoleApplication9\ODataClient1.tt   0   0   ConsoleApplication9
Error   6   Compiling transformation: The type or namespace name 'Vocabularies' does not exist in the namespace 'Microsoft.OData.Edm' (are you missing an assembly reference?)  c:\Users\layliu\AppData\Local\Temp\4x0x3xbv.0.cs    17  31

**Comment by sungwookgit** [comment]
I also had the same issue when trying to generate OData query due to conflicts. This happens because Scope Studio extension is referencing to the conflicting DLLs. It looks like this issue was addressed in the latest version of Scope Studio (2.0).

**Comment by AlanWong-MS** [comment]
Closing this as issue seems to be have been resolved in Scope Studio end.
