### ISSUE TITLE
Problem serializing collection of long or complex type with long property in Url 

### ISSUE THREAD

**Issue by sundalova** [OData/odata.net#329]
I have a function with one parameter IEnumerable of long
When I try to call it my arguments serialized as @arg=["1","2"]; as a result I get 404 error.

To get same result you could just use this code
```
Microsoft.OData.Client.Serializer.GetParameterString(DataServiceContext, new Microsoft.OData.Client.UriOperationParameter("arg", new long[] {1L, 2L}));
```

I've looked into code and found out that it's because for collections and complex types is used JsonWritter with attribute isIeee754Compatible = true.
Particularly I'm talking about ODataUriConversionUtils.WriteJsonLightLiteral which is used fo ConvertToUriComplexLiteral and ConvertToUriCollectionLiteral
I was thinking that perhaps this attribute should be false by default? Actually, why is it used at all to serialize url arguments? I feel like this could be a bug

Could you please investigate?

**Comment by congysu** [comment]
@sundalova Which server library do you use - OData Web API or RESTier?

**Comment by sundalova** [comment]
@congysu OData Web API

**Comment by CrazyViper** [comment]
Also wating for this fix.

@congysu what's the state of this issue?

**Comment by chinadragon0515** [comment]
@sundalova I write a test case today to reproduce with newest code, I did not see any issues. can you help to have a try with newest code?
If you can reproduce the issue, I will need more information,
1. From test cases, you are using OData lib client, can you help to test with manually construct  URL to see whether there is any issues?  And the URL should like function(arg=["1","2"])
2. Show me the server side code how to define the function passed in parameters.

@CrazyViper , can you help to try with newest code too to see whether there is any issues in the newer version? thanks.

**Comment by LaylaLiu** [comment]
@sundalova @CrazyViper, Thanks for reporting this issue. I will close this issue right now since we cannot repro this issue. If you have more update on this issue or if you have still questions about this issue, please reopen it.
