### ISSUE TITLE
ForeignKey properrty nullable=false not set

### ISSUE THREAD

**Issue by pysco68** [OData/odata.net#337]
Hello,

I hope this is in the right place. I am currently migrating to OData v4 since DateTime support is finally there in a usable form. 

My issue is that there's apparently a change in the behavior how the Model builder is "understanding" entity properties that make the foreign key available. 

Considering entity framework model example:

    public class Entity1 
    {
        public int Id { get; set; }  
        public string Name { get; set; }
    }

    public class Entity2
    {
        public int Id { get; set; } 

        [ForeignKey("EntityOneId")]
        public virtual Entity1 EntityOne { get; set; }
        public int EntityOneId { get; set; }
    }

I would expect that the property `EntityOneId` of `Entity2` is marked as `nullable=false` but the generated `$metadata` doesn't contain the information. 

This in turn has the consequence that the T4 Client Generator does generate a class on the client side that has a `Nullable<int> EntityOneId` instead of the expected `int` data type.

Am I missing some thing or is this a bug?

**Comment by xuzhg** [comment]
@pysco68 Would you please show us about how you build your Edm model? 

Basically, if you are building the Edm by Web API OData, here's some material that you can refer to this issue. http://odata.github.io/WebApi/#04-02-referential-constraint

Look forward more feedback from you. Thanks.

**Comment by pysco68** [comment]
I'm using the `ODataConventionModelBuilder` as I'm publishing the EF model with OData.

    var builder = new ODataConventionModelBuilder();
    builder.ContainerName = "MyContext";
    builder.Namespace = "MyContext.Model";

    builder.EntitySet<Entity1>("Entity1");
    builder.EntitySet<Entity2>("Entity2");

    var model = builder.GetModel();

**Comment by congysu** [comment]
OData v4 Web API 5.7 supports to advertise vocabulary annotation in $metadata.

**Comment by pysco68** [comment]
Could you elaborate that a little bit please?

**Comment by xuzhg** [comment]
Close it because it is related to Web API. And Same issue is created at: https://github.com/OData/WebApi/issues/690
