### ISSUE TITLE
Test - Strong name validation failed

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#344]
Test Name:	String2Guid
Test FullName:	Microsoft.Test.OData.Query.TDD.Tests.ODataUriUtilsTest.String2Guid
Test Source:	C:\Users\su\Documents\repo\odata.net\test\FunctionalTests\Tests\DataOData\Tests\OData.Query.TDD.Tests\ODataUriUtilsTest.cs : line 223
Test Outcome:	Failed
Test Duration:	0:00:00.223029

Result StackTrace:	at Microsoft.Test.OData.Query.TDD.Tests.ODataUriUtilsTest.String2Guid()
Result Message:	
Test method Microsoft.Test.OData.Query.TDD.Tests.ODataUriUtilsTest.String2Guid threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.OData.Core, Version=6.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by YogiBear52** [comment]
I have this problem too, is there a soultion? I can't event run the unit tests..

**Comment by azachert** [comment]
Have same issue after downloading fresh sources from ODataV4-6.x branch. Any solution?
