### ISSUE TITLE
Support Edm.Date as edm:Key

### ISSUE THREAD

**Issue by SageLukeDean** [OData/odata.net#347]
### Description
Currently, if an Edm.Date is used as a key field, it is impossible to fetch an individual element because LiteralParser has no parser for Edm.Date.

### Minimal repro steps
Define an Entity type that has an Edm.Date as a key field.
Attempt to fetch ~/MyEntity(DateKey=2015-09-28)

### Expected result
Date keys should now be supported as per section 8.2 "Element edm:Key" of the Common Schema Definition Language.  http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397981

### Actual result
Microsoft.OData.Core.UriParser.Parsers.LiteralParser Parsers is missing an entry for Edm.Date, so it fails with an exception saying as much.

### Further technical details
The SelfLinks generator already supports Edm.Date properly, so we're able to generate links for elements who have Edm.Date as key segments.  The Uri parser just fails to parse them.

Adding a PrimitiveParser to LiteralParser.Parsers for Edm.Date fixes the issue and allows me to fetch entities with Edm.Date in the key.
LiteralParser currently uses XmlConvert.ToDateTimeOffset() to parse a string into a DateTime.  We can use that same function to parse a string into an Edm.Date.

I can submit a pull request for the modified LiteralParser.cs and a unit test.

**Comment by xuzhg** [comment]
@SageLukeDean Thanks your feedback and warmly welcome send us pull request.

**Comment by LianwMS** [comment]
Committed and closed
