### ISSUE TITLE
[V3] Test regression caused by untyped json change

### ISSUE THREAD

**Issue by luoyan0517** [OData/odata.net#348]
Failed cases are:
<strong>1. Command: </strong>
    `TaupoAstoriaRunner.exe /suite:Client.Query.suite /host:wcf /runner:Silverlight /slrunnerpath:%SilverlightPath% /slpath:%SilverlightPath% /logfile:%ResultFolder%\Astoria.Test.Taupo.Client.Query.Silverlight.xml /autorun /autoexit /t:AuthenticationProvider=Windows /t:ClientCodeLayerGenerator=Binding /t:Language=CSharp /t:MetadataProviderTypingStrategy=CLR /t:Model=AstoriaDefaultModelGenerator /t:QueryVerifier=ClientExecute /t:ServiceBuilder/Provider=Reflection /t:Asynchronous=true /t:ExecuteURI=false /t:MaxProtocolVersion=V3 /t:ClientMaxProtocolVersion=V3 /t:ModelFeatureVersion=V3 /t:MaxPriority=1 /t:UsePayloadDrivenVerification=True /Browser:iexplore`

<strong>Cases:</strong>
* Basic Query Test cases --> Get specific entity, Get specific entity, expand nav props 1 level deep, Get specific entity, expand nav props 2 levels deep
* RowCount Query Test cases --> Inline count of a queryable
* TopSkipOrderByTestCase Query Test cases --> Query using top option, equal total

<strong>2. Command: </strong>
    `TaupoAstoriaRunner.exe /suite:Client.Query.suite /host:wcf /runner:Silverlight /slrunnerpath:%SilverlightPath% /slpath:%SilverlightPath% /logfile:%ResultFolder%\Astoria.Test.Taupo.Client.Query.Silverlight.1.xml /autorun /autoexit /t:AuthenticationProvider=Windows /t:ClientCodeLayerGenerator=POCO /t:Language=CSharp /t:MetadataProviderTypingStrategy=CLR /t:Model=AstoriaDefaultModelGenerator /t:QueryVerifier=ClientExecute /t:ServiceBuilder/Provider=Reflection /t:Asynchronous=true /t:ExecuteURI=false /t:MaxProtocolVersion=V3 /t:ClientMaxProtocolVersion=V3 /t:ModelFeatureVersion=V3 /t:MaxPriority=1 /t:UsePayloadDrivenVerification=True /Browser:iexplore`

<strong>Cases:</strong>
* Default shared filter tests--> Filter with And and EqualTo, Filter with Or and EqualTo,  Filter+Key with And and EqualTo
* RowCount Query Test cases-->Inline count of a Queryable

<strong>3. Command: </strong>
    `TaupoAstoriaRunner.exe /suite:Protocol.Spatial.CUD.suite /runner:console /host:wcf /logfile:%ResultFolder%\Astoria.Test.Taupo.Protocol.Spatial.CUD.xml /autorun /autoexit /t:AuthenticationProvider=Windows /t:ClientCodeLayerGenerator=Remote /t:DataServiceDeployment=IIS /t:Language=CSharp /t:MetadataProviderTypingStrategy=Random /t:Model=AstoriaDefaultModelGenerator /t:QueryVerifier=XmlProtocol /t:ServiceBuilder/Provider=Dictionary /t:Asynchronous=false /t:ExecuteURI=false /t:MaxProtocolVersion=V3 /t:ServiceBuilder/Provider/EF/DatabaseProvider=SQL /t:ServiceBuilder/Provider/EF/EntityModelSourceFilesGenerator= /t:ServiceBuilder/Provider/EF/ContextType=ObjectContext /t:MaxPriority=1` 

<strong>Cases:</strong>
* Protocol CUD Test Case --> Katmai Spatial Put Protocol tests --> Katmai Spatial Put Protocol tests --> Modify an entity using JSON-Light

<strong>4. Command: </strong>
    `TaupoAstoriaRunner.exe /suite:ODataCommonTests.suite /runner:wpf /host:wcf /logfile:%ResultFolder%\ODataCommonTests.xml /autorun /autoexit /t:MaxPriority=2 /t:TestRunKind=All /Browser:IE`

<strong>Cases:</strong>
* ObjectModelTypesTests --> Verifies that all OData public types are sealed as appropriate.

**Comment by challenh** [comment]
close it. https://github.com/OData/odata.net/commit/f1934b38346cc328bfdd2db9757c0be2c7c16942
