### ISSUE TITLE
Parser conflict between UrlConventions KeyAsSegment and last segment == TypeSegment

### ISSUE THREAD

**Issue by sleetaylor** [OData/odata.net#349]
When submitting a request with a TypeSegment and using UrlConventions KeyAsSegment,(example: /Me/Messages/Microsoft.OutlookServices.EventMessage) the ODataUriParser returns the last segment as a KeySegment and not a TypeSegment. When removing the UrlConventions KeyAsSegment the UriParser recognizes the last segment to be a TypeSegment.

**Comment by karataliu** [comment]
@sleetaylor 

Thanks a lot for the PR.

This is designed behavior, when KeyAsSegment is truned on, every element appear in the key placeholder would be treated as key, and you should use '$' to escape all non-key segments.

So /Me/Messages/$/Microsoft.OutlookServices.EventMessage should work for that case.

If taking this, this would introduce breaking changes to existing users who would expect all unescaped key candidates to be actual keys.

**Comment by VikingsFan** [comment]
Checked in f1dcbffae7277f5b6c61e50ad6eebd980743be2c

**Comment by congysu** [comment]
The merged pull requests are https://github.com/OData/odata.net/pull/350 and https://github.com/OData/odata.net/pull/372.
