### ISSUE TITLE
[V3 WCFDS 5.7.0.0-beta] Client would throw exception if the payload includes a NavigationProperty on some entity that the client does not know 

### ISSUE THREAD

**Issue by luoyan0517** [OData/odata.net#352]
WCFDS 5.7.0.0 Beta introduces a new property UndeclaredPropertyBehaviour on the DataServiceContext. By default, UndeclaredPropertyBehaviour is set to none for backwards compatibility, however it does not work on NavigationProperty. 

By using the default value of UndeclaredPropertyBehaviour and setting the former IgnoreMissingProperties to be true, client now would throw if the payload includes a NavigationProperty on some entity that the client does not know.

**Comment by challenh** [comment]
close it. https://github.com/OData/odata.net/commit/f1934b38346cc328bfdd2db9757c0be2c7c16942
