### ISSUE TITLE
EdmUtil's static method DictionaryGetOrUpdate is not thread safe

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#353]
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/EdmUtil.cs#L429-L448

Ref to:
http://stackoverflow.com/questions/6738634/is-this-non-locked-trygetvalue-dictionary-access-thread-safe
http://stackoverflow.com/questions/5885193/lock-on-dictionarys-trygetvalue-performance-issues
http://blogs.msdn.com/b/kimhamil/archive/2008/03/08/hashtable-and-dictionary-thread-safety-considerations.aspx

This may apply to both v4 and v3.

Related issue: https://github.com/OData/odata.net/issues/243

**Comment by karataliu** [comment]
The only reason we do not use concurrent dictionary is we've got 3.5 projects. See if we can use pre-compile flags to enable it for non-3.5 projects.

**Comment by LianwMS** [comment]
Submitted with 1576f1eea7c734d1cf46fad886abb2537bc5a2e1
