### ISSUE TITLE
OData Expand overrides Entity Framework includes

### ISSUE THREAD

**Issue by HenkHui** [OData/odata.net#356]
I have posted a question on Stackoverflow regarding OData expands:

http://stackoverflow.com/questions/33164537/odata-expand-override-entity-framework-includes

Any suggestions?

**Comment by congysu** [comment]
@HenkHui There is an auto expand feature in OData v4 Web API.  Would you like to give it a try? http://odata.github.io/WebApi/#04-15-autoexpand-attribute

**Comment by HenkHui** [comment]
Thank you for your answer.
AutoExpand does not work on ComplexTypes (by design).

**Comment by xuzhg** [comment]
Close it because it related to Web API. Same issue create at https://github.com/OData/WebApi/issues/689
