### ISSUE TITLE
Expanding a OData function call result throws exception

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#357]
http://stackoverflow.com/questions/33114858/expanding-a-odata-function-call-result-throws-exception-since-upgrading-generato

**Comment by vilchinsky** [comment]
Moreover, you cannot perform basic query options on function e.g. $count, $top, $skip. The error is the same "Individual properties can only be selected from a single resource or as part of a type. Specify a key predicate to restrict the entity set to a single instance or project the property into a named or anonymous type."

**Comment by LaylaLiu** [comment]
have been fixed by https://github.com/OData/odata.net/commit/e5abc7394786c598413de67589a8f0435bae5fc5
