### ISSUE TITLE
[OData Client] Support TypeDefinition

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#360]
OData client should support type definition.

**Comment by congysu** [comment]
The ask is for OData Client and T4.

**Comment by skottmckay** [comment]
Would be great if this could be added as https://outlook.office.com/api/v2.0/$metadata uses TypeDefinition

**Comment by ultimate-deej** [comment]
I'm trying to use Client Code Generator with Outlook REST API mentioned by @skottmckay.
It works after making the following changes:
1. In the `GetClrTypeName` function, use the underlying type of a type definition just as a regular primitive type.
 ```c#
internal static string GetClrTypeName(IEdmTypeReference edmTypeReference, bool useDataServiceCollection, ODataClientTemplate clientTemplate, CodeGenerationContext context, bool addNullableTemplate = true, bool needGlobalPrefix = true, bool isOperationParameter = false)
{
    string clrTypeName;
    IEdmType edmType = edmTypeReference.Definition;
    IEdmPrimitiveType edmPrimitiveType = edmType as IEdmPrimitiveType;
    // Add this: ↓↓↓
    IEdmTypeDefinition edmTypeDefinition = edmType as IEdmTypeDefinition;
    if (edmPrimitiveType == null && edmTypeDefinition != null)
    {
        edmPrimitiveType = edmTypeDefinition.UnderlyingType;
    }
    …
```
2. In the `WriteNamespace(string fullNamespace)` function, skip writing type declaration for type definitions.
```c#
    …
    Dictionary<IEdmStructuredType, List<IEdmStructuredType>> structuredBaseTypeMap = new Dictionary<IEdmStructuredType, List<IEdmStructuredType>>();
    foreach(IEdmSchemaType type in schemaElements.OfType<IEdmSchemaType>())
    {
        IEdmEnumType enumType = type as IEdmEnumType;
        if (enumType != null)
        {
            this.WriteEnumType(enumType);
        }
        // Add this: ↓↓↓
        else if (type is IEdmTypeDefinition)
        {
            continue;
        }
    …

```
For a general case, however, additional changes are probably needed.

**Comment by mikepizzo** [comment]
We would love a contribution to support TypeDefinitions in ODataClient and codegen!

**Comment by habbes** [comment]
Support for `TypeDefinition` was added to the code generator. If this issue still exists in the latest library versions, kindly open a new issue.
