### ISSUE TITLE
OData V4 Controller Templates only show in C# projects. What about VB?

### ISSUE THREAD

**Issue by ImGonaRot** [OData/odata.net#362]
When installing the OData V4 Controller Templates they are only showing under C# projects.
There are still a lot of VB developers that would like to be able to use the templates.

**Comment by congysu** [comment]
@ImGonaRot Do you mean OData v4 Web API scaffolding?

**Comment by ImGonaRot** [comment]
Yes. I do mean the scaffolding called "Microsoft OData v4 Web API Controller".
This item appears when clicking add new controller but only for C# projects.
It does not appear under VB projects.
