### ISSUE TITLE
Support collection of mixed primitive types and Edm.Untyped

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#366]
Add support for one dimensional array of object for properties, such as [100, "Hello", 200, "World"].

Related OData spec:
·         Collection(Edm.PrimitiveType) and Collection(Edm.ComplexType)
cannot be used as the type of a property.
cannot be used as the return type of a function.
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part3-csdl.html

More:
ODATA-881: Add support for Edm.Untyped
https://issues.oasis-open.org/browse/ODATA-881
ODATA-879 : Support Arrays of Arrays
https://issues.oasis-open.org/browse/ODATA-879

**Comment by zlatko-michailov** [comment]
My PR on #315 and #317 makes it possible to write:
```C#
ODataCollectionValue() 
{
    Items = new ODataUntypedValue[] {...}
}
```

There is a unit test for that.

What's left to do is to recognize "Edm.Untyped" as a built-in type in EDM.
