### ISSUE TITLE
Bug: case insensitivity does not work for collections sometimes

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#371]
Copied from https://github.com/OData/WebApi/issues/511

--

This path is failing in DefaultODataPathHandler.Parse:
me/notes/noTeBooks/12345

"me" is a User
"notes" is a navigationproperty
notebooks is a collection of notebooks

I get the ODataException:
The request URI is not valid. Since the segment 'notebooks' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource.

However, this works with the (properly cased) path: me/notes/notebooks/12345

our metadata document is at https://www.onenote.com/api/beta/$metadata

I have a similar issue with this path:
mYOrgAniZation/SiteCollections?$expand=sites Except it throws an ODataUnrecognizedPathException

**Comment by VikingsFan** [comment]
This is working and closed related bug in webapi.
