### ISSUE TITLE
ODATA EntityType issue

### ISSUE THREAD

**Issue by ankitguptaa** [OData/odata.net#381]
var A= builder.EntitySet<A>("A");
            A.EntityType.Name = "A";
            A.EntityType.Namespace = ResourceConstants.Namespace;

var B= builder.EntitySet<B>("B");
            B.EntityType.Name = "B";
            B.EntityType.Namespace = ResourceConstants.Namespace;

I have two entities A and B and both having their respective controllers and methods inside it. A is a child of B and the relation is like : one A to many B.

Now the problem is, I need to make an action method addAs which will take list of As as input and return updated list of As. But along with A, I was expecting the child entities B as well in response object, but only A came up in result.

var addAs = A.Action("AddAs");
            addSteps.ReturnsCollectionFromEntitySet<A>("A");
            addSteps.CollectionParameter<A>("A");

Any Suggestions how can I achieve this?

**Comment by xuzhg** [comment]
Hi, @ankitguptaa 

I think what you should do is to apply the `$expand=Bs`.

For example, if I have a bound action named "GetCustomersAction"

1. Then, I can call the action as:

 __POST ~/Customers(1)/NS.GetCustomersAction__

I can get the following result:

``` json
{
  "@odata.context":"http://localhost/odata/$metadata#Customers","value":[
    {
      "Id":1
    },{
      "Id":2
    }
  ]
}
```

2. Or I can the action as:

__POST ~/Customers(1)/NS.GetCustomersAction?$expand=Orders__

I can get the following result. You can find the Orders are expanded.

```json
{
  "@odata.context":"http://localhost/odata/$metadata#AbcCustomers","value":[
    {
      "Id":1,"Orders":[
        {
          "OrderId":11
        },{
          "OrderId":12
        ...
        }
      ]
    },{
      "Id":2,"Orders":[
        {
          "OrderId":21
        },{
          "OrderId":22
        ...
      ]
    }
  ]
}
```

Where, the method in the controller is as follows:
```C#
[EnableQuery]
[HttpPost]
public IHttpActionResult GetCustomersAction(int key, ODataActionParameters parameters)
{
      ...
      return Ok(Customers);
 }
```

**Comment by xuzhg** [comment]
Close it. If you have any further concern, please re-open it. Thanks.
