### ISSUE TITLE
Support for properties of type Edm.ComplexType

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#382]
Add built-in abstract type: Edm.ComplexType, Edm.EntityType, Edm.PrimitiveType support to Edm, Parser, Reader/Writer.

**Comment by mikepizzo** [comment]
This has actually come up in a few different forms. Perhaps the untyped work will make this easier to add.

**Comment by xuzhg** [comment]
Same as issue: #1027 
Fixed in PR: https://github.com/OData/odata.net/pull/1051
Thanks.
