### ISSUE TITLE
"inline" navigational properties in the delta sync response

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#390]
Add the ability to contain "inline" navigational properties in the delta sync response, as part of $entity.
The ask is for: protocol, ODataLib, and Client.

**Comment by lewischeng-ms** [comment]
SWAG for this task: **2 months**
 - **Protocol**: **1-2 weeks**. Now the feature ask does not conform to [OData spec](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940645): *Entities include annotations for selected navigation links based on odata.metadata but MUST NOT include expanded navigation properties inline.* So our team first need to go through with mikep about the validity of this feature and how future spec would support it.
 - **Design**: **2 weeks**. To support reading and writing "inline" navigation properties in the $entity part of the delta response, both `ODataJsonLightDeltaReader` and `ODataJsonLightDeltaWriter` need to be redesigned with new scopes, say `InlineDeltaFeedScope` and `InlineDeltaEntryScope` for reading or writing inline entries, and corresponding new states. The reader and writer state machine also need to be revised accordingly. We also need to define the types used to represent the inline feed and entry. Possible options are: 1) reuse `ODataFeed` and `ODataEntry`; 2) define new types. The last part is about URL. What kind of URL should be used to request inline navigation properties? What context URL should be within the inline feed?
 - **Code&Test**: **2-3 weeks** based on the design. What we should do includes: 1) clearly define the new state machine of the reader and the writer; 2) ensure there is no regression for existing delta cases; 3) revise URL parser and context URL builder if necessary; 4) unit and functional tests (also cover round-trip of inline entries).
 - **E2E&Doc**: **2 weeks**. We already have a service supporting delta feature. We need to update the service with inline navigation properties and add client-side test cases. The difficult part is how to compute and present the delta changes of the inline entities. They have to keep consistent with the top-level delta feed. Also there should be a doc telling service developers how to use this new feature.

**Comment by lewischeng-ms** [comment]
Writer: https://github.com/OData/odata.net/commit/86e4f7364aa1efbac92713bff25d8ad7c43f4527
Reader: https://github.com/OData/odata.net/commit/f5046690147bd6c724556d0cc12ef011ac7d3f8d

**Comment by lewischeng-ms** [comment]
Doc: http://odata.github.io/odata.net/#21-24-expanded-navigation-delta

**Comment by lewischeng-ms** [comment]
Current limitations on reading expanded navigation properties in delta response:
 - Cannot read the next link on an expanded feed (which means no paging support)
 - Cannot read the annotations on an expanded navigation property except its navigation link and association link
 - Cannot read the metadata reference properties of an expanded entry (usually appear in full metadata)

The only way to solve all of these problems is to "fabricate" the context URL for an expanded feed/entry in delta response so that the deserializer can have a "fake" `ContextUriParseResult` to parse the above links and annotations.

*But there are no such limitations for the delta writer.*
