### ISSUE TITLE
Client not Parsing properties

### ISSUE THREAD

**Issue by snowppy** [OData/odata.net#393]
I am currently having trouble with the v4 client side where some of the properties of the server response are set in the result entity and some are set to null. In the server response bellow both URL and WebLocation properties are set to null in the client side entity while the Name, FileId and SessionId are set correctly. Am I missing some configuration option in the client code generation or is there a way to make the client correctly parse  Properties containing urls ? 
```
Schema definition of the RWDFile entity: 
<Schema Namespace="LCMSDataModel.File">
<EntityType Name="RWDFile">
<Key><PropertyRef Name="FileId"/></Key>
<Property Name="SessionId" Type="Edm.Int32"/>
<Property Name="FileId" Type="Edm.Int32" Nullable="false"/>
<Property Name="FileName" Type="Edm.String"/>
<Property Name="URL" Type="Edm.String"/>
<Property Name="WebLocation" Type="Edm.String"/>
<NavigationProperty Name="Session" Type="LCMSDataModel.Sessions.RWDSession"><ReferentialConstraint Property="SessionId" ReferencedProperty="SessionId"/></NavigationProperty><NavigationProperty Name="RelatedFiles" Type="Collection(LCMSDataModel.Interface.File.IFile)"/>
</EntityType>
</Schema>
```

I have the following as action server response:
```
{
  "@odata.context":"http://localhost:8500/odata/$metadata#File","value":[
    {     "SessionId":101,"FileId":444,"FileName":"TestFileUpload.txt","URL":"https://dynatestdev1.blob.core.windows.net/project-176/session/101/rwd/TestFileUpload.txt?sv=2015-04-05&sr=b&si=projectWritePolicy&sig=C9zOm4Kwa%2BaCyVQOc1szY%2Bb6GugSeUPBdvmlgR74Xdg%3D","WebLocation":"https://dynatestdev1.blob.core.windows.net/project-176/session/101/rwd/TestFileUpload.txt?sv=2015-04-05&sr=b&si=projectWritePolicy&sig=C9zOm4Kwa%2BaCyVQOc1szY%2Bb6GugSeUPBdvmlgR74Xdg%3D"
    }
  ]
}
```

**Comment by LaylaLiu** [comment]
The only reason that i can think of is that you actually have send two requests, the first one's response doesn't contains the URL and WebLocation in the entry, but the second one does have them for the same entry. By default, the client value will not be changed unless you set the DataServiceContext.MergeOption = MergeOption.OverwriteChanges. So the url and weblocation are still null. 

If it is not the reason. Please send me your client code for us to investigate the issue.

**Comment by LaylaLiu** [comment]
@snowppy Thanks for reporting this issue. I will close this issue right now. If you have more update on this issue or if you have still other questions about this issue, please reopen it.
