### ISSUE TITLE
OData client error when using "where" on a Function or Action

### ISSUE THREAD

**Issue by ImGonaRot** [OData/odata.net#394]
I am receiving the following error when calling an OData function and using a "Where" to filter the function in a .NET client.
> Individual properties can only be selected from a single resource or as part of a type. Specify a key predicate to restrict the entity set to a single instance or project the property into a named or anonymous type.

On the OData client I have the following code:
```c#
    var data = db.TestDatas.GetTestGetByT(1234).Where(x => x.ID == 1).ToList();
```
On the OData host I have the following in the "WebApiConfig"
```c#
FunctionConfiguration getTestGetByT = builder.EntityType<TestData>().Collection.Function("GetTestGetByT");
getTestGetByT.Parameter<Int>("SomeID");
getTestGetByT.ReturnsCollectionFromEntitySet<TestData>("TestDatas");
```
AND the "Controller"
```c#
[EnableQuery()]
[HttpGet()]
public IQueryable<TestData> GetTestGetByT(Int SomeID)
{
	return db.TestDatas;
}
```

BUT in a web client the following works fine.
> http://localhost/TestDatas/Default.GetTestGetByT(SomeID=1234)?$filter=ID%20eq%201

**Comment by LaylaLiu** [comment]
Can you try the latest ODataLib 6.14 to see if the issue still exists? It should have been fixed in ODL 6.14.
