### ISSUE TITLE
Dynamic/Additional properties of a non-open type

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#400]
A dynamic property in a non-open type is asymmetric - Set by server, read by client; but not other way around.

Properties declared as part of a structured type's definition are called declared properties. **Instances of structured types may contain additional undeclared dynamic properties.** A dynamic property cannot have the same name as a declared property. Entity or complex types which allow clients to persist additional undeclared properties are called open types.
...
To create an open entity (an instance of an open type), additional property values beyond those specified in the metadata MAY be sent in the request body. The service MUST treat these as dynamic properties and add them to the created instance.
**If the entity being created is not an open entity, additional property values beyond those specified in the metadata SHOULD NOT be sent in the request body. The service MUST fail if unable to persist all property values specified in the request.**
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html

Dynamic properties can be used in the same way as declared properties. If they are not defined on an instance, they evaluate to null.
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html

**Note: structural and navigation properties MAY be returned by the service on instances of any structured type, whether or not the type is marked as open.** Clients MUST always be prepared to deal with additional properties on instances of any structured type, see [OData‑Protocol].
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part3-csdl.html

**Comment by congysu** [comment]
A related issue https://github.com/OData/odata.net/issues/179 with PR #218's done in 6.13, when EnableFullValidation is false.

**Comment by VikingsFan** [comment]
Cost estimating: 4 days
Pruduct Code: Support open property in ODataJsonLightEntryAndFeedDeserializer & ODataJsonLightPropertySerializer (this is already supported by option (IgnoreUndeclaredValueProperties & EnableFullValidation but need always supported))
Test Code: Need add cases and fix non-throwing exception behavior caused failed case.

**Comment by LianwMS** [comment]
Submitted with 27ded6a0d00e6dd25c237c1875fd089f7fb293a3
