### ISSUE TITLE
Trim CompilerGeneratedAttribute from PublicApi.bsl

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#402]
VS2013 and VS2015 generate different baseline files:
https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/PublicApi.bsl#L16-L22

**Comment by lewischeng-ms** [comment]
Just add a conditional "continue" to the following place would solve this issue:
https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Tests/DataOData/Tests/OData.Common.Tests/PublicApi/DumpPublicApi.cs#L401
