### ISSUE TITLE
Alternat Keys documentation has wrong namespace

### ISSUE THREAD

**Issue by cbrooksmsft** [OData/odata.net#405]
http://odata.github.io/odata.net/#06-06-alternatekey

"Single Alternate Key" has a "Related Metadata" section which has incorrect Annotation Namespaces:

  OData.Community.AlternateKeys.V1.*

should be:

  OData.Community.Keys.V1.*

**Comment by xuzhg** [comment]
@cbrooksmsft The namespace is the result from our discussion. Why do you say it's not correct?

**Comment by cbrooksmsft** [comment]
final namespaces can be found here:
https://github.com/OData/vocabularies/blob/master/OData.Community.Keys.V1.xml

**Comment by xuzhg** [comment]
@cbrooksmsft  

Oh, I see. You means the tutorial doc. 

I updated the doc. http://odata.github.io/odata.net/#06-06-alternatekey. Thanks.
