### ISSUE TITLE
@odata.id for each expanded navigation-property entry in .net C# client

### ISSUE THREAD

**Issue by rudolftraunmueller-celum** [OData/odata.net#407]
Hello, 
 
We’re using expanded navigation-properties to navigate from an entity called “Node” of the resource “Nodes” to “Subnodes” of the same entity type (like a folder structure). We use .net C# (Visual Studio Community 2015, with the OData Client Generator) as client to generate the necessary code for accessing our OData service. 
 
It seems .net requires an @odata.id for each expanded navigation-property entry, but we found in the spec that the @odata.id can be omitted in typical use cases. It has to be present in certain circumstances described here: http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940621.:
 
As we're using Olingo (https://olingo.apache.org/) which doesn't generate the @odata.id we're curious whether we missed something here? Is the behavior of the .net client correct? 
 
Thx for your help!
Best,
Rudolf Traunmüller
CELUM GMBH
rudolf.traunmueller@celum.com
 
Background: 
Our call to https://host/odata/Nodes(900)?$expand=children delivers expanded children without @odata.id for the children -> this fails with the .net client
 
```json
{
  "@odata.context": "https://host/odata/$metadata#Nodes/$entity",
  "id": 900,
"children": [
    {
      "id": 1400
    }
]
}
```
 
Our call using a patched version of Olingo to https:// host/odata/Nodes(900)?$expand=children delivers expanded children with @odata.id for the children -> this is now deserialized correctly within .net
 
```json
{
  "@odata.context": "https://host/odata/$metadata#Nodes/$entity",
  "id": 900,
"children": [
    {
      "@odata.id": "https://host/odata/$metadata#Nodes(id=1400)",
      "id": 1400,
    }
]
}
```

**Comment by chinadragon0515** [comment]
@rudolftraunmueller-celum 
I investigate the issue today, I have some questions,
1. Can you show me the sample code you use to retrieve the data? Do you have some special setting on this part?
2. What's the key name for node? is it ID?
3. What's version of client been used? And what's version of referenced core/edm package?
4. Can you show me the detail exception to me like call stack?

Also I write some testing code today, I did not find any issues, here are more details,
1. I use the client generator to generate the code.
2. I do the expand call like these,
            DefaultContainer context = new DefaultContainer(new Uri("http://localhost:19691/TripPinService/"));
            var peopleWithExpand = context.People.Expand(c => c.Trips);
            foreach (Person p in peopleWithExpand)
            {
                Console.WriteLine("People Name: {0}", p.UserName);

                foreach (Trip trip in p.Trips)
                {
                    Console.WriteLine("\tTrip ID: {0} -- Description: {1}", trip.TripId, trip.Description);
                }
            }
The trips does not have a OData ID, and I can get all the trip data.

Here is the sample output if I use a web browser to initiate a call to URL "http://localhost:19691/TripPinService/People?$expand=Trips", you can see it does not have a trip ID.

{
	@odata.context: "http://localhost:19691/TripPinService/$metadata#People/$entity",
	@odata.id: "http://localhost:19691/TripPinService/People('russellwhyte')",
	@odata.etag: "W/"08D31BDF941A609F"",
	@odata.editLink: "http://localhost:19691/TripPinService/People('russellwhyte')",
	UserName: "russellwhyte",
	FirstName: "Russell",
	LastName: "Whyte",
	Gender: "Male",
	Concurrency: 635882619465785500,
	Trips@odata.context: "http://localhost:19691/TripPinService/$metadata#People('russellwhyte')/Trips",
	Trips: [{
		TripId: 0,
		ShareId: "9d9b2fa0-efbf-490e-a5e3-bac8f7d47354",
		Description: "Trip from San Francisco to New York City. Nice trip with two friends. It is a 4 days' trip. We actually had a client meeting, but we also took one to go sightseeings in New York.",
		Name: "Trip in US",
		Budget: 3000,
		StartsAt: "2014-01-01T00:00:00+08:00",
		EndsAt: "2014-01-04T00:00:00+08:00",
		Tags: ["Trip in New York",
		"business",
		"sightseeing"]
	}]
}

**Comment by rudolftraunmueller-celum** [comment]
Hello chinadragon0515,

Thanks a lot for your comprehensive response. I investigated the issue a bit further and came to the conclusion that we got the context url wrong. After fixing the issue, we have no more problems with the .net client generator and expanded navigation properties. 

Thx for your help!
Best,
Rudolf Traunmüller
CELUM GMBH
rudolf.traunmueller@celum.com
