### ISSUE TITLE
The schema element 'ValueAnnotation' was not expected in the given context.

### ISSUE THREAD

**Issue by vmichalak** [OData/odata.net#414]
Hello,
When i attempt to add "https://public.opendatasoft.com/api/odata/" (collection : "liste-des-cafes-a-un-euro") i got this error :
>Adding OData Connected Service to the project failed: The schema element 'ValueAnnotation' was not expected in the given context.

Do you have any idea of why i got this and how correct it ?
Thanks a lot for your work !
Valentin

**Comment by LaylaLiu** [comment]
vmichalak, I cannot access the $metadata. Could you please provide us with $metadata file?

Another way to investigate the issue. You can try "OData Client Code Generator" extension. and follow http://blogs.msdn.com/b/odatateam/archive/2014/03/12/how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class.aspx to add a new odata client proxy.

Then, you can  debug the generating code, by following http://blogs.msdn.com/b/garethj/archive/2006/01/09/t4debugging.aspx
