### ISSUE TITLE
IEdmEntityContainer does not expose <EntityContainer>'s Extends attribute

### ISSUE THREAD

**Issue by fpintos** [OData/odata.net#42]
When parsing an EDMX we get back an IEdmEntityContainer for the entity container.
However, the interface does not expose the Extends attribute, even thou the underlying CsdlSemanticsEntityContainer has the property available.

Ideally, IEdmEntityContainer would expose the base container as another IEdmEntityContainer, not just a string.

**Comment by mikepizzo** [comment]
Note that Extends is different from inheritance; it's conceptually a shortcut for copying in the definition of the related entity container.  If the exposed entity container contains the entity sets (and functions and singletons) of the extended entity container, then the user model should be correct.

If this is not the case, please feel free to re-open and call out that the exposed entity container does not contain the members of the extended entity container.
