### ISSUE TITLE
The type or namespace name 'DataServiceQuerySingle' does not exist

### ISSUE THREAD

**Issue by VikingRedleg** [OData/odata.net#422]
I got the latest version of oData from Nuget yesterday because I was having trouble adding a second Odata source to a project of mine.  If both client codes are in the same level of the project, same starting namespace, there is a problem.  To fix this problem I recreated the second client in another folder/namespace.  Now the problem is this error:

The type or namespace name 'DataServiceQuerySingle' does not exist in the namespace 'Microsoft.OData.Client' (are you missing an assembly reference?)

Client is generated by means of OData Client item template also downloaded from NuGet.  T4 template builds all the code from an EDMX xml file I got from the OData service in question.  In my references the OData libraries are version 6.4, but Nuget says I have the latest - 6.14. To try to be sure I had the right version I completely uninstalled odata from my project and re-installed it from NuGet.

How can I get my new client to be built?  I'm not touching the original Odata client because that one still  works as far as I can tell.

**Comment by LaylaLiu** [comment]
I hope that i understand you question. You are generating a new client proxy into an existing client project which already have a reference of ODL 6.4. Then you got the "type or namespace doesn't exist" error, right?

If so, you really need to upgrade the reference to the latest version by right click the project->Manage Nuget Packages, Expand “Intalled Project”， Choose "OData Client for .NET", uninstall. And then check packages.config doesn't contains the 6.4 package and the project doesn't have the 6.4 reference.
Then right click the project, project->Manage Nuget Packages, Expand “Online”， Search“OData Client for .net”， choose "OData Client for .Net" which should be 6.14.0, click "Install". check the reference and packages.config.

If this doesn't solve your problem, please send me the detail repro steps which might help me to understand the issue. Thanks.

**Comment by VikingRedleg** [comment]
I uninstalled the odata package, closed the solution and restarted my computer.  When I got everything loaded back up, I attempted to reinstall the odata package from nuget and the instance in the project where my odata client is made is still showing version 6.4 even though the package installer said 6.14 was installed everywhere.

**Comment by VikingRedleg** [comment]
figured it out.  previous developer had attached the 6.4 dll files directly to the project, so when updating via NuGet these files were used instead of the packaged files.

**Comment by LaylaLiu** [comment]
Glad to know that it is solved, I will close this issue.
