### ISSUE TITLE
Breaking change about ODataUndeclaredPropertyBehaviorKinds

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#425]
This is a behavior change corresponding to those in OData v3 Lib 5.6.3 and 5.6.4, at least it breaks the documentation of ODataUndeclaredPropertyBehaviorKinds.

The commit is 
'suppress the error in reading open entity undeclared primitive, collection or complex property value.'
https://github.com/OData/odata.net/commit/f1f910e5df516b7b232a6e25465d0be58928722f

We shall add new enum member to ODataUndeclaredPropertyBehaviorKinds, and turn on the new behavior only for the new value.  So does [ODataJsonLightEntryAndFeedDeserializer#1422](https://github.com/OData/odata.net/commit/f1f910e5df516b7b232a6e25465d0be58928722f#diff-8c588ba8ab66b5173fc1e2a4874e023aL1423)

**Comment by LaylaLiu** [comment]
Related to https://github.com/OData/odata.net/issues/493

**Comment by markdstafford** [comment]
Repurposing this work item for 6.x branch. Description to be updated by @challenh .

**Comment by ElizabethOkerio** [comment]
Related to https://github.com/OData/odata.net/issues/493. Closing this as the other issue it is related to was closed and it has had a lot of inactivity and might have been resolved in the newer versions. Feel free to reopen it.
