### ISSUE TITLE
Can't "modify or replace" SendingRequest2EventArgs.RequestMessage

### ISSUE THREAD

**Issue by taspeotis** [OData/odata.net#426]
`SendingRequest2EventArgs.RequestMessage` has the following summary:

> [The web request reported through this event. The handler may modify or replace it.](https://github.com/OData/odata.net/blob/2b97acbbc33a33295285d410c3df695ae86a7b81/src/Microsoft.OData.Client/SendingRequest2EventArgs.cs#L28)

I assume that _handler_ here refers to my event handling code. Similar documentation appears in the summary for the `DataServiceContact.SendingRequest2` event.

However, the setter is private, so it's impossible to replace it.

```
/// <summary>
/// The web request reported through this event. The handler may modify or replace it.
/// </summary>
public IODataRequestMessage RequestMessage { get; private set; }
```

I'd like to replace the `IODataRequestMessage` with my own, such that my implementation can be backed by `NSUrlSession` and the like on iOS.

**Comment by taspeotis** [comment]
Also if I could put my own `IODataRequestMessage` in, I could control the `Timeout` which is something sorely missing from the PCL version.

**Comment by LaylaLiu** [comment]
To replace the request message with your own message, you actually should set DataServiceContext.Configurations.RequestPipeline.OnMessageCreating.
See http://odata.github.io/odata.net/#04-06-use-client-hooks-in-odata-client.

**Comment by taspeotis** [comment]
Thank you, I'll try it and close this if it works.

**Comment by taspeotis** [comment]
I got it working through `OnMessageCreating`. @LaylaLiu should I keep this issue open to get the documentation for `SendingRequest2` changed or just close it?

**Comment by LaylaLiu** [comment]
Just keep it open, once we fix the documentation issue, we will close it. Thanks.

**Comment by AlanWong-MS** [comment]
@LaylaLiu what is the latest status on this?

**Comment by LaylaLiu** [comment]
I checked the source file, the comments has been updated.
