### ISSUE TITLE
[OData Client] Contained entity Post 

### ISSUE THREAD

**Issue by snowppy** [OData/odata.net#429]
I have a data structure which combines a an Entity frameworks definition of an entity and Azure table storage. This is due to the fact that that each set entity has around 300 000 child entities represented as azure table rows.

In order to query the data I need the set id and rowid to be present in the url of the request. 

I have defined the rows to as contained entities and using T4 generated client I am able to reach the entire structure (Example of the nested path : https://localhost:44300/odata/LCMSDistressRawDataSets(2)/Distresses(1)/Location/PositionDescriptions(1)/Points(1))

My question is how to use the generated client container to express the CRUD operations needed for the contained entities

When I try to add a new distress though the client its being redirected to (https://localhost:4430/Distresses and not to https://localhost:44300/odata/LCMSDistressRawDataSets(2)/Distresses )

If i try to go though the row LCMSDistressRawDataSet object on add the new distress object to the list there and use container save changes no requests are actually fired to the server.

Can someone provide me with example of Post operation on a contained entity using the T4 generated client container.

**Comment by LaylaLiu** [comment]
@snowppy 
For contained.

POST: OData client has DataServiceContext.AddRelatedObject to add a contained entity to a collection. or UpdateRelatedObject to set a contained entity of a single entity navigation.

For query, please use expand.
For update, DataServiceContext.UpdateObject.
For delete, DataServieContext.DeleteObject.

**Comment by weitzhandler** [comment]
@LaylaLiu 
Is there a way to add/post/patch/delete an entire graph of objects without having to manually set each of the related entities individually?
