### ISSUE TITLE
Support hex values in enum member values when parsing an EDM file.

### ISSUE THREAD

**Issue by fpintos** [OData/odata.net#43]
Hello,

It looks like ODATAv4 does not support specifying values of enum members as hex values.
For flag-enums, being able to specify them using hex is usually more intuitive,

For example:

``` xml
<Member Name="All" Value="0xFFFFFFFF" />
```

Instead of:

``` xml
<Member Name="All" Value="4294967295" /> 
```

Reading [odata-abnf-construction-rules.txt](http://docs.oasis-open.org/odata/odata/v4.0/os/abnf/odata-abnf-construction-rules.txt) I see these rules, indicating that hex values are not permitted:

```
enumMemberValue = int64Value
int64Value = [ sign ] 1*19DIGIT ; numbers in the range from -9223372036854775808 to 9223372036854775807
```

Looking further at the implementation of the [`EdmValueParser.TryParseLong`](https://github.com/OData/odata.net/blob/master/src/Edm/Microsoft/OData/Edm/Csdl/EdmValueParser.cs), we land in `XmlConvert.ToInt64` which, consistent with the rule above, does not parse hex values.

Any plans to support hex values in the future?

**Comment by mikepizzo** [comment]
No plans currently to support hex values, although I agree it is more intuitive for flags enums.  This would be a breaking change for clients, though, so since it's not currently part of the standard we would have to add it to a future (breaking change) version.
