### ISSUE TITLE
Support Portable Profile111

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#435]
portable-net45+win+wpa81

**Comment by lewischeng-ms** [comment]
Test plan:
 - Server side (with OData Web API): WA targets *Desktop Net45*. Now its reference to ODL will be changed to the new profile *Portable Net45*. Ensure all unit tests and E2E tests in WA can pass with the new profile.
 - Client side (with OData client): Currently five possible targets of OData client are: 
  - *Desktop Net45*: Will update its reference to the new profile. **Need test**. Can be covered by *Desktop E2E tests*.
  - *Portable Net45 with WP8.1* (aka., Profile259): Will **NOT** update its reference. **No test needed**.
  - *Portable Net45 without WP8.1* (aka., Profile111): Will update its reference to the new profile. **Need test**. . Can be covered by *Portable E2E tests*.
  - *WP Application 8.1* (aka., WPA81): Will update its reference to the new profile. **Need test**. Can be covered by *WP E2E tests*.
  - *Windows Store Application*: Will update its reference to the new profile. **Need test**. Can be covered by *Windows Store E2E tests*.

**Comment by lewischeng-ms** [comment]
Test status of the PR #472:
 - Server side (with OData Web API): Need fix in `PlatformHelper.GetTypeCode()` for enum types. After this fix, **all pass**.
 - Client side (with OData client):
  - *Desktop Net45*: *Desktop E2E tests*: **all pass**.
  - *Portable Net45 with WP8.1* (aka., Profile259): **no test needed**.
  - *Portable Net45 without WP8.1* (aka., Profile111): **all pass**.
  - *WP Application 8.1* (aka., WPA81): **in progress**.
  - *Windows Store Application*: **all pass**.

**Comment by lewischeng-ms** [comment]
@brjohnstmsft Please have a try with our latest ODL nightly packages. Any feedback is welcomed. Thanks for your contribution.

**Comment by lewischeng-ms** [comment]
@xuzhg Please test the latest ODL nightly packages with OData Web API to see if there is any problem. Thanks.

**Comment by lewischeng-ms** [comment]
@brjohnstmsft Feel free to reopen the issue if you have any question.
