### ISSUE TITLE
$Count with filter doesn't work in ODATA queries

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#440]
See related issue:  https://github.com/OData/WebApi/issues/194

Section 11.2.5.1 System Query Option $filter

http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398301 

For this Uri:

http://host/service/Categories?$filter=Products/$count lt 10

The error message is:

{
  "error":{
    "code":"","message":"The query specified in the URI is not valid. The parent value for a property access of a property '$count' is not a single value. Property access can only be applied to a single value."
  }
}

**Comment by chinadragon0515** [comment]
OData lib parser and WCF sample case is ready.
Working on OData lib client support now.

**Comment by mfittko** [comment]
great news! :) will this also include the orderby $count queries?

**Comment by chinadragon0515** [comment]
Yes, both orderby and filter can work with collection/$count now in odata .net lib.

**Comment by mfittko** [comment]
That's great news! :) [off topic] Do you know if it is also possible to return the numbers (e.g. via $select)?

**Comment by chinadragon0515** [comment]
We support both $count in URL ( like ~People/$count) with will only return the number of entity request and $count=true query option (like People?$count=true) which will return the number besides entities as defined in specification.

If you are looking for something like ~People?$orderby=Emails/$count&$select=Emails/$count, this is not supported, but you can define a function to email the $count and return the email count, and use select to retrieve the number.

**Comment by chinadragon0515** [comment]
Client code is in. Close the issue.

**Comment by Bijayakumar1990** [comment]
I am not getting the count of entities when using $count=true, in asp.net core odata integration in abp

**Comment by JohnGalt1717** [comment]
Yes, aspnet core does not return the $count result and won't alter the format of inline $count without using the /odata/ pathing.

You should be able to specify $count=true in the url and application/json and it should change the format of what is returned to include the count. (if you use any odata properties it should change the response accordingly.
