### ISSUE TITLE
Do not include string readonly properties in the add/update payload.

### ISSUE THREAD

**Issue by sergiomoreno** [OData/odata.net#445]
When OData Client sends an Update, it does not include readonly ValueType properties. However, it does include readonly ReferenceType properties. Since the string type is a ReferenceType, it is included.

I have created a partial class for a class generated by the T4 template. This partial class has some readonly int and string properties. Int properties aren't included in the payload but string ones are. String properties included in the payload make server crashes.

So I suggest considering string readonly properties as ValueType properties. I propose change the GetPropertiesOnType method:

                    if (propertyInfo.CanRead &&
                        (!(propertyType.IsValueType() || typeof(string) == propertyType) || propertyInfo.CanWrite) &&
                        !propertyType.ContainsGenericParameters() &&
                        (0 == propertyInfo.GetIndexParameters().Length))
                    {
                        yield return propertyInfo;
                    }

Thanks
Sergio

**Comment by LaylaLiu** [comment]
@sergiomoreno， Thanks for your detailed information.

To workaround this issue before we fix it, you can try to use DataServiceContext.Configurations.RequestPipeline.OnEntryStarting to add or remove the properties that you want to be included in or excluded from the payload.

See: http://odata.github.io/odata.net/#04-06-use-client-hooks-in-odata-client

**Comment by sergiomoreno** [comment]
Very usefull information.
Thank you!

**Comment by chinadragon0515** [comment]
@sergiomoreno I try to recreate the issue, I did not get the issues recreated, I have some questions for you,
1. For the partial class, it is only defined on the client side, but not in the server side, right?
2. On the server side, is the entity type an open type which means support dynamic properties?
3. When you said you define some readonly property, can I know how you defined them? defining with keyword readonly for the property and value can only be set via constructor,  or defining with non-public set method (like internal/private/protected)? 
4. What's the access for the property? public/internal/private/protected?
5. What you mean server crashes? Do you have crash detail?

Also I did some test on this part,
1. If I use readonly to define property, then non of these property (both int type and string type) will be serialized in payload and send to server side, this is because "PlatformHelper.GetPublicProperties()" will not have readonly properties returned.

2. I make the property readonly via private set, I find all these properties will be written into payload and receive on the server side. Server side will deserialize it correctly when the entity type is open type. Or throw exception as expected if entity type is not a open type.

**Comment by sergiomoreno** [comment]
Hi,
1. Yes, it is. Only on the client side.
2. No, I don't know how to make it an open type. In the last version of the odata server, adding a property called DynamicProperties (IDictionary<string, object>) makes it crashes so I had to remove it.
3. I've defined it with readonly keyword. No set is defined. It is a calculated property which depends on another one. I need it for showing in a datagrid.
4.It's a public property.
5.The server side crashes in the Patch method. The patch parameter is null and it makes my code crashes. If I remove the readonly properties of de client side, the patch method is never called with null parameters.
6. The version is 6.14.0 for ODataClient and 5.8.0 for AspNetOData

**Comment by chinadragon0515** [comment]
thanks for your request, I still can not recreate the issue, here is code I used, 
1. On the server side, here is how I define the patch method in contrller,
public IHttpActionResult Patch([FromODataUri] int key, Delta<Product> patch)

2. On the client side, I tried both entity tracking and properties tracking, can not create the issue
            var updatedProduct = context.Products.ByKey( 6).GetValue(); // get an entity
            updatedProduct.Name = "Ross"; // change its property
            context.UpdateObject(updatedProduct); // create an update request
            context.SaveChanges(); // send the request
Refer to link http://odata.github.io/odata.net/#04-01-basic-crud-operations , update an entity part.

I also tried properties level tracking,
            DataServiceCollection<Product> products = new DataServiceCollection<Product>(context.Products.Where(p => p.Id == 5));
            // Update primitive type under entity
            products[0].Name = "Tested";
            context.SaveChanges();
You can refer to link http://odata.github.io/odata.net/#04-09-client-tracking property tracking part.

3. Note here what I have done for patch is not a readonly property as readonly property will not be passed to server side.

So I have some more questions,
1. #2 of your answer, can I know the metadata of your entity type? result is from service_root_url/$metadata.

2. #5 of your answer, The patch parameter is null, do you mean Delta<T> parameter is null?

3. Can I know how your write the client code? what's tracking level you used? entity level or property level?

4. Can I know the patch method definition in controller?

5. What are the properties you plan to update? the readonly property defined in the partial class or other properties which is also defined in server side clr class?

**Comment by sergiomoreno** [comment]
Hi,

I think I've found it. It happens when I set an object as Modified but I haven't modify anything. It generates a PATCH request with a null delta parameter. It Works in previous versions of OData but not in the latest one.

                    var item1 = this.ContextBD.RequestTasks.First();
                    this.ContextBD.UpdateObject(item1);
                    this.ContextBD.SaveChanges();

It only fails when the entity (RequestTask) has readonly properties declared.

Thanks
Sergio

**Comment by chinadragon0515** [comment]
What's previous version of OData you use? And any changes of other package version?

I tried to figure out how version make difference and how readonly make difference.

For the previous version of odata, do you have readonly property? Does patch request pass Delta<T> to server Patch method?

For the this.ContextBD.SaveChanges, this is the code logic in OData controller or some classes used by controller, and client side do pass data to server side (I mean the parameter of patch method in controller has value and it is not null), am I correct?

As  "It only fails when the entity (RequestTask) has readonly properties declared on the client side.",  
1. Are the readonly properties changed when you initiate a request?
2. Are the properties defined in the server side too not changed?
3. Do you debug to see what was passed to server side when no readonly used?

**Comment by sergiomoreno** [comment]
It's possible that the error would be in the server side.

When I do declare the readonly properties they are included in the patch payload. The rest of the properties are included too. In the server side, the delta parameter is null.

If I don't declare the readonly properties the patch payload contains all the properties. The payload seems to be the same with the exception of the readonly properties which logically aren't included. In the server side the delta parameter is not null and include all of the entity properties.

In previous versions of odata server, I had a DynamicProperties dictionary so the entity was an open type and everything works well. In the latest version of odata server, I can’t declare a dictionary of DynamicProperties because it generates an exception, so in the latest version, my entity isn’t an open type. May be it is the problem.

**Comment by chinadragon0515** [comment]
1. For the previous version of odata, do you have readonly property? 
2. What's the exception you get when you have DynamicProperties?

From your descriptions, seems server side looks for some properties you plan to define as readonly which is not in payload and return null, if this is the case, fix server side issue.

Let's know if you have any more issues related to readonly, if no issues related to readonly, then we can close the issue. For any other issue, help to open new issue to track, thanks.

**Comment by sergiomoreno** [comment]
It's seems that the reason is there aren't dynamic properties declared on the server side. Let's close the issue.

Thank you.
