### ISSUE TITLE
[Core] ODataMissingOperationGenerator.ComputeMissingOperationsToEntry() incorrectly looks up operations from the entire model instead of "to the entry".

### ISSUE THREAD

**Issue by zlatko-michailov** [OData/odata.net#453]
I have picked _actions_ to keep this description simple. The same behavior reproes for _functions_ as well.

### Context

Assembly: __Core__.

Examine the following call stack:
```
7: EdmLibraryExtensions.ValidateOperationGroupReturnsOnlyOneKind()
6: EdmLibraryExtensions.ResolveOperations()
5: ODataMissingOperationGenerator.GetOperationsToEntry()
4: ODataMissingOperationGenerator.ComputeMissingOperationsToEntry()
3: ODataMissingOperationGenerator.GetComputedActions()
2: ODataConventionalMetadataBuilder.GetActions()
1: ODataEntry.Actions
```

### Problem
In a large model like Microsoft Graph where different teams contribute to the same model, it is possible that one team has defined function "foo" bound to type "A" while another team has defined action "foo" bound to type "B".

The code above throws when an entry of either type "A" or type "B" is written with full metadata (which requires writing of operations.)

### Suggested Fix
The call from frame `5` to frame `6` loses the information about the entry that's being processed.

There should be an overload of frame `6: EdmLibraryExtensions.ResolveOperations()` that takes the ODataEntry and leaves only the operations bound to the entry's type on the collection before it sends it to frame `7` for validation.

BTW, the only caller of frame 6 seems to be frame 5 and some unit test. It should be possible to fix the existing overload without breaking any existing code.

**Comment by LaylaLiu** [comment]
@zlatko-michailov 

I have one thing to confirm. 

According to current implementation, this exception (A string like "When resolving operations '{0}' the group returned has both actions and functions with an invalid IEdmModel.") should be thrown only when an action and a function are same named, and they are binding to two different entity types. 

If two bound functions have the same function name, no such issue happens, right?

**Comment by zlatko-michailov** [comment]
@LaylaLiu 
Correct - the exception is only thrown when the operations are of different kinds.

**Comment by LaylaLiu** [comment]
@zlatko-michailov,

if two operations are of different kinds, they shouldn't have same name, please see [CSDL 5.1 Element edm:Schema](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397947)

5.1 Element edm:Schema
The edm:Schema element contains one or more of the following elements:
•	edm:Action
•	…
•	edm:Function
•	…
Values of the Name attribute MUST be unique across all direct child elements of a schema, with the sole exception of overloads for an action and overloads for a function. The names are local to the schema; they need not be unique within a document.
