### ISSUE TITLE
Improve the README.md

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#462]
Under the build/testing section, it might be helpful if you:

1.	Mention to ***not*** unzip/git the code into a path with spaces in it – it breaks the build whether using build.cmd or VS2015.
2.	Mention to right click on build.ps1 and choose “Unblock” – otherwise powershell will error out with a less than intuitive error that Google doesn’t provide much help with.

**Comment by chinadragon0515** [comment]
Readme update a341364c3fe9d1a58078f1e538db0786a2086ee4 is committed, close the issue.
