### ISSUE TITLE
Why there is no DateTime support in client library?

### ISSUE THREAD

**Issue by VitaliyKurokhtin** [OData/odata.net#473]
Seems a bit weird, at least for datetimes with Kind=Utc.

**Comment by LaylaLiu** [comment]
@VitaliyKurokhtin,

You are talking about OData V4, right? OData V4 doesn't support DateTime. Please use DateTimeOffset instead.

One reference: ["Converting Between DateTime and DateTimeOffset"](Converting Between DateTime and DateTimeOffset)

**Comment by VitaliyKurokhtin** [comment]
That is true indeed. But from source code I see that it's supported for Astoria at least, so I'm wondering why can't we accept DateTime in query and models and treat it just as DateTimeOffset?

**Comment by VitaliyKurokhtin** [comment]
It was moved from milestore 6.16 to backlog, is this a good thing or a bad? In terms is this any closer to being fixed?

**Comment by rjjkathy** [comment]
Our team has encountered the same blocking issue when trying to upgrade from OData v3 to v4. Our existing base object already uses DateTime in production, therefore it would be a breaking change during the upgrade if there is no DateTime support. It would be great to find a workaround on the client side without changing the odata V4 protocol.

**Comment by chuanboz** [comment]
from https://github.com/OData/WebApi/issues/136 and also http://odata.github.io/WebApi/datetime-support, seems DateTime is officially supported by the OData server side while still maintain the compatibility with the OData v4 protocol, why we could not do the same for client side?

In other words, for the EDM model and over the wire, still use DateTimeOffset to be compatible with OData v4 protocol, while internally convert the DateTimeOffset from/to DateTime, to allow the actual C# object used in client side still be DateTime.

**Comment by AlanWong-MS** [comment]
Closing this issue as it seems to be resolved by @jingjingrong's commit. Please re-open if not the case.

**Comment by wmalgadey** [comment]
I have to reopen the issue again.

Did the PR ever got merged to the main repository? I can't find this functionality in current 7.4.4 release!

**Comment by AlanWong-MS** [comment]
@wmalgadey, thanks for pointing this out. Looks like we need to port the fix to the master branch as well. I've opened #1151 to address this and will take a look.
