### ISSUE TITLE
Adding the version to the user-agent string

### ISSUE THREAD

**Issue by yiil** [OData/odata.net#479]
We have an issue where we have clients who are generating proxies and using older versions of OData to call our service in unsupported ways (such as calling us using version 5.6.1 after we make a multi-valued property addition to an entity). 

We want to verify that the OData version that they are using is greater than a specific version such that we can guarantee on the server side that they are using a version that supports any changes we make (i.e. using a version greater than 5.6.4 for a version of our service that we plan on adding multi-valued property additions).

The ask is to have the client set a request header (or appent to the user-agent) that includes the version of OData so we can enforce this on the server side (and possibly reject calls that do not have this header such that they will not be broken in the future when we add these changes). This is different from asking for the functionality to modify the request header in the sense that the ask is to have the client automatically send the version, without any additional operations from the caller.

**Comment by TomDu** [comment]
ODL version number is now appended to User-Agent in request header in ODL client.

Example for ODL V6.16.0: `User-Agent: Microsoft.OData.Client/6.16.0`
