### ISSUE TITLE
Edm.Single ATOM Not Compliant

### ISSUE THREAD

**Issue by gakt** [OData/odata.net#482]
The OData 5.7.0 assemblies are supposed to support V1-3 of the OData Spec for ATOM; according to the Microsoft Protocols spec it is in compliance. The spec states that the Edm.Single type “Represents a floating point number with 7 digits precision…” However we regularly see where the .NET Single type is not being truncated or rounded to comply with the spec.

For Example, consider we have a value of -7.18264771 stored in a SQL data base. When it is converted to the .NET Single type it will be sent in the ATOM document with all eight digits. When in fact it should be rounded (-7.182648) to meet the v3 and earlier spec. This causes an issue with clients that are written in strict adherence of the OData v1-3 spec. Same issue is seen when document type is set to JSON.

OData v3 Spec (http://www.odata.org/documentation/odata-version-3-0/atom-format/)
Microsoft CSDL For v1-3( https://msdn.microsoft.com/en-us/library/dd541474.aspx)

**Comment by LaylaLiu** [comment]
@gakt Thanks for reporting this issue. 

Yes, it is not consistent with the spec. But could you let me know what the impact is on your product if a single value has 8 digits. If you could provide a specific scenario, It would be more helpful for us to understand the requirement.

**Comment by gakt** [comment]
The client parser errors out on the out of spec value.
