### ISSUE TITLE
Typo: "vocabularis" directory and namespace in edm lib

### ISSUE THREAD

**Issue by MrTomWhite** [OData/odata.net#49]
Just as the title suggests. It looks like there's a tiny typo. It only looks like it affects a few source files; it should be simple enough to fix with a quick mechanical refactoring

**Comment by bixu-ms** [comment]
Yes, we have noticed that.
However, it will be a break change to rename the namespace. So we create another namespace Microsoft.OData.Edm.Vocabularies.V1 and copy the classes there. People should use the new namespace. But we can't delete the old classes, to not to break the user code who have already used that old namespace.
