### ISSUE TITLE
Tests appear to be missing from odata.net? 

### ISSUE THREAD

**Issue by MrTomWhite** [OData/odata.net#50]
### Description
Tests, such as unit tests, are an important part of the development process. It's hard to imagine how a contributor could safely contribute to this project without automated tests to run for validation. 

### Minimal repro steps
1. `git clone https://github.com/OData/odata.net.git`
2. Browse cloned code and look for tests to read
3. Attempt to run tests in visual studio

### Expected result
Open source code bases should include both product code and relevant test code. 

### Actual result
odata.net does not contain any test code.

**Comment by bixu-ms** [comment]
Thanks for the watching and suggestion. Yes, we know, it is not easy to write code without any tests. 

We are currently working on publishing the test codes within the project, include all the e2e, functional and unit tests.
You should see that happen soon. There just be some internal process/issues we have to handle before publish it.

Welcome to contribute any code (and suggestion) you think is useful to OData! We surely will continue to make this contribution work more and more easy.
