### ISSUE TITLE
Consider maintaining a minimal set of NuGet profiles

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#500]
Now we have: Profile328 (4.0), Profile 259 (4.5), Profile 111 (4.5), DnxCore50 (Profile 259), .NET 3.5.

Profile 111 should be enough I think.

**Comment by nicenemo** [comment]
111 Enough? I plan to use it from UWP on Windows Mobile 10.

**Comment by lewischeng-ms** [comment]
@nicenemo Profile 111 can work well with UWP projects for Win10
