### ISSUE TITLE
Integrate dependency injection into ODataLib

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#501]
Probably we can just start from serialization and deserialization part.

**Comment by lewischeng-ms** [comment]
Committed in https://github.com/OData/odata.net/blob/gh-pages/v7/_posts/core%20libraries/2016-08-18-01-04-di-support.md

**Comment by chuanboz** [comment]
The above link is broken, and I couldn't find the latest link in this repo.
