### ISSUE TITLE
Add SpatialFactory helper class

### ISSUE THREAD

**Issue by Zoe-ms** [OData/odata.net#509]
_Add SpatialFactory helper class to help customer creating spatial types_  
### Assemblies affected

_OData .Net lib 7.0_  
### Reproduce steps

_None_  
### Expected result

_None_  
### Actual result

_None_  
### Additional details

_None_

**Comment by xuzhg** [comment]
Related #1073
Related PR #1309

**Comment by xuzhg** [comment]
It's fixed. Close it.
