### ISSUE TITLE
Capabilities Vocabulary loaded in all EDM Models looks out of date / incomplete

### ISSUE THREAD

**Issue by MrTomWhite** [OData/odata.net#51]
### Description

There is a version of the OData.OData.Capabilities.V1 vocabulary hosted on Oasis which seems mostly complete: https://tools.oasis-open.org/version-control/browse/wsvn/odata/trunk/spec/vocabularies/Org.OData.Capabilities.V1.xml

The version used internally seems to be much smaller and incomplete.  
https://github.com/OData/odata.net/blob/master/src/Edm/Microsoft/OData/Edm/Vocabularies/CapabilitiesVocabularies.xml#L7 

Is there a standard capabilities vocabulary hosted somewhere? Which version should be loaded by EDM implicitly? In the status quo, the latter vocabulary is loaded, but this doesn't seem correct. 
### Minimal repro steps
1. Instantiate a EDMModel
2. Attempt to add InsertRestriction annotation to the model  
### Expected result

InsertRestriction can be added without loading additional vocabularies since capabilities are already implicitly referenced in all EDMModels
### Actual result

Must explicitly load a copy of the capabilities vocabulary that is more complete. Preferably one similar in completeness to https://tools.oasis-open.org/version-control/browse/wsvn/odata/trunk/spec/vocabularies/Org.OData.Capabilities.V1.xml

**Comment by dingeins** [comment]
Capabilities vocabulary isn't completely supported because not all the elements and attributes for defining annotations is supported in the EdmLib.

**Comment by mikepizzo** [comment]
It appears from the conversation thread that this has been addressed. If not, please feel free to re-open and add any missing capabilities.
