### ISSUE TITLE
Add support for json metadata

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#512]
The first draft of a JSON Format for $metadata is announced at: [Here](https://lists.oasis-open.org/archives/odata-comment/201601/msg00000.html)

Update: the latest version can be found at http://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html

**Comment by offbeatful** [comment]
+1

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/WebApi/pull/2361 => /$metadata?$format=application/json
