### ISSUE TITLE
$select with complexCol/prop should be supported

### ISSUE THREAD

**Issue by chinadragon0515** [OData/odata.net#513]
Per specification, $select with complexCol/prop should be supported
### Assemblies affected

OData .Net lib 6.15
### Reproduce steps

Use URLParser to parse a URL with $select=ComplexCol/prop
### Expected result

parsing succeed
### Actual result

exception thrown

**Comment by brjohnstmsft** [comment]
This fix is necessary to get $select working with properties under complex collection properties through Web API too. See related issues: https://github.com/OData/WebApi/issues/989 https://github.com/OData/WebApi/issues/196

**Comment by brjohnstmsft** [comment]
I've determined through testing that this issue was fixed by this commit from July 2016: https://github.com/OData/odata.net/commit/7f8c2f30c02fdfb8773a6319fe24cbbd6277dc39

I'll be sending a PR soon with test coverage to prevent regressions of this scenario.
