### ISSUE TITLE
Centralize validation in reader and writer

### ISSUE THREAD

**Issue by Zoe-ms** [OData/odata.net#517]
We have kinds of validations, like duplicationnamechecker, collectionvalidator, WriterValidationUtils, ReaderValidationUtils, ValidationUtils which are all used through the process of Reader and Writer. Better centralize all validations, so they can be easily turn on and off, also for easier maintenance.

**Comment by luoyan0517** [comment]
This commits https://github.com/OData/odata.net/commit/32860ca156a665d93709b2504643f6747b34d1ba done partially
