### ISSUE TITLE
Support of retrieving annotations on parameters and return types of function & actions

### ISSUE THREAD

**Issue by dingeins** [OData/odata.net#52]
One scenario of it would be that the client can know if to pass an entity or an entity ref for a parameter

**Comment by congysu** [comment]
@dingeins Can we ask a contribution for this task?

**Comment by dingeins** [comment]
I think we can firstly figure out which annotations are appropriate for the scenario described above.

**Comment by xuzhg** [comment]
Reopen it that we should support return type annotation on Edm operation.
