### ISSUE TITLE
OData client always serialize Int64 and Decimal parameters in IEEE754-compatible format.

### ISSUE THREAD

**Issue by dingpl716** [OData/odata.net#522]
_Short summary (3-5 sentences) describing the issue._  
OData client always serialize Int64 and Decimal parameters into string surrounded by double quotes.
Example URL:
https://serverroot/Products(22)/GetSlotComponents(channelId=56,slotId=87,selectedComponents=@selectedComponents)?@selectedComponents=[{"@odata.type":"#ComponentInSlotRelation","ComponentId@odata.type":"#Int64","ComponentId":"22565429523”,”Amount@odata.type":"#Decimal","Amount":"687.19"}]
The value of ComponentId and Amount are surrounded by double quotes which makes the server throw exceptions.  
### Assemblies affected

_Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta._  
### Reproduce steps

_The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue._  
1. Create a Function with complex type parameter.
2. Send the request by using following way
Task.Factory.FromAsync<Uri, IEnumerable<T>>(
    (uri, callback, state) => this.BeginExecute<T>(uri, callback, state, httpMethod, false, parameters),
     this.EndExecute<T>,
     requestUri,
     null);
### Expected result

_What would happen if there wasn't a bug._  
The value of ComponentId and Amount are not surrounded by double quotes. It should look like:
"#ComponentInSlotRelation","ComponentId@odata.type":"#Int64","ComponentId":22565429523,”Amount@odata.type":"#Decimal","Amount":687.19
### Actual result

_What is actually happening._  
### Additional details

_Optional, details of the root cause if known. Delete this section if you have no additional details to add._

**Comment by LaylaLiu** [comment]
#725

**Comment by paulodero** [comment]
@dingpl716 to avoid serializing Int64 and Decimal parameters in `IEEE754-compatible` format you will need to pass in `IEEE754-compatible=false` as part of the `Content-Type` header in your request.
