### ISSUE TITLE
Support .Any() clientside

### ISSUE THREAD

**Issue by nicenemo** [OData/odata.net#523]
Do support .Any() clientside. at least the non argument version.

### Assemblies affected
. OData .Net client  lib 6.15-beta.

### Reproduce steps

Generate a client against an odata service.
 Do something like:

` 
    private static Container CreateContext()
    {
      var ctx = new Container(Service.Default.host);
      ctx.SendingRequest2 += (sender, eventArgs) =>
         {
           //metadata=full is required for selecting properties
           eventArgs.RequestMessage.SetHeader("Accept", "application/json");
           eventArgs.RequestMessage.SetHeader("Prefer", "odata.include-annotations=\"*\"");
           eventArgs.RequestMessage.SetHeader("X-Innovalor-Authorization",Service.Default.authenticationkey.ToString());
         };

      return ctx;
    }

    [TestMethod]
    public void AnyDocumentSessions()
    {
      Assert.IsTrue((from doc in CreateContext().Documents
                     select new  { Sessionid=doc.SessionId}).Any());
    }`  

### Expected result
*What would happen if there wasn't a bug.*  
The result of the test would be true.

### Actual result
NotSupportedExeption is thrown

### Additional details
Implemented as NotSupportedException.

**Comment by LaylaLiu** [comment]
@nicenemo 

About this issue, you could execute the query first, and then use the Any() on the returned docs.

Assert.IsTrue((from doc in CreateContext().Documents
                 select new  { Sessionid=doc.SessionId}).AsEnumerable().Any());

**Comment by nicenemo** [comment]
Hi,

True I could do that and it would functionally work. However, that would
pull the data over the line first and use Any() from LINQ to objects. It
would not use the Any implemented on the server. I Checked with fiddler.

We use an Olingo based server. OLingo has a working any function on the
server.

Kind regards,
Hans


Op do 7 apr. 2016 om 06:05 schreef LaylaLiu <notifications@github.com>:

**Comment by LaylaLiu** [comment]
@nicenemo

Two questions:

1. What's the Uri of the request sent to Olingo based server? I suppose it is ended with /Any() segment.

2. I didn't get the meaning of "select new { Sessionid=doc.SessionId}" in this query. Once the context.Documents has one element, no matter whether you use the select clause. it will always return true, else false. right? Please let me know if I am wrong.

ODataLib doesn't have such built-in segments. So to implement the same function, I have two proposals 

1. The server side can implement a bound function
    Example:

        var anyFunction = new EdmFunction(ns, "Any", EdmCoreModel.Instance.GetBoolean(false), true, null, false);
        anyFunction.AddParameter("Documents", documentCollectionTypeReference);
        model.AddElement(anyFunction);

    Any:

        public bool Any(IEnumerable<Document> docs)
        {
            return docs.Any();
        }

    Then on client side, it could call like 

        Assert.IsTrue((from doc in CreateContext().Documents.Any().GetValue);

2. Another simple way is to use $count which can have the same

        Assert.IsTrue((from doc in CreateContext().Documents.Count);

**Comment by nicenemo** [comment]
Hi,

Good question 1!. Not possible with Olingo too. I cannot do a count on a
collection directly. Thank you.
Question 2: I am creating a "unit test" to test our service and provide our
customers with sample code when they wish to use .NET. The service is made
by another Employee using Apache OLingo as OData service framework.
Ofcourse our new service, my tests, Olingo en OData .NET contain bugs or
the specification is interpreted differently. We prefer to find them before
our customers.

Kind Regards,
Hans



Op vr 8 apr. 2016 om 04:59 schreef LaylaLiu <notifications@github.com>:

**Comment by nicenemo** [comment]
Can be closed.
