### ISSUE TITLE
Support for AnnotationPath

### ISSUE THREAD

**Issue by i040628** [OData/odata.net#525]
### Assemblies affected

Microsoft.OData.Core 6.15.0 library does not support parsing metadata containing AnnotationPath
### Reproduce steps

Try to parse a metadata xml containing AnnotationPath with Microsoft.OData.Core.ODataMessageReader - ReadMetadataDocument method
### Expected result

Parsing is successfull
### Actual result

Method throws an exception with message: UnexpectedXmlAttribute : The attribute 'AnnotationPath' was not expected in the given context.

**Comment by manivannanse** [comment]
Leave a comment
