### ISSUE TITLE
Support for IncludeInServiceDocument

### ISSUE THREAD

**Issue by i040628** [OData/odata.net#526]
### Assemblies affected

Microsoft.OData.Core 6.15.0 library does not support parsing metadata containing IncludeInServiceDocument attribute for EntitySet
### Reproduce steps

Try to parse a metadata xml containing EntitySet with IncludeInServiceDocument attribute with Microsoft.OData.Core.ODataMessageReader - ReadMetadataDocument method  
### Expected result

Parsing is successfull
### Actual result

Method throws an exception with message: UnexpectedXmlAttribute : The attribute 'IncludeInServiceDocument' was not expected in the given context.

**Comment by xuzhg** [comment]
It looks It was fixed. Thanks.
