### ISSUE TITLE
SelectMany is not supported

### ISSUE THREAD

**Issue by nicenemo** [OData/odata.net#528]
Trying to do a 2 or 3 level from x in xs query which should result in something SelectMany is throws an Exception in the Library code that SelectMany is not supported.

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  

### Reproduce steps

Try something like this

    [TestMethod]
    public void DocumentsSelectMany()
    {
      var ctx = CreateContext();
      var res = (from DocumentContent doc in ctx.Documents
                 from FaceImage faceImage in doc.IdentityDocument.FaceImages
                 from int dg in doc.IdentityDocument.Datagroups 
                 where doc.SessionId!=null  && faceImage.MimeType!=null where dg>0 select  doc.IdentityDocument.Datagroups).ToArray();
    }

### Expected result
Supported or a more sensible message on why it is not supported,

### Actual result
NotSupportedException is thrown with message "The method Select is not supported"

No actual call is made to the server. Tested with fiddler.

**Comment by LaylaLiu** [comment]
@nicenemo Thanks for reporting this issue.

One thing to clarify is OData Uri doesn't support returning a collection of collection.
OData client has some difficult to translate this into an OData Uri. A workaround is to use the linq methods as following:

    ctx.Documents
        .Where(doc=> doc.SessionId!=null &&  doc.IdentityDocument.FaceImages.Any(faceImage => faceImage.MimeType != null) && doc.IdentityDocument.Datagroups.Any(dg=>dg > 0))
        .select(doc=>new {doc.IdentityDocument.Datagroups})
        .ToArray();

Please let me know whether it can solve your issue.

**Comment by nicenemo** [comment]
Works for me, integrated in tests.
