### ISSUE TITLE
OData nextLink Issue

### ISSUE THREAD

**Issue by Venkateshjsoft** [OData/odata.net#531]
I am planing to use oData pagination in my webapi (server side), I have found that oData provide an option to return nextLink which internally handle the pagination. If my calling application want to access nth page, I am not sure how oData can handle it? Please advice

Reference
[Queryable(PageSize=10)]
public IQueryable<Product> Get() 
{
    return products.AsQueryable();
}

  "odata.metadata":"http://localhost/$metadata#Products",
  "value":[
    { "ID":1,"Name":"Hat","Price":"15","Category":"Apparel" },
    { "ID":2,"Name":"Socks","Price":"5","Category":"Apparel" },
    // Others not shown
  ],
  "odata.nextLink":"http://localhost/Products?$skip=10"
}

**Comment by nicenemo** [comment]
What happens with your next links if another user adds or deletes records?
What should happen?

**Comment by markdstafford** [comment]
Hi @Venkateshjsoft, StackOverflow is our usual venue for these sorts of questions, but to answer your question briefly, there's a difference between server-side paging and client-side paging. To get more details on these things, check out odata.org and look into the documentation there. Specifically, look for $top and $skip.

A couple of notes:
* The nextLink is for server-side paging and should be opaque, meaning you shouldn't try to pretend like you understand its structure even if you can make sense out of it when you look at it.
* To @nicenemo's point, with either form of pagination there are no guarantees about what will happen if another user adds or deletes records. IOW when using either form of pagination, a client should be prepared to miss records or deal with duplicated records.
