### ISSUE TITLE
ODataUriConversionUtils.ConvertToUriCollectionLiteral serializes Int64[] as string[]

### ISSUE THREAD

**Issue by zivillian** [OData/odata.net#536]
The uri conversion for collections uses the JsonWriter which in this case has IEEE754Compatible set to true, so that all Int64 and decimals are wrapped in quotes, which is not supported in ASP.NET on IIS (returns 404) and violates the spec.

### Assemblies affected
Microsoft.OData.Core 6.15.0.0

### Reproduce steps
```
ODataCollectionValue value = new ODataCollectionValue
{
    Items = new long[] { 1,2,Int64.MaxValue},
    TypeName = "Collection(Edm.Int64)"
};
var collectionString = ODataUriConversionUtils.ConvertToUriCollectionLiteral(value, Microsoft.OData.Edm.Library.EdmCoreModel.Instance, ODataVersion.V4);
```
  

### Expected result
Int64[] in uri should be serialized as `[1,2,9223372036854775807]`

### Actual result
The value is serialized as `["1","2","9223372036854775807"]`

### Additional details
OData-ABNF states the following:
```
primitiveColInUri = begin-array 
                    [ primitiveLiteralInJSON *( value-separator primitiveLiteralInJSON ) ] 
                    end-array

primitiveLiteralInJSON = stringInJSON
                       / numberInJSON
                       / 'true' 
                       / 'false'
                       / 'null'

numberInJSON = [ "-" ] int [ frac ] [ exp ]
```

**Comment by LaylaLiu** [comment]
@zivillian Thanks for reporting this one. We have an existing issue #522 same as this one. So I will close this as a dup. If you have different idea, please reopen it.
