### ISSUE TITLE
The EDM.TimeOfDay type doesn't work if declared as [Key]

### ISSUE THREAD

**Issue by VikingsFan** [OData/odata.net#537]
The EDM.TimeOfDay type doesn't work if declared as [Key]
### Assemblies affected

_OData .Net lib 6.15._  
### Reproduce steps

https://github.com/OData/WebApi/issues/702 
### Expected result

no error
### Actual result

https://github.com/OData/WebApi/issues/702

**Comment by dr-noise** [comment]
Is there any chance this issue will be fixed?..
