### ISSUE TITLE
How do we do OData in ASP.NET 5 vNext/ASP.NET Core 1.0

### ISSUE THREAD

**Issue by wingnut808** [OData/odata.net#540]
Is there support i.e. has the feature been started/finished for OData in ASP.NET 5 vNext/ASP.NET Core 1.0 any sign of a finish date?  

My project is a Web API Template project that targets .Net Framework 4.6

targets:- 
"frameworks": {
    "dnx46": { }
  }, 

If so how do we create our controllers?

Can we get an update for this in April 2016?  Is there a myget feed that I can trial?

I am only finding resources to System.Web namespaces.  I have been told by my management team that I should where possible avoid writing against these namespaces.  Due to the .net team looking to remove this namespace from future versions of the .net framework?  Is this correct?

How would one produce an OData endpoint in .net today in a stable release?  Should they fall back to a 4.5.x (.1.2) and target the other ASP.NET 4.6 templates?

Thanks for any information possible.

Adrian

**Comment by nicenemo** [comment]
Interesting for mobile support

**Comment by markdstafford** [comment]
This sounds like more of a Web API OData issue, tracked for instance in https://github.com/OData/WebApi/issues/628. We owe the community an updated status here, but for the most part we are still trying to figure out how to resource this (not so much the initial work as the ongoing support necessary). Does that makes sense? If not, please reopen the issue.

**Comment by jods4** [comment]
@markdstafford Would it be possible to use the libraries in this folder with ASP.NET Core to parse out a query string and apply it to a specific `IQueryable`? Or are important missing pieces inside OData/WebApi even for that limited scenario?
