### ISSUE TITLE
There will be an assertion failure complaining "edit link must already be set to location header", if the location header in the OData response is an URI having no local path, e.g. https://graph.microsoft.com

### ISSUE THREAD

**Issue by weiran-ms** [OData/odata.net#541]
There will be an assertion failure complaining "edit link must already be set to location header", if the location header in the OData response is an URI having no local path, e.g. https://graph.microsoft.com

### Assemblies affected
Microsoft.OData.Client.dll

### Reproduce steps
Use a debug version of the OData v4 client library to call a web service to add a resource, if the location header in the OData response is an URI having no local path, e.g. https://graph.microsoft.com.

### Expected result
No assertion failure 

### Actual result
There will be an assertion failure complaining "edit link must already be set to location header"

### Additional details
**Root cause**:
if the location header in the OData response is an URI having no local path, e.g. https://graph.microsoft.com, it will be added a tailing slash automatically when converted to an Uri object (i.e. https://graph.microsoft.com/ ). therefore, it will always fail, when comparing the location string to an Uri.AbsoluteUri, because of an extra tailing slash.

**Fix**: Convert the location string to a Uri first, when comparing it to an Uri

**Comment by TomDu** [comment]
Merged, thanks a lot!
