### ISSUE TITLE
OData Client Requires Microsoft.OData.Client.Key attribute for the entity, does not support the common key.

### ISSUE THREAD

**Issue by rjjkathy** [OData/odata.net#543]
OData client doesn't support the System.ComponentModel.DataAnnotations.Key

**Comment by tfabian** [comment]
Hi, we are sharing our POCO classes on the server and client side (OData web service and WPF client).  This means for us that the domain layer has a dependency on Microsoft.OData.Client.dll. Entity Framework already uses KeyAttribute from DataAnnotations. So we have to duplicate the key attributes on property level and class level.
In my opinion DataServiceContext should be able to infer the entity key, based on metadata (EDM Key element) or based on convention (*Id). Thx

**Comment by newclaus** [comment]
@ElizabethOkerio 
https://github.com/OData/odata.net/commit/7bbc068193a299ab11316eb7f4bcc273e87b7394#r44804113
