### ISSUE TITLE
Edm model with enum members' out of line annotation(s) fails to serialize

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#549]
_Short summary (3-5 sentences) describing the issue._  

It looks like EdmUtil.FullyQualifiedName() method doesn't support EdmEnumMember elements and returns null. 
### Assemblies affected

_Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta._  
Microsoft.OData.Edm.dll
### Reproduce steps

_The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue._  
### Expected result

_What would happen if there wasn't a bug._  

Enum member elements should be treated similar to operation parameters or properties. The fully qualified name is a combination of enumeration's qualified name + "/" + member name.
### Actual result

_What is actually happening._  
EdmUtil.FullyQualifiedName() returns null for enum member elements. This results in NullReferenceException being thrown from EdmUtil.IsQualifiedName() method called from IEdmVocabularyAnnotation.TargetString() extension method. This error is triggered by SerializationValidator class, line # 98.
### Additional details

_Optional, details of the root cause if known. Delete this section if you have no additional details to add._

**Comment by xuzhg** [comment]
Same as issue: https://github.com/OData/odata.net/issues/1262
Fixed in PR: https://github.com/OData/odata.net/pull/1263

Thanks.
