### ISSUE TITLE
Recurrence not serialized.

### ISSUE THREAD

**Issue by dawiduniec** [OData/odata.net#552]
When i'm trying to make an action with entity referenced to itself, it works fine on the service side, but when i'm sending the request the property with recurrence is not serialized.
### Assemblies affected

Microsoft.OData.Client 6.15.0.0
### Reproduce steps

Create basic OData service with entity referencing to itself:

```
public class Update
{
    [Key]
    public string Key { get; set; }
    public Update[] Parameter { get; set; }
}
```

Create action with this entity as parameter:

```
        builder.EntityType<Update>().Collection
                    .Action("Insert")
                    .Returns<string>()
                    .CollectionEntityParameter<Update>("Updates");
```

Create client which will send simple request like:

```
        var tsUpdate = new Update
            {
                Key = "Parent"
            };

        tsUpdate.Parameter.Add(new Update
        {
            Key = "Child"
        });
```
### Expected result

Should serialize whole object together with Parameter array
### Actual result

{"Updates":[{"@odata.type":"#OdataTest.Models.Update","Key":"Parent"}]}

Parameter array is not serialized at all.

**Comment by LaylaLiu** [comment]
@xfreakx, My understanding is that Parameter is actually a navigation property of Update. So this is known for OData client. OData client doesn't support deep insert. You can do two steps to finish this
    var tsUpdate = new Update
            {
                Key = "test/1"
            };
    dsc.AddObject(entitySetName, tsUpdate);
    dsc.SaveChanges();
    dsc.AddLink(tsUpdate, "Parameter", tsUpdate);
    dsc.SaveChanges();

**Comment by xfreakx** [comment]
@LaylaLiu thank you for a quick answer, but i have no idea what is dsc, could you please explain? Also I simplify the update object normally it also contains value, and the update is in tree structure, it's used to modify xml and the last step.
