### ISSUE TITLE
Possible wrong LINQ Query translation

### ISSUE THREAD

**Issue by nicenemo** [OData/odata.net#555]
When I use a LINQ query to select two properties, one at top level and one of a nested object the complete nested object is retrieved and select is performed client side.
### Assemblies affected

. OData .Net lib 6.15.0.0 Client library
### LINQ Query to Reproduce the problem

`
      var lazyQuery0 = from document in ctx.Documents.ByKey(sessionId)
                       select new
                       {
                         SessionId = document.SessionId,
                         NameOfHolder = document.IdentityDocument.NameOfHolder
                       };
      var item0 = lazyQuery0.GetValue();
`
### Url Produced

`GET /odata/ODataServlet/Documents('deadbeef-e2f0-4bad-cafe-218ddeadbeef')?$select=sessionId,identityDocument HTTP/1.1`

This results in having a complete identity document pulled over the 'wire'.
The select is performed clientside.
### Expected result

-We would expect another url similar to the sample code below.
-Resulting in the select being performed serverside.
### Ugly workaround

```
var url = string.Format("{0}/Documents('{1}')?%24select=sessionId%2CidentityDocument%2FnameOfHolder",host,sessionId);
      var lazyQuery1 = ctx.Execute<DocumentContent>(new Uri(url), "GET", true, new DummyOp("dummy", "dummy"));//Similar to bare http request and java code.
      var item1 = lazyQuery1.Single();
```
### Url produced

`
GET /odata/ODataServlet/Documents('deadbeef-e2f0-4bad-cafe-218ddeadbeef')?%24select=sessionId%2CidentityDocument%2FnameOfHolder HTTP/1.1
`
This results in only the SessionID and NameOfHolder being retrieved.
However:
- The result is fed to a DocumentContent object generated with the wizard in VS2015. It is not possible to feed it to a Tuple or a custom type containing only two fields. 
- We see no way to use anonymous types like in the LINQ query
- We are aware that this requires serverside support to generate another type and/or a change in the OData standard to do this efficiently.
### Additional details

For the workaround call to compile we had to define an extra dummytype. Otherwise the compiler did not select the right overload.

**Comment by LaylaLiu** [comment]
@nicenemo Thanks for reporting this. Right now, OData client only support select nested object for entity, but not for complex property. 
So if identityDocument is an entity type. OData client can translate it into /odata/ODataServlet/Documents('deadbeef-e2f0-4bad-cafe-218ddeadbeef')?$expand=identityDocument($select=nameOfHolder)&$select=sessionId.

But for complex type, OData client doesn't support it now.

**Comment by nicenemo** [comment]
Thanks @manivananse. What branch(es) is it fixed? or what commit does fix it?
