### ISSUE TITLE
JsonReader error messages are missing important context

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/odata.net#561]
When deserializing a JSON OData payload, syntax errors cause `JsonReader` to throw an `ODataException`. While the message in this exception describes the type of syntax error encountered, it doesn't include any context from the JSON being parsed, making it very difficult for customers to troubleshoot issues in how they produce the JSON.

### Assemblies affected
Microsoft.OData.Core, all versions.

### Reproduce steps
Try to read an OData JSON request payload that contains a syntax error, such as a missing comma.

### Expected result
The resulting `ODataException` message should contain enough context to identify the location of the syntax error in the JSON payload.

### Actual result
No context is given in the `ODataException`.

**Comment by brjohnstmsft** [comment]
I'm going to attempt to fix this.

**Comment by VikingsFan** [comment]
Merged 53967fde8da504dfc56945757e9e4642ade3c9a7
