### ISSUE TITLE
Verify and Remove Edm.ConcurrencyMode

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#564]
In [What's new in OData Version 4](http://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html#_Toc366145507)

It says:

```txt
4.3.4 Pruned: ConcurrencyMode

This was a nice idea, but somewhat inflexible, so it has been replaced with an annotation using the term Core.OptimisticConcurrencyControl.
```

However, in ODL for v4, we still have EdmCurrencyMode definition, see https://github.com/OData/odata.net/blob/cae9bbb85b5a45cc03dc42eec84f5e9eb1a41ed9/src/Microsoft.OData.Edm/Library/EdmStructuralProperty.cs#L56-L59

So, please verify and remove it.

### Assemblies affected
*OData .Net lib 7.x  

### Reproduce steps
None

### Expected result
Removed

### Actual result
No removed

**Comment by TomDu** [comment]
There remains some code logic in test framework that handles CurrencyMode, will remove them later.
