### ISSUE TITLE
Enum prefix free doesn't work for function parameter.

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#57]
For example:
I have a bound function named "GetCustomerByGender", with an enum parameter named "gender", type is Enum type.

When I call :
~/Customers/Default.GetCustomerByGender(gender=System.Web.OData.KenGender'Male')
It works.

But, when I enable Enum prefix free and call 
~/Customers/Default.GetCustomerByGender(gender='Male')
It fails.

The reason is that: 

The following function:

public static object ConvertFromUriLiteral(string value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference);

can't convent "Male" to a ODataEnumValue.

Please fix it. Thanks.

**Comment by congysu** [comment]
Does #66 also fix this?

**Comment by karataliu** [comment]
Verified a WebAPI OData issue: https://github.com/OData/WebApi/issues/243
