### ISSUE TITLE
Support Computed/Immutable/Permission annotation during read and write

### ISSUE THREAD

**Issue by chinadragon0515** [OData/odata.net#574]
Support Computed/Immutable/Permission annotation during read and write
### Assemblies affected

Can be considered as 7.0 lib content
### Reproduce steps
1. Add a property with some annotation line Computed (supported)
2. Any client send a patch request with this property.
3. Server deserialize the request, and should ignore the property.
### Expected result

The computed property for insert and update is ignored.
### Actual result

The computed property is not ignored.
### Additional details

Also add support for Immutable annotation and Permission annotation.

**Comment by chinadragon0515** [comment]
For properties whose has annotation Computed = true
1.	During query, server should return the computed property and client should serialized the property.
2.	During update/insert, Client may or may not include these properties, but when server receive the request, it should ignore any value from client if property has computed annotation.

For properties whose has annotation Immutable = true (Or this is removed as comments in ODATA-454?)
1.	During query, server should return the Immutable property and client should serialized the property.
2.	During insert, client may or may not include these properties, if client includes the property, the value from client is been used, but if client does not include, it will use value set by server.
3.	During update, Client may or may not include these properties, but when server receive the request, it should ignore any value from client if property has computed annotation.

In case of permission setting, 
1.	 For read, if permission is set to None or wirte (Added with ODATA-732), the property is not returned by server.
If permission is set to read/readwrite, it will be always returned during read.

2.	(Not finalize) For Write, if permission is set to None/Read, then user should not set the value during update, if user set the value and is different from previous value, then unauthorized error code is returned. And during insert, will throw exception if user set the value.
If permission is set to Write/Readwrite, then processed as normal.

**Comment by snebjorn** [comment]
why was this closed?
