### ISSUE TITLE
Abstract class deserialization

### ISSUE THREAD

**Issue by igclk** [OData/odata.net#576]
`<ComplexType` Name="A" `Abstract="true">`
`<ComplexType` Name="B" `BaseType="A">`
`<ComplexType` Name="C" `BaseType="A">`
 
Here class "A" generated as abstract with 2 concrete subclasses inherit from him.
But when trying to query for some object which contains one on the subclasses an exception of “cannot create an abstract class” is thrown.

**Comment by TomDu** [comment]
@igclk Could you please tell us how you encountered this issue (via ODL client or plain web request) so we can reproduce it? Thanks.

**Comment by igclk** [comment]
Hi Tom,

Via OData Client for .NET 6.15.

**Comment by TomDu** [comment]
Hi, I built a sample service with abstract base class `Address` and derived calss `SupplierAddress`, `SupplierAddress` is refered in entity type `Supplier`. Then I generated a client to query, update and add this property, but did not meet the exception you mentioned.

```
      <EntityType Name="Supplier">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
        <Property Name="SupplierAddress" Type="ProductService.Models.SupplierAddress" />
        <NavigationProperty Name="Products" Type="Collection(ProductService.Models.Product)" />
      </EntityType>
      <ComplexType Name="Address" Abstract="true">
        <Property Name="Street" Type="Edm.String" />
        <Property Name="ZipCode" Type="Edm.String" />
      </ComplexType>
      <ComplexType Name="SupplierAddress" BaseType="ProductService.Models.Address">
        <Property Name="CompanyName" Type="Edm.String" />
      </ComplexType>
```

**Comment by TomDu** [comment]
Fixed, thanks a lot for reporting this issue.
