### ISSUE TITLE
Want to have setting to indicate whether some setting is supported or not

### ISSUE THREAD

**Issue by chinadragon0515** [OData/odata.net#577]
For ODL consumer, allow a setting whether some query options is supported or not, and if a query option is not supported, then throw exception during URL parsing.
Another options is having some URL validator, and allow consumer to customize the validator.
### Assemblies affected

ODL 7.0
### Additional details

From Jeff Wight:

We are not using WebApi (but Peter is), and we have a need for almost exactly https://github.com/OData/WebApi/issues/465.  I’m suggesting that we try to create an extension of the core ODataLib that would allow us to do such validation, which could be used in WebAPI as well as when directly talking to ODataLib.

**Comment by JefWight** [comment]
Please consider using annotations already available on the IEdmModel for determining whether the request is valid.  Note that this requires an entire IODataRequestMessage, and not just an ODataUri, as it should validate a request based on the Method, EntitySet, and QueryOptions to the annotations found on the model.

For example, a GET to an EntitySet using $search with a SearchRestrictions/Searchable==false should fail.  Likewise, a POST to an EntitySet with an InsertRestrictions/Insertable==false should fail.

Please consider making this validation extensible for services that may extend the available annotations (such as adding SelectRestrictions/Selectable).

**Comment by ElizabethOkerio** [comment]
A workaround was provided here https://github.com/OData/WebApi/issues/465. Please feel free to reopen if the issue persists.
