### ISSUE TITLE
Remove the KeyAsSegment annotation in public V4 Northwind service

### ISSUE THREAD

**Issue by bixu-ms** [OData/odata.net#58]

**Comment by mikepizzo** [comment]
Confirmed we still have the annotation at http://services.odata.org/Experimental/Northwind/Northwind.svc/$metadata.

<Annotations Target="ODataWebExperimental.Northwind.Model.NorthwindEntities">
<Annotation Term="Com.Microsoft.OData.Service.Conventions.V1.UrlConventions" String="KeyAsSegment"/>
</Annotations>

This should be a trivial fix. However, note this service (while still live) is no longer linked from odata.org (or other public links that I'm aware of).

**Comment by mikepizzo** [comment]
Will re-visit if based on user feedback.
