### ISSUE TITLE
CreateODataCollectionReader can't work for collection of enum

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#580]
To read a top level collection of enum property, the `CreateODataCollectionReader `() will be failed.

```json
{"@odata.type":"Collection(NS.Color)","value":[
      "Blue",
      "Red",
       "Green"
   ]
}
```

The exception is thrown at `VerifyCanCreateODataCollectionReader` function. It's only process the collection of primitive and collection of complex.

Please help to investigate and fix it.

**Comment by TomDu** [comment]
[V6] CreateODataCollectionReader can't work for collection of enum.

**Comment by TomDu** [comment]
Done.
