### ISSUE TITLE
ODL 7.0 nightly doesn't work for complex as action parameter.

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#597]
### Assemblies affected
ODL 7.0.0-Nightly20160606 

### Reproduce steps

For example: I have the following payload for action parameter:

```
const string Body = @"{ ""Quantity"": 1 , ""Address"": { ""StreetAddress"":""1 Microsoft Way"", ""City"": ""Redmond"", ""State"": ""WA"", ""ZipCode"": 98052 } }";
```
**Address** is the action parameter of complex type.

I use the following to create a reader:

```
ODataParameterReader reader = messageReader.CreateODataParameterReader(action);
```

When access the `reader.State`, it gives `ODataParameterReaderState.Value`:

### Expected result
It should be `ODataParameterReaderState.Resource`

### Actual result
it gives `ODataParameterReaderState.Value`:

**Comment by LaylaLiu** [comment]
Have been fixed by https://github.com/OData/odata.net/commit/b730b5945133bb482b4118015c5512ea524ba735
