### ISSUE TITLE
ODL 7.0 nightly doesn't work to read dynamic property with collection complex type

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#599]
### Assemblies affected

ODL 7.0.0-Nightly20160606 

### Reproduce steps

For example: I want to read a dynamic property with collection complex type:

```json
{
    ......
    "Addresses@odata.type":"#Collection(NS.Address)",
     "Addresses":[
             {
                "@odata.type":"#NS.Address","Street":"Street 7","City":"City 7"
            }
      ]
}
```
**Addresses** is the dynamic property.

I use the following to create a reader:
`ODataReader odataReader = messageReader.CreateODataResourceReader(...);`

### Expected result

It should give a `ODataResourceSet` object for the `Addresses`.

### Actual result

it gives  a `ODataProperty` with `ODataCollectionValue`

It's definitely wrong.

**Comment by LaylaLiu** [comment]
Cannot repro this issue by using the latest nightly build
