### ISSUE TITLE
no navigation property binding can't work for multiple expand clause

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#603]
For example:

I have the following model:

```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Microsoft.AspNet.OData.Test.CRUD" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="ProtoMeasure">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <NavigationProperty Name="Metadata" Type="Microsoft.AspNet.OData.Test.CRUD.MeasureMetadata" />
      </EntityType>
      <EntityType Name="MeasureMetadata">
        <Key>
          <PropertyRef Name="MeasureId" />
        </Key>
        <Property Name="MeasureId" Type="Edm.Int32" Nullable="false" />
        <NavigationProperty Name="PackageTypes" Type="Collection(Microsoft.AspNet.OData.Test.CRUD.PackageType)" />
      </EntityType>
      <EntityType Name="PackageType">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
        <Property Name="Version" Type="Edm.Binary" />
      </EntityType>
    </Schema>
    <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="Container">
        <EntitySet Name="Measures" EntityType="Microsoft.AspNet.OData.Test.CRUD.ProtoMeasure" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

Where, I only create one entity set named "Measures", and the navigation property doesn't have any binding.

This following queries work as expected:

1. `Measures(key)?$expand=Metadata($expand=PackageTypes)`
2. `Measures(key)?$expand=Metadata($expand=PackageTypes($select=Name))`
3. `Measures(key)?$expand=Metadata($expand=PackageTypes($select=Name;$top=1))`

but, the following queries failed:

1. `Measures(key)?$expand=Metadata($expand=PackageTypes($select=Name;$top=1;$filter=Name ne 'foo'))`
2. `Measures(key)?$expand=Metadata($expand=PackageTypes($select=Name;$top=1;$orderby=Name))`

The problem is that:

For the first `$expand=Metadata`,  ODL will get a “Unknown” entity set for the target navigation source of the navigation property.

But the second `$expand=PackageTypes`, ODL can't get the target navigation source of the navigation property from the "Unknown" entity set.

Please verify.

**Comment by TomDu** [comment]
Didn't reproduce on ODL 7.x.
