### ISSUE TITLE
if .Contains() is not supported (it easy could be, but OK) then the proper exception should be thrown regardless of the collection type

### ISSUE THREAD

**Issue by nickkin-msft** [OData/odata.net#608]
When querying for a property being one of several possible values, if you create a long "or" conditional like so:

odataClient.MyCollection.Where(x => x.prop == "val1" || x.prop == "val2") 

this works just fine.  However, if you try to simplify the query like so:

List<string> values = new List<string>();
values.Add("val1");
values.Add("val2");
odataClient.MyCollection.Where(x => list.Contains(x.prop))

then it fails with: "System.NotSupportedException: Could not convert constant System.Collections.Generic.List`1[System.String] expression to string."  This confused me for a while until eventually I tried

var values = new string[] { "val1", "val2" };
odataClient.MyCollection.Where(x => list.Contains(x.prop))

Then you get a reasonable exception: "System.NotSupportedException: The method 'Contains' is not supported."  Now I understand.

This is inconsistent.  If .Contains() is not supported, that's fine, but it should throw the proper exception on .Contains based on any collection type.
### Assemblies affected

Microsoft.OData.Client v4.0.30319
Microsoft.OData.Core v4.0.30319
Microsoft.OData.Edm v4.0.30319 
### Reproduce steps

Simply execute the example queries using the T4 generated client code against any OData endpoint.
### Expected result

If .Contains() is not supported, that's fine, but it should throw the proper exception on .Contains based on any collection type.
### Actual result

A difficult to understand error is emitted in some variations, for example when trying List<>.Contains() instead of Array.Contains().

**Comment by tomidix** [comment]
This is a joke. This kind of issue open for more than 3 years still not solved.. This should already be implemented and not only message changed for list vs array..

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/pull/1868
