### ISSUE TITLE
Selecting a string property from single entity ByKey uses incorrect uri

### ISSUE THREAD

**Issue by AdamCaviness** [OData/odata.net#615]
When attempting to $select a string property on an entity via ByKey(), OData Client constructs `/PropertyName` instead of `$select=PropertyName`.  This works correctly for Navigation Properties but not primitive properties.

### Assemblies affected
OData Client 6.14 and possibly others

### Reproduce steps
Query a single entity and use Linq to select just a single string property before calling GetValue().
`Context.Customers.ByKey(entityKeys).Select(cs => cs.CustomerName).GetValue();`

### Expected result
`{
  "@odata.context": "https://localhost/DataApi/$metadata#Customers(CustomerName)",
  "value": [
    {
      "CustomerName": "Obi-wan Enterprises"
    }
  ]
}`

### Actual result

> No HTTP resource was found that matches the request URI 'https://localhost/DataApi/Customers(CustomerID%3D0db7f025-c881-4340-9e2e-0fe812b25211%2CMetaSchemeID%3D38752f27-ae72-42d9-b878-e749c06c9e1e)/CustomerName'.

**Comment by LaylaLiu** [comment]
@AdamCaviness, if you want to use $select, you need to use projection. The client code should be like 

Context.Customers.ByKey(entityKeys).Select(cs => new Customer(){CustomerName = cs.CustomerName}).GetValue();

**Comment by AdamCaviness** [comment]
@LaylaLiu Thanks!
