### ISSUE TITLE
$ref not working with System Query Option $expand

### ISSUE THREAD

**Issue by LianwMS** [OData/odata.net#62]
As per the Protocol Document

11.2.4.2 System Query Option $expand

The $expand system query option indicates the related entities that MUST be
represented inline. The service MUST return the specified content, and MAY
choose to return additional information.

The value of the $expand query option is a comma-separated list of navigation
property names, optionally followed by a /$ref path segment or a /$count path
segment, and optionally a parenthesized set of expand options (for filtering,
sorting, selecting, paging, or expanding the related entities).

For a full description of the syntax used when building requests, see [OData-
URL].

Example 36: for each customer entity within the Customers entity set the value
of all related Orders will be represented inline

    http://host/service.svc/Customers?$expand=Orders

Example 37: for each customer entity within the Customers entity set the
references to the related Orders will be represented inline

    http://host/service.svc/Customers?$expand=Orders/$ref

The above query in example 37 is not functioning, tried it on sample ODataV4
web api service

Query: 
    http://services.odata.org/TripPinWebApiService/People?$expand=Trips/$ref

Output:

    {
    "error":{
     "code":"","message":"The query specified in the URI is not valid. Found system token '$ref' in select or expand clause 'Trips/$ref'."
    }
    }

**Comment by congysu** [comment]
Handle together with `*`.

**Comment by chinadragon0515** [comment]
This is already supported. Refer to sample service http://services.odata.org/V4/TripPinService/People?$expand=Friends/$ref

Close the issue.
