### ISSUE TITLE
Status of RTM/GA packages that are .NET Core (Core CLR) compat

### ISSUE THREAD

**Issue by GuardRex** [OData/odata.net#620]
May I inquire on the status on getting `Microsoft.Data.OData`, `Microsoft.Data.Services.Client`, `System.Spatial`, and `Microsoft.Data.Edm` .NET Core (Core CLR for TFM's `netstandard1.x`/`netcoreapp1.0`) compatible packages?

This seems to be blocking the Azure Storage folks (https://github.com/Azure/azure-storage-net/issues/298) from releasing their RTM/GA package (maybe ... they won't say for sure), which is in-turn blocking me from getting a contract wrapped up with a client (i.e., my contract stipulates "no preview packages"). Even if it isn't blocking them, it is forcing us to provide TFM `imports` to get the packages restored in our .NET Core projects.

Is there any status you can provide? Thanks.

**Comment by mirobers** [comment]
It's not blocking Azure Storage. But you are right that it does require `imports`.

**Comment by GuardRex** [comment]
This turned out to be a dup of https://github.com/OData/odata.net/issues/568 with a PR hanging out there without comment at https://github.com/OData/odata.net/pull/591.

It might have been blocking if the Azure Storage team cannot release a GA package on the basis of pre-release dependencies coming from other teams ... sort of along the lines of what was said about the preview `WindowsAzure.Storage` lib for .NET Core both during RC1 and RC2 nightly (i.e., 'we only go release-to-release').

**Comment by mirobers** [comment]
Certainly, I agree that it would not make much sense to GA with prerelease dependencies. The difference here is that these aren't prerelease packages.

**Comment by GuardRex** [comment]
They are crudely "prerelease" if they require `imports` because the lib authors haven't updated them for NETStandard TFM's. Technically, you're right. I see your point. However ... practically ... they are sort of prerelease because we are having to force them into .NET Core. Maybe "prerelease" just isn't the right word. Let's just say "incompatible," because that's what they are. That's the actual error that the `dotnet cli` even throws on them.

This could get worse before it gets better. Reading even more in the OData issues, I hope that PR looks good to them and they can move on it quickly. The comment that they might have something by the end of July is really bad ....... really, really bad.

**Comment by advancedrei** [comment]
@GuardRex, please refer to my comment on Issue #568. There is nothing "really, really bad" about it. You need to be thinking like Microsoft just shipped .NET 1.0 all over again. It's going to be _months_ before everyone in the industry has caught up. Every single NuGet package owner got screwed with this release. Everyone has to update their packages now. I have 33 separate OSS NuGet packages I now have to update. PCLs were supposed to be the way this crap got avoided.

If you're moving to .NET Core now, and not in six months + like you should, you do so at your own risk. And no one is *obligated* to support your scenario right now. Each package will get there when it is ready.

**Comment by GZidar** [comment]
Has there been any progress on this since that previous comment? Azure Storage still has a dependency on the full framework until this library has .net core support. I am just curious as to timeframes because I can't find any such information in the documentation.

**Comment by GuardRex** [comment]
Azure Storage does have .NET Core support: https://www.nuget.org/packages/WindowsAzure.Storage/

The imports are still required for OData libs. There's a good issue comment that may help if you're using `project.json` at: https://github.com/OData/odata.net/issues/568#issuecomment-274119903

If you need to set it up for an MSBuild/`csproj` project, use ...
```xml
<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.2' ">$(PackageTargetFallback);dnxcore50;portable-net45+win8</PackageTargetFallback>
```
:point_up: Set the "1.2" to whatever version of `netcoreapp` you're using.

... and then ...

```xml
<PackageReference Include="WindowsAzure.Storage" Version="8.0.1" />
```

**Comment by GZidar** [comment]
Version 8.0.1 still pulls in the 5.7.0 versions of the odata, spatial, and edm which have a dependency on net framework 451 so these can't be built for netcore... however it seems that there are newer versions of all three of those libraries 5.8.2 which do work with dnxcore50 so as long as you explicitly reference those newer versions in your project it will build properly which is great. Thanks for your help.

**Comment by mirobers** [comment]
OData 5.8.2 was released yesterday. We are aware and will upgrade soon.
