### ISSUE TITLE
Support DI in OData Client

### ISSUE THREAD

**Issue by LianwMS** [OData/odata.net#623]
Support DI in OData Client
### Assemblies affected

OData.Client.dll

**Comment by AlanWong-MS** [comment]
Associated test case:
test\FunctionalTests\Tests\DataServices\UnitTests\ServerUnitTests\Tests\KeyAsSegmentLongSpanIntegrationTests.cs : KeyAsSegmentEndToEndSmokeTestInJsonLight()
