### ISSUE TITLE
Support ODataInstanceAnnotation in Complex Type.

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#625]
[ODL 7.0] After removed the ODataComplexValue. ODataLib doesn't support the instance annotation in complex type any more.

**Comment by nyndo** [comment]
We used the ODataComplexValue to fill the instance annotations with metadata.

Is there any workaround?
And do you know when this will be fixed?

Thank you for your answers.

**Comment by gathogojr** [comment]
Instance annotations in complex types supported in current Microsoft.OData.Core 7.10.0 release

**Comment by giulianob** [comment]
@gathogojr Where can I find an example or the commit which added annotation support to complex types? Thanks!
