### ISSUE TITLE
Floating point type parameters parsing problem

### ISSUE THREAD

**Issue by RuslanMarchenko** [OData/odata.net#63]
When I call odata function with a double parameter, I can see that ExpressionLexer.MakeBestGuessOnNoSuffixStr method is using current thread culture for several TryParse method calls when trying to parse the parameter from the url. I suppose that to be a bug because the numeric literal format is fixed in OData-ABNF, the double one for example. It seems that there is a need to call TryParse with invariant culture, insn’t it?

**Comment by congysu** [comment]
Ruslan: Would you like to contribute a fix for the issue? Thanks.

**Comment by cisnetsov** [comment]
Same problem. Any update?

**Comment by maximpashuk** [comment]
If CurrentCulture is russian (for example), then double.Parse("0.23") will fail and double.Parse("0,23") will success - used comma instead of dot.
Because ABNF for ODATA resticted to dots, so ExpressionLexer should use InvariantCulture then parsing strings.
I made in in my pull request #374

**Comment by lewischeng-ms** [comment]
PR #374 has been merged. @maximpashuk Thanks for your contribution again!
