### ISSUE TITLE
Support no-$ for system query parameters in OData library.

### ISSUE THREAD

**Issue by cpham97** [OData/odata.net#637]
### Rationale

OData makes liberal use of the '$' sign prefix for its system query parameters.  Customers across several of our REST APIs have expressed distaste for this atypical formation, and also expressed that this stops them from using Microsoft APIs inside 3rd party tooling that tends to define query parameters particularly as having a syntax similar to typical programming language identifiers (e.g., something like [a-zA-Z][a-zA-Z0-9]\* ). Therefore, **making '$' sign prefix of system query parameters become optional** would be significant tool unblocker and delighter.
### Assemblies affected

OData .Net lib 6.16.
### Change proposal

All '$' signs in system query parameters after the '?' should become optional.
Here is an example of a complex query using OData query parameters to their fullest, nested form:
GET www.onenote.com/api/beta/Notebooks?expand=sections,sectionGroups(expand=sections,sectionGroups(levels=max;expand=sections))
**should yield same result as**
GET www.onenote.com/api/beta/Notebooks?$expand=sections,sectionGroups($expand=sections,sectionGroups($levels=max;$expand=sections)) 
### Additional details

It's important to note that the standard-compliant '$' prefix syntax for system query parameters must not be affected by this change, but rather an additional and simpler syntax is being added. The support **MUST be opt-in** for the library consumer.

**Comment by manivannanse** [comment]
Closed per #639
