### ISSUE TITLE
Calling OData function: Int64 collection type parameter parsing problem

### ISSUE THREAD

**Issue by RuslanMarchenko** [OData/odata.net#64]
It seems that the uri parsing infrastructure does not take the IEEE 754 specification into account. When I call an odata function with a Collection(Edm.Int64) parameter, I can see that each item in the collection argument  is encoded according to this standard as a string. But the function call in Web API OData service fails with 404 error and the message "An unexpected node was found for property named StartObject when reading from the JSON reader. A StartArray node was expected.".

**Comment by congysu** [comment]
OData Web API issue https://github.com/OData/WebApi/issues/7
