### ISSUE TITLE
Incorrect boundary delimiter used in multipart responses to batch requests on Mono

### ISSUE THREAD

**Issue by benmunro** [OData/odata.net#646]
When a batch response is serialized running on Mono the HTTP response uses `\n` as the boundary delimited rather than `\r\n` as required by [RFC2046](https://tools.ietf.org/html/rfc2046#section-5.1.1).  This results in the [HttpContentMultipartExtensions.ReadAsMultipartAsync](https://msdn.microsoft.com/en-us/library/system.net.http.httpcontentmultipartextensions.readasmultipartasync%28v=vs.118%29.aspx#M:System.Net.Http.HttpContentMultipartExtensions.ReadAsMultipartAsync%28System.Net.Http.HttpContent%29) throwing an exception when used on one of these responses.
### Assemblies affected

Microsoft.OData.Core 6.15.0
### Reproduce steps
1. Run an OData service on Mono, I was using 4.2.2. If helpful I can provide a minimal service which will run on Mono.
2. Perform a request to the `/$batch` endpoint
### Expected result

A valid HTTP response is returned.
### Actual result

An HTTP response is returned with the incorrect boundary delimiter between the mime body parts.
### Additional details

This is caused by the use of a `StreamWriter` to write out the http parts of the batch content in [`ODataBatchWriter`](https://github.com/OData/odata.net/blob/ODataV4-6.x/src/Microsoft.OData.Core/ODataBatchWriter.cs). When running on Windows this is fine as the default new line characters are `\r\n` but on Mono [`TextWriter`](https://github.com/mono/mono/blob/8f2487b3ce2817d0d9013981272b876371222f64/mcs/class/referencesource/mscorlib/system/io/textwriter.cs#L99-L112) uses `\n`. I was able to fix this by changing [`RawValueWriter`](https://github.com/OData/odata.net/blob/3445a856c7c2498036235516a31966cf1f53e45a/src/Microsoft.OData.Core/RawValueWriter.cs#L168) to create a `StreamWriter` with the `NewLine` property set to `\r\n` but I'm not sure where else this is used and what that change could affect. Alternatively `ODataBatchWriter` could be changed to write the `\r\n` explicitly rather than using `TextWriter.WriteLine`. If you let me know the preferred change I am happy to submit a PR.

**Comment by Lingxi-Li** [comment]
Thanks for reporting this issue. It has been [confirmed](http://melpon.org/wandbox/permlink/PbddEGcXkdg6FngL). `TextWriter.NewLine` is the intended interface to address such issue, and should be used. We will be waiting and looking forward to your PR :smiley:

**Comment by benmunro** [comment]
@Lingxi-Li Great I'll look to get something in next week. I just have to sort out the CLA with my employer first. The CONTRIBUTING.md mentions signing a pdf and emailing it. Can I go through the process at https://cla.microsoft.com/ instead?

Regarding testing for this I can add testing to ensure that the http responses use the correct delimiters but testing this on Windows won't provide much benefit. I noticed #627 mentions a teamcity server used for doing builds. Would it be an option to set up a build on there to run some of the tests under mono as well? I could look at using something like [Travis CI](https://travis-ci.org/) to do a build and run the tests but from experience it is much simpler to take binaries for tests which have been build on Windows and run them under mono than it is to do the entire build on mono. I had a quick go at building some of the slns with xbuild but ran into issues pretty quickly with FxCop and the other tools used at compile time. Any thoughts you have on this would be great.

**Comment by Lingxi-Li** [comment]
Regarding the CLA, you could give https://cla.microsoft.com/ a try. If you managed to complete the whole procedure (which may involve emailing a signed pdf anyway), it should be OK.

Currently, we are unable to run the tests on non-Windows OSes. Besides, since we have really complicated project configurations, it's very unlikely that you could build successfully using tool sets other than Visual Studio (2013, in particular). The solution is, as you have suggested, to build the assemblies on Windows using Visual Studio 2013, and test the assemblies on Mono. If everything works out fine, you could just submit a pull request then, and we will lead from there and take care of the rest.

I know all these are annoying and somewhat demanding. But this is just the best solution we can come up with by now. Sorry for the inconveniences caused. Feel free to ask should any problem arise.

**Comment by Lingxi-Li** [comment]
Hi, @benmunro Have you made any progress recently? If you encountered any blocking difficulties, please let us know. We are here to help :smiley:

**Comment by benmunro** [comment]
Hi @Lingxi-Li sorry for not responding sooner. At this point I've got the changes ready to go I'm just waiting to hear back from my employer about the CLA. Hopefully I'll get an answer on it soon :)

**Comment by Lingxi-Li** [comment]
Looking forward to your good news :)

**Comment by andygjp** [comment]
Hello,

I'm currently using Microsoft.AspNetCore.OData v7.4.0 on Linux and I have this same issue. When do you plan to fix it?

Cheers,
Andy

**Comment by marabooy** [comment]
@andygjp there is a Pr to address this which should come to the next release.

**Comment by andygjp** [comment]
Its working for me. Thank you!
