### ISSUE TITLE
Please upgrade OData to Microsoft.AspNet.WebApi.Core v 5.2.3

### ISSUE THREAD

**Issue by jhensley707** [OData/odata.net#649]
Current release of Microsoft.AspNet.OData, v 5.9.1 is incompatible with current release of Microsoft.AspNet.WebApi.Cors v 5.2.3.

### Assemblies affected
System.Web.OData, Version=5.9.1.0 is built with System.Net.Http.Formatting, Version 5.2.2.0. 
System.Web.Cors, Version=5.2.3 is built with System.Net.Http.Formatting, Version 5.2.3

### Reproduce steps
Create a new WebApi 2.2 project.
Add both Microsoft.AspNet.OData and Microsoft.AspNet.WebApiCors.
In WebApiConfig.Register(), add config.EnableCors();

### Expected result
Web service should activate and respond to requests 

### Actual result
Web service returns this error
Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.2.0

Failure occurs on startup in line below:

GlobalConfiguration.Configure(WebApiConfig.Register);

### Additional details
Microsoft.AspNet.OData, v 5.9.1 requires Microsoft.AspNet.WebApi.Core v 5.2.2
Microsoft.AspNet.WebApi.Cors v 5.2.3 requires Microsoft.AspNet.WebApi.Core v 5.2.3

**Comment by Lingxi-Li** [comment]
This should be a WebApi issue, not ODL issue.

**Comment by xuzhg** [comment]
https://github.com/OData/WebApi/issues/781

**Comment by xuzhg** [comment]
@jhensley707 Would you please take the comment in OData/WebApi#781. Thanks.
