### ISSUE TITLE
DataServiceClient QueryResult.ExecuteQuery: An in memory copy of the server response stream is generated - Avoid this at least for synchroneous requests.

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#655]
Performance issue.
DataServiceClient QueryResult.ExecuteQuery: An in memory copy of the server response stream is generated leading to excessive overhead. Please allow direct reading from the response stream.
### Assemblies affected

WCDS Client 5.7 (V3).
ODataClient (V4)
### Reproduce steps

Compare an ODataReader implementation with a Query.Execute implementation of getting a large data set with the same query.
### Expected result

The time taken to get large data sets would be comparable. 
### Actual result

Query.Execute is significantly slower. 
### Additional details

This is due to an in-memory stream copy being generested of the web response stream.

**Comment by manivannanse** [comment]
Closed as fixed by #656
