### ISSUE TITLE
OData Client can't work if the client side use string while the server side uses enum type.

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#657]
For example:

### Client side:

```C#
public class ModelTest
{
    public string Enum { get; set; }
}

```

### Server side:

```C#
public class ModelTest
{
    public EnumType Enum { get; set; }
}

```

If I add a new entity using the OData client, it will fail at (Debug mode):

https://github.com/OData/odata.net/blob/ODataV4-6.x/src/Microsoft.OData.Client/ClientConvert.cs#L128

Actually: before this` Debug.Assert(...), `we should add:

```c#
ODataEnumValue enumValue = propertyValue as ODataEnumValue;
if (enumValue != null)
{
      return enumValue.Value;
}
```

**Comment by LaylaLiu** [comment]
Fix has been checked-in by 9271fbec498c0b014e85c
