### ISSUE TITLE
DataServiceClient Navigation property name missing escaping during savechanges if both ends are new.

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#664]
_Navigation property names with special characters is not handled during save changes if bot ends are new - they should be escaped._  
### Assemblies affected

_WCF DS Client 5.7.0._  
### Reproduce steps

_The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue._  
### Expected result

_The following message would be generated showing correct escaping of the property name Køntrollør into "Kontroll%C3%B8r"._ 

--changeset_6f70cdd9-55b1-4b33-b3f8-c9cd98c6f171
Content-Type: application/http
Content-Transfer-Encoding: binary

PUT $2/$links/Kontroll%C3%B8r HTTP/1.1
Content-ID: 4
DataServiceVersion: 3.0;NetFx
MaxDataServiceVersion: 3.0;NetFx
Accept: application/json;odata=minimalmetadata
Accept-Charset: UTF-8
Content-Type: application/json;odata=minimalmetadata
User-Agent: Microsoft ADO.NET Data Services

{"url":"$3"}
--changeset_6f70cdd9-55b1-4b33-b3f8-c9cd98c6f171--
### Actual result

_The following message is generated showing the unescaped property name "Kontrollør"._

--changeset_6f70cdd9-55b1-4b33-b3f8-c9cd98c6f171
Content-Type: application/http
Content-Transfer-Encoding: binary

PUT $2/$links/Kontrollør HTTP/1.1
Content-ID: 4
DataServiceVersion: 3.0;NetFx
MaxDataServiceVersion: 3.0;NetFx
Accept: application/json;odata=minimalmetadata
Accept-Charset: UTF-8
Content-Type: application/json;odata=minimalmetadata
User-Agent: Microsoft ADO.NET Data Services

{"url":"$3"}
--changeset_6f70cdd9-55b1-4b33-b3f8-c9cd98c6f171--
### Additional details

_Optional, details of the root cause if known. Delete this section if you have no additional details to add._

**Comment by markdstafford** [comment]
Closed by #665.
