### ISSUE TITLE
Support instance annotations on ODataEntityReferenceLink/ODataEntityReferenceLinks

### ISSUE THREAD

**Issue by karataliu** [OData/odata.net#67]
Currently custom instance annotations is not available on ODataEntityReferenceLink/ODataEntityReferenceLinks. But JSON spec allows this.

**Comment by congysu** [comment]
Follow up with the original request.

**Comment by kenmuse** [comment]
This one is particularly difficult to work around given that both the properties for setting the annotations on ODataEntityReferenceLink and the various classes involved in serializing those entities are currently all internal.

**Comment by shahzorkhan123** [comment]
The aim is for us to use SetAnnotation on ODataEntityReferenceLinks and ODataEntityReferenceLink.
And the WriteEntityReferenceInNavigationLinkContent adds the code for writing the annotations as there is no possible way of override found.

**Comment by karataliu** [comment]
https://github.com/OData/odata.net/commit/b32de1b50b56092a6d8eef34668f55154ba3358a
https://github.com/OData/odata.net/commit/5aba823b787301644be80d647ba01f0988601226

**Comment by karataliu** [comment]
Done with previous two commits as mentioned.
