### ISSUE TITLE
In .Net 4.5 the exception message was Garbled

### ISSUE THREAD

**Issue by VikingsFan** [OData/odata.net#673]
like this:
:!FIaGa!Invalid JSON. An unexpected comma was found in scope 'Object'. A comma is only valid between properties of an object or between elements of an array. 表©鷗字㌍ 表©鷗字㌍ 表©鷗字!
ps:the language of vs is Simplified Chinese .

**Comment by kfstorm** [comment]
Any update?

**Comment by ElizabethOkerio** [comment]
This is an old issue that might have been fixed in newer versions of the library. Reopen if it still persists.
