### ISSUE TITLE
Select property from inherited type - Exception: Could not find a property named 'X' on type 'T'

### ISSUE THREAD

**Issue by FordSoft** [OData/odata.net#676]
I have this domain model:

```
public class Parent 
{  
   public string Prop1 {get;set;}
}

public class Child : Parent
{
   public string Prop2 {get;set;}
}

public class Container
{
  public  Parent Dummy {get;set;}
}

var instance = new Container()
{
  Dummy = new Child ()
  {
    Prop1 = "BLA BLA",
    Prop2 = "Property 2"
  }
}
```
when I call this:

`/api/Container(1)?$expand=Dummy($select=Prop1)`
it's ok.

when I call this:

`/api/Container(1)?$expand=Dummy($select=Prop2)`
I get exception:

Could not find a property named 'Prop2' on type 'Parent'.
how do I get the property 'Prop2' ?

**Comment by Lingxi-Li** [comment]
Please provide a [MCVE](http://stackoverflow.com/help/mcve). From the code you have provided, I have seen the following issues:

1. `Container` does not inherit from `Parent`. So how could you initialize the `Dummy` property (which is of type `Parent`) with a `Container` instance?

2. Likewise, `Container` does not have a property named `Prop1`.

**Comment by FordSoft** [comment]
sorry I corrected code, but nevertheless it does not solve my problem

**Comment by Lingxi-Li** [comment]
You also need to show how you have used the OData library to construct the service. Without the necessary information, we cannot figure out what may have gone wrong. Specifically, since you are posting this issue on the OData.NET repository instead of the other OData libraries ([WebApi.OData](https://github.com/OData/WebApi), [RESTier](https://github.com/OData/RESTier)), you should show how you have used the OData.NET library.

**Comment by uffelauesen** [comment]
Isn't this simply a missing type cast that is missing? Container declares Dummy as Parent. Your $select specifies you want the property Prop2 returned, but that property is only available on the derived type Child. You need to do a type filtering/casting on you Url. See example 34 on [V4 Url Conventions](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752352)

**Comment by Lingxi-Li** [comment]
@uffelauesen Exactly. I didn't even bother to look at the request URLs (only looked at the code). My bad, and thank you for your response :)

**Comment by Lingxi-Li** [comment]
@FordSoft, I would expect uffelauesen's comment to solve your problem. So I will close this issue. If you still have problems, feel free to reopen this or open up a new issue. Thanks.
