### ISSUE TITLE
DataServicesClient - OnEntityMaterialized/ReadingEntity does not fire for projected results.

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#677]
_The ResponsePipeline's OnEntityMaterialized (JSON+ATOM) and ReadingEntity (ATOM) does not fire if the query had projection._  
### Assemblies affected

_WCF DS Client 5.7.0._  
### Reproduce steps

_The following code demonstrates the issue._  

```
var ctx = Context();
ctx.Format.UseJson();
var q = from f in ctx.Files
        select new File
        {
            ID = f.ID
        };
((DataServiceContext)ctx).Configurations.ResponsePipeline.OnEntityMaterialized(a =>
{
    Console.WriteLine(a.Entry.Id);
});
foreach (var f in q)
    Console.WriteLine(f.ID);
```
### Expected result

_Both the entity ID and the entry Id is written to the console._  
### Actual result

_Only the entity ID is written to the console._  
### Additional details

_Optional, details of the root cause if known. Delete this section if you have no additional details to add._

**Comment by markdstafford** [comment]
Closed by #678.
