### ISSUE TITLE
DataServicesClient - DSC AutoChangeTracking does not work for subsequent server pages.

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#681]
_Expanded navigation properties of DataServiceCollection<> with AutoChangeTracking will only have change tracking enabled for the first server page. This only happens if the root entity is not itself in a DataServiceCollection._  
### Assemblies affected

_WCF DS Client 5.7.0_  
### Reproduce steps

_Suppose File with ID="2908170" has 52 Records in the FileRecord property and the server uses server driven paging with a pagesize of 50, we can then reproduce the issue with the following code._

```
var q = from f in ctx.Files
        where f.ID == "2908170"
        select new File
        {
            ID = f.ID,
            FileRecords = new DataServiceCollection<Record>
                (
                    from r in f.FileRecords
                    select new Record
                    {
                        ID = r.ID,
                        Title = r.Title
                    }
                )
        };
var file = q.Single();
// We assert that we have another server page...
file.FileRecords.Load(ctx.Execute(file.FileRecords.Continuation));
foreach (Record rec in file.FileRecords)
    rec.Title = "Changed title";
foreach (Record rec in file.FileRecords)
    Console.WriteLine(((DataServiceContext)ctx).GetEntityDescriptor(rec).State);
```
### Expected result

_All Records in FileRecords property will have State=Modified._  
### Actual result

_Only the first 50 Records in FileRecords will have State=Modified the last two have State=Unchanged._  
### Additional details

_It seems to be related to ODataEntityMaterializer::MergeLists() that checks if property.GetValue(entry.ResolvedObject) is null - which it never is with the standard proxy that does eager initializing of all DSC<> typed properties. I can fix this issue if I change the proxy to have lazy or uninitialized DSC<> properties as reported in #662. and use check the backing field instead.
If I change the query so it is loaded into a DataServiceCollection<File> making the File object itself be placed in a DSC - the problem goes away._

**Comment by manivannanse** [comment]
Fixed by #682
