### ISSUE TITLE
Serialization of edmCollectionobject of type abstact base entity type fails and expects entity set to be exposed and not possible by entitytype

### ISSUE THREAD

**Issue by kedarnath-k** [OData/odata.net#69]
Dear Team,

We are exposing an operation which returns collection of entities of different edm entity types and the we marked the operation return type as collection of abstract base entity type which is base for all the entities we are exposing in our endpoint.

At the time of serializing the response , the navigation source needs to be set to entityset of abstract base entity type and we cant expose entityset for our abstract base entity type.

The serialization of response should be possible using entity type too apart from entityset.

Thanks,
Kedar

**Comment by abkmr** [comment]
Needed for CRM

**Comment by LianwMS** [comment]
@abkmr @kedarnath-k 
The PR https://github.com/OData/odata.net/pull/421 is for this issue.
After the PR, OData Lib allow the navigation source be null during serialization, but the serialization info need to be passed to ODataFeed, like the case in Class WriteFeedWithoutNavigationSourceTests.

Could you help to review?

**Comment by LianwMS** [comment]
Submitted
