### ISSUE TITLE
Getting back wrong HTTP status code for the error "The $filter expression must evaluate to a single boolean value." in OData V4.

### ISSUE THREAD

**Issue by umagarwa** [OData/odata.net#696]
When a user makes a malformed request eg. (?$filter=TextFilter) instead of (?$filter=TextFilter eq 1), OData v4 should return HTTP status code 400 or bad request. 

But instead it returns HTTP status code 500 or Internal server error. 

Since the user did something wrong here(The $filter expression must evaluate to a single boolean value), we expect this to return a status code 400 like OData V3 WCF data services did.
### Assemblies affected

OData v4 (Microsoft.OData.Core.6.15.0)
### Reproduce steps

Make a request using malformed query to an odatav4 endpoint. For example  (?$filter=TextFilter) instead of a valid query like (?$filter=TextFilter eq 1).
### Expected result

HTTP status code 400.
### Actual result

HTTP status code 500.

**Comment by ElizabethOkerio** [comment]
This issue is fixed in the latest versions of the library.
