### ISSUE TITLE
DataServiceQuerySingle<T>.GetValueAsync inconsistent with GetValue in support for GET returning 404

### ISSUE THREAD

**Issue by skottmckay** [OData/odata.net#698]
Using GetValueAsync throws if the request is reading a single entity and that entity is not found, and IgnoreResourceNotFoundException is set to true.

GetValue works as expected.

The different is that GetValue calls SingleOrDefault(), and EndGetValue (used by GetValueAsync) calls Single(). The usage of Single leads to an InvalidOperationException as the sequence has no elements due to the entity not being found.

OData Client v4.6

**Comment by patrickmichalina** [comment]
Hit with this error as well!
