### ISSUE TITLE
Decimal function parameter parsed failed with cast error.

### ISSUE THREAD

**Issue by VikingsFan** [OData/odata.net#702]
_Short summary (3-5 sentences) describing the issue._  
Detail in https://github.com/OData/WebApi/issues/813
### Assemblies affected

7.0
### Reproduce steps

see issue above
### Expected result

https://github.com/OData/odata.net/blob/ODataV4-7.x/src/Microsoft.OData.Edm/Schema/EdmCoreModel.cs 

GetPrimitiveType method and GetDecimal method should work as same result.

and https://github.com/OData/odata.net/blob/ODataV4-7.x/src/Microsoft.OData.Core/UriParser/Binders/MetadataBindingUtils.cs#L88

should check it can be cast or not.

**Comment by mikepizzo** [comment]
Unable to repo in 7.4.3.

~~~~c#
            EdmModel model = new EdmModel();
            var function = new EdmFunction("ns", "TestDecimal", EdmCoreModel.Instance.GetDecimal(false));
            function.AddParameter("val", EdmCoreModel.Instance.GetDecimal(false));
            model.AddElement(function);
            var container = model.AddEntityContainer("ns", "container");
            container.AddFunctionImport("TestDecimal", function);

            string relativeUri = @"TestDecimal(val=1.1)";
            var parser = new ODataUriParser(model, new Uri(relativeUri, UriKind.Relative));
            var path = parser.ParsePath();
            Debug.Assert(path != null);
~~~

**Comment by ElizabethOkerio** [comment]
This issue could have been fixed in newer versions of the library. Reopen if still there.
