### ISSUE TITLE
"top" command not working in OData V4 version 7.0.0.0

### ISSUE THREAD

**Issue by ImGonaRot** [OData/odata.net#707]
The "$top" command is no longer working when referencing OData .Net lib 7.0
Works fine in OData .Net lib 6.15

Using "$top=x" will result in "The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is 'x'."

Microsoft.OData.ODataException

**Comment by VikingsFan** [comment]
Duplicate like https://github.com/OData/WebApi/issues/814
