### ISSUE TITLE
Unable to add vocabulary annotations to EdmEnumMember

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#71]
Cannot add vocabulary annotation to an [EdmEnumMember](https://github.com/OData/odata.net/blob/master/src/Edm/Microsoft/OData/Edm/Library/EdmEnumMember.cs), since EdmEnumMember does not implement [IEdmVocabularyAnnotatable](https://github.com/OData/odata.net/blob/master/src/Edm/Microsoft/OData/Edm/Interfaces/IEdmVocabularyAnnotatable.cs).
Additionally, if an Edm Enum member has annotations, Microsoft.OData.Core.ODataMessageReader fails when parsing the metadata document with an unexpected annotation exception.

**Comment by MrTomWhite** [comment]
:+1: 
This would be a great thing to fix. It'd be wonderful to add `Core.Description` Annotations to enumerations and their members in metadata documents.

**Comment by LaylaLiu** [comment]
Checked in by https://github.com/OData/odata.net/pull/96
