### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.OData.Edm.Library.EdmConstants'

### ISSUE THREAD

**Issue by abatishchev** [OData/odata.net#711]
I have a unit test to validate ODataConventionModelBuilder sanity:

``` csharp
[TestMethod]
public void Builder_ValidateModel_Should_Not_Throw_Exception()
{
    // Arrange
    var config = new HttpConfiguration();
    var builder = ODataConfig.CreateBuilder(config);
    var model = builder.GetEdmModel();

    // Act
    // Assert
    builder.ValidateModel(model);
}

public static class ODataConfig
{
    public static ODataConventionModelBuilder CreateBuilder(HttpConfiguration config)
    {
        var builder = new ODataConventionModelBuilder(config, isQueryCompositionMode: true);
        // builder.EntitySet<...>.EntityType.HasKey(...);
        return builder;
    }
```

After updating to Microsoft.OData.Edm version 7.0.0 it stopped working, now throws an exception:

> System.TypeInitializationException: The type initializer for 'System.Web.OData.Builder.ODataModelBuilder' threw an exception. ---> System.TypeLoadException: Could not load type 'Microsoft.OData.Edm.Library.EdmConstants' from assembly 'Microsoft.OData.Edm, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by RaviDesai** [comment]
Yup.  Having this same problem when building an OData Core application using Visual Studio code on a Macintosh.

**Comment by carathorys** [comment]
We have the same issue here, do you guys have a workaround?

**Comment by RaviDesai** [comment]
None.  6.5 doesn't have the issue.  But it isn't the latest either.

**Comment by tadmcclellan** [comment]
Any ideas here?

**Comment by Roman-Bober** [comment]
got similar issue , when upgraded to Microsoft.OData.Edm.dll 7.0.0
Are there any workarounds, fixes for this?

CS1684: Warning as Error: Reference to type 'Microsoft.OData.Edm.Annotations.IEdmValueAnnotation' claims it is defined in '\Microsoft.OData.Edm.7.0.0\lib\portable-net45+win8+wpa81\Microsoft.OData.Edm.dll', but it could not be found

**Comment by abatishchev** [comment]
The only viable solution is to upgrade all OData related packages in the same time, don't end up with partial upgrade, that's exactly what causes this exception. Either NuGet is incapable to enforce this or NuGet's capabilities weren't leveraged in the right way.

**Comment by Roman-Bober** [comment]
I have upgraded Microsoft.OData.Core.dll, Microsoft.OData.Edm.dll and Microsoft.Spatial.dll to 7.0.0.0, still getting errors , tried to look for Microsoft.OData.Client.dll 7.0.0 - no such version yet
Could be I miss more dlls to upgrade?

**Comment by abatishchev** [comment]
Do you use WebApi.OData by chance? Upgrade it to 5.7 and Microsoft.Data.OData to 5.8.2, iirc.

**Comment by daviburg** [comment]
Beware implicit references to System.Web.OData i.e you use another Nuget which in turn loads an old version of System.Web.OData which tries to find a type in Microsoft.OData.* that has changed location or name with the big V4 breaking change. I was able to locate it with full fusion logging of all assembly resolutions (even the one that pass) to figure out who was trying to find a type that no longer exists.

**Comment by madansr7** [comment]
this should not be an issue anymore since we released the 7.x for OData Client. If this still an issue, please open a new bug.
