### ISSUE TITLE
V3Client - High CPU when loading to DataServiceCollection<>

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#713]
_Loading many entities into a DataServiceCollection<> is very slow._  
### Assemblies affected

_V3Client._  
### Reproduce steps

_Load many entities into a DataServiceCollection<>._  
### Expected result

_Performance should not decrease._  
### Actual result

_The performance decreases the more entities you have loaded._  
### Additional details

_This is already reported as part of #662. I created this separate issue report to track it as a separate issue. The issue is due to a check for Contains() during insert/adding an entity. Contains() on an ObservableCollection is very ineffective._

**Comment by LaylaLiu** [comment]
Leave a comment
