### ISSUE TITLE
V3Client - High CPU when adding an entity to a tracking DataServiceCollection<> 

### ISSUE THREAD

**Issue by uffelauesen** [OData/odata.net#714]
_When a DataServiceCollection<> is constructed with TrackingMode.AutoChangeTracking (the default) adding entities is significantly slower than adding entities to a None tracking DataServiceCollection._  
### Assemblies affected

_V3Client._  
### Reproduce steps

_Compare the performance of adding many entities to an auto tracking and a non tracking DataServiceCollection<>._  
### Expected result

_The performance should be comparable._  
### Actual result

_Adding many entities to a tracking DataServiceCollection<> is significantly slower._  
### Additional details

_This issue was originally reported as part of #662. I have created this separate issue report so we can track it separately. The issue is due to the BindingGraph doing an ineffective check for existence of an Edge_

**Comment by robward-ms** [comment]
Appears to be addressed by PR #710. If this is not the case, feel free to re-open.
