### ISSUE TITLE
V3Client: Any plans for PCL profile 111?

### ISSUE THREAD

**Issue by object** [OData/odata.net#716]
ODataLib V4 has been recently updated to support PCL profile 111 (and profile 259 was deprecated). It would be great to do the same with ODataLib V3. Event though it will be a major version upgrade, the change itself is rather formal and should not be very difficult.

**Comment by xuzhg** [comment]
We are not actively developing OData V3 libraries and put all effort to ODaa v4 stack and move to .NET Standard. 
Please update to use OData V4 library and please let us know if you  have any issue to update to OData V4? Thanks.

**Comment by object** [comment]
The library has been ported to .NET Standard, so this issue is no longer relevant.
