### ISSUE TITLE
Support relative context URLs

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#717]
ODataLib should support reading and writing relative context URLs. 

_[4.5.1 Annotation odata.context](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata03/os/odata-json-format-v4.0-errata03-os-complete.html#_The_odata.metadata_Annotation_1)_

_The odata.context annotation returns the context URL (see [OData-Protocol]) for the payload. This URL can be absolute or relative._

**Comment by ElizabethOkerio** [comment]
fixed by this pr : https://github.com/OData/odata.net/pull/2216
