### ISSUE TITLE
Unable to create an unbound function that returns a complex type

### ISSUE THREAD

**Issue by unlimited071** [OData/odata.net#719]
Unable to create an unbound function that returns a complex type.  

### Assemblies affected
* OData .Net lib 6.15

### Reproduce steps
* Running the app and trying to consume an endpoint, any endpoint.

### Expected result
* When consuming the endpoint ~/odata/Company.Functions.GlobalStats the method GetGlobalStats of the GlobalController class should be executed.

### Actual result
* The application produces the following error:
> An exception of type 'System.InvalidOperationException' occurred in System.Web.OData.dll but was not handled in user code.

> Additional information: The path template 'Company.Functions.GlobalStats' on the action 'GetGlobalStats' in controller 'Global' is not a valid OData path template. Resource not found for the segment 'Company.Functions.GlobalStats'..

### Additional details
The complete details can be found on the following stackoverflow [question](https://stackoverflow.com/questions/40518545/odata-v4-resource-not-found-for-the-segment).

**Comment by xuzhg** [comment]
@unlimited071 

Should call the unbound function using the function name directly after the service root. Don't use the namespace. 

namespace-qualified function call is for bound function call.

**Comment by robward-ms** [comment]
Question is answered here and stackoverflow.
