### ISSUE TITLE
[7.0.0] An incompatible primitive type 'Edm.Int32[Nullable=False]' was found for an item that was expected to be of type 'Edm.String[Nullable=True]

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#724]
See detail at: https://github.com/OData/WebApi/issues/855

**Comment by AlanWong-MS** [comment]
Per comment in #855 by "tyrius02": Issue OData/odata.net#724 is a duplicate of OData/odata.net#706. The latter contains a bit more detail.

**Comment by ElizabethOkerio** [comment]
fixed by thos pr: https://github.com/OData/odata.net/pull/756
