### ISSUE TITLE
Odata Client doe not exists in visual studio add new item

### ISSUE THREAD

**Issue by Alikhll** [OData/odata.net#726]
I've downloaded odata v4 client code generator in visual studio Extensions and Updates but after install that and restart vs I can't find OData client t4 !
I'm using vs 2015 update 3

**Comment by AlanWong-MS** [comment]
Hi @Alikhll, from [this set of directions](https://blogs.msdn.microsoft.com/odatateam/2014/03/11/tutorial-sample-how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class/), I was able to find and use the Client Code Generator in my Visual Studio 2015 Update 3. Can you give that a try? Thanks.

**Comment by Uriahas** [comment]
I also cannot find this item in the Add New Item dialog. I did everything exactly as described in the [How to use OData Client Code Generator](https://blogs.msdn.microsoft.com/odatateam/2014/03/11/tutorial-sample-how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class/) article.

As a workaround, I am adding the [odata.net/src/CodeGen/ODataT4CodeGenerator.tt](https://github.com/OData/odata.net/blob/master/src/CodeGen/ODataT4CodeGenerator.tt) and [odata.net/src/CodeGen/ODataT4CodeGenerator.ttinclude](https://github.com/OData/odata.net/blob/master/src/CodeGen/ODataT4CodeGenerator.ttinclude) files to the project. After changing the MetadataDocumentUri and NamespacePrefix options as described in the tutorial, I save changes and have required classes generated.

**Comment by gathogojr** [comment]
OData V4 Client Code Generator no longer supported. OData Connected Service Visual Studio extension used in it's place
