### ISSUE TITLE
Fix NullReferenceException when call ODataUriParser.ParsePath() in 6.15.* NuGet Package

### ISSUE THREAD

**Issue by ngRevan** [OData/odata.net#730]
When there is function which returns an entity type, if the function does not specify EntitySetPath, the ODataUriParser.ParsePath() will throw NullReferenceException. #592 

The issue is fixed in the OData .Net lib 6.15 and 7.0 source code but is only contained in 7.0 NuGet Package and not in 6.15.

**Comment by robward-ms** [comment]
6.16 and 6/17 have been released, let us know if you don't see the fix in those packages.
