### ISSUE TITLE
Insert entry with media resource

### ISSUE THREAD

**Issue by sschutten** [OData/odata.net#733]
I'm trying to insert a new entry to my OData service, which is an item that requires a media resource. I'm not able to figure out how to do that using the ODataClient.

I tried Simple.OData.Client v4.24.0.1, but it doesn't seem to support media resources. At least I couldn't find the Media() method on the IBoundClient.
Currently I'm trying Simple.OData.Client v5.0.0-alpha2, but I can't figure out how to combine an InsertEntryAsync with Media().

Below if a snippet of my code. It's using the SharePoint listdata.svc OData service btw, which appears to be supporting OData V3.
```
folder = await client
    .For<MyDocument>()
    .Set(new {
        ContentTypeID = "0x012000E63BCA9D2BE9454E94DF0F0C88B141E9",
        ContentType = "Folder",
        Name = "Folder 1",
        Path = "/MyList"
    })
    .InsertEntryAsync();
```
This code throws the exception:
`An entry with type 'Microsoft.SharePoint.DataService.DmsDocumentsWithVersionsItem' was found without a media resource, but this entity type is a media link entry (MLE). When the type is an MLE entity, the entry must have a media resource.`  

I can't change it to use Media().SetResourceStream(...) as that would translate in an update (PUT) and I need to create the item first.

I've searched for samples but so far came up short. I also looked through the unit tests on GitHub. Is this possible to do and if so, what would the syntax be?

**Comment by markdstafford** [comment]
This does not appear to be an issue with the Microsoft.OData.Client, so for now we will close this issue and we recommend opening an issue in the Simple.OData repository: https://github.com/object/Simple.OData.Client/issues. If for some reason we have misunderstood the issue, please leave a comment and reopen the issue.
