### ISSUE TITLE
mapping navigation collection

### ISSUE THREAD

**Issue by maiselsernan** [OData/odata.net#737]
Hi,
i'm trying to request this:

http://localhost/MyProject/reseller?$expand=Suppliers

and i get this error:

"Missing map from System.Web.OData.Query.Expressions.SelectExpandBinder+SelectAllAndExpand`1[MyProject.DataModel.Models.Reseller] to MyProject.Dto.ResellerDto. Create using Mapper.CreateMap<SelectAllAndExpand`1, ResellerDto>.",

the metadata looks like this:

<EntityType Name="Reseller">

                <Key>

                    <PropertyRef Name="Id" />

                </Key>

                <Property Name="Id" Type="Edm.Int32" Nullable="false" />

                <Property Name="Name" Type="Edm.String" />

                <Property Name="EmailAddress" Type="Edm.String" />

                <Property Name="PhoneNumber" Type="Edm.String" />

                <NavigationProperty Name="Suppliers" Type="Collection(MyProject.DataModel.Models.Supplier)" />

            </EntityType>

the mapping looks like this:
 var builder = new ODataConventionModelBuilder(config);

            var reseller = builder.EntitySet<Reseller>("resellerDb");
            reseller.EntityType.HasKey(i => i.Id);
            //
            var entityReseller = builder.EntitySet<ResellerDto>("reseller");
            entityReseller.EntityType.HasKey(i => i.Id);

            var supplier = builder.EntitySet<Supplier>("supplierDb");
            supplier.EntityType.HasKey(i => i.Id);
            //
            var entitySupplier = builder.EntitySet<SupplierDto>("supplier");
            entitySupplier.EntityType.HasKey(i => i.Id);

and 
 Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Customer, CustomerDto>();
                cfg.CreateMap<CustomerDto, Customer>();
                cfg.CreateMap<Supplier, SupplierDto>();
                cfg.CreateMap<SupplierDto, Supplier>();
                cfg.CreateMap<Reseller, ResellerDto>();
                cfg.CreateMap<ResellerDto, Reseller>();
    
            });
            Mapper.AssertConfigurationIsValid();

what i missing?

**Comment by patrickmichalina** [comment]
What does your controller look like? Are you projecting to the Dto from the Entity?

**Comment by maiselsernan** [comment]
Thanks for your unswer.
have have base controller that looks like this:
   [EnableQuery]
        public virtual async Task<IHttpActionResult> Get(ODataQueryOptions<TEntity> queryOptions)
        {
           // try to look for route data that begines with "key" - this means that the CompositeKeyRoutingConvention has added the key columns
            // this is needed in order to supoport generic GET for single entity according to composite key
            var keys = RequestContext.RouteData.Values.Where(i => i.Key.StartsWith("key")).ToList();
            if (keys.Count > 0)
            {
                var q = GetQueryAccordingToRouteKeyData(keys);
                var modifiedQuery = queryOptions.ApplyTo(q);
                SingleResult<TDto> dto = SingleResult.Create(modifiedQuery.ProjectTo<TDto>().ToList().AsQueryable());
                return Ok(dto);
            }

            // in case no entity key specified, return list
            List<TDto> dtos = queryOptions.ApplyTo(EntitiesCtx.Repository<TEntity>().AsQueryable()).ProjectTo<TDto>().ToList();
            return Ok(dtos);
        }

**Comment by maiselsernan** [comment]
the pasted code don't look right.
here is an attached file:
[new  6.txt](https://github.com/OData/odata.net/files/668300/new.6.txt)

**Comment by xuzhg** [comment]
close it. Please file new issue if you think it's not fixed yet.
