### ISSUE TITLE
Annotations being misinterpreted as duplicate with the OData Client

### ISSUE THREAD

**Issue by aveyrier** [OData/odata.net#739]
The OData client cannot serialize a payload that contains an instance annotation on an entity (let's say `@foo.bar: true`) and the same instance annotation on one of its attributes (`name@foo.bar: true` for instance). An ODataException is thrown with the message "Multiple annotations with the name 'foo.bar' were detected. In OData, duplicate annotations are not allowed".

### Assemblies affected
Microsoft.OData.Client 6.15.0 and below

### Reproduce steps
You can see a repo reproducing this error here: [https://github.com/aveyrier/ODataClientAnnotationIssue](https://github.com/aveyrier/ODataClientAnnotationIssue).

These are the steps to reproduce it:

1. Create an OData endpoint that return entities with an instance annotation on the entity (`@foo.bar: true`) and the same instance annotation for one or all of its attributes (`name@foo.bar: true`).
2. Make sure that the Web API respond with the header `Preference-Applied: odata.include-annotations="*"` when the request contain the header `Prefer: odata.include-annotations="*"` (see section [8.2.8.4 Preference odata.include-annotations](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc370126018) of the OData protocol).
3. Create a client project containing a DataServiceContext based on this OData endpoint.
4. Instantiate the DataServiceContext and specify to set the header `Prefer: odata.include-annotations="*"` on the request messages (`container.SendingRequest2 += (sender, e) => e.RequestMessage.SetHeader("Prefer", "odata.include-annotations=\"*\"");`).
5. Send a query on the OData endpoint (e.g. `container.Products.ToList()`).

### Expected result
The client materializes the entities returned by the Web API and calling the `DataServiceContext.TryGetAnnotation` method on the entity return the desired annotation (e.g. `container.TryGetAnnotation(products.First(), "foo.bar", out bool annotation);` => `annotation == true`).

### Actual result
The client throws an exception when it receives the response:

    System.InvalidOperationException occurred
      HResult=0x80131509
      Message=Multiple annotations with the name 'foo.bar' were detected. In OData, duplicate annotations are not allowed.
      Source=Microsoft.OData.Client
      StackTrace:
       at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()
       at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryStartReadFeedOrEntry()
       at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
       at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__0.MoveNext()
       at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
       at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
       at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
       at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
       at Microsoft.OData.Client.MaterializeAtom.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at FixAnnotationIssue.Program.Main(String[] args)

    Inner Exception 1:
    ODataException: Multiple annotations with the name 'foo.bar' were detected. In OData, duplicate annotations are not allowed.

### Additional details
If two attributes have the same instance annotation (e.g. `code@foo.bar: true` and `name@foo.bar: true`) then the entity is correctly materialized. So I think that the OData client misreads the entity instance annotation as an attribute instance annotation (or the other way around) and considers the annotations to be duplicates.

**Comment by mikepizzo** [comment]
@robward-ms: Any chance this is addressed by your fix in https://github.com/OData/odata.net/pull/756?

**Comment by odero** [comment]
Needs verification to check whether this was fixed by https://github.com/OData/odata.net/pull/740

**Comment by paulodero** [comment]
@odero Issue was fixed in Microsoft.OData.Client 7.6.2
