### ISSUE TITLE
Please provide pdb and symbol server support in nuget releases

### ISSUE THREAD

**Issue by phatcher** [OData/odata.net#743]
Can't debug an error as I can't step into the OData.Core code and can't produce a version for myself as it is signed.

For bonus points use the something like https://github.com/ctaggart/SourceLink to link directly to the source in github.

### Assemblies affected
 OData .Net lib 6.x

### Reproduce steps
Try debugging into the code

### Expected result
Be able to step into the code

### Actual result
Steps over the code, can't see underlying reason for exceptions

**Comment by gathogojr** [comment]
Symbols package currently published to nuget. For current Microsoft.OData.Core 7.10.0 available [here](https://www.nuget.org/api/v2/symbolpackage/Microsoft.OData.Core/7.10.0)
