### ISSUE TITLE
Support for SSL certificate

### ISSUE THREAD

**Issue by abiratsis** [OData/odata.net#748]
Does odata.net support the certificate for SSL connections? I need to connect to a web service which provides odata through certificates. I tried to attach my certificate but I couldn't find an accessible  point for the underlying HTTPWebRequest

**Comment by AlexKasaku** [comment]
Any updates for this? Is it possible to attach a client certificate when making requests?

**Comment by AlexKasaku** [comment]
It looks like you can do it this way, would this be the recommended method?

```
context.SendingRequest2 += (sender, eventArgs) =>
{
   var requestMessage = eventArgs.RequestMessage as HttpWebRequestMessage;

   // Update client certs here   
   requestMessage.HttpWebRequest.ClientCertificates.Add(cert);
};
```

**Comment by abiratsis** [comment]
I never tried this solution Alex. I guess you have to test it by your own.

Good luck

**Comment by AlexKasaku** [comment]
No worries @abiratsis , was more a question for the repo team! It does seem to work though.

**Comment by KenitoInc** [comment]
It seems a working solution was provided. Closing this issue.
