### ISSUE TITLE
EnableCaseInsensitive HttpConfig extension was removed in `System.Web.OData` 6.0.0

### ISSUE THREAD

**Issue by v17al** [OData/odata.net#750]
When upgrading my Nuget packages, it seems that the case insensitive functionality described http://odata.github.io/WebApi/#06-01-custom-url-parsing is removed when moving from `System.Web.OData` 5.9.1 => 6.0.0.

This doesn't seem to be intended, as the documentation continues to describe this functionality, and there was no mention of this change in the release notes.

**Comment by gathogojr** [comment]
Issues references outdated OData libraries
