### ISSUE TITLE
OData 7.0.0 libs do not support a array of untyped primitive values

### ISSUE THREAD

**Issue by abkmr** [OData/odata.net#759]
OData 7.0.0 libs do not support a array of untyped primitive values in an array.

### Assemblies affected
OData .Net lib 7.0.0, WebApi.OData 6.0.0

### Reproduce steps
Create Edm.Model with Collection[type]

Request URL: http://alexumoca5/org1/api/data/v8.2/FullTextSearchKnowledgeArticle
Request Method: POST

   "SearchText" : "",
    "UseInflection" : false,
    "RemoveDuplicates" : false,
    "StateCode" : 3,
    "QueryExpression" : {
        "Distinct" : false,
        "NoLock" : false,
        "PageInfo" : {
            "PageNumber" : 1,
            "Count" : 10,
            "ReturnTotalRecordCount" : true,
            "PagingCookie" : ""
        },
        "LinkEntities" : [],
        "Criteria" : {
            "FilterOperator" : "And",
            "Conditions" : [{
                    "EntityName" : "knowledgearticle",
                    "AttributeName" : "languagelocaleid",
                    "Operator" : "Equal",
                    **"Values" : ["56940B3E-300F-4070-A559-5A6A4D11A8A3" 123 ]**
                }
            ],

### Expected result
Client should be able to provide multiple primitive types in the Values array

### Actual result
Exception since the ODataResourceSetDeserializer raises exception.
    "error" : {
        "code" : "0x0",
        "message" : "A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a resource set; however, a node of type 'StartObject' or 'EndArray' was expected.",
        "innererror" : {
            "message" : "A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a resource set; however, a node of type 'StartObject' or 'EndArray' was expected.",
            "type" : "Microsoft.Crm.CrmHttpException",
            "stacktrace" : "   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInputParameters(ModelStateDictionary controllerModelState)\r\n   at Microsoft.Crm.Extensibility.OData.ActionController.PostUnboundAction(String operationName, ODataUntypedActionParameters parameters)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, 

### Additional details
Edm.Untyped support does not exist fully in WebApi.OData, though partial support is there in ODL libs.

**Comment by odero** [comment]
Addressed in PR #894
