### ISSUE TITLE
Add Target and Details properties to ODataError

### ISSUE THREAD

**Issue by lencharest** [OData/odata.net#76]
OData v4 allows for `target` and `details` properties on an error response. The ODataError class should provide parity with the v4 error specification. Please add `Target` (type: `String`) and `Details` (type: `IEnumerable<ODataErrorDetail>`) properties, _or_ unseal the ODataError class.

**Comment by congysu** [comment]
@lencharest Thanks for reporting this issue.  What is your user scenario?

**Comment by lencharest** [comment]
My scenario is simply that I've written an OData-based service and I want to send rich(er) error responses. In practice, I'm using `System.Net.Http.HttpRequestMessage.CreateErrorResponse` to set the `Response` property on a `System.Web.Http.Filters.HttpActionExecutedContext`, and `CreateErrorResponse` takes an `ODataError` instance as an argument.

**Comment by lencharest** [comment]
I should also mention that my service depends on 3rd-party OData-based services (e.g., Azure Table Storage). When my service receives an error response from one of its dependencies, I want to propagate some of the error info from the 3rd-party service by setting `target` and `details` in my error response.

**Comment by congysu** [comment]
PR https://github.com/OData/odata.net/pull/364
