### ISSUE TITLE
microsoft.data.edm package 5.8.2 has file version 5.8.1

### ISSUE THREAD

**Issue by SeanFeldman** [OData/odata.net#765]
Discrepancy between nuget version and file version

### Assemblies affected

Microsoft.Data.Edm.dll & microsoft.data.edm.5.8.2.nupkg

### Reproduce steps
Download and use nuget package

### Expected result
Expected to see version 5.8.2.x

### Actual result
Version 5.8.1

```xml
 <Reference Include="Microsoft.Data.Edm, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Data.Edm.5.8.2\lib\net40\Microsoft.Data.Edm.dll</HintPath>
```

**Comment by xuzhg** [comment]
I think it's already fixed. See the latest version: https://www.nuget.org/packages/Microsoft.Data.Edm/5.8.4

Please let us know if you have further concern.
