### ISSUE TITLE
Support VS2017 with the client code Generator

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#768]
The latest version (v2.4.0) OData V4 Client Code Generator supports VS 2015. 
Along with the VS2017 GA,  do we need to support it?

### Assemblies affected
OData .Net Client lib

### Expected result
Support VS 2017 with OData V4 client code Gen

### Actual result
The latest version (v2.4.0) OData V4 Client Code Generator supports VS 2015.

**Comment by TonyHenrique** [comment]
I newer used ODATA before, now with Visual Studio 2017 I tryed to start on ODATA but discovered there is no support yet.
I plan to use a WPF client consuming ODATA from ASP.Net + AZURE SQL

**Comment by MAOliver** [comment]
I'm going to assume that this should be resolved with #731 as well (which is marked next 3 months currently) - just fyi.

**Comment by AlanWong-MS** [comment]
Code Gen supports VS2015 and VS2017 with ODL 7.5.0.

**Comment by weitzhandler** [comment]
@AlanWong-MS Related: https://github.com/OData/odata.net/issues/1485.
