### ISSUE TITLE
Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6

### ISSUE THREAD

**Issue by per3ian** [OData/odata.net#772]
I am trying to add Microsoft.Spatial": "7.0.0", to my class library and I got this error :

Errors in F:\Projects\Gits\xProject\src\xViewModels\xViewModels.xproj
    Package Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Spatial 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
Errors in F:\Projects\Gits\xProject\src\xServices\xServices.xproj
    Package Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Spatial 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
log  : F:\Projects\Gits\xProject\src\xProject\xProject.xproj
    One or more packages are incompatible with .NETStandard,Version=v1.6.
Errors in F:\Projects\Gits\xProject\src\xEntities\xEntities.xproj
    Package Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Spatial 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
Errors in F:\Projects\Gits\xProject\src\xDataLayers\xDataLayers.xproj
    Package Microsoft.Spatial 7.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Spatial 7.0.0 supports: portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
log  : Restore completed in 12478ms.

**Comment by AlanWong-MS** [comment]
Hi @per3ian , thank you for the question. The Microsoft.Spatial 7.0.0 that you tried was compatible with only PCL Profile 111 and not .NET Standard 1.6. We recently updated the [repository](https://github.com/OData/odata.net/tree/ODataV4-7.x) to compile against with .NET Standard 1.1 for broader compatibility and will shortly follow up with the release of the NuGet package. If your app allows it, you can try building against .NET Standard 1.1 or you can port the library to .NET Standard 1.6 locally.

Thanks!
