### ISSUE TITLE
System.TypeLoadException: Could not load type Microsoft.OData.Core.ODataPayloadKind from assembly Microsoft.OData.Core

### ISSUE THREAD

**Issue by rschuerer** [OData/odata.net#783]
After updating from version 6.15 to Microsoft.OData.Core, Microsoft.OData.Edm and Microsoft.Spatial to version 7.0.0 our app is running into this exception:

System.TypeLoadException: Could not load type Microsoft.OData.Core.ODataPayloadKind from assembly Microsoft.OData.Core 7.0.0

I updated also all other OData related nugets to latest release version

Microsoft.OData.Client 6.15
Microsoft.Data.OData 5.8.2

The project is an UWP app

Maybe related to issue #711

**Comment by gathogojr** [comment]
Shouldn't be an issue for in the current Microsoft.OData.Core 7.10.0 package
