### ISSUE TITLE
OData v4, Query Options for Initial client query to Bound Functions is carried over to the next query

### ISSUE THREAD

**Issue by mikitaka** [OData/odata.net#794]
When calling Controller bound functions from Native client and we assign Container.Controller.Function() to a local query variable and the query execute the first time, that query carries over the queryoptions (such as $count) to the next subsequent queries.

1st Query : query.Count();
2nd Query: query.Top(10); // here the query variable remembers the first Count() and produces .../$count?$orderby=PK. By right, the second query should be only .../$orderby=PK

This only happens when we use a local variable assigned with the original query.

### Assemblies affected
OData .Net lib 7.0.0  - server side
OData 6.15 - client side

### Reproduce steps

```
//Client Side using T4 template and container
Container dataService = new Container(App.ODataUrl);
var myquery = dataService.Classes.GetTree(101, 728544);
var c = myquery.Count(); // after this query, the variable myquery always carry $count options
var list = myquery.OrderBy(x => x.PK).ToList(); // this will result in /$count?$orderby=PK

```
### Expected result
Every query should be clean without remembering the previously issued query options

### Actual result
A local query variable remembers the query issued before.
This results in strange query uri such as 
http://localhost:55432/odata4/Classes/JEdixOData4Service.GetTree(FKTenant=101,FKParent=728544)**/$count?$top=1**

**Comment by mikitaka** [comment]
To be clearer, linq query is handled properly, just that when it translates to odata uri service string, the previous string is carried over to the next query, resulting in accumulating uri string.

1st time /$count
2nd time /$count?$orderBy=PK ... This is strange queryoption string

See attached.

[ODataClientTest201704.zip](https://github.com/OData/odata.net/files/921670/ODataClientTest201704.zip)
[ODataServerTest201704.zip](https://github.com/OData/odata.net/files/921671/ODataServerTest201704.zip)

**Comment by Benjamin-Berry** [comment]
I'm seeing this with Microsoft.OData.Client 6.17.0
