### ISSUE TITLE
[Nuget] netstandard support

### ISSUE THREAD

**Issue by genusP** [OData/odata.net#795]
Description for package [Microsoft.OData.Core](https://www.nuget.org/packages/Microsoft.OData.Core/) 
 wrote .NET Platform Standard 1.1 is target framework.
After install this package, in package cache I see folder only profile111:
%USERPROFILE%\.nuget\packages\microsoft.odata.core\7.1.1\lib\portable-net45+win8+wpa81

**Comment by xiaoxin1983** [comment]
+1

unsupport .net core 1.1, just portable-net45+win8+wpa81 like v7.0.0

**Comment by robertmclaws** [comment]
-1

We need to leave .NET Standard support, but fix the package so it works properly.

**Comment by AlanWong-MS** [comment]
This has been resolved in 7.2.0. .NET Standard 1.1 has been re-added. Thanks!
