### ISSUE TITLE
Conflicting Microsoft.Data.Services and Microsoft.Data.Services.Client 5.8.2

### ISSUE THREAD

**Issue by daghb** [OData/odata.net#797]
Microsoft.Data.Services.Client v5.8.2 is not available if the project is using Microsoft.Data.Services in the same project due to inconsistent versions.

### Assemblies affected
Microsoft.Data.Services.Client v5.8.2
Microsoft.Data.Services v5.8.1

### Reproduce steps
Reference both Microsoft.Data.Services.Client v5.8.1 and Microsoft.Data.Services v.5.8.1 in the same project. Try to upgrade Microsoft.Data.Services.Client to 5.8.2. As Microsoft.Data.Services is not available in v5.8.2, this fails.

### Expected result
Upgrading should be possible without errors.

### Actual result
Unable to resolve dependencies. 'Microsoft.Data.Services.Client 5.8.2' is not compatible with 'Microsoft.Data.Services 5.8.1 constraint: Microsoft.Data.Services.Client (= 5.8.1)'. As Microsoft.Data.Services uses Microsoft.Data.Services.Client 5.8.1, this fails.

**Comment by AdReTos** [comment]
Good Day
Any solution to this problem, or suggestion?

**Comment by daghb** [comment]
@AdReTos 
Looks like the new v5.8.3 solved this problem
