### ISSUE TITLE
Make ODataUriParser extendable to parse apply and other extensions: e.g., Aggregation

### ISSUE THREAD

**Issue by bixu-ms** [OData/odata.net#8]
In order to extend ODataUriParser to parse apply specified in [OData Extension for Data Aggregation](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html), some classes and methods need to be made public.
1. The ODataQueryOptionParser propery in ODataUriParser.
2. The intern class ODataUriParserConfiguration.
3. The states in ODataQueryOptionParser, like TargetNavigationSource, TargetEdmType, QueryOptions etc.
4. Some internal methods used to parse filter expression.

**Comment by congysu** [comment]
Related issue: https://github.com/OData/WebApi/issues/70

**Comment by rwb196884** [comment]
What's the current status on this?
