### ISSUE TITLE
Supporting Primitive Type Casts

### ISSUE THREAD

**Issue by ysanghi** [OData/odata.net#801]
*Short summary (3-5 sentences) describing the issue.*  
It will be nice to have the ability to do cast properties as primitive types in $select, $filter, $order by. Today you can only use non primitive types in the type segment.

### Assemblies affected
OData.Net 7.x

### Reproduce steps
CurrentCollections('id')/Items?$select=Prop1/Edm.String&$filter=Prop2/Edm.String%20eq%20'sdb'

### Expected result
Found a path with multiple navigation properties or a bad complex property path in a select clause. Please reword your query such that each level of select or expand only contains either TypeSegments or Properties.

### Actual result
It work as normal type segment

**Comment by mikepizzo** [comment]
Addressed in PR #848.
