### ISSUE TITLE
Microsoft Graph NextLink Not Working

### ISSUE THREAD

**Issue by Wendytay** [OData/odata.net#812]
Customer has problems using the server-side paging for @odata.nextlink to fetch the next page of data. Posted on StackOverflow May 18, 2017. 0 votes, viewed 21 times as of May 19, 2017.

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  

### Reproduce steps
see http://stackoverflow.com/questions/44036262/microsoft-graph-nextlink-not-working

### Expected result
*What would happen if there wasn't a bug.*  

### Actual result
*What is actually happening.*  

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by mikepizzo** [comment]
This does not appear to be an issue in our stack.  I followed up on the StackOverflow issue.
