### ISSUE TITLE
About Versioning

### ISSUE THREAD

**Issue by am11** [OData/odata.net#820]
On NuGet.org, if we search for OData, we find: https://www.nuget.org/packages/Microsoft.Data.OData/ that states:

> ### ODataLib for OData V1-3 5.8.2

Questions:

* What does V1-3 signify?
* How does `5.8.2` compare with [ODataV4-6.x](https://github.com/OData/odata.net/tree/ODataV4-6.x) and [ODataV4-7.x](https://github.com/OData/odata.net/tree/ODataV4-7.x) branches?
* How does the release tag: <kbd>[7.2.0](https://github.com/OData/odata.net/releases/tag/7.2.0)</kbd> compare with all of the above?

Are there plans to unify all these varied versionings? For instance, using the popular http://semver.org/.

Lastly, it would be very helpful if you could provide links to your package at NuGet.org in each release notes for easy / one-click discoverability. For example, I couldn't find <kbd>[7.2.0](https://github.com/OData/odata.net/releases/tag/7.2.0)</kbd>  anywhere on NuGet which provides the support for .NET Standard 1x.

**Comment by robward-ms** [comment]
Sorry for the confusion, here are a few answers:

V1-3 is the protocol version.  You can find more information about protocol versions here: http://www.odata.org/documentation/

5.8.2 is an ODataLib library version number. The Nuget package "ODataLib for OData V1-3" has 5.8.2 as it's latest version. The code for this version can be found here: https://github.com/OData/odata.net/tree/maintenance-5.x

OData V4-6.x and V4-7.x are both implementation of the V4 protocol. The Nuget package for both 6.x and 7.x can be found here (there are actually  3 Nuget packages but this one is dependent on the other 2):  https://www.nuget.org/packages/Microsoft.OData.Core/

The ODataV4-6.x and ODataV4-7.x branches hold the code for the ODataLib implementations for 6.x and 7.x receptively. However, we recently updated the branch name in an attempt to make this more clear; you can now find 6.x in https://github.com/OData/odata.net/tree/maintenance-6.x and 7.x in https://github.com/OData/odata.net/tree/master. The Readme for this project describes the branches.

The 7.2.0 tag is a marker for the code as of the 7.2 release of the ODataLib Nuget packages. You can find its Nuget package here: https://www.nuget.org/packages/Microsoft.OData.Core/

Thanks for the suggestions!
