### ISSUE TITLE
What happened to IUpdatable in system. Data Services

### ISSUE THREAD

**Issue by AdReTos** [OData/odata.net#831]
In a project I use the interface System.Data.Services.IUpdatable, when upgrading to the version 5.8.2, does not install Microsoft.Data.Services, I can do or I have to use an earlier version ?

**Comment by xuzhg** [comment]
@robertmclaws Would you please share your input? Thanks.

**Comment by xuzhg** [comment]
@AdReTos 

[[Microsoft.Data.Services v5.8.3]](https://www.nuget.org/packages/Microsoft.Data.Services/5.8.3) was just released. Would you please help try it out and give us some feedbacks. Thanks!

**Comment by AdReTos** [comment]
Nice day @xuzhg 
Upgrade to the 5.8.3 version, and I still have the same problem, not add the reference to Microsoft. 5.8.3 or 5.8.2 Services.

**Comment by AdReTos** [comment]
I found my problem, I was using the visual option to add the package, if I do it by console works to perfection. Thank you and excuse me.

Thanks a lot @xuzhg

**Comment by xuzhg** [comment]
Never mind and welcome. 
Please feel free send us any concerns and further questions. We'd love to help.

-OData Team.
