### ISSUE TITLE
Expose additional Preference Headers

### ISSUE THREAD

**Issue by JefWight** [OData/odata.net#84]
Per the OData protocol spec, section 8.2.8, there are a handful of documented preference headers.

The library already supports parsing any preference, but this logic is kept private / internal and only exposes some of them (ReturnContent, AnnotationFilter, RespondAsync, and Wait).

It would be nice to expose the rest of the documented ones or provide access to the raw parsed values.

**Comment by piotrpMSFT** [comment]
Adding link to mentioned documentation:
http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793624

**Comment by JefWight** [comment]
I know I'm supposed to wait for issue to switch to "Accepting Pull Requests" but I submitted one anyhow.
