### ISSUE TITLE
Add compute transformation support to $apply in ODL parsers.

### ISSUE THREAD

**Issue by mtroth-microsoft** [OData/odata.net#847]
For completeness, the compute transformation should be supported in ODL's $apply parsing operations. When $compute was implemented, it was included inside of $expand but not as a transformation in $apply.

**Comment by kosinsky** [comment]
Good sample how it can be used: https://github.com/OData/WebApi/issues/793

**Comment by xuzhg** [comment]
@mtroth-microsoft @kosinsky 

It looks the similar feature is implemented in PR: https://github.com/OData/odata.net/pull/1050


I closed it. If you find any problem, please re-open it or leave your comments.
