### ISSUE TITLE
DataServiceQuery makes a "by key" request when Where clause compares just the ID, causing exception instead of empty result if the entity is not found.

### ISSUE THREAD

**Issue by fpintos** [OData/odata.net#851]
### Summary

When using an ODATA client built with the [Microsoft.OData.Client](https://www.nuget.org/packages/Microsoft.OData.Client/) package, a Where clause that just compares the id property becomes a by-key request instead of using $filter. If an entity with that id is not found, the query ends up with an exception instead of returning empty results.

### Assemblies affected

[Microsoft.OData.Client](https://www.nuget.org/packages/Microsoft.OData.Client/) 6.13.0

### Reproduce steps
Consider the following queries:
1. [http://services.odata.org/V4/OData/OData.svc/Products(-1)](http://services.odata.org/V4/OData/OData.svc/Products(-1))
2. [http://services.odata.org/V4/OData/OData.svc/Products?$filter=ID eq -1 or ID eq -2&$top=1](http://services.odata.org/V4/OData/OData.svc/Products?$filter=ID%20eq%20-1%20or%20ID%20eq%20-2&$top=1)
3. [http://services.odata.org/V4/OData/OData.svc/Products?$filter=ID eq -1&$top=1](http://services.odata.org/V4/OData/OData.svc/Products?$filter=ID%20eq%20-1&$top=1)

The first one returns 404 and the other two return 200 with empty results.
So far this is expected.

Install LINQPad and setup a connection to the reference service:
*. Setup [LINQPad](http://www.linqpad.net/).
*. Install the [ODATAv4 driver](https://github.com/meancrazy/LINQPadOData4) by clicking "Add Connection" followed by "View more drivers".
*. Add an ODATAv4 connection to http://services.odata.org/V4/OData/OData.svc/
*. Open a new LINQPad query, select the connection above and select "C# Expression" language.

Now issue the following queries:
```c#
this.Products.ByKey(-1).GetValue()
```
This correctly executes the query using the 1st URL above and the result is the expected exception, indicating the entity was not found.

```c#
this.Products.Where(x => x.ID == -1 || x.ID == -2)
```
This correctly executes the query using the 2nd URL above and the result is an expected empty list.

**However**
```c#
this.Products.Where(x => x.ID == -1)
```
This results in an unexpected exception.

### Expected result
One would expect this query to issue a $filter, like URL 3 above, in which case it would return an empty list, well within the semantics of "Where". 

### Actual results
We end up issuing a query using URL 1, which returns 404, causing the client library to throw an exception.

### Additional detail
The client library is being "too smart" and detecting that the Where expression is simply comparing the key of the entity to a value. If we change the operator in the expression to something else, for example, '<', then we end up with a corresponding $filter.

The current behavior makes the ODATA queries behave differently than ordinary queries, say, like the ones against in-memory objects. For example, the following query returns an empty list:
```c#
Enumerable.Range(0, 5).Where(_ => _ == -1)
```

This difference in behavior causes problem for code that creates the query in one place and then passes it around to functions that expect an IQueryable<T> that is supposed to return a list, because one might not be expecting such a query to return a 'not found' error.

Code that uses `Where(_ => _.Id == value)` should use `First()` or `Single()` to grab the data of that entity; that will ensure consistent semantics across all LINQ providers.

All this being said, understanding that changing the behavior of the library can be a breaking change as not all ODATA services support $filter, my suggestion would be to allow developers to configure the data context with settings that control whether $filter or by-key should be used in such cases.

A LINQPad sample that reproduces the issue can be found here: http://share.linqpad.net/2htvdi.linq

**Comment by francisharvey** [comment]
I also notice when using a string wildcard (StringKeyField == 'ABC*') in the Where query, the client is still building a By-Key ('ABC*') instead of a $filter query.

Fabio's workaround of using another operator like < doesn't work with string, I'm not sure how to make it works for now.

**Comment by premiaware** [comment]
OData v 7.6.2
I have a similar case. the follow code working only the a.ID == ID exist, if the query return empty result the exception is throw with InnerException = "NotFound", why this problem? and how can fix it?

try
                {
                    var accesso = (await (((DataServiceQuery<AnagraficaTokenAccesso>)(from a in _containerPrimario.AnagraficaTokenAccesso
                                                                                      where a.ID == ID
                                                                                      select a
                                                    ))).ExecuteAsync()).SingleOrDefault(); 
                    return accesso != null;
                }
                catch (Exception ex)
                {
                    await DisplayException(ex);
                }

**Comment by KenitoInc** [comment]
The feature will be available in the next release
