### ISSUE TITLE
Support OptionalParameter as an external annotation

### ISSUE THREAD

**Issue by mikepizzo** [OData/odata.net#855]
*PR #828 added support for optional parameters by looking for the "OptonalParameter" annotation term.  However, the code for the OnParameterElement method in CsdlDocumentParser only looks for this term applied as an in-line annotation. Although this is where it will be most common, for completeness we should also support it as an external annotation.*

### Assemblies affected

*OData.NET V7.x and greater.*

### Reproduce steps

*Apply the OptionalParameter term to a parameter as an external annotation.*
~~~xml
<Annotations Target="MyFunction/MyOptionalParameter"/>
    <Annotation Term="Org.OData.Core.V1.OptionalParameter" />
</Annotations>
~~~

### Expected result

*When read in, MyOptionalParameter should be read as an EdmOptionalParameter*

### Actual result

*When read in, MyOptionalParameter is read as a (required) EdmOperationParameter*

### Additional detail

*Probably a low priority, since I would expect that, in the bulk of cases, OptionalParameter will be applied as an inline annotation.*

**Comment by mikepizzo** [comment]
Will re-open if we get requests/scenarios for this functionality.

**Comment by xuzhg** [comment]
Fixed and Merged. Thanks.
