### ISSUE TITLE
Support parsing $skipToken and $deltaToken in ODataUri

### ISSUE THREAD

**Issue by JefWight** [OData/odata.net#86]
Per [Protocol 11.2.5.7](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398310), the reserved $skipToken parameter can be used for server driven paging.

Per [Protocol 10.17](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398282) and [JSon Format 14](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940644), $deltaToken is used in Delta Links for indicating a change state to compare to.

It would be nice if ODataUri provided easy access to this when parsed from a request, much like $skip, $top, etc.

**Comment by congysu** [comment]
Will follow up with spec, especially for $deltaToken.

**Comment by MrTomWhite** [comment]
What's the status of this issue? @congysu @LaylaLiu

**Comment by xuzhg** [comment]
It is fixed already. 
See https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Uri/ODataUri.cs#L201-L206

Thanks. Please let us know if you have further concern.
