### ISSUE TITLE
MaxExpansionDepth = 0 appears to have no effect

### ISSUE THREAD

**Issue by bdebaere** [OData/odata.net#860]
Setting the MaxExpansionDepth to 0 appears to have no effect. Testing parent-child database classes yields the same result as not setting this attribute with: ?$expand=x($levels=max). Also when trying to set $levels to a number higher than default for example the following error is given: "Value cannot be null. Parameter name: value" suggesting it is replaced when higher than default.

Setting MaxExpansionDepth to, for example, 10 solves the problem.
**EDIT: Setting to 10 solves the error from appearing, but the JSON output is still a maximum of 3 levels deep! Even though the query being executed actually fetches the necessary data (confirmed by EF query logging).**

### Assemblies affected

Latest NuGet Microsoft.AspNet.Odata.

### Reproduce steps

Create a class with parent-child relation.
Set MaxExpansionDepth of the controller to 0.
Notice that the expansion only works until the default allowed levels.

### Expected result

I would expect setting MaxExpansionDepth = 0 would allow me to go as deep as I want in a class with parent-child relation, until the parent or child is null.

At least to me this is the result I would expect when looking at the documentation and attribute property summary.

See documentation: "Cyclic navigation properties (whose target type is identical or can be cast to its source type) can be recursively expanded using the special $levels option. The value of the $levels option is either a positive integer to specify the number of levels to expand, or the literal string max to specify the maximum expansion level supported by that service."

And attribute property summary: "Gets or sets the max expansion depth for the $expand query option. To disable the maximum expansion depth check, set this property to 0."

### Actual result

MaxExpansionDepth = 0 does not disable the MaxExpansionDepth check.

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@bdebaere I moved this issue to Web API repository. See https://github.com/OData/WebApi/issues/1065
