### ISSUE TITLE
"Microsoft.OData.Client"  support for dot net core

### ISSUE THREAD

**Issue by ramygad** [OData/odata.net#866]
currently the package "Microsoft.OData.Client" does not support dotnet core.
Is this a bug ? or missing feature?

I will be very happy if someone answers me.

**Comment by morquan** [comment]
It says this in the readme...

This master branch is the developement branch for ODataV4 7.x and is now most actively iterated. It builds upon the OData 6.15 release which is now on maintenance-6.x branch and produces both PCL (Portable Class Libraries) Profile111 and .NET Standard 1.1 libraries.

**Comment by xuzhg** [comment]
@morquan Thanks for your inputs.

@ramygad Thanks your question. And we are working on the OData Client for .NET Core. I can't give you the correct release date. Once we release it, we will update the release note. Thanks a lot.

**Comment by robward-ms** [comment]
Included in 7.4.0 Beta (1), Beta2, Beta3 and RTM.
