### ISSUE TITLE
navigation property in a complex type

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#88]
OData Spec says:

9.1 Element edm:ComplexType

The edm:ComplexType element represents a complex type in an entity model. It contains zero or more edm:Property and edm:NavigationProperty elements describing properties of the complex type.

However, it doesn't support in ODL. Please investigate and fix.

**Comment by shahzorkhan123** [comment]
The scenario we are trying to solve here is for Operations to return Entities and other parameters together. Currently only ComplexTypes and Basic OData Types are supported as properties of ComplexType, and we are not able to add the Navigation Property there.

**Comment by lewischeng-ms** [comment]
EDM Part 1: Add APIs for navigation property to EdmComplexType #274

**Comment by lewischeng-ms** [comment]
EDM Part 2: Verify that model validation won't raise error on navigation properties in complex types #275 
If there is model validation error on navigation properties in complex types, we should remove that validation rule.
SWAG: 1 day (primary test code)

**Comment by lewischeng-ms** [comment]
EDM Part 3: Make CsdlWriter correctly write out navigation properties to CSDL #276
SWAG: 3 days (dev + test code)

**Comment by lewischeng-ms** [comment]
EDM Part 4: Make CsdlReader and CsdlParser correctly read out navigation properties on complex types from CSDL #277 
SWAG: 3 days (dev + test code)

**Comment by lewischeng-ms** [comment]
EDM Part 5: Verify that we can add `NavigationPropertyBinding` to an EntitySet with `Path` to the navigation property under a complex type #278
SWAG: 1 day (test code) or 3 days (dev code if fix needed)

**Comment by lewischeng-ms** [comment]
Core.UriParser Part 1: Verify that ODataPathParser can parse navigation property after complex type #279
SWAG: 3 days (test code) or 1 week (+dev code if fix needed)

**Comment by lewischeng-ms** [comment]
Core.UriParser Part 2: Change *Binder to support binding navigation property after complex type #280
Please **DO** clarify the specific scenarios we want to support at first otherwise the dev code for this issue will be very very complicated.
SWAG: 2 weeks (dev + test code)

**Comment by lewischeng-ms** [comment]
Core.Serialization Part 1: Change ODataJsonLight*Serializer to correctly serialize navigation properties in ODataComplexValue #281
SWAG: 1.5 week (dev + test code)

**Comment by lewischeng-ms** [comment]
Core.Serialization Part 2: Make sure that EntityMetadataBuilder generate correct OData links for navigation property after complex type #282
SWAG: 1 week (dev + test code if fix needed)

**Comment by lewischeng-ms** [comment]
Core.Deserialization: Change ODataJsonLight*Deserializer to correctly read out navigation properties in an ODataComplexValue #283
SWAG: 2 week (dev + test code)

**Comment by lewischeng-ms** [comment]
Client: Track in another issue #284 
May require much more work in EntityTracker, CodeGen and Materialization.
Will investigate later since this is low priority for CRM? @shahzorkhan123

**Comment by lewischeng-ms** [comment]
@congysu @shahzorkhan123 @dingeins  All the tasks required in ODL to support navigation property in complex type should need about 50 days or 10 weeks (1 week = 5 working days) per developer full-time.

**Comment by congysu** [comment]
@cbrooksmsft @markdstafford FYI.

**Comment by congysu** [comment]
Design doc: http://odata.github.io/odata.net/#07-03-NavigationProperty-In-ComplexType

**Comment by jslegers** [comment]
@congysu :

Thanks for referencing this issue on my StackOverflow question.

So I guess this means that Odata's metadata are really nothing but a single static XML file today?!

I guess that explains why there's no Json support either.

**Comment by jslegers** [comment]
I suppose this is related to the question [Fetching $metadata for a specific collection or entity with Odata web services in Microsoft Dynamics NAV 2016](http://stackoverflow.com/questions/35543769/fetching-metadata-for-a-specific-collection-or-entity-with-odata-web-services-i) that I posted on StackOverflow today?!

**Comment by mikepizzo** [comment]
I believe this is fixed in ODL 7.x.  Please reopen if there are remaining issues.
