### ISSUE TITLE
Parsing Preference headers with invalid values has unexpected results

### ISSUE THREAD

**Issue by JefWight** [OData/odata.net#92]
When Preference headers are parsed, if an invalid value was specified the result is mostly unexpected.  For example, with “wait=#”, if specified as “Prefer: wait” or “Prefer: wait=abc”, ODataPreferenceHeaders.Wait will result in an ArgumentNullException and FormatException respectively.  If “Prefer: odata.respond-async=false” is submitted, ODataPreferenceHeader.RespondAsync will actually read true.  Both of those are unexpected.  We should probably be doing some parameter validation and TryParse instead of Parse, throwing ODataExceptions indicating where the problem was or ignoring the error (depending on the expected behavior).

**Comment by congysu** [comment]
@JefWight Thanks for the findings.

**Comment by LianwMS** [comment]
submit with f32aa58
