### ISSUE TITLE
No matching Microsoft.Data.Services v5.8.2 with client

### ISSUE THREAD

**Issue by bwang2019** [OData/odata.net#924]
When my project need to reference one of DMLib v0.6, or latest Azure storage 8.2.3, together with Microsoft.Data.Services, then nuget package manager breaks, since it cannot find a version of Microsoft.Data.Services.Client that works with both.

These other packages require >v5.8.2 of Microsoft.Data.Services.Client, while Microsoft.Data.Services need a fixed version v5.8.1.

**Comment by xuzhg** [comment]
Similar to: #831, #853

**Comment by xuzhg** [comment]
@bwang2019 

[[Microsoft.Data.Services v5.8.3]](https://www.nuget.org/packages/Microsoft.Data.Services/5.8.3) was just released. Would you please help try it out and give us some feedbacks. Thanks!
