### ISSUE TITLE
License link on NuGet page does not work

### ISSUE THREAD

**Issue by henkkuli** [OData/odata.net#925]
License link on [NuGet](https://www.nuget.org/packages/Microsoft.OData.Core/) page does not work.

**Comment by xuzhg** [comment]
When I click the link named "License Info" in black circle of this picture:

![image](https://user-images.githubusercontent.com/9426627/29798512-3b596452-8c12-11e7-9913-98fc75cdb352.png)

I will be navigated to the below page:

![image](https://user-images.githubusercontent.com/9426627/29798534-6728c668-8c12-11e7-8f05-0eed904ec320.png)

Thanks your input.

**Comment by henkkuli** [comment]
Thank you! Good to know that it works now. The link was down for at least two or three weeks after I reported it here.
