### ISSUE TITLE
Updating Microsoft.Data.Services.Client 5.8.1 to 5.8.2 brings Core packages on .NET

### ISSUE THREAD

**Issue by abatishchev** [OData/odata.net#928]
Updating Microsoft.Data.Services.Client 5.8.1 to 5.8.2 brings Core packages (System.*) on non-Core, i.e. regular .NET platform.

### Assemblies affected

[Microsoft.Data.Services.Client](https://www.nuget.org/packages/Microsoft.Data.Services.Client/) nuget package spec's dependencies definition.

### Reproduce steps

0. Have a project targeting .NET 4.5.2 or 4.6.2 or similar
1. Install-Package Microsoft.Data.Services.Client -Version 5.8.1
2. Observe there are *no* System.* packages installed
3. Update-Package Microsoft.Data.Services.Client -Version 5.8.2
4. Observe System.* packages installed

### Expected result

Installing 4.8.2 in projects targets full .NET should no install Core packages

### Actual result

Installing 4.8.2 in projects targets full .NET does install Core packages

### Additional detail

I believe this can be fixed by updating the nuspec to **.NETStandard 1.4**, e.g. see [Microsoft.Azure.KeyVault](https://preview.nuget.org/packages/Microsoft.Azure.KeyVault) dependencies definition.

**Comment by abatishchev** [comment]
Any response, pleae?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by xuzhg** [comment]
Similar to: #924, #853, #831

**Comment by xuzhg** [comment]
Ok,
In 5.8.1, only install:

![image](https://user-images.githubusercontent.com/9426627/30087339-01cb150c-9255-11e7-89f2-9df5fd991baf.png)

but, in 5.8.2, installs:
![image](https://user-images.githubusercontent.com/9426627/30087396-55a553fe-9255-11e7-8167-89c64495524c.png)

**Comment by xuzhg** [comment]
@abatishchev

[[Microsoft.Data.Services.Client v5.8.3]](https://www.nuget.org/packages/Microsoft.Data.Services.Client/5.8.3) was just released. Would you please help try it out and give us some feedbacks. Thanks!

Here's the snapshot:

![image](https://user-images.githubusercontent.com/9426627/30192005-843d7020-93f9-11e7-855a-29b694d974ae.png)

and its dependencies:
![image](https://user-images.githubusercontent.com/9426627/30192019-8e8522d0-93f9-11e7-8823-68082ac1760e.png)

**Comment by abatishchev** [comment]
Seems to work fine now, thanks!
