### ISSUE TITLE
Custom route path without creating entity

### ISSUE THREAD

**Issue by mddheeraj** [OData/odata.net#941]
We are planning to access a Function with custom route path /serviceroute/controller('key')/test/report.
At present we don't have any entity for test. Can we create a route path without creating any entity set.

### Assemblies affected

6.15.00

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@mddheeraj If you want to use ODL to parse the URL, I don't think it can work.

please feel free to re-open it if you have further concern. Thanks a lot.
