### ISSUE TITLE
Move test cases using IIS Web Server to different assembly to ensure proper IIS server cleanup and test stablility

### ISSUE THREAD

**Issue by biaol-odata** [OData/odata.net#947]
This is to log an item post PR OData/odata.net#935.
These tests are disabled for now.

Two test cases in RequestUriProcessorTest:
•RequestUriProcessorKeySpecialCharsTest
•RequestUriCaseInsensitive

Also three testing case/data related to Local IIS server is disabled in the following tests:
 - SecurityPartialTrustTest
 - HttpContextServiceHostTunnelingTest

**Comment by xuzhg** [comment]
Closed
