### ISSUE TITLE
ODataUriExtensions.BuildUri ignores $skiptoken

### ISSUE THREAD

**Issue by henkkuli** [OData/odata.net#949]
`ODataUriExtensions.BuildUri` does not add $skiptoken to the uri.

### Assemblies affected
Microsoft.OData.Core 7.3.0.10724
Microsoft.OData.Edm 7.3.0.10724
Microsoft.Spatial 7.3.0.10724

### Reproduce steps
```C#
ODataUri odataUri = new ODataUri();
odataUri.Path = new ODataPath();
odataUri.SkipToken = "token";
var uri = odataUri.BuildUri(ODataUrlKeyDelimiter.Parentheses);
```

### Expected result
`uri` should be `?$skiptoken=token`.

### Actual result
`uri` is empty.

**Comment by xuzhg** [comment]
Fixed at: 51136eaadab8fd371b28d9ab5fd2f4ac6a680874
