### ISSUE TITLE
NuGet install the wrong dependecies.

### ISSUE THREAD

**Issue by liushuanggang** [OData/odata.net#953]
*Short summary*
Install the NuGet package Microsoft.Data.Services.Client 5.8.2 to the .net framework project, NuGet will install the dependencies under the framework .NET Standard 1.1.

### Reproduce steps
1. Create a C# project with .net 4.5.2.
2. Install the NuGet package  Microsoft.Data.Services.Client with latest version 5.8.2
3. Confirmation window shows up it lists dependencies under installing section, which seem to be pulled from Microsoft.Data.Services.Client .NETStandard 1.1 list of dependencies:

### Expected result
Only the dependence Microsoft.Data.OData should be install.

### Actual result
The dependencies under .NETStandard 1.1 frame work are installed.

**Comment by xuzhg** [comment]
Similar to: #831, #853, #924, #928

**Comment by xuzhg** [comment]
@liushuanggang 

I follow up your steps:
1. Create a C# console application (.Net Framework) with .net 4.5.2
2. `Install-Package Microsoft.Data.Services.Client `

Find the OData dll refers to "net40" subfolder, not the `netstandard1.1` subfolder.
![image](https://user-images.githubusercontent.com/9426627/30087192-16a809e0-9254-11e7-9613-e7a6744aad32.png)

Below are the folders from the nuget package installation:
![image](https://user-images.githubusercontent.com/9426627/30087215-3ecf89c0-9254-11e7-9e2a-ee5b0f9d6c40.png)

So, What's your problem?

**Comment by xuzhg** [comment]
@liushuanggang 

[[Microsoft.Data.Services.Client v5.8.3]](https://www.nuget.org/packages/Microsoft.Data.Services.Client/5.8.3) was just released. Would you please help try it out and give us some feedbacks. Thanks!

**Comment by liushuanggang** [comment]
@xuzhg , Sorry for later reply. I have verified this with the version v5.8.3, it works fine. Thanks you!

**Comment by xuzhg** [comment]
@liushuanggang 

Be glad to hear that! 
Please feel free let us know if you have any further questions/problems/issues. 

Regards,
-Sam
