### ISSUE TITLE
Support ODataLib/EdmLib/MS.Spatial on ASP.NET 5/ASP.NET Core 5

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/odata.net#97]
Target: support referencing ODataLib/EdmLib/MS.Spatial NuGet packages from ASP.NET 5 projects.

In ASP.NET 5, there are two profiles to be supported:

* ASP.NET 5
* ASP.NET Core 5

**Comment by lewischeng-ms** [comment]
@PinpointTownes Please download preview packages for ASP.NET 5 from https://github.com/lewischeng-ms/vNext/tree/master/packages.

##### Profile mapping
 - aspnet50 <=> portable40+profile328 (dotnet40 also work perfect)
 - aspnetcore50 <=> portable45+profile259

To resolve the issue `'System.Object' defined in an assembly not imported`, just need to add the following content to `.nuspec`:

    <dependencies>
	  <group targetFramework="Asp.NetCore5.0">
        <dependency id="System.Runtime" version="4.0.20-beta-22523" />
		<dependency id="Microsoft.Spatial" version="[$VersionNuGetSemantic$]" />
        <dependency id="Microsoft.OData.Edm" version="[$VersionNuGetSemantic$]" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework="Asp.Net5.0" />
      <frameworkAssembly assemblyName="System" targetFramework="Asp.Net5.0" />
      <frameworkAssembly assemblyName="System.Core" targetFramework="Asp.Net5.0" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="Asp.Net5.0" />
    </frameworkAssemblies>

##### Version
Though the version was set to `7.0.0-preview` to avoid ambiguity with the existing 6.XX.X packages from nuget.org, they are actually `6.10.0`. 

##### Source
https://github.com/lewischeng-ms/odata.net/tree/vNext

##### Known Issues
ODataLib has TypeInitialization problem under `aspnetcore50` (though compilable) but works fine under `aspnet50`.

**Comment by lewischeng-ms** [comment]
@PinpointTownes Fixed the TypeInitialization problem. It was due to dlls not signed. So I decided to temporarily make them `non-transparent` assemblies. Now they seemed to work fine under `aspnetcore50`.

**Comment by PinpointTownes** [comment]
@lewischeng-ms great, thanks! :+1: 

I finally ported Web API OData to `dnxcore50`: https://github.com/PinpointTownes/WebApi/commit/f2fffbc2b32b48179b20865a7e5b0d50a656da4c

Sadly, there's currently a bug in CoreCLR that prevents it from working, but it should be fixed soon :dancers: 

To be honest, I'm not totally happy with all the changes needed to make it work (specially the `Type.GetTypeCode` replacement), so feel free to review it and tell me what you think (I'm on JabbR).

**Comment by lewischeng-ms** [comment]
@PinpointTownes Yeah, I've already seen your commits and you REALLY did an amazing job! Cheers! And for `Type.GetTypeCode`, my replacemnt is https://github.com/lewischeng-ms/odata.net/commit/77c702084f7a0c393798dc141e7ee872edb0c574. Though I am not totally happy about that solution tooooo.. we are reinventing the wheel, but looks like currently there is no better solution.

**Comment by PinpointTownes** [comment]
Nice, I'll reuse your `PlatformHelper` approach: even if it does something similar internally, the resulting code is probably easier to read than a ton of if/elseif :smile:

**Comment by lewischeng-ms** [comment]
Do with #136

**Comment by lewischeng-ms** [comment]
Step 2: Create `Net45` projects for the profile `DNX452` and use **ApiPort** to verify.

**Comment by lewischeng-ms** [comment]
Step 3: Create `Profile259` (Portable .NET 4.0) projects for the profile `DNXCORE50` and use **ApiPort** to verify.

Reference: [NuGetFramework and FrameworkReducer tests](https://github.com/NuGet/NuGet3/blob/c9aa766effd1b7bb9ea0e50af2822a4a0a8671f9/test/NuGet.Frameworks.Test/FrameworkReducerTests.cs)

ApiPort analysis results:
 - `ASP.NET 5` - N/A

**Comment by lewischeng-ms** [comment]
Step **4**: Add `Net45` and `Profile259` libraries into NuGet packages.

Remarks: `Net45` corresponds to the profile `net45` in the NuGet packages while `Profile259` corresponds to the profile `portable-net45+win8+wp8+wpa81+dnxcore50`.

**Comment by lewischeng-ms** [comment]
Step **5**: Update TFS and produce signed packages.

Preview packages updated: https://www.myget.org/feed/Packages/odlpreview

**Comment by lewischeng-ms** [comment]
Step **6**: Test & resolve any incompatibility on ASP.NET 5.0

Status: Working...

**Comment by lewischeng-ms** [comment]
Final commit https://github.com/OData/odata.net/commit/84716acaf999bae560b5b90b0da44b21fd7a2ea6
