### ISSUE TITLE
Flaky metadata/service doc validation test cases

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#970]
At times, the following test cases will fail due to the test service not initializing correctly and therefore the tests fail when they receive 400 responses.

- test\endtoendtests\tests\client\build.desktop\publicprovidertests\efservicetests.cs
    - ValidMetadata()
    - ValidServiceDocument()
- test\endtoendtests\tests\client\build.desktop\publicprovidertests\hybridservicetests.cs
    - ValidMetadata()
    - ValidServiceDocument()

On the service side when this happens, there is an issue with the cast in `test\FunctionalTests\Service\Microsoft\OData\Service\Providers\BaseServiceProvider.cs` with the exception message:
`The exception message is 'Attempt by method 'Microsoft.OData.Service.Providers.BaseServiceProvider.AddStreamProperties(Microsoft.OData.Service.Providers.ResourceType, System.Type, Boolean)' to access method 'System.Linq.Enumerable.Cast<Microsoft.OData.Client.NamedStreamAttribute>(System.Collections.IEnumerable)' failed.'.`

### Assemblies affected
The affected test cases are in the test binary `Microsoft.Test.OData.Tests.Client`.

### Reproduce steps
Sporadic with no consistent repro steps.

### Expected result
Tests pass.

### Actual result
See above.

### Additional detail
Error output of test case:
`Microsoft.OData.ODataContentTypeException: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/xml' matches the content type 'text/html'.`

This due to the fact that the server sometimes returns 400 along with an text/html error and therefore OData sees that there isn't a match.

**Comment by gathogojr** [comment]
Issue cannot be reproduced currently
