### ISSUE TITLE
ODATA Support for .net core 

### ISSUE THREAD

**Issue by alpeejain** [OData/odata.net#976]
Hi, 
I am going to start the development of a new Product, would like to use .net core + ef core + ODATA. Do let me know when will we have the official support for the same?

**Comment by robertmclaws** [comment]
You cannot do OData on .NET Core right now. You'd be better off spinning up a separate API project and using EF6 and WebApi 2 on .NET Framework 4.7.1, and then having the web front-end being .NET Core. It is better for scalability anyways, and you can upgrade the back-end to .NET Core in a few months when OData vNext is ready.

**Comment by sbaker** [comment]
Would you guys mind if i took a stab at upgrading to netstandard2.0?

**Comment by robertmclaws** [comment]
It's going to be on .NET Standard 1.1 very shortly, which means it will run on 2.0. Probably not worth the effort at this point, since they're almost done.

**Comment by robward-ms** [comment]
This issue is file in the OData Lib repo, is this about OData Lib or WebApi?  OData Lib supports NetStandard 1.1 as of 7.2. For WebApi, see https://github.com/OData/WebApi/issues/939.
