### ISSUE TITLE
Edm.Stream Property not supported (Issue #2)

### ISSUE THREAD

**Issue by jnanneng** [OData/odata.net#979]
If we put any kind of System.IO.Stream instance into an Edm.Stream property, EdmLibraryExtensions.GetPrimitiveTypeReference returns null.

EdmLibraryExtensions.cs contains:
internal static IEdmPrimitiveTypeReference GetPrimitiveTypeReference(Type clrType)
{
       .
       .
       .
       // Try to lookup the type in our map.
       IEdmPrimitiveTypeReference primitiveTypeReference;
       if (PrimitiveTypeReferenceMap.TryGetValue(clrType, out primitiveTypeReference))
       {
           return primitiveTypeReference;
       }
       .
       .
       .
       // If it didn't work, try spatial types which need assignability.
       .
       .
       .
       if (primitiveType == null)
       {
           return null;
       }
       .
       .
       .
}

### Assemblies affected

OData .Net lib 7.2.0
OData .Net lib 7.3.1

**Comment by gathogojr** [comment]
Insufficient details to understand and reproduce issue

**Comment by jnanneng** [comment]
Granted, this was logged four and a half years ago.  However, OData properties which return streams did not work.  i.e. if a person actually implemented an OData property and had it return a stream, the code mentioned above would simply return null and errors would be encountered.  I.e. it was pointing out the code defect within the area of 'GetPrimitiveTypeReference'.

The libs affected were noted:  
OData .Net lib 7.2.0
OData .Net lib 7.3.1

==

Since this has now been closed, has anyone verified that steam properties actually now work and can return the streamed information?
