### ISSUE TITLE
Isolate OData Attributes different/separate assembly.

### ISSUE THREAD

**Issue by NetTecture** [OData/odata.net#983]
I prefer to keep my API objects defined in a separate assembly.

OData now has a lot of nice attributes that make sense on those api objects. Some are even needed (or how else do I set "Contained"?)

But to get there... I have to add... Microsoft.AspNet.Odata, which is heavy in cascading requirements (AspNet.WebApi.Client, AspNet.WebApi.Core, OData.Core). This enters a lot of references into any project that is accessing this objects, including some third party Odata client library (Simple.Odata.Client( that has no need to actually add the webapi core.

It would make more sense to move those attributes into a base assembly that does not require the runtime to be present. This could be either Microsoft.Odata.Core or even a separate assembly.

**Comment by mtroth-microsoft** [comment]
WebApi is an an Open Source project. Contributions are always welcome.
Did you mean to open this issue in WebApi? if so, you may wish to look there for others with similar feature asks. Adding +1 to their issue under WebApi increased the visibility of the issue to the community more so.

**Comment by NetTecture** [comment]
Quite obviously I did not want to open this with WebApi - because it is not WebApi's fault that Odata attributes are defined in a way that requires WebApi references to be fullfilled?

The issue is with Microsoft.AspNet.Odata.

**Comment by mtroth-microsoft** [comment]
Generally issues about the factoring of a component are best targeted at that component. You may find some community agreement there which may help you to generate attention to the matter.

**Comment by NetTecture** [comment]
And "THAT COMPONENT" being Microsoft.AspNet.Odata. Is that not maintained here?

**Comment by mtroth-microsoft** [comment]
This is the ODL repository. Microsoft.AspNet.OData is what I am referring to as WebApi.
https://github.com/OData/WebApi

**Comment by NetTecture** [comment]
Ah, then this here is the wrong place. Thanks.
