### ISSUE TITLE
Serialization of null complex types in delta responses throws ArgumentNullException

### ISSUE THREAD

**Issue by gasgesgos** [OData/odata.net#993]
ArgumentNullException - delta serialization code explicitly passes null to a method that explicitly does not allow it in the case of a null complex type. 

### Assemblies affected

Not working in
Microsoft.AspNet.OData.6.1.0
Microsoft.OData.Core.7.2.0

Previously working in:
Microsoft.AspNet.OData.5.10.0
Microsoft.OData.Core.6.15.0

### Reproduce steps

With an untyped model, trying to serialize a delta feed with 'null' complex type value in the entity causes the exception.

### Expected result

Serializing 'null' or omitting the property.

### Actual result

System.ArgumentNullException: 'Value cannot be null.
Parameter name: resource

### Additional detail

Stack trace shows a call to WriteStart(deltaResource). This parameter is passed as 'null' in the case of a null complex type in a delta entity that is undergoing serialization.

ODataResourceSerializer.WriteDeltaComplexAndExpandedNavigationProperty:201
```
writer.WriteStart(deltaResource: null);
```
The target method at 
https://github.com/OData/odata.net/blob/dece13339942dd5ef7405e38720991063ec8ee39/src/Microsoft.OData.Core/JsonLight/ODataJsonLightDeltaWriter.cs#L409
eventually does a null check on this parameter. 

Stack trace:
```
 	Microsoft.OData.Core.dll!Microsoft.OData.ExceptionUtils.CheckArgumentNotNull<System.__Canon>(System.__Canon value, string parameterName)
	Microsoft.OData.Core.dll!Microsoft.OData.JsonLight.ODataJsonLightDeltaWriter.WriteStart(Microsoft.OData.ODataResource deltaResource)
	System.Web.OData.dll!System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteDeltaComplexAndExpandedNavigationProperty(Microsoft.OData.Edm.IEdmProperty edmProperty, Microsoft.OData.UriParser.SelectExpandClause selectExpandClause, System.Web.OData.ResourceContext resourceContext, Microsoft.OData.ODataDeltaWriter writer)	
	System.Web.OData.dll!System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteDeltaComplexProperties(System.Collections.Generic.IEnumerable<Microsoft.OData.Edm.IEdmStructuralProperty> complexProperties, System.Web.OData.ResourceContext resourceContext, Microsoft.OData.ODataDeltaWriter writer)
	System.Web.OData.dll!System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteDeltaResource(object graph, Microsoft.OData.ODataDeltaWriter writer, System.Web.OData.Formatter.Serialization.ODataSerializerContext writeContext)
	System.Web.OData.dll!System.Web.OData.Formatter.Serialization.ODataDeltaFeedSerializer.WriteFeed(System.Collections.IEnumerable enumerable, Microsoft.OData.Edm.IEdmTypeReference feedType, Microsoft.OData.ODataDeltaWriter writer, System.Web.OData.Formatter.Serialization.ODataSerializerContext writeContext)
	System.Web.OData.dll!System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(System.Type type, object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content, System.Net.Http.Headers.HttpContentHeaders contentHeaders)
	System.Web.OData.dll!System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(System.Type type, object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content, System.Net.TransportContext transportContext, System.Threading.CancellationToken cancellationToken)	
```

**Comment by mikepizzo** [comment]
This was fixed as part of PR #989.  We now explicitly support passing a null resource for a complex type.  Please let us know if you still encounter this issue after updating to the latest ODataLib.
